[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm ci --prefix api --include=dev"
]

[phases.build]
cmds = [
  "npm run db:generate",
  "npm run build"
]

[start]
cmd = "npm --prefix api start"
