import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.CEO] as const;
const serviceTypes=['HOMEMAKER_PERSONAL_CARE','SHARED_LIVING','RESPITE','TRANSPORTATION','NURSING','HOME_HEALTH','COMMUNITY_INTEGRATION','OTHER'] as const;
const statuses=['NEW','REVIEWING','CONTACTED','INTAKE_STARTED','ACCEPTED','DECLINED','CLOSED'] as const;
const requestSchema=z.object({requesterName:z.string().trim().min(2).max(200),requesterRelationship:z.string().trim().max(120).default('Self'),clientName:z.string().trim().min(2).max(200),clientDateOfBirth:z.string().trim().max(20).default(''),email:z.string().trim().email().max(320),phone:z.string().trim().min(7).max(40),preferredContact:z.enum(['EMAIL','PHONE','TEXT']).default('EMAIL'),streetAddress:z.string().trim().max(300).default(''),city:z.string().trim().max(120).default(''),state:z.string().trim().max(40).default('OH'),zipCode:z.string().trim().max(10).default(''),county:z.string().trim().max(120).default(''),fundingSource:z.string().trim().max(160).default(''),serviceTypes:z.array(z.enum(serviceTypes)).min(1).max(8),urgency:z.enum(['ROUTINE','SOON','URGENT']).default('ROUTINE'),currentProvider:z.string().trim().max(200).default(''),requestedStartDate:z.string().trim().max(20).default(''),notes:z.string().trim().max(8000).default(''),consent:z.literal(true)});
const reviewSchema=z.object({status:z.enum(statuses).optional(),assignedToUserId:z.string().trim().optional().nullable(),serviceHomeId:z.string().trim().optional().nullable(),clientId:z.string().trim().optional().nullable(),internalNotes:z.string().trim().max(12000).optional(),dispositionReason:z.string().trim().max(2000).optional(),nextFollowUpAt:z.coerce.date().optional().nullable()});
const requestNumber=()=>`SR-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;

export function registerClientServiceRequestRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  const gate=requireRoles(...managerRoles);
  const resolveOrganizationId=async()=>{const configured=String(process.env.SULANDRA_ORGANIZATION_ID||'').trim();if(configured)return configured;const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "Organization" LIMIT 1`);if(!rows[0]?.id)throw Object.assign(new Error('Sulandra organization is not configured for service requests'),{status:503});return rows[0].id;};

  app.post('/public/client-service-requests',async(req,res,next)=>{try{const input=requestSchema.parse(req.body);const organizationId=await resolveOrganizationId();const id=randomUUID(),number=requestNumber();await prisma.$executeRawUnsafe(`INSERT INTO "ClientServiceRequest" ("id","organizationId","requestNumber","requesterName","requesterRelationship","clientName","clientDateOfBirth","email","phone","preferredContact","streetAddress","city","state","zipCode","county","fundingSource","serviceTypes","urgency","currentProvider","requestedStartDate","notes","status","consentAt") VALUES ($1,$2,$3,$4,$5,$6,NULLIF($7,''),$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::jsonb,$18,$19,NULLIF($20,''),$21,'NEW',NOW())`,id,organizationId,number,input.requesterName,input.requesterRelationship,input.clientName,input.clientDateOfBirth,input.email,input.phone,input.preferredContact,input.streetAddress,input.city,input.state,input.zipCode,input.county,input.fundingSource,JSON.stringify(input.serviceTypes),input.urgency,input.currentProvider,input.requestedStartDate,input.notes);res.status(201).json({data:{id,requestNumber:number,status:'NEW'}});}catch(error){next(error)}});

  app.get('/api/admin/client-service-requests',gate,async(req,res,next)=>{try{const auth=authOf(res);const status=String(req.query.status||'').trim();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT r.*,u."email" AS "assignedToEmail",sh."name" AS "serviceHomeName" FROM "ClientServiceRequest" r LEFT JOIN "User" u ON u."id"=r."assignedToUserId" LEFT JOIN "ServiceHome" sh ON sh."id"=r."serviceHomeId" WHERE r."organizationId"=$1 AND ($2='' OR r."status"=$2) ORDER BY CASE r."urgency" WHEN 'URGENT' THEN 0 WHEN 'SOON' THEN 1 ELSE 2 END,r."createdAt" DESC LIMIT 1000`,auth.organizationId,status);const metrics={total:rows.length,new:rows.filter(r=>r.status==='NEW').length,urgent:rows.filter(r=>r.urgency==='URGENT'&&!['ACCEPTED','DECLINED','CLOSED'].includes(r.status)).length,intakeStarted:rows.filter(r=>r.status==='INTAKE_STARTED').length};res.json({data:{requests:rows,metrics}});}catch(error){next(error)}});

  app.get('/api/admin/client-service-requests/:requestId',gate,async(req,res,next)=>{try{const auth=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ClientServiceRequest" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.requestId);if(!rows[0])return void res.status(404).json({error:'Service request was not found'});res.json({data:rows[0]});}catch(error){next(error)}});

  app.patch('/api/admin/client-service-requests/:requestId',gate,async(req,res,next)=>{try{const auth=authOf(res),input=reviewSchema.parse(req.body);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ClientServiceRequest" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.requestId))[0];if(!current)return void res.status(404).json({error:'Service request was not found'});const status=input.status??current.status,assigned=input.assignedToUserId===undefined?current.assignedToUserId:input.assignedToUserId,home=input.serviceHomeId===undefined?current.serviceHomeId:input.serviceHomeId,clientId=input.clientId===undefined?current.clientId:input.clientId,notes=input.internalNotes===undefined?current.internalNotes:input.internalNotes,reason=input.dispositionReason===undefined?current.dispositionReason:input.dispositionReason,follow=input.nextFollowUpAt===undefined?current.nextFollowUpAt:input.nextFollowUpAt;await prisma.$executeRawUnsafe(`UPDATE "ClientServiceRequest" SET "status"=$1,"assignedToUserId"=$2,"serviceHomeId"=$3,"clientId"=$4,"internalNotes"=$5,"dispositionReason"=$6,"nextFollowUpAt"=$7,"reviewedById"=$8,"reviewedAt"=COALESCE("reviewedAt",NOW()),"updatedAt"=NOW() WHERE "organizationId"=$9 AND "id"=$10`,status,assigned,home,clientId,notes,reason,follow,auth.userId,auth.organizationId,current.id);await audit?.(auth,'UPDATE_CLIENT_SERVICE_REQUEST','ClientServiceRequest',current.id,{requestNumber:current.requestNumber,before:{status:current.status,assignedToUserId:current.assignedToUserId,serviceHomeId:current.serviceHomeId,clientId:current.clientId},after:{status,assignedToUserId:assigned,serviceHomeId:home,clientId}});res.json({data:{id:current.id,status,clientId}});}catch(error){next(error)}});

  app.post('/api/admin/client-service-requests/:requestId/start-intake',gate,async(req,res,next)=>{try{const auth=authOf(res);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ClientServiceRequest" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.requestId))[0];if(!current)return void res.status(404).json({error:'Service request was not found'});const draft={source:'CLIENT_SERVICE_REQUEST',serviceRequestId:current.id,requestNumber:current.requestNumber,client:{name:current.clientName,dateOfBirth:current.clientDateOfBirth,email:current.email,phone:current.phone,address:{streetAddress:current.streetAddress,city:current.city,state:current.state,zipCode:current.zipCode,county:current.county}},requester:{name:current.requesterName,relationship:current.requesterRelationship,preferredContact:current.preferredContact},serviceTypes:current.serviceTypes,fundingSource:current.fundingSource,currentProvider:current.currentProvider,requestedStartDate:current.requestedStartDate,urgency:current.urgency,notes:current.notes};let intakeImportId=current.intakeImportId as string|null;if(!intakeImportId){intakeImportId=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireIntakeImport" ("id","organizationId","clientId","fileName","mimeType","storageKey","status","extractionProvider","extractedData","submittedByUserId","createdAt","updatedAt") VALUES ($1,$2,NULL,$3,$4,NULL,'REVIEW_REQUIRED','SULANDRA_SERVICE_REQUEST',$5::jsonb,$6,NOW(),NOW())`,intakeImportId,auth.organizationId,`Service Request ${current.requestNumber}`,'application/vnd.sulandra.service-request+json',JSON.stringify(draft),auth.userId);}await prisma.$executeRawUnsafe(`UPDATE "ClientServiceRequest" SET "status"='INTAKE_STARTED',"intakeImportId"=$1,"reviewedById"=$2,"reviewedAt"=COALESCE("reviewedAt",NOW()),"updatedAt"=NOW() WHERE "organizationId"=$3 AND "id"=$4`,intakeImportId,auth.userId,auth.organizationId,current.id);await audit?.(auth,'START_CLIENT_INTAKE','ClientServiceRequest',current.id,{requestNumber:current.requestNumber,clientName:current.clientName,intakeImportId});res.json({data:{id:current.id,status:'INTAKE_STARTED',intakeImportId,clientDraft:draft}});}catch(error){next(error)}});
}
