import { createHash, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const readers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.CEO,UserRole.DOO]);
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening annual QA analysis');return a.legalEntityId;};
const ensureRead=(a:AuthContext)=>{entity(a);if(!readers.has(a.role)&&!owner(a))throw httpError(403,'Company compliance trend access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writers.has(a.role)&&!owner(a))throw httpError(403,'Company compliance annual-analysis write access is required');};
const analysisSchema=z.object({reportYear:z.number().int().min(2000).max(2200),findings:z.string().trim().max(10000).optional().nullable(),actionPlan:z.string().trim().max(10000).optional().nullable(),notes:z.string().trim().max(5000).optional().nullable()});
const n=(v:unknown)=>Number(v||0);
const csv=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
const yearOf=(value:unknown)=>{const year=Number(value);if(!Number.isInteger(year)||year<2000||year>2200)throw httpError(400,'year must be an integer from 2000 through 2200');return year;};
const monthKey=(year:number,index:number)=>`${year}-${String(index+1).padStart(2,'0')}`;
async function grouped(prisma:PrismaClient,sql:string,args:unknown[]){return prisma.$queryRawUnsafe<Array<{month:string;count:number}>>(sql,...args);}
async function yearMetrics(prisma:PrismaClient,a:AuthContext,year:number){
 const e=entity(a),start=`${year}-01-01`,end=`${year+1}-01-01`,args=[a.organizationId,e,start,end];
 const [evv,billing,claims,remits,screening,ui,mui,expirations,packets]=await Promise.all([
  grouped(prisma,`SELECT to_char(date_trunc('month',"createdAt"),'YYYY-MM') month,count(*)::int count FROM "SpireEvvPrebillDecision" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "decisionCode"='BLOCK' AND "createdAt">=$3::date AND "createdAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"createdAt"),'YYYY-MM') month,count(*)::int count FROM "SpireDoddBillingValidationDecision" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "decisionCode"='BLOCK' AND "createdAt">=$3::date AND "createdAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"createdAt"),'YYYY-MM') month,count(*)::int count FROM "RevenueCycleClaimExchangeEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "status" IN ('ACK_REJECTED','FAILED','PARTIAL') AND "createdAt">=$3::date AND "createdAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"createdAt"),'YYYY-MM') month,count(*)::int count FROM "RevenueCycleRemittance" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "createdAt">=$3::date AND "createdAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"createdAt"),'YYYY-MM') month,count(*)::int count FROM "EmployeeOhioScreeningEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "toStatus" IN ('BLOCKED','EXPIRED') AND "createdAt">=$3::date AND "createdAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"discoveredAt"),'YYYY-MM') month,count(*)::int count FROM "SpireIncidentRegulatoryCase" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "classification"='UI' AND "discoveredAt">=$3::date AND "discoveredAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"discoveredAt"),'YYYY-MM') month,count(*)::int count FROM "SpireIncidentRegulatoryCase" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "classification"='MUI' AND "discoveredAt">=$3::date AND "discoveredAt"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"expirationDate"),'YYYY-MM') month,count(*)::int count FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "expirationDate">=$3::date AND "expirationDate"<$4::date GROUP BY 1`,args),
  grouped(prisma,`SELECT to_char(date_trunc('month',"generatedAt"),'YYYY-MM') month,count(*)::int count FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "generatedAt">=$3::date AND "generatedAt"<$4::date GROUP BY 1`,args),
 ]);
 const maps=[evv,billing,claims,remits,screening,ui,mui,expirations,packets].map(rows=>new Map(rows.map(r=>[r.month,n(r.count)])));
 const monthly=Array.from({length:12},(_,i)=>{const month=monthKey(year,i),row={month,evvBlocks:maps[0].get(month)||0,doddBillingBlocks:maps[1].get(month)||0,claimExceptions:maps[2].get(month)||0,remittances:maps[3].get(month)||0,workforceBlockTransitions:maps[4].get(month)||0,uiIncidents:maps[5].get(month)||0,muiIncidents:maps[6].get(month)||0,complianceExpirations:maps[7].get(month)||0,auditPackets:maps[8].get(month)||0};return{...row,exceptionActivity:row.evvBlocks+row.doddBillingBlocks+row.claimExceptions+row.workforceBlockTransitions+row.uiIncidents+row.muiIncidents+row.complianceExpirations};});
 const keys=['evvBlocks','doddBillingBlocks','claimExceptions','remittances','workforceBlockTransitions','uiIncidents','muiIncidents','complianceExpirations','auditPackets','exceptionActivity'] as const;
 const totals=Object.fromEntries(keys.map(key=>[key,monthly.reduce((sum,row)=>sum+n(row[key]),0)]));
 return{year,monthly,totals};
}
function signals(current:Record<string,unknown>,previous:Record<string,unknown>){const labels:{key:string;label:string}[]=[{key:'evvBlocks',label:'EVV pre-bill blocks'},{key:'doddBillingBlocks',label:'DODD billing blocks'},{key:'claimExceptions',label:'Claim exchange exceptions'},{key:'workforceBlockTransitions',label:'Workforce blocked/expired transitions'},{key:'uiIncidents',label:'UI incidents'},{key:'muiIncidents',label:'MUI incidents'},{key:'complianceExpirations',label:'Company compliance expirations'}];return labels.map(({key,label})=>{const c=n(current[key]),p=n(previous[key]),delta=c-p;return{metric:key,label,current:c,previous:p,delta,direction:delta>0?'INCREASED':delta<0?'DECREASED':'UNCHANGED',interpretation:'Directional count comparison only; no causal conclusion is inferred.'};});}
async function packetIds(prisma:PrismaClient,a:AuthContext,year:number){const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "periodStart"<=make_date($3,12,31) AND "periodEnd">=make_date($3,1,1) ORDER BY "generatedAt"`,a.organizationId,entity(a),year);return rows.map(r=>r.id);}
export const registerCompanyComplianceTrendRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/company-compliance/qa/trends',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const year=yearOf(req.query.year??new Date().getUTCFullYear()),current=await yearMetrics(prisma,a,year),previous=await yearMetrics(prisma,a,year-1);res.json({data:{...current,previousYearTotals:previous.totals,trendSignals:signals(current.totals,previous.totals),metricMode:'RECORDED_ACTIVITY_COUNTS',warning:'Trend counts describe recorded system activity; they do not establish causes, regulatory findings, or external acceptance.'}});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/trends.csv',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const year=yearOf(req.query.year??new Date().getUTCFullYear()),d=await yearMetrics(prisma,a,year),headers=['month','evvBlocks','doddBillingBlocks','claimExceptions','remittances','workforceBlockTransitions','uiIncidents','muiIncidents','complianceExpirations','auditPackets','exceptionActivity'],body=[headers.map(csv).join(','),...d.monthly.map(row=>headers.map(k=>csv((row as Record<string,unknown>)[k])).join(','))].join('\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="company-compliance-trends-${year}.csv"`);res.setHeader('Cache-Control','private, no-store');res.send(body);}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/packets/:packetId/exceptions.csv',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "packetNumber","periodStart","periodEnd","snapshotSha256","sourceIndex","exceptionSummary" FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.packetId),p=rows[0];if(!p)throw httpError(404,'Compliance audit packet was not found');const source=p.sourceIndex&&typeof p.sourceIndex==='object'&&!Array.isArray(p.sourceIndex)?p.sourceIndex as Record<string,unknown>:{},lines=[['packetNumber','snapshotSha256','periodStart','periodEnd','domain','sourceRecordId'].map(csv).join(',')];for(const [domain,ids] of Object.entries(source))for(const id of Array.isArray(ids)?ids:[])lines.push([p.packetNumber,p.snapshotSha256,String(p.periodStart).slice(0,10),String(p.periodEnd).slice(0,10),domain,id].map(csv).join(','));res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${String(p.packetNumber).replace(/[^A-Za-z0-9_-]/g,'_')}-exceptions.csv"`);res.setHeader('Cache-Control','private, no-store');res.send(lines.join('\n'));}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/annual-analyses',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const year=req.query.year?yearOf(req.query.year):null,rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","analysisNumber","reportYear","version","generatedByUserId","generatedAt","snapshotSha256","yearTotals","trendSignals","sourcePacketIds","findings","actionPlan","notes" FROM "CompanyComplianceAnnualQaAnalysis" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ($3::int IS NULL OR "reportYear"=$3) ORDER BY "reportYear" DESC,"version" DESC,"generatedAt" DESC LIMIT 250`,a.organizationId,entity(a),year);res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/annual-analyses/:analysisId',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceAnnualQaAnalysis" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.analysisId);if(!rows[0])throw httpError(404,'Annual QA analysis was not found');res.json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/annual-analyses/:analysisId/file.json',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceAnnualQaAnalysis" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.analysisId),row=rows[0];if(!row)throw httpError(404,'Annual QA analysis was not found');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${String(row.analysisNumber).replace(/[^A-Za-z0-9_-]/g,'_')}.json"`);res.setHeader('Cache-Control','private, no-store');res.send(JSON.stringify(row,null,2));}catch(e){next(e);}});
 app.post('/api/company-compliance/qa/annual-analyses',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=analysisSchema.parse(req.body),[current,p1,p2,p3,sources]=await Promise.all([yearMetrics(prisma,a,i.reportYear),yearMetrics(prisma,a,i.reportYear-1),yearMetrics(prisma,a,i.reportYear-2),yearMetrics(prisma,a,i.reportYear-3),packetIds(prisma,a,i.reportYear)]),trendSignals=signals(current.totals,p1.totals),priorYearComparison=[p1,p2,p3].map(d=>({year:d.year,totals:d.totals})),versionRows=await prisma.$queryRawUnsafe<Array<{version:number}>>(`SELECT COALESCE(MAX("version"),0)::int+1 AS version FROM "CompanyComplianceAnnualQaAnalysis" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "reportYear"=$3`,a.organizationId,entity(a),i.reportYear),version=versionRows[0]?.version||1,id=randomUUID(),analysisNumber=`QA-ANNUAL-${i.reportYear}-V${version}-${randomUUID().slice(0,6).toUpperCase()}`,snapshot={generatedAt:new Date().toISOString(),reportYear:i.reportYear,version,monthlyMetrics:current.monthly,yearTotals:current.totals,priorYearComparison,trendSignals,sourcePacketIds:sources,findings:i.findings??null,actionPlan:i.actionPlan??null,notes:i.notes??null,metricMode:'RECORDED_ACTIVITY_COUNTS',externalBoundaries:{noCausalInference:true,noExternalCertificationClaim:true,noExternalSubmissionAttestation:true}},snapshotText=JSON.stringify(snapshot),snapshotSha256=createHash('sha256').update(snapshotText).digest('hex');await prisma.$executeRawUnsafe(`INSERT INTO "CompanyComplianceAnnualQaAnalysis"("id","organizationId","legalEntityId","analysisNumber","reportYear","version","generatedByUserId","snapshotSha256","monthlyMetrics","yearTotals","priorYearComparison","trendSignals","sourcePacketIds","findings","actionPlan","notes","snapshot") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14,$15,$16,$17::jsonb)`,id,a.organizationId,entity(a),analysisNumber,i.reportYear,version,a.userId,snapshotSha256,JSON.stringify(current.monthly),JSON.stringify(current.totals),JSON.stringify(priorYearComparison),JSON.stringify(trendSignals),JSON.stringify(sources),i.findings??null,i.actionPlan??null,i.notes??null,snapshotText);await audit?.(a,'GENERATE_COMPANY_COMPLIANCE_ANNUAL_QA_ANALYSIS','CompanyComplianceAnnualQaAnalysis',id,{analysisNumber,reportYear:i.reportYear,version,snapshotSha256,sourcePacketCount:sources.length});res.status(201).json({data:{id,analysisNumber,reportYear:i.reportYear,version,snapshotSha256,sourcePacketCount:sources.length,immutable:true}});}catch(e){next(e);}});
};
