import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import type { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const readRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','AUDITOR','HR_MANAGER','BILLING_SPECIALIST','RN','DELEGATING_NURSE','CEO','DOO']);
const writeRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','HR_MANAGER','RN','DELEGATING_NURSE','CEO','DOO']);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before linking compliance evidence');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureRead=(a:AuthContext)=>{entity(a);if(!readRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Compliance evidence access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writeRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Compliance evidence administration is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const q=(name:string)=>`"${name.replaceAll('"','""')}"`;
async function tableExists(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1) AS exists`,table);return rows[0]?.exists===true;}
async function columns(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{column_name:string}>>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,table);return new Set(rows.map(r=>r.column_name));}
async function documentTable(prisma:PrismaClient){for(const table of ['CompanyDocument','CompanyDocumentRecord','CompanyFile'])if(await tableExists(prisma,table))return table;return null;}
async function complianceItem(prisma:PrismaClient,a:AuthContext,id:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),id);if(!rows[0])throw httpError(404,'Compliance item was not found');return rows[0];}
async function documentById(prisma:PrismaClient,a:AuthContext,documentId:string){const table=await documentTable(prisma);if(!table)throw httpError(409,'Company Documents storage is not available');const cols=await columns(prisma,table),args:unknown[]=[documentId],where=`t."id"=$1`;if(cols.has('organizationId')){args.push(a.organizationId);where+=` AND t."organizationId"=$${args.length}`;}if(cols.has('legalEntityId')){args.push(entity(a));where+=` AND t."legalEntityId"=$${args.length}`;}const rows=await prisma.$queryRawUnsafe<Array<{data:Record<string,unknown>}>>(`SELECT (to_jsonb(t)-'content'-'fileContent'-'contentBase64'-'data'-'bytes') AS data FROM ${q(table)} t WHERE ${where} LIMIT 1`,...args);if(!rows[0]?.data)throw httpError(404,'Company document was not found in the selected company');return{table,data:rows[0].data};}
const evidenceSchema=z.object({documentId:z.string().trim().min(1).max(160),evidenceType:z.enum(['PRIMARY','SUPPORTING','RENEWAL','VERIFICATION','OTHER']).default('SUPPORTING'),notes:z.string().trim().max(4000).optional().nullable()});
export const registerCompanyComplianceEvidenceRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/company-compliance/evidence-documents',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const table=await documentTable(prisma);if(!table)return void res.json({data:[]});const cols=await columns(prisma,table),args:unknown[]=[];let where='TRUE';if(cols.has('organizationId')){args.push(a.organizationId);where=`t."organizationId"=$${args.length}`;}if(cols.has('legalEntityId')){args.push(entity(a));where+=` AND t."legalEntityId"=$${args.length}`;}if(cols.has('status'))where+=` AND COALESCE(t."status"::text,'ACTIVE') NOT IN ('ARCHIVED','DELETED','SUPERSEDED')`;const rows=await prisma.$queryRawUnsafe<Array<{data:Record<string,unknown>}>>(`SELECT (to_jsonb(t)-'content'-'fileContent'-'contentBase64'-'data'-'bytes') AS data FROM ${q(table)} t WHERE ${where} ORDER BY COALESCE(to_jsonb(t)->>'updatedAt',to_jsonb(t)->>'createdAt','') DESC LIMIT 2000`,...args),query=clean(req.query.q,300).toLowerCase(),data=rows.map(r=>r.data||{}).filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query));res.json({data});}catch(e){next(e);}});
  app.get('/api/company-compliance/items/:itemId/evidence',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const item=await complianceItem(prisma,a,req.params.itemId),rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceEvidence" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "complianceItemId"=$3 ORDER BY CASE WHEN "removedAt" IS NULL THEN 0 ELSE 1 END,"addedAt" DESC`,a.organizationId,entity(a),req.params.itemId),active=rows.filter(r=>!r.removedAt),autoProjected=String((item.metadata as Record<string,unknown>|undefined)?.autoProjected||'false')==='true',legacy=clean(item.linkedDocumentId,160);res.json({data:{item,evidence:rows,activeEvidenceCount:active.length,autoProjected,legacyLinkedDocumentId:legacy||null,verificationReady:autoProjected||active.length>0||Boolean(legacy)}});}catch(e){next(e);}});
  app.post('/api/company-compliance/items/:itemId/evidence',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);await complianceItem(prisma,a,req.params.itemId);const i=evidenceSchema.parse(req.body),doc=await documentById(prisma,a,i.documentId),title=clean(doc.data.title||doc.data.name||doc.data.originalFileName||doc.data.fileName,400)||null,id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "CompanyComplianceEvidence"("id","organizationId","legalEntityId","complianceItemId","documentId","documentTitleSnapshot","evidenceType","notes","addedByUserId","metadata") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) ON CONFLICT DO NOTHING`,id,a.organizationId,entity(a),req.params.itemId,i.documentId,title,i.evidenceType,i.notes??null,a.userId,JSON.stringify({documentTable:doc.table}));if(i.evidenceType==='PRIMARY')await prisma.$executeRawUnsafe(`UPDATE "CompanyComplianceItem" SET "linkedDocumentId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4`,i.documentId,a.organizationId,entity(a),req.params.itemId);await audit?.(a,'LINK_COMPLIANCE_EVIDENCE','CompanyComplianceItem',req.params.itemId,{documentId:i.documentId,evidenceType:i.evidenceType,title});res.status(201).json({data:{id,documentId:i.documentId,evidenceType:i.evidenceType,title}});}catch(e){next(e);}});
  app.post('/api/company-compliance/items/:itemId/evidence/:evidenceId/remove',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const reason=z.string().trim().min(3).max(4000).parse(req.body?.reason),rows=await prisma.$queryRawUnsafe<Array<{id:string;documentId:string;evidenceType:string}>>(`SELECT "id","documentId","evidenceType" FROM "CompanyComplianceEvidence" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "complianceItemId"=$3 AND "id"=$4 AND "removedAt" IS NULL LIMIT 1`,a.organizationId,entity(a),req.params.itemId,req.params.evidenceId),row=rows[0];if(!row)throw httpError(404,'Active compliance evidence link was not found');await prisma.$executeRawUnsafe(`UPDATE "CompanyComplianceEvidence" SET "removedAt"=NOW(),"removedByUserId"=$1,"removalReason"=$2 WHERE "id"=$3`,a.userId,reason,row.id);if(row.evidenceType==='PRIMARY')await prisma.$executeRawUnsafe(`UPDATE "CompanyComplianceItem" SET "linkedDocumentId"=NULL,"updatedAt"=NOW() WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 AND "linkedDocumentId"=$4`,a.organizationId,entity(a),req.params.itemId,row.documentId);await audit?.(a,'REMOVE_COMPLIANCE_EVIDENCE','CompanyComplianceItem',req.params.itemId,{documentId:row.documentId,evidenceType:row.evidenceType,reason});res.json({data:{id:row.id,removed:true}});}catch(e){next(e);}});
};
