import { createHash, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const readers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.CEO,UserRole.DOO]);
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening Regulatory QA');return a.legalEntityId;};
const ensureRead=(a:AuthContext)=>{entity(a);if(!readers.has(a.role)&&!owner(a))throw httpError(403,'Company compliance QA access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writers.has(a.role)&&!owner(a))throw httpError(403,'Company compliance QA packet generation access is required');};
const datePattern=/^\d{4}-\d{2}-\d{2}$/;
const packetSchema=z.object({periodStart:z.string().regex(datePattern),periodEnd:z.string().regex(datePattern),label:z.string().trim().max(300).optional().nullable(),notes:z.string().trim().max(5000).optional().nullable()}).refine(v=>v.periodEnd>=v.periodStart,{message:'periodEnd must be on or after periodStart'});
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const today=()=>new Date().toISOString().slice(0,10);
const defaultStart=()=>`${new Date().getUTCFullYear()}-01-01`;
const bounds=(query:express.Request['query'])=>{const periodStart=clean(query.from,10)||defaultStart(),periodEnd=clean(query.to,10)||today();if(!datePattern.test(periodStart)||!datePattern.test(periodEnd)||periodEnd<periodStart)throw httpError(400,'Use valid from/to dates in YYYY-MM-DD order');return{periodStart,periodEnd};};
const number=(v:unknown)=>Number(v||0);
const strings=(v:unknown)=>Array.isArray(v)?v.map(String):[];

async function qaSnapshot(prisma:PrismaClient,a:AuthContext,periodStart:string,periodEnd:string){
 const e=entity(a);
 const [evvTx,evvGate,billingGate,claimStatus,claimAux,screening,incident,register]=await Promise.all([
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT count(*)::int AS total,count(*) FILTER(WHERE "environment"='PRODUCTION')::int AS "productionTotal",count(*) FILTER(WHERE "environment"='PRODUCTION' AND "status"='ACCEPTED')::int AS "productionAccepted",count(*) FILTER(WHERE "environment"='PRODUCTION' AND "status" IN ('REJECTED','FAILED'))::int AS "productionFailed",count(*) FILTER(WHERE "status" IN ('QUEUED','SENT','ACKNOWLEDGED','RETRY_PENDING'))::int AS pending,COALESCE(array_agg("id") FILTER(WHERE "environment"='PRODUCTION' AND "status" IN ('REJECTED','FAILED')),ARRAY[]::text[]) AS "issueIds" FROM "SpireEvvTransmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "createdAt">=$3::date AND "createdAt"<($4::date+1)`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`WITH latest AS (SELECT DISTINCT ON ("serviceEventId") "serviceEventId","decisionCode","ready" FROM "SpireEvvPrebillDecision" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "createdAt">=$3::date AND "createdAt"<($4::date+1) ORDER BY "serviceEventId","createdAt" DESC) SELECT count(*)::int total,count(*) FILTER(WHERE "decisionCode"='PASS' OR "decisionCode"='NOT_REQUIRED')::int passed,count(*) FILTER(WHERE "decisionCode"='BLOCK' OR NOT "ready")::int blocked,COALESCE(array_agg("serviceEventId") FILTER(WHERE "decisionCode"='BLOCK' OR NOT "ready"),ARRAY[]::text[]) AS "issueIds" FROM latest`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`WITH latest AS (SELECT DISTINCT ON ("serviceEventId") "serviceEventId","decisionCode","ready" FROM "SpireDoddBillingValidationDecision" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "createdAt">=$3::date AND "createdAt"<($4::date+1) ORDER BY "serviceEventId","createdAt" DESC) SELECT count(*)::int total,count(*) FILTER(WHERE "decisionCode"='PASS' OR "decisionCode"='NOT_REQUIRED')::int passed,count(*) FILTER(WHERE "decisionCode"='BLOCK' OR NOT "ready")::int blocked,COALESCE(array_agg("serviceEventId") FILTER(WHERE "decisionCode"='BLOCK' OR NOT "ready"),ARRAY[]::text[]) AS "issueIds" FROM latest`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "status",count(*)::int AS count,COALESCE(array_agg("id") FILTER(WHERE "status" IN ('ACK_REJECTED','FAILED','PARTIAL')),ARRAY[]::text[]) AS "issueIds" FROM "RevenueCycleClaimSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "generatedAt">=$3::date AND "generatedAt"<($4::date+1) GROUP BY "status" ORDER BY "status"`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT (SELECT count(*)::int FROM "RevenueCycleRemittance" r WHERE r."organizationId"=$1 AND r."legalEntityId"=$2 AND r."createdAt">=$3::date AND r."createdAt"<($4::date+1)) AS remittances,(SELECT count(*)::int FROM "RevenueCycleExternalWorkflow" w WHERE w."organizationId"=$1 AND w."legalEntityId"=$2 AND w."status" NOT IN ('VERIFIED','CLOSED')) AS "openExternalWorkflows",COALESCE((SELECT array_agg(w."id") FROM "RevenueCycleExternalWorkflow" w WHERE w."organizationId"=$1 AND w."legalEntityId"=$2 AND w."status" NOT IN ('VERIFIED','CLOSED')),ARRAY[]::text[]) AS "workflowIssueIds"`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "status",count(*)::int AS count,COALESCE(array_agg("id") FILTER(WHERE "status" IN ('BLOCKED','EXPIRED')),ARRAY[]::text[]) AS "issueIds",count(*) FILTER(WHERE "nextRecheckDate" IS NOT NULL AND "nextRecheckDate"<CURRENT_DATE)::int AS overdue FROM "EmployeeOhioScreeningCase" WHERE "organizationId"=$1 AND "legalEntityId"=$2 GROUP BY "status" ORDER BY "status"`,a.organizationId,e),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT (SELECT count(*)::int FROM "SpireIncidentRegulatoryCase" c WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."discoveredAt">=$3::date AND c."discoveredAt"<($4::date+1)) AS total,(SELECT count(*)::int FROM "SpireIncidentRegulatoryCase" c WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."status"='ACTIVE' AND c."classification"='PENDING') AS "pendingClassification",(SELECT count(*)::int FROM "SpireIncidentRegulatoryDeadline" d WHERE d."organizationId"=$1 AND d."legalEntityId"=$2 AND d."required"=true AND d."status" NOT IN ('SATISFIED','NOT_APPLICABLE','WAIVED') AND d."dueAt"<NOW()) AS "overdueDeadlines",(SELECT count(*)::int FROM "SpireIncidentUiMonthlyReview" m WHERE m."organizationId"=$1 AND m."legalEntityId"=$2 AND m."monthStart">=date_trunc('month',$3::date)::date AND m."monthStart"<=date_trunc('month',$4::date)::date) AS "monthlyUiReviews",COALESCE((SELECT array_agg(d."id") FROM "SpireIncidentRegulatoryDeadline" d WHERE d."organizationId"=$1 AND d."legalEntityId"=$2 AND d."required"=true AND d."status" NOT IN ('SATISFIED','NOT_APPLICABLE','WAIVED') AND d."dueAt"<NOW()),ARRAY[]::text[]) AS "deadlineIssueIds",COALESCE((SELECT array_agg(c."id") FROM "SpireIncidentRegulatoryCase" c WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."status"='ACTIVE' AND c."classification"='PENDING'),ARRAY[]::text[]) AS "classificationIssueIds"`,a.organizationId,e,periodStart,periodEnd),
  prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT count(*) FILTER(WHERE "status"='EXPIRED')::int AS expired,count(*) FILTER(WHERE "verifiedAt" IS NULL AND "status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE'))::int AS unverified,COALESCE(array_agg("id") FILTER(WHERE "status"='EXPIRED' OR ("verifiedAt" IS NULL AND "status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE'))),ARRAY[]::text[]) AS "issueIds" FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2`,a.organizationId,e),
 ]);
 const tx=evvTx[0]||{},eg=evvGate[0]||{},bg=billingGate[0]||{},ca=claimAux[0]||{},sc=Object.fromEntries(screening.map(r=>[String(r.status),number(r.count)]));
 const claimByStatus=Object.fromEntries(claimStatus.map(r=>[String(r.status),number(r.count)]));
 const claimIssueIds=claimStatus.flatMap(r=>strings(r.issueIds));
 const claimProblems=number(claimByStatus.ACK_REJECTED)+number(claimByStatus.FAILED)+number(claimByStatus.PARTIAL)+number(ca.openExternalWorkflows);
 const screenProblems=number(sc.BLOCKED)+number(sc.EXPIRED)+screening.reduce((sum,r)=>sum+number(r.overdue),0);
 const inc=incident[0]||{},reg=register[0]||{};
 const domains={
  evv:{totalTransmissions:number(tx.total),productionTransmissions:number(tx.productionTotal),productionAccepted:number(tx.productionAccepted),productionFailed:number(tx.productionFailed),pending:number(tx.pending),latestPrebillDecisions:number(eg.total),prebillPassed:number(eg.passed),prebillBlocked:number(eg.blocked),blockers:number(eg.blocked)+number(tx.productionFailed),issueIds:[...strings(eg.issueIds),...strings(tx.issueIds)]},
  doddBilling:{latestDecisions:number(bg.total),passed:number(bg.passed),blocked:number(bg.blocked),blockers:number(bg.blocked),issueIds:strings(bg.issueIds)},
  claims:{byStatus:claimByStatus,remittances:number(ca.remittances),openExternalWorkflows:number(ca.openExternalWorkflows),blockers:claimProblems,issueIds:[...claimIssueIds,...strings(ca.workflowIssueIds)],directElectronicSubmissionConfigured:false,directStateSubmissionConfigured:false},
  workforce:{byStatus:sc,overdueRechecks:screening.reduce((sum,r)=>sum+number(r.overdue),0),blockers:screenProblems,issueIds:screening.flatMap(r=>strings(r.issueIds)),liveRegistryIntegrationConfigured:false},
  incidents:{periodCases:number(inc.total),pendingClassification:number(inc.pendingClassification),overdueDeadlines:number(inc.overdueDeadlines),monthlyUiReviews:number(inc.monthlyUiReviews),blockers:number(inc.pendingClassification)+number(inc.overdueDeadlines),issueIds:[...strings(inc.deadlineIssueIds),...strings(inc.classificationIssueIds)],liveOitmsIntegrationConfigured:false},
  complianceRegister:{expired:number(reg.expired),unverified:number(reg.unverified),blockers:number(reg.expired)+number(reg.unverified),issueIds:strings(reg.issueIds)},
 };
 const blockerCount=Object.values(domains).reduce((sum,d)=>sum+number(d.blockers),0);
 const sourceIndex=Object.fromEntries(Object.entries(domains).map(([key,value])=>[key,value.issueIds]));
 return{generatedAt:new Date().toISOString(),period:{start:periodStart,end:periodEnd},readiness:blockerCount===0?'READY_FOR_INTERNAL_REVIEW':'ATTENTION_REQUIRED',blockerCount,domains,sourceIndex,externalBoundaries:{evvCertificationClaimed:false,claimDirectSubmissionConfigured:false,claimDirectStateSubmissionConfigured:false,workforceRegistryLiveIntegrationConfigured:false,oitmsLiveIntegrationConfigured:false},warning:'QA readiness means internal evidence review only. It is not a state/vendor certification, claim acceptance, or external submission attestation.'};
}

export const registerCompanyComplianceQaRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/company-compliance/qa/summary',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const{periodStart,periodEnd}=bounds(req.query);res.json({data:await qaSnapshot(prisma,a,periodStart,periodEnd)});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/packets',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","packetNumber","packetType","label","periodStart","periodEnd","generatedByUserId","generatedAt","snapshotSha256","exceptionSummary","notes" FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 ORDER BY "generatedAt" DESC LIMIT 250`,a.organizationId,entity(a));res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/packets/:packetId',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.packetId);if(!rows[0])throw httpError(404,'Compliance audit packet was not found');res.json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/company-compliance/qa/packets/:packetId/file.json',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceAuditPacket" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.packetId),row=rows[0];if(!row)throw httpError(404,'Compliance audit packet was not found');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${String(row.packetNumber).replace(/[^A-Za-z0-9_-]/g,'_')}.json"`);res.setHeader('Cache-Control','private, no-store');res.send(JSON.stringify(row,null,2));}catch(e){next(e);}});
 app.post('/api/company-compliance/qa/packets',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=packetSchema.parse(req.body),snapshot=await qaSnapshot(prisma,a,i.periodStart,i.periodEnd),snapshotText=JSON.stringify(snapshot),snapshotSha256=createHash('sha256').update(snapshotText).digest('hex'),id=randomUUID(),packetNumber=`QA-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,8).toUpperCase()}`,exceptionSummary={readiness:snapshot.readiness,blockerCount:snapshot.blockerCount,externalBoundaries:snapshot.externalBoundaries};await prisma.$executeRawUnsafe(`INSERT INTO "CompanyComplianceAuditPacket"("id","organizationId","legalEntityId","packetNumber","packetType","label","periodStart","periodEnd","generatedByUserId","snapshotSha256","sourceIndex","exceptionSummary","snapshot","notes") VALUES($1,$2,$3,$4,'REGULATORY_QA',$5,$6::date,$7::date,$8,$9,$10::jsonb,$11::jsonb,$12::jsonb,$13)`,id,a.organizationId,entity(a),packetNumber,i.label??null,i.periodStart,i.periodEnd,a.userId,snapshotSha256,JSON.stringify(snapshot.sourceIndex),JSON.stringify(exceptionSummary),snapshotText,i.notes??null);await audit?.(a,'GENERATE_COMPANY_COMPLIANCE_AUDIT_PACKET','CompanyComplianceAuditPacket',id,{packetNumber,periodStart:i.periodStart,periodEnd:i.periodEnd,snapshotSha256,blockerCount:snapshot.blockerCount});res.status(201).json({data:{id,packetNumber,snapshotSha256,readiness:snapshot.readiness,blockerCount:snapshot.blockerCount,immutable:true}});}catch(e){next(e);}});
};
