import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const roles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const writeRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening Compliance');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensure=(a:AuthContext)=>{entity(a);if(!roles.has(a.role)&&!owner(a))throw httpError(403,'Company compliance access is required');};
const ensureWrite=(a:AuthContext)=>{ensure(a);if(!writeRoles.has(a.role)&&!owner(a))throw httpError(403,'Company compliance write access is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const categories=['LICENSE','MEDICAID_PROVIDER','CERTIFICATION','INSURANCE','REGISTRATION','CONTRACT','ACCREDITATION','POLICY_REVIEW','FLEET_VEHICLE','DRIVER_COMPLIANCE','FACILITY_HOME','HOME_HEALTH','NMT','SCLS_DODD','CORPORATE','TAX','OTHER'] as const;
const itemSchema=z.object({category:z.enum(categories),requirementName:z.string().trim().min(2).max(300),authority:z.string().trim().max(300).optional().nullable(),referenceNumber:z.string().trim().max(250).optional().nullable(),status:z.enum(['ACTIVE','RENEWAL_IN_PROGRESS','PENDING_VERIFICATION','EXPIRED','SUSPENDED','NOT_APPLICABLE','SUPERSEDED','CLOSED']).default('ACTIVE'),effectiveDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),expirationDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),renewalLeadDays:z.number().int().min(0).max(730).default(60),responsibleUserId:z.string().trim().max(120).optional().nullable(),linkedDocumentId:z.string().trim().max(160).optional().nullable(),documentFolderHint:z.string().trim().max(300).optional().nullable(),verificationMethod:z.string().trim().max(1000).optional().nullable(),notes:z.string().trim().max(10000).optional().nullable(),metadata:z.record(z.unknown()).optional().default({})});
const patchSchema=itemSchema.partial();
const actionSchema=z.object({action:z.enum(['REVIEW','VERIFY','START_RENEWAL','SUBMIT_RENEWAL','RENEW','SUSPEND','SUPERSEDE','CLOSE','COMMENT']),comment:z.string().trim().max(5000).optional().nullable(),renewalConfirmation:z.string().trim().max(1000).optional().nullable(),newExpirationDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),newEffectiveDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable()});
async function event(prisma:PrismaClient,a:AuthContext,id:string,eventType:string,fromStatus:string|null,toStatus:string|null,comment:string|null,metadata:Record<string,unknown>={}){await prisma.$executeRawUnsafe(`INSERT INTO "CompanyComplianceEvent"("id","organizationId","legalEntityId","complianceItemId","eventType","actorUserId","fromStatus","toStatus","comment","metadata") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,randomUUID(),a.organizationId,entity(a),id,eventType,a.userId,fromStatus,toStatus,comment,JSON.stringify(metadata));}
async function refreshExpired(prisma:PrismaClient,a:AuthContext){await prisma.$executeRawUnsafe(`UPDATE "CompanyComplianceItem" SET "status"='EXPIRED',"updatedAt"=NOW() WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "expirationDate" IS NOT NULL AND "expirationDate"<CURRENT_DATE AND "status" IN ('ACTIVE','PENDING_VERIFICATION','RENEWAL_IN_PROGRESS')`,a.organizationId,entity(a));}
export const registerCompanyComplianceRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/company-compliance/context',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","code","displayName","legalName","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));res.json({data:{company:rows[0]||null,role:a.role,write:writeRoles.has(a.role)||owner(a),categories}});}catch(e){next(e);}});
 app.get('/api/company-compliance/items',async(req,res,next)=>{try{const a=authOf(res);ensure(a);await refreshExpired(prisma,a);const status=clean(req.query.status,40),category=clean(req.query.category,80),ownerId=clean(req.query.responsibleUserId,120),days=Math.min(730,Math.max(0,Number(req.query.days||730)));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT item.*,(CASE WHEN item."expirationDate" IS NULL THEN NULL ELSE (item."expirationDate"-CURRENT_DATE)::int END) AS "daysToExpiration",COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e."createdAt" DESC) FROM "CompanyComplianceEvent" e WHERE e."complianceItemId"=item."id"),'[]'::jsonb) AS events FROM "CompanyComplianceItem" item WHERE item."organizationId"=$1 AND item."legalEntityId"=$2 AND ($3='' OR item."status"=$3) AND ($4='' OR item."category"=$4) AND ($5='' OR item."responsibleUserId"=$5) AND (item."expirationDate" IS NULL OR item."expirationDate"<=CURRENT_DATE+$6::int) ORDER BY CASE item."status" WHEN 'EXPIRED' THEN 0 WHEN 'SUSPENDED' THEN 1 WHEN 'RENEWAL_IN_PROGRESS' THEN 2 ELSE 3 END,item."expirationDate" NULLS LAST,item."requirementName"`,a.organizationId,entity(a),status,category,ownerId,days);res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/company-compliance/summary',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);await refreshExpired(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<{status:string;count:number}>>(`SELECT "status",count(*)::int AS count FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 GROUP BY "status"`,a.organizationId,entity(a));const due=await prisma.$queryRawUnsafe<Array<{expired:number;days15:number;days60:number;unverified:number}>>(`SELECT count(*) FILTER(WHERE "expirationDate"<CURRENT_DATE)::int AS expired,count(*) FILTER(WHERE "expirationDate">=CURRENT_DATE AND "expirationDate"<=CURRENT_DATE+15)::int AS days15,count(*) FILTER(WHERE "expirationDate">CURRENT_DATE+15 AND "expirationDate"<=CURRENT_DATE+60)::int AS days60,count(*) FILTER(WHERE "verifiedAt" IS NULL AND "status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE'))::int AS unverified FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2`,a.organizationId,entity(a));res.json({data:{byStatus:rows,expired:due[0]?.expired||0,due15:due[0]?.days15||0,due60:due[0]?.days60||0,unverified:due[0]?.unverified||0}});}catch(e){next(e);}});
 app.post('/api/company-compliance/items',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=itemSchema.parse(req.body);if(i.expirationDate&&i.effectiveDate&&i.expirationDate<i.effectiveDate)throw httpError(400,'Expiration date must be after effective date');const id=randomUUID();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "CompanyComplianceItem"("id","organizationId","legalEntityId","category","requirementName","authority","referenceNumber","status","effectiveDate","expirationDate","renewalLeadDays","responsibleUserId","linkedDocumentId","documentFolderHint","verificationMethod","notes","metadata","createdByUserId") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::date,$10::date,$11,$12,$13,$14,$15,$16,$17::jsonb,$18) RETURNING *`,id,a.organizationId,entity(a),i.category,i.requirementName,i.authority??null,i.referenceNumber??null,i.status,i.effectiveDate??null,i.expirationDate??null,i.renewalLeadDays,i.responsibleUserId??null,i.linkedDocumentId??null,i.documentFolderHint??null,i.verificationMethod??null,i.notes??null,JSON.stringify(i.metadata),a.userId);await event(prisma,a,id,'CREATED',null,i.status,i.notes??null,{category:i.category,authority:i.authority??null});await audit?.(a,'CREATE_COMPANY_COMPLIANCE_ITEM','CompanyComplianceItem',id,{category:i.category,requirementName:i.requirementName});res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.patch('/api/company-compliance/items/:itemId',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const current=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.itemId);if(!current[0])throw httpError(404,'Compliance item was not found');const i=patchSchema.parse(req.body),merged={...current[0],...i};if(merged.expirationDate&&merged.effectiveDate&&String(merged.expirationDate).slice(0,10)<String(merged.effectiveDate).slice(0,10))throw httpError(400,'Expiration date must be after effective date');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "CompanyComplianceItem" SET "category"=COALESCE($1,"category"),"requirementName"=COALESCE($2,"requirementName"),"authority"=CASE WHEN $3::boolean THEN $4 ELSE "authority" END,"referenceNumber"=CASE WHEN $5::boolean THEN $6 ELSE "referenceNumber" END,"status"=COALESCE($7,"status"),"effectiveDate"=CASE WHEN $8::boolean THEN $9::date ELSE "effectiveDate" END,"expirationDate"=CASE WHEN $10::boolean THEN $11::date ELSE "expirationDate" END,"renewalLeadDays"=COALESCE($12,"renewalLeadDays"),"responsibleUserId"=CASE WHEN $13::boolean THEN $14 ELSE "responsibleUserId" END,"linkedDocumentId"=CASE WHEN $15::boolean THEN $16 ELSE "linkedDocumentId" END,"documentFolderHint"=CASE WHEN $17::boolean THEN $18 ELSE "documentFolderHint" END,"verificationMethod"=CASE WHEN $19::boolean THEN $20 ELSE "verificationMethod" END,"notes"=CASE WHEN $21::boolean THEN $22 ELSE "notes" END,"metadata"=CASE WHEN $23::boolean THEN $24::jsonb ELSE "metadata" END,"updatedAt"=NOW() WHERE "organizationId"=$25 AND "legalEntityId"=$26 AND "id"=$27 RETURNING *`,i.category??null,i.requirementName??null,Object.hasOwn(i,'authority'),i.authority??null,Object.hasOwn(i,'referenceNumber'),i.referenceNumber??null,i.status??null,Object.hasOwn(i,'effectiveDate'),i.effectiveDate??null,Object.hasOwn(i,'expirationDate'),i.expirationDate??null,i.renewalLeadDays??null,Object.hasOwn(i,'responsibleUserId'),i.responsibleUserId??null,Object.hasOwn(i,'linkedDocumentId'),i.linkedDocumentId??null,Object.hasOwn(i,'documentFolderHint'),i.documentFolderHint??null,Object.hasOwn(i,'verificationMethod'),i.verificationMethod??null,Object.hasOwn(i,'notes'),i.notes??null,Object.hasOwn(i,'metadata'),i.metadata?JSON.stringify(i.metadata):null,a.organizationId,entity(a),req.params.itemId);await event(prisma,a,req.params.itemId,'UPDATED',String(current[0].status),String(rows[0].status),i.notes??null,{changedFields:Object.keys(i)});await audit?.(a,'UPDATE_COMPANY_COMPLIANCE_ITEM','CompanyComplianceItem',req.params.itemId,{changedFields:Object.keys(i)});res.json({data:rows[0]});}catch(e){next(e);}});
 app.post('/api/company-compliance/items/:itemId/action',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=actionSchema.parse(req.body),rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.itemId),item=rows[0];if(!item)throw httpError(404,'Compliance item was not found');const from=String(item.status);let to=from,eventType='COMMENT';if(i.action==='REVIEW')eventType='REVIEWED';if(i.action==='VERIFY'){eventType='VERIFIED';to=from==='PENDING_VERIFICATION'?'ACTIVE':from;}if(i.action==='START_RENEWAL'){eventType='RENEWAL_STARTED';to='RENEWAL_IN_PROGRESS';}if(i.action==='SUBMIT_RENEWAL'){eventType='RENEWAL_SUBMITTED';to='PENDING_VERIFICATION';}if(i.action==='SUSPEND'){eventType='SUSPENDED';to='SUSPENDED';}if(i.action==='SUPERSEDE'){eventType='SUPERSEDED';to='SUPERSEDED';}if(i.action==='CLOSE'){eventType='CLOSED';to='CLOSED';}if(i.action==='RENEW'){if(!i.newExpirationDate)throw httpError(400,'New expiration date is required for renewal');eventType='RENEWED';to='ACTIVE';}
 await prisma.$executeRawUnsafe(`UPDATE "CompanyComplianceItem" SET "status"=$1,"lastReviewedAt"=CASE WHEN $2 IN ('REVIEW','VERIFY') THEN NOW() ELSE "lastReviewedAt" END,"lastReviewedByUserId"=CASE WHEN $2 IN ('REVIEW','VERIFY') THEN $3 ELSE "lastReviewedByUserId" END,"verifiedAt"=CASE WHEN $2='VERIFY' THEN NOW() WHEN $2='RENEW' THEN NOW() ELSE "verifiedAt" END,"verifiedByUserId"=CASE WHEN $2 IN ('VERIFY','RENEW') THEN $3 ELSE "verifiedByUserId" END,"renewalSubmittedAt"=CASE WHEN $2='SUBMIT_RENEWAL' THEN NOW() ELSE "renewalSubmittedAt" END,"renewalConfirmation"=CASE WHEN $2 IN ('SUBMIT_RENEWAL','RENEW') THEN COALESCE($4,"renewalConfirmation") ELSE "renewalConfirmation" END,"effectiveDate"=CASE WHEN $2='RENEW' AND $5::date IS NOT NULL THEN $5::date ELSE "effectiveDate" END,"expirationDate"=CASE WHEN $2='RENEW' THEN $6::date ELSE "expirationDate" END,"notes"=CASE WHEN $7::text IS NULL THEN "notes" ELSE concat_ws(E'\n',"notes",$7) END,"updatedAt"=NOW() WHERE "organizationId"=$8 AND "legalEntityId"=$9 AND "id"=$10`,to,i.action,a.userId,i.renewalConfirmation??null,i.newEffectiveDate??null,i.newExpirationDate??null,i.comment??null,a.organizationId,entity(a),req.params.itemId);await event(prisma,a,req.params.itemId,eventType,from,to,i.comment??null,{renewalConfirmation:i.renewalConfirmation??null,newExpirationDate:i.newExpirationDate??null});await audit?.(a,`COMPANY_COMPLIANCE_${i.action}`,'CompanyComplianceItem',req.params.itemId,{fromStatus:from,toStatus:to});res.json({data:{id:req.params.itemId,status:to}});}catch(e){next(e);}});
};
