import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.COO]);
const elevatedRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);

const assetSchema=z.object({assetTag:z.string().trim().min(1).max(120),category:z.enum(['COMPUTER','PHONE','TABLET','VEHICLE','BADGE','KEY','UNIFORM','MEDICAL_DEVICE','FURNITURE','TOOL','OTHER']),name:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),manufacturer:z.string().trim().max(240).default(''),model:z.string().trim().max(240).default(''),serialNumber:z.string().trim().max(240).default(''),purchaseDate:z.coerce.date().optional().nullable(),purchaseCost:z.number().nonnegative().optional().nullable(),warrantyEndDate:z.coerce.date().optional().nullable(),status:z.enum(['AVAILABLE','ASSIGNED','IN_REPAIR','LOST','STOLEN','RETIRED','DISPOSED']).default('AVAILABLE'),locationId:z.string().trim().optional().nullable(),condition:z.enum(['NEW','GOOD','FAIR','POOR','DAMAGED']).default('GOOD'),notes:z.string().trim().max(12000).default('')});
const assignmentSchema=z.object({employeeId:z.string().trim().min(1),assignedAt:z.coerce.date(),expectedReturnDate:z.coerce.date().optional().nullable(),conditionAtIssue:z.enum(['NEW','GOOD','FAIR','POOR','DAMAGED']).default('GOOD'),issueNotes:z.string().trim().max(8000).default(''),acknowledgmentRequired:z.boolean().default(true)});
const returnSchema=z.object({returnedAt:z.coerce.date(),conditionAtReturn:z.enum(['GOOD','FAIR','POOR','DAMAGED','LOST','STOLEN']),returnNotes:z.string().trim().max(8000).default(''),chargesAssessed:z.number().nonnegative().default(0)});
const accessSchema=z.object({accessType:z.enum(['BUILDING','SERVICE_HOME','SYSTEM','APPLICATION','EMAIL','VPN','DATABASE','SHARED_DRIVE','KEY','BADGE','VEHICLE','OTHER']),name:z.string().trim().min(2).max(240),identifier:z.string().trim().max(240).default(''),locationId:z.string().trim().optional().nullable(),status:z.enum(['REQUESTED','APPROVED','ACTIVE','SUSPENDED','REVOKED','EXPIRED']).default('ACTIVE'),effectiveAt:z.coerce.date().optional().nullable(),expiresAt:z.coerce.date().optional().nullable(),leastPrivilegeJustification:z.string().trim().max(8000).default(''),notes:z.string().trim().max(12000).default('')});
const maintenanceSchema=z.object({maintenanceType:z.enum(['INSPECTION','REPAIR','PREVENTIVE','REPLACEMENT','CLEANING','OTHER']),reportedAt:z.coerce.date(),scheduledAt:z.coerce.date().optional().nullable(),completedAt:z.coerce.date().optional().nullable(),status:z.enum(['OPEN','SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED']).default('OPEN'),description:z.string().trim().min(2).max(12000),vendor:z.string().trim().max(240).default(''),cost:z.number().nonnegative().optional().nullable(),resolution:z.string().trim().max(12000).default('')});
const facilitySchema=z.object({name:z.string().trim().min(2).max(240),facilityType:z.enum(['OFFICE','SERVICE_HOME','WAREHOUSE','TRAINING_SITE','VEHICLE_LOT','OTHER']),address:z.string().trim().max(8000).default(''),status:z.enum(['ACTIVE','INACTIVE','CLOSED']).default('ACTIVE'),managerUserId:z.string().trim().optional().nullable(),emergencyContact:z.string().trim().max(240).default(''),notes:z.string().trim().max(12000).default('')});
const incidentSchema=z.object({incidentType:z.enum(['LOST_ASSET','STOLEN_ASSET','DAMAGE','SECURITY_BREACH','ACCESS_MISUSE','KEY_LOSS','BADGE_LOSS','VEHICLE_INCIDENT','OTHER']),occurredAt:z.coerce.date(),severity:z.enum(['LOW','MODERATE','HIGH','CRITICAL']),description:z.string().trim().min(2).max(12000),reportedToLawEnforcement:z.boolean().default(false),reportNumber:z.string().trim().max(240).default(''),status:z.enum(['OPEN','INVESTIGATING','RESOLVED','CLOSED']).default('OPEN'),resolution:z.string().trim().max(12000).default('')});

const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
export function registerEmployeeAssetsAccessRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAsset" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"assetTag" TEXT NOT NULL,"category" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"manufacturer" TEXT NOT NULL DEFAULT '',"model" TEXT NOT NULL DEFAULT '',"serialNumber" TEXT NOT NULL DEFAULT '',"purchaseDate" DATE,"purchaseCost" NUMERIC(12,2),"warrantyEndDate" DATE,"status" TEXT NOT NULL DEFAULT 'AVAILABLE',"locationId" TEXT,"condition" TEXT NOT NULL DEFAULT 'GOOD',"notes" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeAsset_asset_tag_unique" ON "EmployeeAsset"("organizationId","assetTag")`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAsset_status_idx" ON "EmployeeAsset"("organizationId","status","category")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAssetAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"assetId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"assignedAt" TIMESTAMPTZ NOT NULL,"expectedReturnDate" DATE,"returnedAt" TIMESTAMPTZ,"conditionAtIssue" TEXT NOT NULL DEFAULT 'GOOD',"conditionAtReturn" TEXT,"issueNotes" TEXT NOT NULL DEFAULT '',"returnNotes" TEXT NOT NULL DEFAULT '',"chargesAssessed" NUMERIC(12,2) NOT NULL DEFAULT 0,"acknowledgmentRequired" BOOLEAN NOT NULL DEFAULT TRUE,"acknowledgedAt" TIMESTAMPTZ,"acknowledgmentComments" TEXT NOT NULL DEFAULT '',"issuedById" TEXT NOT NULL,"returnedById" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeAssetAssignment_active_asset_unique" ON "EmployeeAssetAssignment"("organizationId","assetId") WHERE "returnedAt" IS NULL`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAssetAssignment_employee_idx" ON "EmployeeAssetAssignment"("organizationId","employeeId","returnedAt","expectedReturnDate")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAccessGrant" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"accessType" TEXT NOT NULL,"name" TEXT NOT NULL,"identifier" TEXT NOT NULL DEFAULT '',"locationId" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"effectiveAt" TIMESTAMPTZ,"expiresAt" TIMESTAMPTZ,"leastPrivilegeJustification" TEXT NOT NULL DEFAULT '',"notes" TEXT NOT NULL DEFAULT '',"grantedById" TEXT NOT NULL,"revokedById" TEXT,"revokedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAccessGrant_employee_idx" ON "EmployeeAccessGrant"("organizationId","employeeId","status","expiresAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAssetMaintenance" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"assetId" TEXT NOT NULL,"maintenanceType" TEXT NOT NULL,"reportedAt" TIMESTAMPTZ NOT NULL,"scheduledAt" TIMESTAMPTZ,"completedAt" TIMESTAMPTZ,"status" TEXT NOT NULL DEFAULT 'OPEN',"description" TEXT NOT NULL,"vendor" TEXT NOT NULL DEFAULT '',"cost" NUMERIC(12,2),"resolution" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAssetMaintenance_asset_idx" ON "EmployeeAssetMaintenance"("organizationId","assetId","status","scheduledAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeFacility" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"facilityType" TEXT NOT NULL,"address" TEXT NOT NULL DEFAULT '',"status" TEXT NOT NULL DEFAULT 'ACTIVE',"managerUserId" TEXT,"emergencyContact" TEXT NOT NULL DEFAULT '',"notes" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeFacility_org_idx" ON "EmployeeFacility"("organizationId","status","facilityType","name")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAssetIncident" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"assetId" TEXT,"employeeId" TEXT,"accessGrantId" TEXT,"incidentType" TEXT NOT NULL,"occurredAt" TIMESTAMPTZ NOT NULL,"severity" TEXT NOT NULL,"description" TEXT NOT NULL,"reportedToLawEnforcement" BOOLEAN NOT NULL DEFAULT FALSE,"reportNumber" TEXT NOT NULL DEFAULT '',"status" TEXT NOT NULL DEFAULT 'OPEN',"resolution" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAssetIncident_org_idx" ON "EmployeeAssetIncident"("organizationId","status","severity","occurredAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAssetAccessEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAssetAccessEvent_org_idx" ON "EmployeeAssetAccessEvent"("organizationId","createdAt" DESC)`);
  })().catch(e=>{readyPromise=null;throw e});

  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor asset and access management is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('You are not authorized to manage employee assets or access'),{status:403});return a};
  const requireElevated=async(auth:AuthContext)=>{const a=await actor(auth);if(!a.isOwner&&!elevatedRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage security-sensitive access'),{status:403});return a};
  const employee=async(org:string,id:string)=>{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS "role",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName",p."jobTitle",p."department",COALESCE(p."employmentStatus",'ACTIVE') AS "employmentStatus" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 AND u."id"=$2 LIMIT 1`,org,id);if(!rows[0])throw Object.assign(new Error('Employee was not found'),{status:404});return rows[0]};
  const protectOwner=async(auth:AuthContext,id:string)=>{const row=await employee(auth.organizationId,id);if(normalizeEmail(row.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner asset and access record cannot be changed by another user'),{status:403});return row};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAssetAccessEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-assets/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const a=await actor(auth);const [assets,assignments,accessGrants,maintenance,facilities,incidents,employees]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAsset" WHERE "organizationId"=$1 ORDER BY "status","category","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT a.*,e."displayName",x."assetTag",x."name" AS "assetName",x."category" FROM "EmployeeAssetAssignment" a JOIN "EmployeeAsset" x ON x."id"=a."assetId" AND x."organizationId"=a."organizationId" LEFT JOIN LATERAL (SELECT COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."id"=a."employeeId") e ON TRUE WHERE a."organizationId"=$1 ORDER BY a."returnedAt" NULLS FIRST,a."assignedAt" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT g.*,e."displayName" FROM "EmployeeAccessGrant" g LEFT JOIN LATERAL (SELECT COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."id"=g."employeeId") e ON TRUE WHERE g."organizationId"=$1 ORDER BY g."status",g."accessType",g."name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT m.*,a."assetTag",a."name" AS "assetName" FROM "EmployeeAssetMaintenance" m JOIN "EmployeeAsset" a ON a."id"=m."assetId" AND a."organizationId"=m."organizationId" WHERE m."organizationId"=$1 ORDER BY m."status",m."scheduledAt" NULLS LAST`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeFacility" WHERE "organizationId"=$1 ORDER BY "status","facilityType","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAssetIncident" WHERE "organizationId"=$1 ORDER BY "status","severity" DESC,"occurredAt" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName",p."jobTitle",p."department" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 ORDER BY "displayName"`,auth.organizationId)
  ]);res.json({data:{permissions:{actorIsOwner:a.isOwner,readOnly:auth.role===UserRole.AUDITOR,canManage:writableRoles.has(auth.role)||a.isOwner,canManageSensitive:elevatedRoles.has(auth.role)||a.isOwner},metrics:{assetCount:assets.length,availableAssetCount:assets.filter(r=>r.status==='AVAILABLE').length,assignedAssetCount:assets.filter(r=>r.status==='ASSIGNED').length,maintenanceOpenCount:maintenance.filter(r=>!['COMPLETED','CANCELLED'].includes(r.status)).length,activeAccessCount:accessGrants.filter(r=>r.status==='ACTIVE').length,expiringAccessCount:accessGrants.filter(r=>r.status==='ACTIVE'&&r.expiresAt&&new Date(r.expiresAt).getTime()<Date.now()+30*86400000).length,openIncidentCount:incidents.filter(r=>!['RESOLVED','CLOSED'].includes(r.status)).length,unacknowledgedAssignments:assignments.filter(r=>!r.returnedAt&&r.acknowledgmentRequired&&!r.acknowledgedAt).length},assets,assignments,accessGrants,maintenance,facilities,incidents,employees}})}catch(e){next(e)}});

  app.get('/api/admin/employees/:employeeId/assets-access',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const row=await employee(auth.organizationId,req.params.employeeId);const [assignments,accessGrants,incidents,events]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT x.*,a."assetTag",a."name" AS "assetName",a."category",a."serialNumber" FROM "EmployeeAssetAssignment" x JOIN "EmployeeAsset" a ON a."id"=x."assetId" AND a."organizationId"=x."organizationId" WHERE x."organizationId"=$1 AND x."employeeId"=$2 ORDER BY x."returnedAt" NULLS FIRST,x."assignedAt" DESC`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccessGrant" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "status","accessType","name"`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAssetIncident" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "occurredAt" DESC`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAssetAccessEvent" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC LIMIT 500`,auth.organizationId,row.id)
  ]);res.json({data:{employee:row,assignments,accessGrants,incidents,events}})}catch(e){next(e)}});

  app.post('/api/admin/employee-assets',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=assetSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAsset" ("id","organizationId","assetTag","category","name","description","manufacturer","model","serialNumber","purchaseDate","purchaseCost","warrantyEndDate","status","locationId","condition","notes","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17)`,id,auth.organizationId,input.assetTag,input.category,input.name,input.description,input.manufacturer,input.model,input.serialNumber,input.purchaseDate??null,input.purchaseCost??null,input.warrantyEndDate??null,input.status,input.locationId??null,input.condition,input.notes,auth.userId);await audit?.(auth,'CREATE_EMPLOYEE_ASSET','EmployeeAsset',id,{assetTag:input.assetTag});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-assets/:assetId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAsset" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.assetId))[0];if(!current)return void res.status(404).json({error:'Asset was not found'});const input=assetSchema.parse({...current,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeAsset" SET "assetTag"=$1,"category"=$2,"name"=$3,"description"=$4,"manufacturer"=$5,"model"=$6,"serialNumber"=$7,"purchaseDate"=$8,"purchaseCost"=$9,"warrantyEndDate"=$10,"status"=$11,"locationId"=$12,"condition"=$13,"notes"=$14,"updatedById"=$15,"updatedAt"=NOW() WHERE "organizationId"=$16 AND "id"=$17`,input.assetTag,input.category,input.name,input.description,input.manufacturer,input.model,input.serialNumber,input.purchaseDate??null,input.purchaseCost??null,input.warrantyEndDate??null,input.status,input.locationId??null,input.condition,input.notes,auth.userId,auth.organizationId,current.id);await audit?.(auth,'UPDATE_EMPLOYEE_ASSET','EmployeeAsset',current.id,{assetTag:input.assetTag});res.json({data:{id:current.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-assets/:assetId/assign',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=assignmentSchema.parse(req.body);const row=await protectOwner(auth,input.employeeId);const asset=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAsset" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.assetId))[0];if(!asset)return void res.status(404).json({error:'Asset was not found'});if(!['AVAILABLE','ASSIGNED'].includes(asset.status))return void res.status(409).json({error:'Asset is not available for assignment'});const active=(await prisma.$queryRawUnsafe<any[]>(`SELECT "id" FROM "EmployeeAssetAssignment" WHERE "organizationId"=$1 AND "assetId"=$2 AND "returnedAt" IS NULL LIMIT 1`,auth.organizationId,asset.id))[0];if(active)return void res.status(409).json({error:'Asset already has an active assignment'});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAssetAssignment" ("id","organizationId","assetId","employeeId","assignedAt","expectedReturnDate","conditionAtIssue","issueNotes","acknowledgmentRequired","issuedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,auth.organizationId,asset.id,row.id,input.assignedAt,input.expectedReturnDate??null,input.conditionAtIssue,input.issueNotes,input.acknowledgmentRequired,auth.userId);await prisma.$executeRawUnsafe(`UPDATE "EmployeeAsset" SET "status"='ASSIGNED',"updatedById"=$1,"updatedAt"=NOW() WHERE "id"=$2`,auth.userId,asset.id);await event(auth,row.id,'ASSET_ASSIGNED','ASSET_ASSIGNMENT',id,{assetId:asset.id,assetTag:asset.assetTag});await audit?.(auth,'ASSIGN_EMPLOYEE_ASSET','EmployeeAssetAssignment',id,{employeeId:row.id,assetId:asset.id});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-asset-assignments/:assignmentId/return',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=returnSchema.parse(req.body);const a=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAssetAssignment" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.assignmentId))[0];if(!a)return void res.status(404).json({error:'Asset assignment was not found'});await protectOwner(auth,a.employeeId);if(a.returnedAt)return void res.status(409).json({error:'Asset assignment is already closed'});await prisma.$executeRawUnsafe(`UPDATE "EmployeeAssetAssignment" SET "returnedAt"=$1,"conditionAtReturn"=$2,"returnNotes"=$3,"chargesAssessed"=$4,"returnedById"=$5,"updatedAt"=NOW() WHERE "id"=$6`,input.returnedAt,input.conditionAtReturn,input.returnNotes,input.chargesAssessed,auth.userId,a.id);const nextStatus=['LOST','STOLEN'].includes(input.conditionAtReturn)?input.conditionAtReturn:(input.conditionAtReturn==='DAMAGED'?'IN_REPAIR':'AVAILABLE');await prisma.$executeRawUnsafe(`UPDATE "EmployeeAsset" SET "status"=$1,"condition"=$2,"updatedById"=$3,"updatedAt"=NOW() WHERE "id"=$4`,nextStatus,input.conditionAtReturn==='LOST'||input.conditionAtReturn==='STOLEN'?'DAMAGED':input.conditionAtReturn,auth.userId,a.assetId);await event(auth,a.employeeId,'ASSET_RETURNED','ASSET_ASSIGNMENT',a.id,{condition:input.conditionAtReturn,chargesAssessed:input.chargesAssessed});await audit?.(auth,'RETURN_EMPLOYEE_ASSET','EmployeeAssetAssignment',a.id,{employeeId:a.employeeId,condition:input.conditionAtReturn});res.json({data:{id:a.id,status:nextStatus}})}catch(e){next(e)}});

  app.post('/api/employee/me/assets/:assignmentId/acknowledge',async(req,res,next)=>{try{await ready();const auth=authOf(res);const comments=z.object({comments:z.string().trim().max(8000).default('')}).parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`UPDATE "EmployeeAssetAssignment" SET "acknowledgedAt"=NOW(),"acknowledgmentComments"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "id"=$3 AND "employeeId"=$4 AND "returnedAt" IS NULL AND "acknowledgmentRequired"=TRUE RETURNING *`,comments.comments,auth.organizationId,req.params.assignmentId,auth.userId);if(!rows[0])return void res.status(404).json({error:'Active asset assignment was not found'});await event(auth,auth.userId,'ASSET_ASSIGNMENT_ACKNOWLEDGED','ASSET_ASSIGNMENT',rows[0].id,{});await audit?.(auth,'ACKNOWLEDGE_ASSIGNED_ASSET','EmployeeAssetAssignment',rows[0].id);res.json({data:rows[0]})}catch(e){next(e)}});

  app.post('/api/admin/employees/:employeeId/access-grants',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireElevated(auth);const row=await protectOwner(auth,req.params.employeeId);const input=accessSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAccessGrant" ("id","organizationId","employeeId","accessType","name","identifier","locationId","status","effectiveAt","expiresAt","leastPrivilegeJustification","notes","grantedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,id,auth.organizationId,row.id,input.accessType,input.name,input.identifier,input.locationId??null,input.status,input.effectiveAt??null,input.expiresAt??null,input.leastPrivilegeJustification,input.notes,auth.userId);await event(auth,row.id,'ACCESS_GRANTED','ACCESS_GRANT',id,{accessType:input.accessType,name:input.name});await audit?.(auth,'CREATE_EMPLOYEE_ACCESS_GRANT','EmployeeAccessGrant',id,{employeeId:row.id,accessType:input.accessType});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-access-grants/:grantId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireElevated(auth);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccessGrant" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.grantId))[0];if(!current)return void res.status(404).json({error:'Access grant was not found'});await protectOwner(auth,current.employeeId);const input=accessSchema.parse({...current,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeAccessGrant" SET "accessType"=$1,"name"=$2,"identifier"=$3,"locationId"=$4,"status"=$5,"effectiveAt"=$6,"expiresAt"=$7,"leastPrivilegeJustification"=$8,"notes"=$9,"revokedById"=CASE WHEN $5 IN ('REVOKED','SUSPENDED') THEN $10 ELSE NULL END,"revokedAt"=CASE WHEN $5 IN ('REVOKED','SUSPENDED') THEN NOW() ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$11 AND "id"=$12`,input.accessType,input.name,input.identifier,input.locationId??null,input.status,input.effectiveAt??null,input.expiresAt??null,input.leastPrivilegeJustification,input.notes,auth.userId,auth.organizationId,current.id);await event(auth,current.employeeId,'ACCESS_UPDATED','ACCESS_GRANT',current.id,{status:input.status});await audit?.(auth,'UPDATE_EMPLOYEE_ACCESS_GRANT','EmployeeAccessGrant',current.id,{employeeId:current.employeeId,status:input.status});res.json({data:{id:current.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-assets/:assetId/maintenance',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=maintenanceSchema.parse(req.body);const asset=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAsset" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.assetId))[0];if(!asset)return void res.status(404).json({error:'Asset was not found'});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAssetMaintenance" ("id","organizationId","assetId","maintenanceType","reportedAt","scheduledAt","completedAt","status","description","vendor","cost","resolution","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)`,id,auth.organizationId,asset.id,input.maintenanceType,input.reportedAt,input.scheduledAt??null,input.completedAt??null,input.status,input.description,input.vendor,input.cost??null,input.resolution,auth.userId);if(!['COMPLETED','CANCELLED'].includes(input.status))await prisma.$executeRawUnsafe(`UPDATE "EmployeeAsset" SET "status"='IN_REPAIR',"updatedById"=$1,"updatedAt"=NOW() WHERE "id"=$2`,auth.userId,asset.id);await audit?.(auth,'CREATE_ASSET_MAINTENANCE','EmployeeAssetMaintenance',id,{assetId:asset.id});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-facilities',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=facilitySchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeFacility" ("id","organizationId","name","facilityType","address","status","managerUserId","emergencyContact","notes","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)`,id,auth.organizationId,input.name,input.facilityType,input.address,input.status,input.managerUserId??null,input.emergencyContact,input.notes,auth.userId);await audit?.(auth,'CREATE_EMPLOYEE_FACILITY','EmployeeFacility',id,{name:input.name});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-asset-incidents',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=incidentSchema.parse(req.body);const refs=z.object({assetId:z.string().trim().optional().nullable(),employeeId:z.string().trim().optional().nullable(),accessGrantId:z.string().trim().optional().nullable()}).parse(req.body);if(refs.employeeId)await protectOwner(auth,refs.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAssetIncident" ("id","organizationId","assetId","employeeId","accessGrantId","incidentType","occurredAt","severity","description","reportedToLawEnforcement","reportNumber","status","resolution","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14)`,id,auth.organizationId,refs.assetId??null,refs.employeeId??null,refs.accessGrantId??null,input.incidentType,input.occurredAt,input.severity,input.description,input.reportedToLawEnforcement,input.reportNumber,input.status,input.resolution,auth.userId);await event(auth,refs.employeeId??null,'ASSET_ACCESS_INCIDENT_RECORDED','INCIDENT',id,{incidentType:input.incidentType,severity:input.severity});await audit?.(auth,'CREATE_ASSET_ACCESS_INCIDENT','EmployeeAssetIncident',id,{employeeId:refs.employeeId,assetId:refs.assetId,severity:input.severity});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.get('/api/employee/me/assets-access',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [assignments,accessGrants]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT x.*,a."assetTag",a."name" AS "assetName",a."category",a."serialNumber",a."model" FROM "EmployeeAssetAssignment" x JOIN "EmployeeAsset" a ON a."id"=x."assetId" AND a."organizationId"=x."organizationId" WHERE x."organizationId"=$1 AND x."employeeId"=$2 ORDER BY x."returnedAt" NULLS FIRST,x."assignedAt" DESC`,auth.organizationId,auth.userId),
    prisma.$queryRawUnsafe<any[]>(`SELECT "id","accessType","name","identifier","locationId","status","effectiveAt","expiresAt","notes" FROM "EmployeeAccessGrant" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "status","accessType","name"`,auth.organizationId,auth.userId)
  ]);res.json({data:{assignments,accessGrants,metrics:{activeAssignments:assignments.filter(r=>!r.returnedAt).length,pendingAcknowledgments:assignments.filter(r=>!r.returnedAt&&r.acknowledgmentRequired&&!r.acknowledgedAt).length,activeAccess:accessGrants.filter(r=>r.status==='ACTIVE').length,expiringAccess:accessGrants.filter(r=>r.status==='ACTIVE'&&r.expiresAt&&new Date(r.expiresAt).getTime()<Date.now()+30*86400000).length}}})}catch(e){next(e)}});
}
