import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();

const surveySchema=z.object({title:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),audience:z.enum(['ALL_EMPLOYEES','MANAGERS','CUSTOM']).default('ALL_EMPLOYEES'),anonymous:z.boolean().default(true),opensAt:z.coerce.date().optional().nullable(),closesAt:z.coerce.date().optional().nullable(),recipientUserIds:z.array(z.string().trim().min(1)).max(1000).default([]),questions:z.array(z.object({prompt:z.string().trim().min(1).max(1000),type:z.enum(['RATING','TEXT','YES_NO','MULTIPLE_CHOICE']),required:z.boolean().default(true),options:z.array(z.string().trim().min(1).max(240)).max(20).default([])})).min(1).max(100)});
const responseSchema=z.object({answers:z.array(z.object({questionIndex:z.number().int().min(0),value:z.union([z.string(),z.number(),z.boolean(),z.array(z.string())])})).min(1).max(100)});
const recognitionSchema=z.object({recipientEmployeeId:z.string().trim().min(1),title:z.string().trim().min(2).max(240),message:z.string().trim().min(1).max(4000),category:z.enum(['TEAMWORK','LEADERSHIP','CLIENT_CARE','RELIABILITY','INNOVATION','SAFETY','OTHER']).default('OTHER'),visibility:z.enum(['PRIVATE','TEAM','COMPANY']).default('TEAM')});

export function registerEmployeeEngagementFeedbackRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeEngagementSurvey" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"audience" TEXT NOT NULL DEFAULT 'ALL_EMPLOYEES',"anonymous" BOOLEAN NOT NULL DEFAULT TRUE,"opensAt" TIMESTAMPTZ,"closesAt" TIMESTAMPTZ,"recipientUserIds" JSONB NOT NULL DEFAULT '[]'::jsonb,"questions" JSONB NOT NULL DEFAULT '[]'::jsonb,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeEngagementSurvey_org_idx" ON "EmployeeEngagementSurvey"("organizationId","active","opensAt","closesAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeEngagementResponse" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"surveyId" TEXT NOT NULL,"employeeId" TEXT,"answers" JSONB NOT NULL,"submittedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeEngagementResponse_unique" ON "EmployeeEngagementResponse"("organizationId","surveyId","employeeId") WHERE "employeeId" IS NOT NULL`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeRecognition" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"recipientEmployeeId" TEXT NOT NULL,"senderEmployeeId" TEXT NOT NULL,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"category" TEXT NOT NULL,"visibility" TEXT NOT NULL DEFAULT 'TEAM',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeRecognition_recipient_idx" ON "EmployeeRecognition"("organizationId","recipientEmployeeId","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeEngagementEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor engagement access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage engagement surveys'),{status:403});return a};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeEngagementEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-engagement/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [surveys,responses,recognitions]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeEngagementSurvey" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 300`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeEngagementResponse" WHERE "organizationId"=$1 ORDER BY "submittedAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeRecognition" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 500`,auth.organizationId)
  ]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{activeSurveys:surveys.filter(r=>r.active).length,totalResponses:responses.length,totalRecognitions:recognitions.length},surveys,responses,recognitions}})}catch(e){next(e)}});

  app.post('/api/admin/employee-engagement/surveys',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=surveySchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeEngagementSurvey" ("id","organizationId","title","description","audience","anonymous","opensAt","closesAt","recipientUserIds","questions","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11)`,id,auth.organizationId,input.title,input.description,input.audience,input.anonymous,input.opensAt??null,input.closesAt??null,JSON.stringify(input.recipientUserIds),JSON.stringify(input.questions),auth.userId);await event(auth,null,'ENGAGEMENT_SURVEY_CREATED','ENGAGEMENT_SURVEY',id,{audience:input.audience,anonymous:input.anonymous});await audit?.(auth,'CREATE_EMPLOYEE_ENGAGEMENT_SURVEY','EmployeeEngagementSurvey',id,{audience:input.audience,anonymous:input.anonymous});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.get('/api/employee/me/engagement',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const surveys=await prisma.$queryRawUnsafe<any[]>(`SELECT s.* FROM "EmployeeEngagementSurvey" s WHERE s."organizationId"=$1 AND s."active"=TRUE AND (s."opensAt" IS NULL OR s."opensAt"<=NOW()) AND (s."closesAt" IS NULL OR s."closesAt">NOW()) AND (s."audience"<>'CUSTOM' OR s."recipientUserIds" ? $2) ORDER BY s."createdAt" DESC`,auth.organizationId,auth.userId);const recognitions=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeRecognition" WHERE "organizationId"=$1 AND ("recipientEmployeeId"=$2 OR "visibility"='COMPANY') ORDER BY "createdAt" DESC LIMIT 200`,auth.organizationId,auth.userId);res.json({data:{surveys,recognitions}})}catch(e){next(e)}});

  app.post('/api/employee/me/engagement/surveys/:surveyId/respond',async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=responseSchema.parse(req.body);const survey=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeEngagementSurvey" WHERE "organizationId"=$1 AND "id"=$2 AND "active"=TRUE LIMIT 1`,auth.organizationId,req.params.surveyId))[0];if(!survey)return void res.status(404).json({error:'Survey was not found'});const employeeId=survey.anonymous?null:auth.userId;await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeEngagementResponse" ("id","organizationId","surveyId","employeeId","answers") VALUES ($1,$2,$3,$4,$5::jsonb)`,randomUUID(),auth.organizationId,survey.id,employeeId,JSON.stringify(input.answers));await event(auth,auth.userId,'ENGAGEMENT_SURVEY_RESPONSE_SUBMITTED','ENGAGEMENT_SURVEY',survey.id,{anonymous:survey.anonymous});res.status(201).json({data:{submitted:true}})}catch(e){next(e)}});

  app.post('/api/employee/me/engagement/recognition',async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=recognitionSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeRecognition" ("id","organizationId","recipientEmployeeId","senderEmployeeId","title","message","category","visibility") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,id,auth.organizationId,input.recipientEmployeeId,auth.userId,input.title,input.message,input.category,input.visibility);await event(auth,input.recipientEmployeeId,'EMPLOYEE_RECOGNITION_CREATED','EMPLOYEE_RECOGNITION',id,{category:input.category,visibility:input.visibility});res.status(201).json({data:{id}})}catch(e){next(e)}});
}
