import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.COO]);
const hrRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);

const leavePolicySchema=z.object({name:z.string().trim().min(2).max(240),leaveType:z.enum(['PTO','VACATION','SICK','UNPAID','BEREAVEMENT','JURY_DUTY','MILITARY','PARENTAL','FMLA','MEDICAL','OTHER']),accrualMethod:z.enum(['NONE','PER_PAY_PERIOD','MONTHLY','ANNUAL','HOURS_WORKED']),accrualRate:z.number().nonnegative().default(0),annualGrant:z.number().nonnegative().default(0),maxBalance:z.number().nonnegative().default(0),carryoverLimit:z.number().nonnegative().default(0),waitingDays:z.number().int().min(0).max(3650).default(0),minimumIncrement:z.number().positive().max(24).default(1),requiresApproval:z.boolean().default(true),requiresDocumentation:z.boolean().default(false),active:z.boolean().default(true),description:z.string().trim().max(8000).default('')});
const balanceSchema=z.object({leavePolicyId:z.string().trim().min(1),balanceHours:z.number(),pendingHours:z.number().nonnegative().default(0),usedHours:z.number().nonnegative().default(0),effectiveDate:z.coerce.date(),notes:z.string().trim().max(4000).default('')});
const requestSchema=z.object({leavePolicyId:z.string().trim().min(1),startDate:z.coerce.date(),endDate:z.coerce.date(),hoursRequested:z.number().positive(),reason:z.string().trim().min(2).max(8000),documentationProvided:z.boolean().default(false),emergency:z.boolean().default(false)}).refine(v=>v.endDate>=v.startDate,{message:'Leave end date must be on or after the start date'});
const decisionSchema=z.object({status:z.enum(['APPROVED','REJECTED','CANCELLED']),decisionNotes:z.string().trim().min(2).max(8000)});
const accommodationSchema=z.object({accommodationType:z.enum(['SCHEDULE','DUTY_MODIFICATION','EQUIPMENT','REMOTE_WORK','TRANSFER','LEAVE','OTHER']),requestDate:z.coerce.date(),effectiveDate:z.coerce.date().optional().nullable(),reviewDate:z.coerce.date().optional().nullable(),status:z.enum(['REQUESTED','UNDER_REVIEW','APPROVED','DENIED','IMPLEMENTED','CLOSED']),restrictions:z.string().trim().max(12000).default(''),accommodationDetails:z.string().trim().max(12000).default(''),confidentialNotes:z.string().trim().max(12000).default('')});
const offboardingSchema=z.object({separationType:z.enum(['RESIGNATION','TERMINATION','LAYOFF','RETIREMENT','END_OF_CONTRACT','JOB_ABANDONMENT','DEATH']),noticeDate:z.coerce.date().optional().nullable(),lastWorkingDate:z.coerce.date(),effectiveDate:z.coerce.date(),reason:z.string().trim().min(2).max(12000),eligibleForRehire:z.boolean().default(true),rehireNotes:z.string().trim().max(8000).default(''),finalPayRequired:z.boolean().default(true),benefitsEndDate:z.coerce.date().optional().nullable(),accessEndAt:z.coerce.date().optional().nullable(),exitInterviewRequired:z.boolean().default(true),status:z.enum(['PLANNED','IN_PROGRESS','COMPLETED','CANCELLED']).default('PLANNED')});
const taskSchema=z.object({category:z.enum(['HR','PAYROLL','BENEFITS','IT','SECURITY','EQUIPMENT','TRAINING','MANAGER','FACILITIES','OTHER']),title:z.string().trim().min(2).max(300),description:z.string().trim().max(6000).default(''),assignedToUserId:z.string().trim().optional().nullable(),dueDate:z.coerce.date().optional().nullable(),status:z.enum(['NOT_STARTED','IN_PROGRESS','COMPLETED','BLOCKED','WAIVED']).default('NOT_STARTED'),required:z.boolean().default(true)});
const exitInterviewSchema=z.object({conductedAt:z.coerce.date(),conductedByUserId:z.string().trim().optional().nullable(),reasonForLeaving:z.string().trim().max(8000).default(''),whatWorkedWell:z.string().trim().max(8000).default(''),whatCouldImprove:z.string().trim().max(8000).default(''),managerFeedback:z.string().trim().max(8000).default(''),wouldRecommend:z.boolean().optional().nullable(),wouldReturn:z.boolean().optional().nullable(),confidentialNotes:z.string().trim().max(12000).default('')});

const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
export function registerEmployeeLeaveOffboardingRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLeavePolicy" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"leaveType" TEXT NOT NULL,"accrualMethod" TEXT NOT NULL,"accrualRate" NUMERIC(10,4) NOT NULL DEFAULT 0,"annualGrant" NUMERIC(10,2) NOT NULL DEFAULT 0,"maxBalance" NUMERIC(10,2) NOT NULL DEFAULT 0,"carryoverLimit" NUMERIC(10,2) NOT NULL DEFAULT 0,"waitingDays" INTEGER NOT NULL DEFAULT 0,"minimumIncrement" NUMERIC(6,2) NOT NULL DEFAULT 1,"requiresApproval" BOOLEAN NOT NULL DEFAULT TRUE,"requiresDocumentation" BOOLEAN NOT NULL DEFAULT FALSE,"active" BOOLEAN NOT NULL DEFAULT TRUE,"description" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLeavePolicy_org_idx" ON "EmployeeLeavePolicy"("organizationId","active","leaveType","name")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLeaveBalance" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"leavePolicyId" TEXT NOT NULL,"balanceHours" NUMERIC(10,2) NOT NULL DEFAULT 0,"pendingHours" NUMERIC(10,2) NOT NULL DEFAULT 0,"usedHours" NUMERIC(10,2) NOT NULL DEFAULT 0,"effectiveDate" DATE NOT NULL,"notes" TEXT NOT NULL DEFAULT '',"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeLeaveBalance_employee_policy_unique" ON "EmployeeLeaveBalance"("organizationId","employeeId","leavePolicyId")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLeaveRequest" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"leavePolicyId" TEXT NOT NULL,"startDate" DATE NOT NULL,"endDate" DATE NOT NULL,"hoursRequested" NUMERIC(10,2) NOT NULL,"reason" TEXT NOT NULL,"documentationProvided" BOOLEAN NOT NULL DEFAULT FALSE,"emergency" BOOLEAN NOT NULL DEFAULT FALSE,"status" TEXT NOT NULL DEFAULT 'PENDING',"submittedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"decidedById" TEXT,"decidedAt" TIMESTAMPTZ,"decisionNotes" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLeaveRequest_employee_idx" ON "EmployeeLeaveRequest"("organizationId","employeeId","status","startDate")`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLeaveRequest_pending_idx" ON "EmployeeLeaveRequest"("organizationId","status","submittedAt") WHERE "status"='PENDING'`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAccommodation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"accommodationType" TEXT NOT NULL,"requestDate" DATE NOT NULL,"effectiveDate" DATE,"reviewDate" DATE,"status" TEXT NOT NULL,"restrictions" TEXT NOT NULL DEFAULT '',"accommodationDetails" TEXT NOT NULL DEFAULT '',"confidentialNotes" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAccommodation_employee_idx" ON "EmployeeAccommodation"("organizationId","employeeId","status","reviewDate")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeOffboardingCase" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"separationType" TEXT NOT NULL,"noticeDate" DATE,"lastWorkingDate" DATE NOT NULL,"effectiveDate" DATE NOT NULL,"reason" TEXT NOT NULL,"eligibleForRehire" BOOLEAN NOT NULL DEFAULT TRUE,"rehireNotes" TEXT NOT NULL DEFAULT '',"finalPayRequired" BOOLEAN NOT NULL DEFAULT TRUE,"benefitsEndDate" DATE,"accessEndAt" TIMESTAMPTZ,"exitInterviewRequired" BOOLEAN NOT NULL DEFAULT TRUE,"status" TEXT NOT NULL DEFAULT 'PLANNED',"createdById" TEXT NOT NULL,"completedById" TEXT,"completedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeOffboardingCase_active_employee_unique" ON "EmployeeOffboardingCase"("organizationId","employeeId") WHERE "status" IN ('PLANNED','IN_PROGRESS')`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeOffboardingTask" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"offboardingCaseId" TEXT NOT NULL,"category" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"assignedToUserId" TEXT,"dueDate" DATE,"status" TEXT NOT NULL DEFAULT 'NOT_STARTED',"required" BOOLEAN NOT NULL DEFAULT TRUE,"completedAt" TIMESTAMPTZ,"completedById" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeOffboardingTask_case_idx" ON "EmployeeOffboardingTask"("organizationId","offboardingCaseId","status","dueDate")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeExitInterview" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"offboardingCaseId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"conductedAt" TIMESTAMPTZ NOT NULL,"conductedByUserId" TEXT,"reasonForLeaving" TEXT NOT NULL DEFAULT '',"whatWorkedWell" TEXT NOT NULL DEFAULT '',"whatCouldImprove" TEXT NOT NULL DEFAULT '',"managerFeedback" TEXT NOT NULL DEFAULT '',"wouldRecommend" BOOLEAN,"wouldReturn" BOOLEAN,"confidentialNotes" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeExitInterview_case_unique" ON "EmployeeExitInterview"("organizationId","offboardingCaseId")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLeaveOffboardingEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLeaveOffboardingEvent_org_idx" ON "EmployeeLeaveOffboardingEvent"("organizationId","createdAt" DESC)`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const r=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(r[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor leave and offboarding access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('You are not authorized to modify leave or offboarding records'),{status:403});return a};
  const requireHr=async(auth:AuthContext)=>{const a=await actor(auth);if(!a.isOwner&&!hrRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage accommodations or offboarding'),{status:403});return a};
  const employee=async(org:string,id:string)=>{const r=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS "role",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName",p."jobTitle",p."department",COALESCE(p."employmentStatus",'ACTIVE') AS "employmentStatus" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 AND u."id"=$2 LIMIT 1`,org,id);if(!r[0])throw Object.assign(new Error('Employee was not found'),{status:404});return r[0]};
  const protectOwner=async(auth:AuthContext,id:string)=>{const row=await employee(auth.organizationId,id);if(normalizeEmail(row.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner leave and offboarding record cannot be changed by another user'),{status:403});return row};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLeaveOffboardingEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-leave/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const a=await actor(auth);const [employees,policies,balances,requests,accommodations,cases,tasks]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName",p."jobTitle",p."department",COALESCE(p."employmentStatus",'ACTIVE') AS "employmentStatus" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 ORDER BY "displayName"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeavePolicy" WHERE "organizationId"=$1 ORDER BY "active" DESC,"leaveType","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeaveBalance" WHERE "organizationId"=$1`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT r.*,p."name" AS "policyName",e."displayName" FROM "EmployeeLeaveRequest" r JOIN "EmployeeLeavePolicy" p ON p."id"=r."leavePolicyId" AND p."organizationId"=r."organizationId" LEFT JOIN LATERAL (SELECT COALESCE(NULLIF(c."displayName",''),NULLIF(m."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" m ON m."userId"=u."id" AND m."organizationId"=u."organizationId" WHERE u."id"=r."employeeId") e ON TRUE WHERE r."organizationId"=$1 ORDER BY r."submittedAt" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccommodation" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT c.*,e."displayName" FROM "EmployeeOffboardingCase" c LEFT JOIN LATERAL (SELECT COALESCE(NULLIF(pc."displayName",''),NULLIF(pm."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" pc ON pc."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" pm ON pm."userId"=u."id" AND pm."organizationId"=u."organizationId" WHERE u."id"=c."employeeId") e ON TRUE WHERE c."organizationId"=$1 ORDER BY c."effectiveDate" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingTask" WHERE "organizationId"=$1 ORDER BY "dueDate" NULLS LAST,"createdAt"`,auth.organizationId)
  ]);res.json({data:{permissions:{actorIsOwner:a.isOwner,readOnly:auth.role===UserRole.AUDITOR,canManage:writableRoles.has(auth.role)||a.isOwner,canManageHr:hrRoles.has(auth.role)||a.isOwner},metrics:{employeeCount:employees.length,pendingLeaveCount:requests.filter(r=>r.status==='PENDING').length,employeesOnLeave:requests.filter(r=>r.status==='APPROVED'&&new Date(r.startDate)<=new Date()&&new Date(r.endDate)>=new Date()).length,activeAccommodationCount:accommodations.filter(r=>!['DENIED','CLOSED'].includes(r.status)).length,activeOffboardingCount:cases.filter(r=>['PLANNED','IN_PROGRESS'].includes(r.status)).length,overdueTaskCount:tasks.filter(r=>!['COMPLETED','WAIVED'].includes(r.status)&&r.dueDate&&new Date(r.dueDate)<new Date()).length},employees,policies,balances,requests,accommodations,offboardingCases:cases,tasks}})}catch(e){next(e)}});

  app.get('/api/admin/employees/:employeeId/leave-offboarding',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const row=await employee(auth.organizationId,req.params.employeeId);const [balances,requests,accommodations,cases,events]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT b.*,p."name" AS "policyName",p."leaveType" FROM "EmployeeLeaveBalance" b JOIN "EmployeeLeavePolicy" p ON p."id"=b."leavePolicyId" AND p."organizationId"=b."organizationId" WHERE b."organizationId"=$1 AND b."employeeId"=$2`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT r.*,p."name" AS "policyName",p."leaveType" FROM "EmployeeLeaveRequest" r JOIN "EmployeeLeavePolicy" p ON p."id"=r."leavePolicyId" AND p."organizationId"=r."organizationId" WHERE r."organizationId"=$1 AND r."employeeId"=$2 ORDER BY r."submittedAt" DESC`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccommodation" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingCase" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,row.id),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeaveOffboardingEvent" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC LIMIT 500`,auth.organizationId,row.id)
  ]);for(const c of cases){c.tasks=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingTask" WHERE "organizationId"=$1 AND "offboardingCaseId"=$2 ORDER BY "dueDate" NULLS LAST,"createdAt"`,auth.organizationId,c.id);c.exitInterview=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeExitInterview" WHERE "organizationId"=$1 AND "offboardingCaseId"=$2 LIMIT 1`,auth.organizationId,c.id))[0]||null}res.json({data:{employee:row,balances,requests,accommodations,offboardingCases:cases,events}})}catch(e){next(e)}});

  app.post('/api/admin/employee-leave/policies',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=leavePolicySchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLeavePolicy" ("id","organizationId","name","leaveType","accrualMethod","accrualRate","annualGrant","maxBalance","carryoverLimit","waitingDays","minimumIncrement","requiresApproval","requiresDocumentation","active","description","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16)`,id,auth.organizationId,input.name,input.leaveType,input.accrualMethod,input.accrualRate,input.annualGrant,input.maxBalance,input.carryoverLimit,input.waitingDays,input.minimumIncrement,input.requiresApproval,input.requiresDocumentation,input.active,input.description,auth.userId);await audit?.(auth,'CREATE_LEAVE_POLICY','EmployeeLeavePolicy',id,{name:input.name});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employees/:employeeId/leave-balances',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const row=await protectOwner(auth,req.params.employeeId);const input=balanceSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLeaveBalance" ("id","organizationId","employeeId","leavePolicyId","balanceHours","pendingHours","usedHours","effectiveDate","notes","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT ("organizationId","employeeId","leavePolicyId") DO UPDATE SET "balanceHours"=EXCLUDED."balanceHours","pendingHours"=EXCLUDED."pendingHours","usedHours"=EXCLUDED."usedHours","effectiveDate"=EXCLUDED."effectiveDate","notes"=EXCLUDED."notes","updatedById"=EXCLUDED."updatedById","updatedAt"=NOW()`,id,auth.organizationId,row.id,input.leavePolicyId,input.balanceHours,input.pendingHours,input.usedHours,input.effectiveDate,input.notes,auth.userId);await event(auth,row.id,'LEAVE_BALANCE_UPDATED','LEAVE_BALANCE',id,{policyId:input.leavePolicyId,balanceHours:input.balanceHours});await audit?.(auth,'UPDATE_EMPLOYEE_LEAVE_BALANCE','EmployeeLeaveBalance',id,{employeeId:row.id});res.json({data:{id}})}catch(e){next(e)}});

  app.post('/api/employee/me/leave-requests',async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=requestSchema.parse(req.body);const policy=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeavePolicy" WHERE "organizationId"=$1 AND "id"=$2 AND "active"=TRUE LIMIT 1`,auth.organizationId,input.leavePolicyId))[0];if(!policy)return void res.status(404).json({error:'Active leave policy was not found'});if(policy.requiresDocumentation&&!input.documentationProvided)return void res.status(409).json({error:'Documentation is required for this leave policy'});const id=randomUUID();const initialStatus=policy.requiresApproval?'PENDING':'APPROVED';await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLeaveRequest" ("id","organizationId","employeeId","leavePolicyId","startDate","endDate","hoursRequested","reason","documentationProvided","emergency","status") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,id,auth.organizationId,auth.userId,input.leavePolicyId,input.startDate,input.endDate,input.hoursRequested,input.reason,input.documentationProvided,input.emergency,initialStatus);if(initialStatus==='PENDING')await prisma.$executeRawUnsafe(`UPDATE "EmployeeLeaveBalance" SET "pendingHours"="pendingHours"+$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "employeeId"=$3 AND "leavePolicyId"=$4`,input.hoursRequested,auth.organizationId,auth.userId,input.leavePolicyId);await event(auth,auth.userId,'LEAVE_REQUEST_SUBMITTED','LEAVE_REQUEST',id,{status:initialStatus,hoursRequested:input.hoursRequested});await audit?.(auth,'SUBMIT_EMPLOYEE_LEAVE_REQUEST','EmployeeLeaveRequest',id,{hoursRequested:input.hoursRequested});res.status(201).json({data:{id,status:initialStatus}})}catch(e){next(e)}});

  app.post('/api/admin/employee-leave/requests/:requestId/decision',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=decisionSchema.parse(req.body);const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeaveRequest" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.requestId))[0];if(!r)return void res.status(404).json({error:'Leave request was not found'});await protectOwner(auth,r.employeeId);if(r.status!=='PENDING')return void res.status(409).json({error:'Only pending leave requests can be decided'});await prisma.$executeRawUnsafe(`UPDATE "EmployeeLeaveRequest" SET "status"=$1,"decidedById"=$2,"decidedAt"=NOW(),"decisionNotes"=$3,"updatedAt"=NOW() WHERE "id"=$4`,input.status,auth.userId,input.decisionNotes,r.id);await prisma.$executeRawUnsafe(`UPDATE "EmployeeLeaveBalance" SET "pendingHours"=GREATEST(0,"pendingHours"-$1),"balanceHours"=CASE WHEN $2='APPROVED' THEN "balanceHours"-$1 ELSE "balanceHours" END,"usedHours"=CASE WHEN $2='APPROVED' THEN "usedHours"+$1 ELSE "usedHours" END,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "employeeId"=$4 AND "leavePolicyId"=$5`,Number(r.hoursRequested),input.status,auth.organizationId,r.employeeId,r.leavePolicyId);await event(auth,r.employeeId,'LEAVE_REQUEST_DECIDED','LEAVE_REQUEST',r.id,{status:input.status});await audit?.(auth,'DECIDE_EMPLOYEE_LEAVE_REQUEST','EmployeeLeaveRequest',r.id,{employeeId:r.employeeId,status:input.status});res.json({data:{id:r.id,status:input.status}})}catch(e){next(e)}});

  app.post('/api/admin/employees/:employeeId/accommodations',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const row=await protectOwner(auth,req.params.employeeId);const input=accommodationSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAccommodation" ("id","organizationId","employeeId","accommodationType","requestDate","effectiveDate","reviewDate","status","restrictions","accommodationDetails","confidentialNotes","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)`,id,auth.organizationId,row.id,input.accommodationType,input.requestDate,input.effectiveDate??null,input.reviewDate??null,input.status,input.restrictions,input.accommodationDetails,input.confidentialNotes,auth.userId);await event(auth,row.id,'ACCOMMODATION_CREATED','ACCOMMODATION',id,{type:input.accommodationType,status:input.status});await audit?.(auth,'CREATE_EMPLOYEE_ACCOMMODATION','EmployeeAccommodation',id,{employeeId:row.id});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employees/:employeeId/offboarding',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const row=await protectOwner(auth,req.params.employeeId);const input=offboardingSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeOffboardingCase" ("id","organizationId","employeeId","separationType","noticeDate","lastWorkingDate","effectiveDate","reason","eligibleForRehire","rehireNotes","finalPayRequired","benefitsEndDate","accessEndAt","exitInterviewRequired","status","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,id,auth.organizationId,row.id,input.separationType,input.noticeDate??null,input.lastWorkingDate,input.effectiveDate,input.reason,input.eligibleForRehire,input.rehireNotes,input.finalPayRequired,input.benefitsEndDate??null,input.accessEndAt??null,input.exitInterviewRequired,input.status,auth.userId);const defaults=[['HR','Complete separation documentation'],['PAYROLL','Process final pay'],['BENEFITS','End or convert benefits'],['IT','Disable systems and email access'],['SECURITY','Recover keys, badges and credentials'],['EQUIPMENT','Recover company property'],['MANAGER','Transfer duties and records'],['TRAINING','Remove future training assignments']];for(const [category,title] of defaults)await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeOffboardingTask" ("id","organizationId","offboardingCaseId","category","title","dueDate","required") VALUES ($1,$2,$3,$4,$5,$6,TRUE)`,randomUUID(),auth.organizationId,id,category,title,input.effectiveDate);await event(auth,row.id,'OFFBOARDING_STARTED','OFFBOARDING_CASE',id,{type:input.separationType,status:input.status});await audit?.(auth,'START_EMPLOYEE_OFFBOARDING','EmployeeOffboardingCase',id,{employeeId:row.id,separationType:input.separationType});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-offboarding/:caseId/tasks',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const c=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingCase" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.caseId))[0];if(!c)return void res.status(404).json({error:'Offboarding case was not found'});await protectOwner(auth,c.employeeId);const input=taskSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeOffboardingTask" ("id","organizationId","offboardingCaseId","category","title","description","assignedToUserId","dueDate","status","required") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,auth.organizationId,c.id,input.category,input.title,input.description,input.assignedToUserId??null,input.dueDate??null,input.status,input.required);await event(auth,c.employeeId,'OFFBOARDING_TASK_CREATED','OFFBOARDING_TASK',id,{title:input.title});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-offboarding/tasks/:taskId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const t=(await prisma.$queryRawUnsafe<any[]>(`SELECT t.*,c."employeeId" FROM "EmployeeOffboardingTask" t JOIN "EmployeeOffboardingCase" c ON c."id"=t."offboardingCaseId" AND c."organizationId"=t."organizationId" WHERE t."organizationId"=$1 AND t."id"=$2 LIMIT 1`,auth.organizationId,req.params.taskId))[0];if(!t)return void res.status(404).json({error:'Offboarding task was not found'});await protectOwner(auth,t.employeeId);const input=taskSchema.parse({...t,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeOffboardingTask" SET "category"=$1,"title"=$2,"description"=$3,"assignedToUserId"=$4,"dueDate"=$5,"status"=$6,"required"=$7,"completedAt"=CASE WHEN $6='COMPLETED' THEN NOW() ELSE NULL END,"completedById"=CASE WHEN $6='COMPLETED' THEN $8 ELSE NULL END,"updatedAt"=NOW() WHERE "id"=$9`,input.category,input.title,input.description,input.assignedToUserId??null,input.dueDate??null,input.status,input.required,auth.userId,t.id);await event(auth,t.employeeId,'OFFBOARDING_TASK_UPDATED','OFFBOARDING_TASK',t.id,{status:input.status});res.json({data:{id:t.id,status:input.status}})}catch(e){next(e)}});

  app.post('/api/admin/employee-offboarding/:caseId/exit-interview',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const c=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingCase" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.caseId))[0];if(!c)return void res.status(404).json({error:'Offboarding case was not found'});await protectOwner(auth,c.employeeId);const input=exitInterviewSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeExitInterview" ("id","organizationId","offboardingCaseId","employeeId","conductedAt","conductedByUserId","reasonForLeaving","whatWorkedWell","whatCouldImprove","managerFeedback","wouldRecommend","wouldReturn","confidentialNotes") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT ("organizationId","offboardingCaseId") DO UPDATE SET "conductedAt"=EXCLUDED."conductedAt","conductedByUserId"=EXCLUDED."conductedByUserId","reasonForLeaving"=EXCLUDED."reasonForLeaving","whatWorkedWell"=EXCLUDED."whatWorkedWell","whatCouldImprove"=EXCLUDED."whatCouldImprove","managerFeedback"=EXCLUDED."managerFeedback","wouldRecommend"=EXCLUDED."wouldRecommend","wouldReturn"=EXCLUDED."wouldReturn","confidentialNotes"=EXCLUDED."confidentialNotes","updatedAt"=NOW()`,id,auth.organizationId,c.id,c.employeeId,input.conductedAt,input.conductedByUserId??auth.userId,input.reasonForLeaving,input.whatWorkedWell,input.whatCouldImprove,input.managerFeedback,input.wouldRecommend??null,input.wouldReturn??null,input.confidentialNotes);await event(auth,c.employeeId,'EXIT_INTERVIEW_RECORDED','EXIT_INTERVIEW',id,{});await audit?.(auth,'RECORD_EXIT_INTERVIEW','EmployeeExitInterview',id,{employeeId:c.employeeId});res.json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-offboarding/:caseId/complete',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireHr(auth);const c=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeOffboardingCase" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.caseId))[0];if(!c)return void res.status(404).json({error:'Offboarding case was not found'});await protectOwner(auth,c.employeeId);const open=(await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT COUNT(*)::int AS "count" FROM "EmployeeOffboardingTask" WHERE "organizationId"=$1 AND "offboardingCaseId"=$2 AND "required"=TRUE AND "status" NOT IN ('COMPLETED','WAIVED')`,auth.organizationId,c.id))[0]?.count||0;if(open>0&&!req.body?.force)return void res.status(409).json({error:`${open} required offboarding task(s) remain incomplete`});await prisma.$executeRawUnsafe(`UPDATE "EmployeeOffboardingCase" SET "status"='COMPLETED',"completedById"=$1,"completedAt"=NOW(),"updatedAt"=NOW() WHERE "id"=$2`,auth.userId,c.id);await prisma.$executeRawUnsafe(`UPDATE "EmployeeManagementProfile" SET "employmentStatus"='TERMINATED',"terminationDate"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "userId"=$3`,c.effectiveDate,auth.organizationId,c.employeeId).catch(()=>undefined);await prisma.$executeRawUnsafe(`UPDATE "EmployeePortalCredential" SET "lockedUntil"=COALESCE($1,NOW()),"updatedAt"=NOW() WHERE "userId"=$2`,c.accessEndAt,c.employeeId).catch(()=>undefined);await event(auth,c.employeeId,'OFFBOARDING_COMPLETED','OFFBOARDING_CASE',c.id,{forced:Boolean(req.body?.force),openRequiredTasks:open});await audit?.(auth,'COMPLETE_EMPLOYEE_OFFBOARDING','EmployeeOffboardingCase',c.id,{employeeId:c.employeeId,forced:Boolean(req.body?.force)});res.json({data:{id:c.id,status:'COMPLETED'}})}catch(e){next(e)}});

  app.get('/api/employee/me/leave',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [policies,balances,requests]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLeavePolicy" WHERE "organizationId"=$1 AND "active"=TRUE ORDER BY "leaveType","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT b.*,p."name" AS "policyName",p."leaveType" FROM "EmployeeLeaveBalance" b JOIN "EmployeeLeavePolicy" p ON p."id"=b."leavePolicyId" AND p."organizationId"=b."organizationId" WHERE b."organizationId"=$1 AND b."employeeId"=$2`,auth.organizationId,auth.userId),
    prisma.$queryRawUnsafe<any[]>(`SELECT r.*,p."name" AS "policyName",p."leaveType" FROM "EmployeeLeaveRequest" r JOIN "EmployeeLeavePolicy" p ON p."id"=r."leavePolicyId" AND p."organizationId"=r."organizationId" WHERE r."organizationId"=$1 AND r."employeeId"=$2 ORDER BY r."submittedAt" DESC LIMIT 200`,auth.organizationId,auth.userId)
  ]);res.json({data:{policies,balances,requests,metrics:{availableHours:balances.reduce((s,r)=>s+Number(r.balanceHours||0),0),pendingHours:balances.reduce((s,r)=>s+Number(r.pendingHours||0),0),pendingRequests:requests.filter(r=>r.status==='PENDING').length,approvedUpcoming:requests.filter(r=>r.status==='APPROVED'&&new Date(r.endDate)>=new Date()).length}})}catch(e){next(e)}});
}
