import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';
import { evaluateOhioScreeningCase, loadOhioScreeningCase, latestOhioScreeningChecks } from './employee-ohio-screening.js';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const readers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO,UserRole.HOUSE_MANAGER]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.CEO,UserRole.DOO]);
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before Ohio workforce screening');return a.legalEntityId;};
const ensureRead=(a:AuthContext)=>{entity(a);if(!readers.has(a.role)&&!owner(a))throw httpError(403,'Ohio workforce-screening access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writers.has(a.role)&&!owner(a))throw httpError(403,'Ohio workforce-screening write access is required');};
const clean=(v:unknown,max=5000)=>String(v??'').trim().slice(0,max);
const caseSchema=z.object({profileCode:z.enum(['OH_DODD_DIRECT_SERVICES','OH_HOME_HEALTH_DIRECT_CARE']),positionTitle:z.string().trim().max(300).optional().nullable(),directCare:z.boolean().default(true),transportDuties:z.boolean().default(false),ohioResidentFiveYears:z.boolean().optional().nullable(),rapbackUnavailable:z.boolean().default(false),conditionalEmployment:z.boolean().default(false),conditionalStartDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),hireDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable()});
const casePatchSchema=caseSchema.omit({profileCode:true}).partial().refine(v=>Object.keys(v).length>0,'At least one screening-case change is required');
const checkSchema=z.object({checkCode:z.string().trim().min(2).max(160),result:z.enum(['CLEAR','COMPLETED','ENROLLED','PENDING','HIT','DISQUALIFYING','NOT_APPLICABLE','UNAVAILABLE','EXPIRED']),checkedAt:z.string().datetime(),expiresAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),externalReference:z.string().trim().max(500).optional().nullable(),evidenceDocumentId:z.string().trim().max(160).optional().nullable(),evidenceSummary:z.string().trim().max(2000).optional().nullable(),metadata:z.record(z.unknown()).default({})});
const directServiceRoles=new Set(['DSP','LPN','RN','DELEGATING_NURSE','DRIVER','HOUSE_MANAGER']);
async function employeeExists(p:PrismaClient,a:AuthContext,id:string){const rows=await p.$queryRawUnsafe<Array<{id:string;role:string;email:string}>>(`SELECT "id","role"::text AS role,"email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,id);if(!rows[0])throw httpError(404,'Employee was not found in this Sulandra organization');return rows[0]}
async function entityCode(p:PrismaClient,a:AuthContext){const rows=await p.$queryRawUnsafe<Array<{code:string}>>(`SELECT "code" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));return clean(rows[0]?.code,80).toUpperCase()}
async function profileFor(p:PrismaClient,code:string,at:string){const rows=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeOhioScreeningProfileVersion" WHERE "profileCode"=$1 AND "effectiveFrom"<=$2::date AND ("effectiveTo" IS NULL OR "effectiveTo">=$2::date) ORDER BY "effectiveFrom" DESC,"version" DESC LIMIT 1`,code,at);if(!rows[0])throw httpError(409,`No date-effective Ohio screening profile is configured for ${code} on ${at}`);return rows[0]}
async function screeningEvent(p:PrismaClient,a:AuthContext,caseId:string,eventType:string,fromStatus:string|null,toStatus:string|null,reason:string|null,details:unknown={}){await p.$executeRawUnsafe(`INSERT INTO "EmployeeOhioScreeningEvent"("organizationId","legalEntityId","caseId","eventType","fromStatus","toStatus","reason","details","actorUserId") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)`,a.organizationId,entity(a),caseId,eventType,fromStatus,toStatus,reason,JSON.stringify(details??{}),a.userId)}
async function syncEmployee360Compliance(p:PrismaClient,a:AuthContext,caseId:string,r:Awaited<ReturnType<typeof evaluateOhioScreeningCase>>){const code=`OHIO_SCREENING_${r.profileCode}`;let rows=await p.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "EmployeeComplianceRequirement" WHERE "organizationId"=$1 AND "code"=$2 LIMIT 1`,a.organizationId,code).catch(()=>[]);let requirementId=rows[0]?.id;if(!requirementId){requirementId=randomUUID();await p.$executeRawUnsafe(`INSERT INTO "EmployeeComplianceRequirement"("id","organizationId","code","title","description","category","requirementType","requiredForAll","appliesToRoles","appliesToDepartments","appliesToJobTitles","appliesToLocationIds","employmentStatuses","dueDaysAfterHire","renewalDays","warningWindowDays","critical","active","createdById") VALUES($1,$2,$3,$4,$5,'Background Screening','MANUAL',false,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'["ACTIVE","ON_LEAVE"]'::jsonb,0,1825,90,true,true,$6)`,requirementId,a.organizationId,code,r.profileCode==='OH_DODD_DIRECT_SERVICES'?'Ohio DODD Direct-Service Screening':'Ohio Home Health Direct-Care Screening','Ohio workforce-screening readiness synchronized from append-only screening evidence.',a.userId).catch(()=>{});}if(!requirementId)return;rows=await p.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "EmployeeComplianceAssignment" WHERE "organizationId"=$1 AND "requirementId"=$2 AND "employeeId"=$3 LIMIT 1`,a.organizationId,requirementId,r.employeeId).catch(()=>[]);const assignmentId=rows[0]?.id||randomUUID();if(!rows[0])await p.$executeRawUnsafe(`INSERT INTO "EmployeeComplianceAssignment"("id","organizationId","requirementId","employeeId","status","source","dueDate") VALUES($1,$2,$3,$4,'NOT_STARTED','OHIO_SCREENING',$5::date)`,assignmentId,a.organizationId,requirementId,r.employeeId,r.nextRecheckDate).catch(()=>{});const compliant=r.status==='ELIGIBLE',status=compliant?'COMPLIANT':r.status==='CONDITIONAL'?'IN_PROGRESS':r.status==='EXPIRED'?'OVERDUE':'MISSING',summary=`Ohio screening ${r.status}; ${r.blockers.length} blocker(s), ${r.warnings.length} warning(s).`;await p.$executeRawUnsafe(`UPDATE "EmployeeComplianceAssignment" SET "status"=$1,"dueDate"=$2::date,"completedAt"=CASE WHEN $3 THEN NOW() ELSE NULL END,"expiresAt"=$2::date,"evidenceType"='OHIO_SCREENING_CASE',"evidenceId"=$4,"evidenceSummary"=$5,"manuallyCompletedAt"=CASE WHEN $3 THEN NOW() ELSE NULL END,"manualNotes"=$5,"lastEvaluatedAt"=NOW(),"updatedAt"=NOW() WHERE "id"=$6`,status,r.nextRecheckDate,compliant,caseId,summary,assignmentId).catch(()=>{})}
async function evaluateAndSave(p:PrismaClient,a:AuthContext,caseId:string){const current=await loadOhioScreeningCase(p,a.organizationId,entity(a),caseId),r=await evaluateOhioScreeningCase(p,a.organizationId,entity(a),caseId);await p.$executeRawUnsafe(`UPDATE "EmployeeOhioScreeningCase" SET "status"=$1,"lastEvaluatedAt"=NOW(),"nextRecheckDate"=$2::date,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "id"=$5`,r.status,r.nextRecheckDate,a.organizationId,entity(a),caseId);if(clean(current.status,40)!==r.status)await screeningEvent(p,a,caseId,'READINESS_CHANGED',clean(current.status,40)||null,r.status,null,{blockers:r.blockers,warnings:r.warnings,nextRecheckDate:r.nextRecheckDate});await syncEmployee360Compliance(p,a,caseId,r);return r}
export const registerEmployeeOhioScreeningRoutes=(app:express.Express,p:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/employee360/ohio-screening/profiles',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const profiles=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeOhioScreeningProfileVersion" ORDER BY "profileCode","version" DESC`);res.json({data:{profiles,liveRegistryIntegrationConfigured:false,evidenceMode:'MANUAL_VERIFIED_EVIDENCE',criminalReportContentShouldRemainInConfidentialEmployeeDocuments:true}})}catch(e){next(e)}});
 app.get('/api/employee360/employees/:employeeId/ohio-screening',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);await employeeExists(p,a,req.params.employeeId);const cases=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c.*,p."profileCode",p."name" AS "profileName",p."authority",p."authorityUrl",p."reviewedOn" FROM "EmployeeOhioScreeningCase" c JOIN "EmployeeOhioScreeningProfileVersion" p ON p."id"=c."profileVersionId" WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."employeeId"=$3 ORDER BY c."createdAt" DESC`,a.organizationId,entity(a),req.params.employeeId),data=[];for(const row of cases)data.push({...row,readiness:await evaluateOhioScreeningCase(p,a.organizationId,entity(a),String(row.id)),checks:await latestOhioScreeningChecks(p,a.organizationId,entity(a),String(row.id))});res.json({data})}catch(e){next(e)}});
 app.post('/api/employee360/employees/:employeeId/ohio-screening/cases',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);await employeeExists(p,a,req.params.employeeId);const i=caseSchema.parse(req.body),at=i.hireDate||new Date().toISOString().slice(0,10),profile=await profileFor(p,i.profileCode,at),id=randomUUID();await p.$executeRawUnsafe(`INSERT INTO "EmployeeOhioScreeningCase"("id","organizationId","legalEntityId","employeeId","profileVersionId","positionTitle","directCare","transportDuties","ohioResidentFiveYears","rapbackUnavailable","conditionalEmployment","conditionalStartDate","hireDate","createdByUserId") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::date,$13::date,$14) ON CONFLICT("organizationId","legalEntityId","employeeId","profileVersionId") DO UPDATE SET "positionTitle"=EXCLUDED."positionTitle","directCare"=EXCLUDED."directCare","transportDuties"=EXCLUDED."transportDuties","ohioResidentFiveYears"=EXCLUDED."ohioResidentFiveYears","rapbackUnavailable"=EXCLUDED."rapbackUnavailable","conditionalEmployment"=EXCLUDED."conditionalEmployment","conditionalStartDate"=EXCLUDED."conditionalStartDate","hireDate"=EXCLUDED."hireDate","updatedAt"=NOW()`,id,a.organizationId,entity(a),req.params.employeeId,String(profile.id),i.positionTitle??null,i.directCare,i.transportDuties,i.ohioResidentFiveYears??null,i.rapbackUnavailable,i.conditionalEmployment,i.conditionalStartDate??null,i.hireDate??null,a.userId);const rows=await p.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "EmployeeOhioScreeningCase" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "employeeId"=$3 AND "profileVersionId"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.employeeId,String(profile.id)),caseId=rows[0]?.id||id;await screeningEvent(p,a,caseId,'CASE_CREATED_OR_UPDATED',null,'IN_PROGRESS',null,{profileCode:i.profileCode,transportDuties:i.transportDuties,conditionalEmployment:i.conditionalEmployment});res.status(201).json({data:{caseId,readiness:await evaluateAndSave(p,a,caseId)}})}catch(e){next(e)}});
 app.patch('/api/employee360/ohio-screening/cases/:caseId',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=casePatchSchema.parse(req.body),current=await loadOhioScreeningCase(p,a.organizationId,entity(a),req.params.caseId);await p.$executeRawUnsafe(`UPDATE "EmployeeOhioScreeningCase" SET "positionTitle"=CASE WHEN $1 THEN $2 ELSE "positionTitle" END,"directCare"=CASE WHEN $3 THEN $4 ELSE "directCare" END,"transportDuties"=CASE WHEN $5 THEN $6 ELSE "transportDuties" END,"ohioResidentFiveYears"=CASE WHEN $7 THEN $8 ELSE "ohioResidentFiveYears" END,"rapbackUnavailable"=CASE WHEN $9 THEN $10 ELSE "rapbackUnavailable" END,"conditionalEmployment"=CASE WHEN $11 THEN $12 ELSE "conditionalEmployment" END,"conditionalStartDate"=CASE WHEN $13 THEN $14::date ELSE "conditionalStartDate" END,"hireDate"=CASE WHEN $15 THEN $16::date ELSE "hireDate" END,"updatedAt"=NOW() WHERE "organizationId"=$17 AND "legalEntityId"=$18 AND "id"=$19`,Object.hasOwn(i,'positionTitle'),i.positionTitle??null,Object.hasOwn(i,'directCare'),i.directCare??false,Object.hasOwn(i,'transportDuties'),i.transportDuties??false,Object.hasOwn(i,'ohioResidentFiveYears'),i.ohioResidentFiveYears??null,Object.hasOwn(i,'rapbackUnavailable'),i.rapbackUnavailable??false,Object.hasOwn(i,'conditionalEmployment'),i.conditionalEmployment??false,Object.hasOwn(i,'conditionalStartDate'),i.conditionalStartDate??null,Object.hasOwn(i,'hireDate'),i.hireDate??null,a.organizationId,entity(a),req.params.caseId);await screeningEvent(p,a,req.params.caseId,'CASE_UPDATED',clean(current.status,40),clean(current.status,40),null,i);res.json({data:await evaluateAndSave(p,a,req.params.caseId)})}catch(e){next(e)}});
 app.post('/api/employee360/ohio-screening/cases/:caseId/checks',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);await loadOhioScreeningCase(p,a.organizationId,entity(a),req.params.caseId);const i=checkSchema.parse(req.body),id=randomUUID();await p.$executeRawUnsafe(`INSERT INTO "EmployeeOhioScreeningCheck"("id","organizationId","legalEntityId","caseId","checkCode","result","checkedAt","expiresAt","externalReference","evidenceDocumentId","evidenceSummary","metadata","verifiedByUserId") VALUES($1,$2,$3,$4,$5,$6,$7::timestamptz,$8::date,$9,$10,$11,$12::jsonb,$13)`,id,a.organizationId,entity(a),req.params.caseId,i.checkCode,i.result,i.checkedAt,i.expiresAt??null,i.externalReference??null,i.evidenceDocumentId??null,i.evidenceSummary??null,JSON.stringify(i.metadata),a.userId);await screeningEvent(p,a,req.params.caseId,'CHECK_RECORDED',null,null,`${i.checkCode}: ${i.result}`,{checkId:id,checkCode:i.checkCode,result:i.result,checkedAt:i.checkedAt,externalReference:i.externalReference??null,evidenceDocumentId:i.evidenceDocumentId??null});res.status(201).json({data:{checkId:id,readiness:await evaluateAndSave(p,a,req.params.caseId)}})}catch(e){next(e)}});
 app.post('/api/employee360/ohio-screening/cases/:caseId/evaluate',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);res.json({data:await evaluateAndSave(p,a,req.params.caseId)})}catch(e){next(e)}});
 app.post('/api/admin/service-homes/:id/employees',async(req,res,next)=>{try{const a=authOf(res),employeeId=clean(req.body?.employeeId,160);if(!employeeId||(await entityCode(p,a))!=='SCLS')return void next();const employee=await employeeExists(p,a,employeeId);if(!directServiceRoles.has(clean(employee.role,80).toUpperCase()))return void next();const rows=await p.$queryRawUnsafe<Array<{id:string}>>(`SELECT c."id" FROM "EmployeeOhioScreeningCase" c JOIN "EmployeeOhioScreeningProfileVersion" p ON p."id"=c."profileVersionId" WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."employeeId"=$3 AND p."profileCode"='OH_DODD_DIRECT_SERVICES' ORDER BY c."createdAt" DESC LIMIT 1`,a.organizationId,entity(a),employeeId);if(!rows[0])throw httpError(409,'Ohio DODD direct-service screening is required before assigning this employee to an SCLS service home.',{code:'OHIO_SCREENING_REQUIRED',profileCode:'OH_DODD_DIRECT_SERVICES'});const readiness=await evaluateAndSave(p,a,rows[0].id);if(!readiness.workEligible)throw httpError(409,'Ohio DODD workforce screening blocks this service-home assignment.',{code:'OHIO_SCREENING_BLOCKED',readiness});next()}catch(e){next(e)}});
};
