import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();

const courseSchema=z.object({title:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),category:z.enum(['ORIENTATION','COMPLIANCE','CLINICAL','LEADERSHIP','SAFETY','TECHNOLOGY','CUSTOM']).default('CUSTOM'),deliveryType:z.enum(['ONLINE','IN_PERSON','BLENDED']).default('ONLINE'),durationMinutes:z.number().int().min(1).max(100000).default(60),renewalMonths:z.number().int().min(0).max(120).default(0),active:z.boolean().default(true)});
const assignmentSchema=z.object({employeeId:z.string().trim().min(1),courseId:z.string().trim().min(1),dueAt:z.coerce.date().optional().nullable(),required:z.boolean().default(true)});
const completionSchema=z.object({status:z.enum(['NOT_STARTED','IN_PROGRESS','COMPLETED','FAILED','EXEMPT']),score:z.number().min(0).max(100).optional().nullable(),completedAt:z.coerce.date().optional().nullable(),notes:z.string().trim().max(4000).default('')});
const goalSchema=z.object({title:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),targetDate:z.coerce.date().optional().nullable(),status:z.enum(['PLANNED','IN_PROGRESS','COMPLETED','CANCELLED']).default('PLANNED')});

export function registerEmployeeLearningDevelopmentRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLearningCourse" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"category" TEXT NOT NULL DEFAULT 'CUSTOM',"deliveryType" TEXT NOT NULL DEFAULT 'ONLINE',"durationMinutes" INTEGER NOT NULL DEFAULT 60,"renewalMonths" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLearningCourse_org_idx" ON "EmployeeLearningCourse"("organizationId","active","category","title")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLearningAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"required" BOOLEAN NOT NULL DEFAULT TRUE,"dueAt" TIMESTAMPTZ,"status" TEXT NOT NULL DEFAULT 'NOT_STARTED',"score" DOUBLE PRECISION,"notes" TEXT NOT NULL DEFAULT '',"assignedById" TEXT NOT NULL,"assignedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"startedAt" TIMESTAMPTZ,"completedAt" TIMESTAMPTZ,"expiresAt" TIMESTAMPTZ,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeLearningAssignment_unique" ON "EmployeeLearningAssignment"("organizationId","employeeId","courseId")`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeLearningAssignment_employee_idx" ON "EmployeeLearningAssignment"("organizationId","employeeId","status","dueAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDevelopmentGoal" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"targetDate" TIMESTAMPTZ,"status" TEXT NOT NULL DEFAULT 'PLANNED',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDevelopmentGoal_employee_idx" ON "EmployeeDevelopmentGoal"("organizationId","employeeId","status","targetDate")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLearningEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor learning access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage learning and development'),{status:403});return a};
  const protectOwner=async(auth:AuthContext,employeeId:string)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,employeeId);if(normalizeEmail(rows[0]?.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner learning record cannot be changed by another user'),{status:403})};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLearningEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-learning/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [courses,assignments,goals]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLearningCourse" WHERE "organizationId"=$1 ORDER BY "active" DESC,"category","title"`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT a.*,c."title" AS "courseTitle",c."category" FROM "EmployeeLearningAssignment" a JOIN "EmployeeLearningCourse" c ON c."id"=a."courseId" AND c."organizationId"=a."organizationId" WHERE a."organizationId"=$1 ORDER BY a."assignedAt" DESC LIMIT 1000`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDevelopmentGoal" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId)]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{activeCourses:courses.filter(r=>r.active).length,overdueAssignments:assignments.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','EXEMPT'].includes(r.status)).length,completedAssignments:assignments.filter(r=>r.status==='COMPLETED').length,activeGoals:goals.filter(r=>['PLANNED','IN_PROGRESS'].includes(r.status)).length},courses,assignments,goals}})}catch(e){next(e)}});

  app.post('/api/admin/employee-learning/courses',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=courseSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLearningCourse" ("id","organizationId","title","description","category","deliveryType","durationMinutes","renewalMonths","active","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,auth.organizationId,input.title,input.description,input.category,input.deliveryType,input.durationMinutes,input.renewalMonths,input.active,auth.userId);await event(auth,null,'LEARNING_COURSE_CREATED','LEARNING_COURSE',id,{category:input.category});await audit?.(auth,'CREATE_EMPLOYEE_LEARNING_COURSE','EmployeeLearningCourse',id,{category:input.category});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-learning/assignments',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=assignmentSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLearningAssignment" ("id","organizationId","employeeId","courseId","required","dueAt","assignedById") VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT ("organizationId","employeeId","courseId") DO UPDATE SET "required"=EXCLUDED."required","dueAt"=EXCLUDED."dueAt","updatedAt"=NOW()`,id,auth.organizationId,input.employeeId,input.courseId,input.required,input.dueAt??null,auth.userId);await event(auth,input.employeeId,'LEARNING_ASSIGNED','LEARNING_ASSIGNMENT',id,{courseId:input.courseId});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-learning/assignments/:assignmentId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLearningAssignment" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.assignmentId))[0];if(!current)return void res.status(404).json({error:'Learning assignment was not found'});await protectOwner(auth,current.employeeId);const input=completionSchema.parse({...current,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeLearningAssignment" SET "status"=$1,"score"=$2,"notes"=$3,"startedAt"=CASE WHEN $1='IN_PROGRESS' THEN COALESCE("startedAt",NOW()) ELSE "startedAt" END,"completedAt"=CASE WHEN $1='COMPLETED' THEN COALESCE($4,NOW()) ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "id"=$6`,input.status,input.score??null,input.notes,input.completedAt??null,auth.organizationId,current.id);await event(auth,current.employeeId,'LEARNING_ASSIGNMENT_UPDATED','LEARNING_ASSIGNMENT',current.id,{status:input.status});res.json({data:{id:current.id,status:input.status}})}catch(e){next(e)}});

  app.post('/api/admin/employee-learning/goals/:employeeId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);await protectOwner(auth,req.params.employeeId);const input=goalSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDevelopmentGoal" ("id","organizationId","employeeId","title","description","targetDate","status","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,id,auth.organizationId,req.params.employeeId,input.title,input.description,input.targetDate??null,input.status,auth.userId);await event(auth,req.params.employeeId,'DEVELOPMENT_GOAL_CREATED','DEVELOPMENT_GOAL',id,{status:input.status});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.get('/api/employee/me/learning',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [assignments,goals]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT a.*,c."title",c."description",c."category",c."deliveryType",c."durationMinutes",c."renewalMonths" FROM "EmployeeLearningAssignment" a JOIN "EmployeeLearningCourse" c ON c."id"=a."courseId" AND c."organizationId"=a."organizationId" WHERE a."organizationId"=$1 AND a."employeeId"=$2 ORDER BY a."assignedAt" DESC`,auth.organizationId,auth.userId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDevelopmentGoal" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,auth.userId)]);res.json({data:{assignments,goals,metrics:{required:assignments.filter(r=>r.required).length,completed:assignments.filter(r=>r.status==='COMPLETED').length,overdue:assignments.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','EXEMPT'].includes(r.status)).length,activeGoals:goals.filter(r=>['PLANNED','IN_PROGRESS'].includes(r.status)).length}}})}catch(e){next(e)}});

  app.patch('/api/employee/me/learning/assignments/:assignmentId',async(req,res,next)=>{try{await ready();const auth=authOf(res);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeLearningAssignment" WHERE "organizationId"=$1 AND "employeeId"=$2 AND "id"=$3 LIMIT 1`,auth.organizationId,auth.userId,req.params.assignmentId))[0];if(!current)return void res.status(404).json({error:'Learning assignment was not found'});const input=completionSchema.parse({...current,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeLearningAssignment" SET "status"=$1,"score"=$2,"notes"=$3,"startedAt"=CASE WHEN $1='IN_PROGRESS' THEN COALESCE("startedAt",NOW()) ELSE "startedAt" END,"completedAt"=CASE WHEN $1='COMPLETED' THEN COALESCE($4,NOW()) ELSE "completedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "employeeId"=$6 AND "id"=$7`,input.status,input.score??null,input.notes,input.completedAt??null,auth.organizationId,auth.userId,current.id);await event(auth,auth.userId,'EMPLOYEE_LEARNING_UPDATED','LEARNING_ASSIGNMENT',current.id,{status:input.status});res.json({data:{id:current.id,status:input.status}})}catch(e){next(e)}});
}
