import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();

const incidentSchema=z.object({employeeId:z.string().trim().optional().nullable(),incidentType:z.enum(['INJURY','EXPOSURE','NEAR_MISS','VIOLENCE','HARASSMENT','PROPERTY_DAMAGE','VEHICLE','OTHER']),occurredAt:z.coerce.date(),location:z.string().trim().max(500).default(''),description:z.string().trim().min(1).max(12000),severity:z.enum(['LOW','MODERATE','HIGH','CRITICAL']).default('MODERATE'),medicalAttention:z.boolean().default(false),lostTime:z.boolean().default(false),reportable:z.boolean().default(false)});
const actionSchema=z.object({title:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),assignedToUserId:z.string().trim().optional().nullable(),dueAt:z.coerce.date().optional().nullable(),status:z.enum(['OPEN','IN_PROGRESS','COMPLETED','CANCELLED']).default('OPEN')});
const wellnessSchema=z.object({title:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),programType:z.enum(['EAP','MENTAL_HEALTH','FITNESS','NUTRITION','IMMUNIZATION','SCREENING','WELLNESS','OTHER']).default('WELLNESS'),startsAt:z.coerce.date().optional().nullable(),endsAt:z.coerce.date().optional().nullable(),active:z.boolean().default(true),resourceUrl:z.string().trim().max(1000).default('')});

export function registerEmployeeHealthSafetyWellnessRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeSafetyIncident" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"incidentType" TEXT NOT NULL,"occurredAt" TIMESTAMPTZ NOT NULL,"location" TEXT NOT NULL DEFAULT '',"description" TEXT NOT NULL,"severity" TEXT NOT NULL DEFAULT 'MODERATE',"medicalAttention" BOOLEAN NOT NULL DEFAULT FALSE,"lostTime" BOOLEAN NOT NULL DEFAULT FALSE,"reportable" BOOLEAN NOT NULL DEFAULT FALSE,"status" TEXT NOT NULL DEFAULT 'OPEN',"reportedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeSafetyIncident_org_idx" ON "EmployeeSafetyIncident"("organizationId","status","severity","occurredAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeSafetyAction" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"incidentId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"assignedToUserId" TEXT,"dueAt" TIMESTAMPTZ,"status" TEXT NOT NULL DEFAULT 'OPEN',"completedAt" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeSafetyAction_org_idx" ON "EmployeeSafetyAction"("organizationId","status","dueAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWellnessProgram" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"programType" TEXT NOT NULL DEFAULT 'WELLNESS',"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,"active" BOOLEAN NOT NULL DEFAULT TRUE,"resourceUrl" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeWellnessProgram_org_idx" ON "EmployeeWellnessProgram"("organizationId","active","programType","startsAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeHealthSafetyEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor health and safety access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage health, safety, and wellness records'),{status:403});return a};
  const protectOwner=async(auth:AuthContext,employeeId:string|null|undefined)=>{if(!employeeId)return;const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,employeeId);if(normalizeEmail(rows[0]?.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner health and safety record cannot be changed by another user'),{status:403})};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeHealthSafetyEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-health-safety/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [incidents,actions,programs]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSafetyIncident" WHERE "organizationId"=$1 ORDER BY "occurredAt" DESC LIMIT 500`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSafetyAction" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWellnessProgram" WHERE "organizationId"=$1 ORDER BY "active" DESC,"startsAt" DESC NULLS LAST,"title"`,auth.organizationId)]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{openIncidents:incidents.filter(r=>r.status==='OPEN').length,criticalIncidents:incidents.filter(r=>r.status==='OPEN'&&r.severity==='CRITICAL').length,overdueActions:actions.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','CANCELLED'].includes(r.status)).length,activePrograms:programs.filter(r=>r.active).length},incidents,actions,programs}})}catch(e){next(e)}});

  app.post('/api/admin/employee-health-safety/incidents',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=incidentSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSafetyIncident" ("id","organizationId","employeeId","incidentType","occurredAt","location","description","severity","medicalAttention","lostTime","reportable","reportedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,id,auth.organizationId,input.employeeId??null,input.incidentType,input.occurredAt,input.location,input.description,input.severity,input.medicalAttention,input.lostTime,input.reportable,auth.userId);await event(auth,input.employeeId??null,'SAFETY_INCIDENT_CREATED','SAFETY_INCIDENT',id,{severity:input.severity,incidentType:input.incidentType});await audit?.(auth,'CREATE_EMPLOYEE_SAFETY_INCIDENT','EmployeeSafetyIncident',id,{severity:input.severity});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-health-safety/incidents/:incidentId/actions',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=actionSchema.parse(req.body);const incident=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSafetyIncident" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.incidentId))[0];if(!incident)return void res.status(404).json({error:'Safety incident was not found'});await protectOwner(auth,incident.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSafetyAction" ("id","organizationId","incidentId","title","description","assignedToUserId","dueAt","status","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,id,auth.organizationId,incident.id,input.title,input.description,input.assignedToUserId??null,input.dueAt??null,input.status,auth.userId);await event(auth,incident.employeeId,'SAFETY_ACTION_CREATED','SAFETY_ACTION',id,{incidentId:incident.id});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-health-safety/actions/:actionId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=actionSchema.partial().parse(req.body);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT a.*,i."employeeId" FROM "EmployeeSafetyAction" a JOIN "EmployeeSafetyIncident" i ON i."id"=a."incidentId" AND i."organizationId"=a."organizationId" WHERE a."organizationId"=$1 AND a."id"=$2 LIMIT 1`,auth.organizationId,req.params.actionId))[0];if(!current)return void res.status(404).json({error:'Safety action was not found'});await protectOwner(auth,current.employeeId);await prisma.$executeRawUnsafe(`UPDATE "EmployeeSafetyAction" SET "title"=COALESCE($1,"title"),"description"=COALESCE($2,"description"),"assignedToUserId"=COALESCE($3,"assignedToUserId"),"dueAt"=COALESCE($4,"dueAt"),"status"=COALESCE($5,"status"),"completedAt"=CASE WHEN $5='COMPLETED' THEN NOW() ELSE "completedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$6 AND "id"=$7`,input.title??null,input.description??null,input.assignedToUserId??null,input.dueAt??null,input.status??null,auth.organizationId,current.id);await event(auth,current.employeeId,'SAFETY_ACTION_UPDATED','SAFETY_ACTION',current.id,{status:input.status});res.json({data:{id:current.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-health-safety/wellness-programs',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=wellnessSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWellnessProgram" ("id","organizationId","title","description","programType","startsAt","endsAt","active","resourceUrl","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,auth.organizationId,input.title,input.description,input.programType,input.startsAt??null,input.endsAt??null,input.active,input.resourceUrl,auth.userId);await event(auth,null,'WELLNESS_PROGRAM_CREATED','WELLNESS_PROGRAM',id,{programType:input.programType});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.get('/api/employee/me/health-safety',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [incidents,programs]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSafetyIncident" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "occurredAt" DESC`,auth.organizationId,auth.userId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWellnessProgram" WHERE "organizationId"=$1 AND "active"=TRUE AND ("startsAt" IS NULL OR "startsAt"<=NOW()) AND ("endsAt" IS NULL OR "endsAt">NOW()) ORDER BY "startsAt" DESC NULLS LAST,"title"`,auth.organizationId)]);res.json({data:{incidents,programs,metrics:{openIncidents:incidents.filter(r=>r.status==='OPEN').length,activePrograms:programs.length}}})}catch(e){next(e)}});

  app.post('/api/employee/me/health-safety/incidents',async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=incidentSchema.parse({...req.body,employeeId:auth.userId});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSafetyIncident" ("id","organizationId","employeeId","incidentType","occurredAt","location","description","severity","medicalAttention","lostTime","reportable","reportedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,id,auth.organizationId,auth.userId,input.incidentType,input.occurredAt,input.location,input.description,input.severity,input.medicalAttention,input.lostTime,input.reportable,auth.userId);await event(auth,auth.userId,'EMPLOYEE_SAFETY_INCIDENT_REPORTED','SAFETY_INCIDENT',id,{severity:input.severity});res.status(201).json({data:{id}})}catch(e){next(e)}});
}
