import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();

const templateSchema=z.object({name:z.string().trim().min(2).max(240),category:z.enum(['POLICY','HANDBOOK','ONBOARDING','PERFORMANCE','COMPENSATION','BENEFITS','LEAVE','EQUIPMENT','CONFIDENTIALITY','CONSENT','OTHER']),description:z.string().trim().max(8000).default(''),version:z.string().trim().min(1).max(80),contentHtml:z.string().trim().min(1).max(200000),requiresSignature:z.boolean().default(true),requiresWitness:z.boolean().default(false),active:z.boolean().default(true),visibility:z.enum(['EMPLOYEE','MANAGEMENT','HR_CONFIDENTIAL']).default('EMPLOYEE')});
const assignmentSchema=z.object({employeeId:z.string().trim().min(1),templateId:z.string().trim().min(1),dueAt:z.coerce.date().optional().nullable(),message:z.string().trim().max(8000).default(''),signatureOrder:z.enum(['EMPLOYEE_FIRST','MANAGER_FIRST','PARALLEL']).default('EMPLOYEE_FIRST'),managerSignerId:z.string().trim().optional().nullable(),witnessSignerId:z.string().trim().optional().nullable()});
const signatureSchema=z.object({signatureText:z.string().trim().min(2).max(240),signatureType:z.enum(['TYPED','DRAWN','UPLOADED']).default('TYPED'),consent:z.boolean().refine(Boolean,{message:'Signature consent is required'}),comments:z.string().trim().max(8000).default('')});
const statusSchema=z.object({status:z.enum(['VOIDED','DECLINED','CANCELLED']),reason:z.string().trim().min(2).max(8000)});

export function registerEmployeeDocumentsESignRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDocumentTemplate" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"category" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"version" TEXT NOT NULL,"contentHtml" TEXT NOT NULL,"requiresSignature" BOOLEAN NOT NULL DEFAULT TRUE,"requiresWitness" BOOLEAN NOT NULL DEFAULT FALSE,"active" BOOLEAN NOT NULL DEFAULT TRUE,"visibility" TEXT NOT NULL DEFAULT 'EMPLOYEE',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDocumentTemplate_org_idx" ON "EmployeeDocumentTemplate"("organizationId","active","category","name")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDocumentEnvelope" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"templateId" TEXT NOT NULL,"templateName" TEXT NOT NULL,"templateVersion" TEXT NOT NULL,"documentHtml" TEXT NOT NULL,"message" TEXT NOT NULL DEFAULT '',"signatureOrder" TEXT NOT NULL DEFAULT 'EMPLOYEE_FIRST',"managerSignerId" TEXT,"witnessSignerId" TEXT,"status" TEXT NOT NULL DEFAULT 'PENDING',"dueAt" TIMESTAMPTZ,"sentAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"completedAt" TIMESTAMPTZ,"voidedAt" TIMESTAMPTZ,"voidReason" TEXT NOT NULL DEFAULT '',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDocumentEnvelope_employee_idx" ON "EmployeeDocumentEnvelope"("organizationId","employeeId","status","dueAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDocumentSignature" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"envelopeId" TEXT NOT NULL,"signerUserId" TEXT NOT NULL,"signerRole" TEXT NOT NULL,"signatureText" TEXT NOT NULL,"signatureType" TEXT NOT NULL,"comments" TEXT NOT NULL DEFAULT '',"signedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"ipAddress" TEXT NOT NULL DEFAULT '',"userAgent" TEXT NOT NULL DEFAULT '',"signatureHash" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeDocumentSignature_signer_unique" ON "EmployeeDocumentSignature"("organizationId","envelopeId","signerUserId")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDocumentEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDocumentEvent_org_idx" ON "EmployeeDocumentEvent"("organizationId","createdAt" DESC)`);
  })().catch(e=>{readyPromise=null;throw e});

  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor document access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage document templates and envelopes'),{status:403});return a};
  const employee=async(org:string,id:string)=>{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 AND u."id"=$2 LIMIT 1`,org,id);if(!rows[0])throw Object.assign(new Error('Employee was not found'),{status:404});return rows[0]};
  const protectOwner=async(auth:AuthContext,id:string)=>{const row=await employee(auth.organizationId,id);if(normalizeEmail(row.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner document record cannot be changed by another user'),{status:403});return row};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-documents/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [templates,envelopes,signatures,employees]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentTemplate" WHERE "organizationId"=$1 ORDER BY "active" DESC,"category","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT e.*,COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "EmployeeDocumentEnvelope" e JOIN "User" u ON u."id"=e."employeeId" AND u."organizationId"=e."organizationId" LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE e."organizationId"=$1 ORDER BY e."createdAt" DESC`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentSignature" WHERE "organizationId"=$1 ORDER BY "signedAt" DESC LIMIT 500`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 ORDER BY "displayName"`,auth.organizationId)
  ]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{templateCount:templates.length,pendingCount:envelopes.filter(r=>['PENDING','IN_PROGRESS'].includes(r.status)).length,overdueCount:envelopes.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','VOIDED','DECLINED','CANCELLED'].includes(r.status)).length,completedCount:envelopes.filter(r=>r.status==='COMPLETED').length},templates,envelopes,signatures,employees}})}catch(e){next(e)}});

  app.post('/api/admin/employee-documents/templates',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=templateSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentTemplate" ("id","organizationId","name","category","description","version","contentHtml","requiresSignature","requiresWitness","active","visibility","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)`,id,auth.organizationId,input.name,input.category,input.description,input.version,input.contentHtml,input.requiresSignature,input.requiresWitness,input.active,input.visibility,auth.userId);await event(auth,null,'DOCUMENT_TEMPLATE_CREATED','DOCUMENT_TEMPLATE',id,{name:input.name,version:input.version});await audit?.(auth,'CREATE_EMPLOYEE_DOCUMENT_TEMPLATE','EmployeeDocumentTemplate',id,{name:input.name});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-documents/envelopes',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=assignmentSchema.parse(req.body);const row=await protectOwner(auth,input.employeeId);const template=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentTemplate" WHERE "organizationId"=$1 AND "id"=$2 AND "active"=TRUE LIMIT 1`,auth.organizationId,input.templateId))[0];if(!template)return void res.status(404).json({error:'Active document template was not found'});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentEnvelope" ("id","organizationId","employeeId","templateId","templateName","templateVersion","documentHtml","message","signatureOrder","managerSignerId","witnessSignerId","dueAt","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,id,auth.organizationId,row.id,template.id,template.name,template.version,template.contentHtml,input.message,input.signatureOrder,input.managerSignerId??null,input.witnessSignerId??null,input.dueAt??null,auth.userId);await event(auth,row.id,'DOCUMENT_ENVELOPE_SENT','DOCUMENT_ENVELOPE',id,{templateId:template.id});await audit?.(auth,'SEND_EMPLOYEE_DOCUMENT_ENVELOPE','EmployeeDocumentEnvelope',id,{employeeId:row.id,templateId:template.id});res.status(201).json({data:{id,status:'PENDING'}})}catch(e){next(e)}});

  app.get('/api/employee/me/documents',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [envelopes,signatures]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentEnvelope" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,auth.userId),
    prisma.$queryRawUnsafe<any[]>(`SELECT s.* FROM "EmployeeDocumentSignature" s JOIN "EmployeeDocumentEnvelope" e ON e."id"=s."envelopeId" AND e."organizationId"=s."organizationId" WHERE s."organizationId"=$1 AND e."employeeId"=$2 ORDER BY s."signedAt" DESC`,auth.organizationId,auth.userId)
  ]);res.json({data:{envelopes,signatures,metrics:{pending:envelopes.filter(r=>['PENDING','IN_PROGRESS'].includes(r.status)).length,overdue:envelopes.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','VOIDED','DECLINED','CANCELLED'].includes(r.status)).length,completed:envelopes.filter(r=>r.status==='COMPLETED').length}}});}catch(e){next(e)}});

  app.post('/api/employee/me/documents/:envelopeId/sign',async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=signatureSchema.parse(req.body);const envelope=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentEnvelope" WHERE "organizationId"=$1 AND "id"=$2 AND "employeeId"=$3 LIMIT 1`,auth.organizationId,req.params.envelopeId,auth.userId))[0];if(!envelope)return void res.status(404).json({error:'Document envelope was not found'});if(['COMPLETED','VOIDED','DECLINED','CANCELLED'].includes(envelope.status))return void res.status(409).json({error:'This document can no longer be signed'});const signatureHash=`${auth.organizationId}:${envelope.id}:${auth.userId}:${Date.now()}`;const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentSignature" ("id","organizationId","envelopeId","signerUserId","signerRole","signatureText","signatureType","comments","ipAddress","userAgent","signatureHash") VALUES ($1,$2,$3,$4,'EMPLOYEE',$5,$6,$7,$8,$9,$10) ON CONFLICT ("organizationId","envelopeId","signerUserId") DO NOTHING`,id,auth.organizationId,envelope.id,auth.userId,input.signatureText,input.signatureType,input.comments,String(req.ip||''),String(req.headers['user-agent']||''),signatureHash);await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentEnvelope" SET "status"=CASE WHEN "managerSignerId" IS NULL AND "witnessSignerId" IS NULL THEN 'COMPLETED' ELSE 'IN_PROGRESS' END,"completedAt"=CASE WHEN "managerSignerId" IS NULL AND "witnessSignerId" IS NULL THEN NOW() ELSE NULL END,"updatedAt"=NOW() WHERE "id"=$1`,envelope.id);await event(auth,auth.userId,'DOCUMENT_SIGNED','DOCUMENT_ENVELOPE',envelope.id,{signerRole:'EMPLOYEE'});await audit?.(auth,'SIGN_EMPLOYEE_DOCUMENT','EmployeeDocumentEnvelope',envelope.id,{});res.json({data:{id:envelope.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-documents/envelopes/:envelopeId/sign',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=signatureSchema.parse(req.body);const envelope=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentEnvelope" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.envelopeId))[0];if(!envelope)return void res.status(404).json({error:'Document envelope was not found'});await protectOwner(auth,envelope.employeeId);const signerRole=envelope.managerSignerId===auth.userId?'MANAGER':envelope.witnessSignerId===auth.userId?'WITNESS':null;if(!signerRole&&!((await actor(auth)).isOwner||writableRoles.has(auth.role)))return void res.status(403).json({error:'You are not an authorized signer for this document'});const signatureHash=`${auth.organizationId}:${envelope.id}:${auth.userId}:${Date.now()}`;const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentSignature" ("id","organizationId","envelopeId","signerUserId","signerRole","signatureText","signatureType","comments","ipAddress","userAgent","signatureHash") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT ("organizationId","envelopeId","signerUserId") DO NOTHING`,id,auth.organizationId,envelope.id,auth.userId,signerRole||'ADMIN',input.signatureText,input.signatureType,input.comments,String(req.ip||''),String(req.headers['user-agent']||''),signatureHash);const count=(await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT COUNT(*)::int AS "count" FROM "EmployeeDocumentSignature" WHERE "organizationId"=$1 AND "envelopeId"=$2`,auth.organizationId,envelope.id))[0]?.count||0;const required=1+(envelope.managerSignerId?1:0)+(envelope.witnessSignerId?1:0);await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentEnvelope" SET "status"=CASE WHEN $1>=$2 THEN 'COMPLETED' ELSE 'IN_PROGRESS' END,"completedAt"=CASE WHEN $1>=$2 THEN NOW() ELSE NULL END,"updatedAt"=NOW() WHERE "id"=$3`,count,required,envelope.id);await event(auth,envelope.employeeId,'DOCUMENT_SIGNED','DOCUMENT_ENVELOPE',envelope.id,{signerRole:signerRole||'ADMIN'});res.json({data:{id:envelope.id,status:count>=required?'COMPLETED':'IN_PROGRESS'}})}catch(e){next(e)}});

  app.post('/api/admin/employee-documents/envelopes/:envelopeId/status',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=statusSchema.parse(req.body);const envelope=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDocumentEnvelope" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.envelopeId))[0];if(!envelope)return void res.status(404).json({error:'Document envelope was not found'});await protectOwner(auth,envelope.employeeId);await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentEnvelope" SET "status"=$1,"voidedAt"=NOW(),"voidReason"=$2,"updatedAt"=NOW() WHERE "id"=$3`,input.status,input.reason,envelope.id);await event(auth,envelope.employeeId,'DOCUMENT_STATUS_CHANGED','DOCUMENT_ENVELOPE',envelope.id,{status:input.status});res.json({data:{id:envelope.id,status:input.status}})}catch(e){next(e)}});
}
