import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import nodemailer from 'nodemailer';
import { z } from 'zod';
import { entityAccessOf, requireEntityManageAccess } from './entity-access.js';
import { deleteSecureObject, decryptClientEncryptedObject, getSecureObject, putSecureObject, scanBufferForMalware } from './secure-object-storage.js';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO,UserRole.AUDITOR] as const;
const writeRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(value:unknown)=>String(value??'').trim().toLowerCase();
const safeName=(value:string)=>value.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180)||'document';
const uploadSchema=z.object({employeeId:z.string().trim().min(1),category:z.string().trim().min(1).max(120),fileName:z.string().trim().min(1).max(255),mimeType:z.string().trim().min(1).max(160),fileDataBase64:z.string().min(1),retentionUntil:z.coerce.date().optional().nullable(),legalHold:z.boolean().default(false),sensitivity:z.enum(['GENERAL','HR_CONFIDENTIAL','MEDICAL','BACKGROUND','DISCIPLINARY','IDENTITY','COMPENSATION']).default('GENERAL'),reason:z.string().trim().min(3).max(2000)});
const migrationSchema=z.object({limit:z.coerce.number().int().min(1).max(100).default(20),deleteBase64AfterMigration:z.boolean().default(true)});
const onboardingSchema=z.object({applicationId:z.string().trim().min(1),employeeId:z.string().trim().min(1),reason:z.string().trim().min(3).max(2000)});
const lifecycleSchema=z.object({limit:z.coerce.number().int().min(1).max(500).default(100),dryRun:z.boolean().default(true)});
const reminderSchema=z.object({organizationId:z.string().trim().optional(),dryRun:z.boolean().default(false)});

function smtpTransport(){
  const host=process.env.SMTP_HOST;const user=process.env.SMTP_USER;const pass=process.env.SMTP_PASS;
  if(!host||!user||!pass)return null;
  return nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user,pass}});
}

export function registerEmployee360SecureFilesRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeSecureDocument" (
      "id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"sourceType" TEXT NOT NULL DEFAULT 'EMPLOYEE',"sourceId" TEXT,
      "category" TEXT NOT NULL,"sensitivity" TEXT NOT NULL DEFAULT 'GENERAL',"fileName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" BIGINT NOT NULL,
      "bucket" TEXT NOT NULL,"objectKey" TEXT NOT NULL,"sha256" TEXT NOT NULL,"etag" TEXT,"encryption" TEXT NOT NULL,"kmsKeyId" TEXT,"ivBase64" TEXT,"authTagBase64" TEXT,
      "malwareStatus" TEXT NOT NULL,"malwareEngine" TEXT,"malwareSignature" TEXT,"malwareDetail" TEXT,"version" INTEGER NOT NULL DEFAULT 1,
      "replacesDocumentId" TEXT,"retentionUntil" TIMESTAMPTZ,"legalHold" BOOLEAN NOT NULL DEFAULT FALSE,"status" TEXT NOT NULL DEFAULT 'ACTIVE',
      "uploadedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeSecureDocument_object_unique" ON "EmployeeSecureDocument"("bucket","objectKey")`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeSecureDocument_employee_idx" ON "EmployeeSecureDocument"("organizationId","employeeId","category","status","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeSecureDocument_hash_idx" ON "EmployeeSecureDocument"("organizationId","sha256")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDocumentAccessLog" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"documentId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"actorUserId" TEXT NOT NULL,"action" TEXT NOT NULL,"decision" TEXT NOT NULL,"reason" TEXT,"ipAddress" TEXT,"userAgent" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDocumentAccessLog_doc_idx" ON "EmployeeDocumentAccessLog"("organizationId","documentId","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeOnboardingLink" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"legalEntityId" TEXT NOT NULL,"departmentId" TEXT,"applicationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"linkedById" TEXT NOT NULL,"reason" TEXT NOT NULL,"linkedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE("organizationId","applicationId"),UNIQUE("organizationId","employeeId","applicationId"))`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeOnboardingSnapshot" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"legalEntityId" TEXT NOT NULL,"departmentId" TEXT,"applicationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"applicationData" JSONB NOT NULL DEFAULT '{}'::jsonb,"assessmentData" JSONB,"statusHistory" JSONB NOT NULL DEFAULT '[]'::jsonb,"interviews" JSONB NOT NULL DEFAULT '[]'::jsonb,"messages" JSONB NOT NULL DEFAULT '[]'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE("organizationId","applicationId"))`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeComplianceReminderRun" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"runKey" TEXT NOT NULL,"startedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"completedAt" TIMESTAMPTZ,"status" TEXT NOT NULL DEFAULT 'RUNNING',"processed" INTEGER NOT NULL DEFAULT 0,"sent" INTEGER NOT NULL DEFAULT 0,"failed" INTEGER NOT NULL DEFAULT 0,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,UNIQUE("organizationId","runKey"))`);
  })().catch(error=>{readyPromise=null;throw error});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);const email=normalizeEmail(rows[0]?.email||auth.email);return{email,isOwner:email===OWNER_EMAIL}};
  const requireWrite=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writeRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage secure employee files'),{status:403});return a};
  const protectOwner=async(auth:AuthContext,employeeId:string)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,employeeId);if(normalizeEmail(rows[0]?.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner record cannot be changed by another user'),{status:403})};
  const accessLog=(auth:AuthContext,documentId:string,employeeId:string,action:string,decision:string,reason='')=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentAccessLog" ("id","organizationId","documentId","employeeId","actorUserId","action","decision","reason","ipAddress","userAgent") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,randomUUID(),auth.organizationId,documentId,employeeId,auth.userId,action,decision,reason,auth.ipAddress??null,auth.userAgent??null);

  async function storeDocument(auth:AuthContext,input:{employeeId:string;category:string;fileName:string;mimeType:string;buffer:Buffer;retentionUntil?:Date|null;legalHold?:boolean;sensitivity?:string;reason:string;sourceType?:string;sourceId?:string|null}){
    await protectOwner(auth,input.employeeId);
    const scan=await scanBufferForMalware(input.buffer);
    const allowUnavailable=process.env.ALLOW_UPLOAD_WHEN_MALWARE_SCANNER_UNAVAILABLE==='true';
    if(scan.status==='INFECTED')throw Object.assign(new Error(`Upload blocked: malware detected (${scan.signature||'unknown'})`),{status:422});
    if(scan.status==='UNAVAILABLE'&&!allowUnavailable)throw Object.assign(new Error('Upload blocked because malware scanning is unavailable'),{status:503});
    const duplicate=(await prisma.$queryRawUnsafe<any[]>(`SELECT "id","fileName" FROM "EmployeeSecureDocument" WHERE "organizationId"=$1 AND "employeeId"=$2 AND "sha256"=$3 AND "status"='ACTIVE' LIMIT 1`,auth.organizationId,input.employeeId,(await import('node:crypto')).createHash('sha256').update(input.buffer).digest('hex')))[0];
    if(duplicate)throw Object.assign(new Error(`An identical file already exists as ${duplicate.fileName}`),{status:409,documentId:duplicate.id});
    const id=randomUUID();
    const key=`organizations/${auth.organizationId}/employees/${input.employeeId}/${new Date().getUTCFullYear()}/${id}-${safeName(input.fileName)}`;
    const stored=await putSecureObject({key,body:input.buffer,contentType:input.mimeType,metadata:{organization:auth.organizationId,employee:input.employeeId,document:id,category:input.category}});
    const previous=(await prisma.$queryRawUnsafe<any[]>(`SELECT "id","version" FROM "EmployeeSecureDocument" WHERE "organizationId"=$1 AND "employeeId"=$2 AND "category"=$3 AND "status"='ACTIVE' ORDER BY "version" DESC,"createdAt" DESC LIMIT 1`,auth.organizationId,input.employeeId,input.category))[0];
    const version=Number(previous?.version||0)+1;
    await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSecureDocument" ("id","organizationId","employeeId","sourceType","sourceId","category","sensitivity","fileName","mimeType","sizeBytes","bucket","objectKey","sha256","etag","encryption","kmsKeyId","ivBase64","authTagBase64","malwareStatus","malwareEngine","malwareSignature","malwareDetail","version","replacesDocumentId","retentionUntil","legalHold","uploadedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27)`,id,auth.organizationId,input.employeeId,input.sourceType||'EMPLOYEE',input.sourceId??null,input.category,input.sensitivity||'GENERAL',input.fileName,input.mimeType,stored.sizeBytes,stored.bucket,stored.key,stored.sha256,stored.etag,stored.encryption,stored.kmsKeyId,stored.ivBase64,stored.authTagBase64,scan.status,scan.engine,scan.signature,scan.detail,version,previous?.id??null,input.retentionUntil??null,Boolean(input.legalHold),auth.userId);
    if(previous?.id)await prisma.$executeRawUnsafe(`UPDATE "EmployeeSecureDocument" SET "status"='SUPERSEDED',"updatedAt"=NOW() WHERE "organizationId"=$1 AND "id"=$2`,auth.organizationId,previous.id);
    await accessLog(auth,id,input.employeeId,'UPLOAD','ALLOW',input.reason);
    await audit?.(auth,'UPLOAD_SECURE_EMPLOYEE_DOCUMENT','EmployeeSecureDocument',id,{employeeId:input.employeeId,category:input.category,version,sha256:stored.sha256,malwareStatus:scan.status});
    return{id,version,sha256:stored.sha256,malwareStatus:scan.status,encryption:stored.encryption};
  }

  app.get('/api/admin/employee360/secure-files',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const employeeId=String(req.query.employeeId||'');const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT d.*,COALESCE((SELECT COUNT(*)::int FROM "EmployeeDocumentAccessLog" l WHERE l."organizationId"=d."organizationId" AND l."documentId"=d."id"),0) AS "accessCount" FROM "EmployeeSecureDocument" d WHERE d."organizationId"=$1 AND ($2='' OR d."employeeId"=$2) ORDER BY d."createdAt" DESC LIMIT 1000`,auth.organizationId,employeeId);res.json({data:rows})}catch(error){next(error)}});

  app.post('/api/admin/employee360/secure-files',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWrite(auth);const input=uploadSchema.parse(req.body);const buffer=Buffer.from(input.fileDataBase64,'base64');if(!buffer.length||buffer.length>25_000_000)return void res.status(400).json({error:'File must be between 1 byte and 25 MB'});const result=await storeDocument(auth,{...input,buffer});res.status(201).json({data:result})}catch(error){next(error)}});

  app.get('/api/admin/employee360/secure-files/:documentId/download',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const row=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSecureDocument" WHERE "organizationId"=$1 AND "id"=$2 AND "status"<>'DESTROYED' LIMIT 1`,auth.organizationId,req.params.documentId))[0];if(!row)return void res.status(404).json({error:'Document not found'});let buffer=await getSecureObject(row.objectKey);if(row.encryption==='CLIENT-AES-256-GCM')buffer=decryptClientEncryptedObject(buffer,row.ivBase64,row.authTagBase64);await accessLog(auth,row.id,row.employeeId,'DOWNLOAD','ALLOW','Authorized employee file download');res.setHeader('content-type',row.mimeType);res.setHeader('content-disposition',`attachment; filename="${String(row.fileName).replace(/["\r\n]/g,'_')}"`);res.setHeader('content-length',String(buffer.length));res.send(buffer)}catch(error){next(error)}});

  app.post('/api/admin/employee360/secure-files/migrate-base64',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const access=entityAccessOf(res);requireEntityManageAccess(access);await requireWrite(auth);const input=migrationSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT d.*,a."organizationId" FROM "ApplicantDocument" d JOIN "EmployeeApplication" a ON a."id"=d."applicationId" WHERE a."organizationId"=$1 AND a."legalEntityId"=$2 AND ($3::text IS NULL OR a."departmentId"=$3) AND d."fileData" IS NOT NULL ORDER BY d."createdAt" LIMIT $4`,auth.organizationId,access.legalEntityId,access.departmentId,input.limit);let migrated=0,failed=0;const errors:any[]=[];for(const row of rows){try{const link=(await prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId" FROM "EmployeeOnboardingLink" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "applicationId"=$3 LIMIT 1`,auth.organizationId,access.legalEntityId,row.applicationId))[0];if(!link)throw new Error('Applicant is not linked to an employee');await storeDocument(auth,{employeeId:link.employeeId,category:String(row.category||'ONBOARDING'),fileName:String(row.fileName||row.label||'applicant-document'),mimeType:String(row.mimeType||'application/octet-stream'),buffer:Buffer.from(row.fileData),reason:'Migrate legacy applicant Base64 document',sourceType:'APPLICANT',sourceId:row.id,sensitivity:String(row.category||'').includes('BACKGROUND')?'BACKGROUND':'GENERAL'});if(input.deleteBase64AfterMigration)await prisma.$executeRawUnsafe(`UPDATE "ApplicantDocument" SET "fileData"=NULL,"storagePath"=$1,"updatedAt"=NOW() WHERE "id"=$2`, `employee-secure-document:${row.id}`,row.id);migrated++}catch(error){failed++;errors.push({id:row.id,error:error instanceof Error?error.message:String(error)})}}res.json({data:{selected:rows.length,migrated,failed,errors}})}catch(error){next(error)}});

  app.post('/api/admin/employee360/onboarding/convert',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const access=entityAccessOf(res);requireEntityManageAccess(access);await requireWrite(auth);const input=onboardingSchema.parse(req.body);await protectOwner(auth,input.employeeId);const application=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeApplication" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ($3::text IS NULL OR "departmentId"=$3) AND "id"=$4 LIMIT 1`,auth.organizationId,access.legalEntityId,access.departmentId,input.applicationId))[0];if(!application)return void res.status(404).json({error:'Applicant record not found'});const employment=(await prisma.$queryRawUnsafe<any[]>(`SELECT "departmentId" FROM "Employment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "status"<>'TERMINATED' LIMIT 1`,auth.organizationId,access.legalEntityId,input.employeeId))[0];if(!employment)return void res.status(409).json({error:'The employee must have an active employment in the selected company before onboarding can be converted'});await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeOnboardingLink" ("id","organizationId","legalEntityId","departmentId","applicationId","employeeId","linkedById","reason") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("organizationId","applicationId") DO UPDATE SET "legalEntityId"=EXCLUDED."legalEntityId","departmentId"=EXCLUDED."departmentId","employeeId"=EXCLUDED."employeeId","linkedById"=EXCLUDED."linkedById","reason"=EXCLUDED."reason","linkedAt"=NOW()`,randomUUID(),auth.organizationId,access.legalEntityId,application.departmentId||employment.departmentId||null,input.applicationId,input.employeeId,auth.userId,input.reason);
    const [history,interviews,messages]=await Promise.all([
      prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ApplicantStatusHistory" WHERE "applicationId"=$1 ORDER BY "createdAt"`,input.applicationId).catch(()=>[]),
      prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "InterviewAppointment" WHERE "applicationId"=$1 ORDER BY "createdAt"`,input.applicationId).catch(()=>[]),
      prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ApplicantMessage" WHERE "applicationId"=$1 ORDER BY "createdAt"`,input.applicationId).catch(()=>[])
    ]);
    await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeOnboardingSnapshot" ("id","organizationId","legalEntityId","departmentId","applicationId","employeeId","applicationData","assessmentData","statusHistory","interviews","messages") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb) ON CONFLICT ("organizationId","applicationId") DO UPDATE SET "legalEntityId"=EXCLUDED."legalEntityId","departmentId"=EXCLUDED."departmentId","employeeId"=EXCLUDED."employeeId","applicationData"=EXCLUDED."applicationData","assessmentData"=EXCLUDED."assessmentData","statusHistory"=EXCLUDED."statusHistory","interviews"=EXCLUDED."interviews","messages"=EXCLUDED."messages","updatedAt"=NOW()`,randomUUID(),auth.organizationId,access.legalEntityId,application.departmentId||employment.departmentId||null,input.applicationId,input.employeeId,JSON.stringify(application.applicationData||application),JSON.stringify(application.assessmentAnswers||null),JSON.stringify(history),JSON.stringify(interviews),JSON.stringify(messages));
    for(const message of messages){await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeUnifiedCommunication" ("id","organizationId","employeeId","channel","category","subject","body","status","externalMessageId","attachmentRefs","acknowledgedAt","createdById","createdAt") VALUES ($1,$2,$3,$4,'ONBOARDING',$5,$6,$7,$8,'[]'::jsonb,NULL,$9,COALESCE($10,NOW()))`,randomUUID(),auth.organizationId,input.employeeId,String(message.channel||'EMAIL'),String(message.subject||'Onboarding communication'),String(message.body||message.message||''),String(message.deliveryStatus||message.status||'SENT'),message.externalMessageId??null,auth.userId,message.createdAt??null).catch(()=>undefined)}
    await audit?.(auth,'CONVERT_APPLICANT_TO_EMPLOYEE_360','EmployeeOnboardingLink',input.applicationId,{employeeId:input.employeeId,legalEntityId:access.legalEntityId,departmentId:application.departmentId||employment.departmentId||null});res.json({data:{applicationId:input.applicationId,employeeId:input.employeeId,legalEntityId:access.legalEntityId,departmentId:application.departmentId||employment.departmentId||null,historyCount:history.length,interviewCount:interviews.length,messageCount:messages.length}})}catch(error){next(error)}});

  app.post('/api/admin/employee360/secure-files/lifecycle',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWrite(auth);const input=lifecycleSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeSecureDocument" WHERE "organizationId"=$1 AND "status" IN ('ACTIVE','SUPERSEDED') AND "legalHold"=FALSE AND "retentionUntil" IS NOT NULL AND "retentionUntil"<=NOW() ORDER BY "retentionUntil" LIMIT $2`,auth.organizationId,input.limit);let destroyed=0;for(const row of rows){if(!input.dryRun){await deleteSecureObject(row.objectKey);await prisma.$executeRawUnsafe(`UPDATE "EmployeeSecureDocument" SET "status"='DESTROYED',"updatedAt"=NOW() WHERE "organizationId"=$1 AND "id"=$2`,auth.organizationId,row.id);await accessLog(auth,row.id,row.employeeId,'DESTROY','ALLOW','Retention schedule elapsed');destroyed++}}res.json({data:{eligible:rows.length,destroyed,dryRun:input.dryRun,documents:rows.map(r=>({id:r.id,fileName:r.fileName,retentionUntil:r.retentionUntil}))}})}catch(error){next(error)}});

  async function runComplianceReminders(organizationId:string,dryRun=false){
    await ready();const runKey=new Date().toISOString().slice(0,10);const runId=randomUUID();
    const inserted=await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeComplianceReminderRun" ("id","organizationId","runKey") VALUES ($1,$2,$3) ON CONFLICT ("organizationId","runKey") DO NOTHING`,runId,organizationId,runKey);if(!inserted)return{duplicate:true,processed:0,sent:0,failed:0};
    const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT c.*,u."email",COALESCE(NULLIF(p."displayName",''),u."email",u."id") AS "displayName" FROM "EmployeeCredential" c JOIN "User" u ON u."id"=c."employeeId" AND u."organizationId"=c."organizationId" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE c."organizationId"=$1 AND c."expiresAt" IS NOT NULL AND DATE_PART('day',c."expiresAt"-NOW())::int IN (90,60,30,14,7,0)`,organizationId).catch(()=>[]);
    const transport=smtpTransport();let sent=0,failed=0;for(const row of rows){const days=Math.max(0,Math.ceil((new Date(row.expiresAt).getTime()-Date.now())/86400000));const subject=`Credential ${days===0?'expired':`expires in ${days} days`}: ${row.credentialType||row.name||'Required credential'}`;const body=`${row.displayName}, your required credential ${row.credentialType||row.name||''} ${days===0?'has expired':`expires in ${days} days`}. Upload the renewal in the Employee Portal immediately. This notice is also visible to your assigned manager and Human Resources.`;let status='QUEUED';try{if(!dryRun&&transport&&row.email){await transport.sendMail({from:`${process.env.SMTP_FROM_NAME||'Sulandra Health Human Resources Department'} <${process.env.SMTP_USER}>`,to:row.email,subject,text:body});status='DELIVERED';sent++}else if(!dryRun){failed++;status='FAILED'}}catch{failed++;status='FAILED'}await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeUnifiedCommunication" ("id","organizationId","employeeId","channel","category","subject","body","status","attachmentRefs","createdById") VALUES ($1,$2,$3,'EMAIL','COMPLIANCE',$4,$5,$6,'[]'::jsonb,$7)`,randomUUID(),organizationId,row.employeeId,subject,body,status,process.env.PRIMARY_ADMIN_USER_ID||row.employeeId).catch(()=>undefined)}
    await prisma.$executeRawUnsafe(`UPDATE "EmployeeComplianceReminderRun" SET "completedAt"=NOW(),"status"='COMPLETED',"processed"=$1,"sent"=$2,"failed"=$3,"details"=$4::jsonb WHERE "id"=$5`,rows.length,sent,failed,JSON.stringify({dryRun}),runId);return{duplicate:false,processed:rows.length,sent,failed};
  }

  app.post('/internal/employee360/compliance-reminders',async(req,res,next)=>{try{const configured=process.env.SULANDRA_INTERNAL_API_KEY||'';if(!configured||req.header('x-sulandra-api-key')!==configured)return void res.status(401).json({error:'Internal authentication required'});const input=reminderSchema.parse(req.body||{});const organizationId=input.organizationId||process.env.CAREERS_ORGANIZATION_ID;if(!organizationId)return void res.status(400).json({error:'organizationId is required'});res.json({data:await runComplianceReminders(organizationId,input.dryRun)})}catch(error){next(error)}});

  if(process.env.EMPLOYEE360_COMPLIANCE_SCHEDULER==='true'){
    const interval=Math.max(60_000,Number(process.env.EMPLOYEE360_COMPLIANCE_INTERVAL_MS||3_600_000));setInterval(async()=>{const organizationId=process.env.CAREERS_ORGANIZATION_ID;if(!organizationId)return;try{await runComplianceReminders(organizationId,false)}catch(error){console.error('[employee360-compliance-scheduler]',error)}},interval).unref();
  }
}
