import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const reportRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const elevatedRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);

const reportDefinitionSchema=z.object({name:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),reportType:z.enum(['WORKFORCE','COMPLIANCE','TIME_ATTENDANCE','PERFORMANCE','COMPENSATION','LEAVE','ASSETS_ACCESS','OFFBOARDING','CUSTOM']),filters:z.record(z.any()).default({}),columns:z.array(z.string().trim().min(1)).default([]),schedule:z.enum(['NONE','DAILY','WEEKLY','MONTHLY','QUARTERLY']).default('NONE'),recipientEmails:z.array(z.string().email()).default([]),active:z.boolean().default(true),visibility:z.enum(['OWNER_ONLY','HR_ADMIN','MANAGEMENT','AUDITOR']).default('HR_ADMIN')});
const exportSchema=z.object({reportType:z.enum(['WORKFORCE','COMPLIANCE','TIME_ATTENDANCE','PERFORMANCE','COMPENSATION','LEAVE','ASSETS_ACCESS','OFFBOARDING']),format:z.enum(['CSV','JSON']).default('CSV'),filters:z.record(z.any()).default({})});

const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
const csvCell=(v:unknown)=>{const s=v==null?'':String(v);return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};
const toCsv=(rows:any[])=>{if(!rows.length)return'';const keys=Array.from(rows.reduce((set,row)=>{Object.keys(row).forEach(k=>set.add(k));return set},new Set<string>()));return [keys.map(csvCell).join(','),...rows.map(row=>keys.map(k=>csvCell(row[k])).join(','))].join('\n')};

export function registerEmployeeAnalyticsReportsRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeReportDefinition" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"reportType" TEXT NOT NULL,"filters" JSONB NOT NULL DEFAULT '{}'::jsonb,"columns" JSONB NOT NULL DEFAULT '[]'::jsonb,"schedule" TEXT NOT NULL DEFAULT 'NONE',"recipientEmails" JSONB NOT NULL DEFAULT '[]'::jsonb,"active" BOOLEAN NOT NULL DEFAULT TRUE,"visibility" TEXT NOT NULL DEFAULT 'HR_ADMIN',"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"lastRunAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeReportDefinition_org_idx" ON "EmployeeReportDefinition"("organizationId","active","reportType","name")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeReportRun" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"reportDefinitionId" TEXT,"reportType" TEXT NOT NULL,"format" TEXT NOT NULL,"requestedById" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'COMPLETED',"rowCount" INTEGER NOT NULL DEFAULT 0,"filters" JSONB NOT NULL DEFAULT '{}'::jsonb,"errorMessage" TEXT NOT NULL DEFAULT '',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeReportRun_org_idx" ON "EmployeeReportRun"("organizationId","createdAt" DESC,"reportType")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAnalyticsEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAnalyticsEvent_org_idx" ON "EmployeeAnalyticsEvent"("organizationId","createdAt" DESC)`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...reportRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor reporting access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage report definitions'),{status:403});return a};
  const canViewSensitive=async(auth:AuthContext)=>{const a=await actor(auth);return a.isOwner||elevatedRoles.has(auth.role)||auth.role===UserRole.AUDITOR};
  const event=async(auth:AuthContext,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAnalyticsEvent" ("id","organizationId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb)`,randomUUID(),auth.organizationId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  const dataFor=async(org:string,type:string,sensitive:boolean)=>{
    if(type==='WORKFORCE')return prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS "role",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email",u."id") AS "displayName",p."jobTitle",p."department",COALESCE(p."employmentStatus",'ACTIVE') AS "employmentStatus",p."hireDate",p."terminationDate" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 ORDER BY "displayName"`,org);
    if(type==='COMPLIANCE')return prisma.$queryRawUnsafe<any[]>(`SELECT u."id" AS "employeeId",u."email",COALESCE(NULLIF(c."displayName",''),u."email",u."id") AS "displayName",COUNT(r."id")::int AS "requirementCount",COUNT(r."id") FILTER (WHERE r."status" IN ('EXPIRED','NON_COMPLIANT'))::int AS "nonCompliantCount",COUNT(r."id") FILTER (WHERE r."expiresAt" IS NOT NULL AND r."expiresAt"<=NOW()+INTERVAL '30 days')::int AS "expiringSoonCount" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeComplianceRequirement" r ON r."employeeId"=u."id" AND r."organizationId"=u."organizationId" WHERE u."organizationId"=$1 GROUP BY u."id",u."email",c."displayName" ORDER BY "displayName"`,org).catch(()=>[]);
    if(type==='TIME_ATTENDANCE')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId",COUNT(*)::int AS "punchCount",SUM(EXTRACT(EPOCH FROM (COALESCE("clockOutAt",NOW())-"clockInAt"))/3600)::numeric(12,2) AS "hours",COUNT(*) FILTER (WHERE "clockOutAt" IS NULL)::int AS "openPunches" FROM "TimeAttendanceEntry" WHERE "organizationId"=$1 GROUP BY "employeeId" ORDER BY "employeeId"`,org).catch(()=>[]);
    if(type==='PERFORMANCE')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId","status",COUNT(*)::int AS "reviewCount",AVG("finalScore")::numeric(10,2) AS "averageScore" FROM "EmployeePerformanceReview" WHERE "organizationId"=$1 GROUP BY "employeeId","status" ORDER BY "employeeId","status"`,org).catch(()=>[]);
    if(type==='COMPENSATION')return sensitive?prisma.$queryRawUnsafe<any[]>(`SELECT c."employeeId",c."payType",c."amount",c."currency",c."effectiveDate",c."endDate" FROM "EmployeeCompensationHistory" c WHERE c."organizationId"=$1 ORDER BY c."employeeId",c."effectiveDate" DESC`,org).catch(()=>[]):[];
    if(type==='LEAVE')return prisma.$queryRawUnsafe<any[]>(`SELECT r."employeeId",p."leaveType",r."status",SUM(r."hoursRequested")::numeric(12,2) AS "hoursRequested",COUNT(*)::int AS "requestCount" FROM "EmployeeLeaveRequest" r JOIN "EmployeeLeavePolicy" p ON p."id"=r."leavePolicyId" AND p."organizationId"=r."organizationId" WHERE r."organizationId"=$1 GROUP BY r."employeeId",p."leaveType",r."status" ORDER BY r."employeeId",p."leaveType",r."status"`,org).catch(()=>[]);
    if(type==='ASSETS_ACCESS')return prisma.$queryRawUnsafe<any[]>(`SELECT a."assetTag",a."category",a."name",a."status",x."employeeId",x."assignedAt",x."expectedReturnDate",x."returnedAt" FROM "EmployeeAsset" a LEFT JOIN "EmployeeAssetAssignment" x ON x."assetId"=a."id" AND x."organizationId"=a."organizationId" WHERE a."organizationId"=$1 ORDER BY a."category",a."name"`,org).catch(()=>[]);
    if(type==='OFFBOARDING')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId","separationType","status","noticeDate","lastWorkingDate","effectiveDate","eligibleForRehire","completedAt" FROM "EmployeeOffboardingCase" WHERE "organizationId"=$1 ORDER BY "effectiveDate" DESC`,org).catch(()=>[]);
    return[];
  };

  app.get('/api/admin/employee-analytics/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [workforce,leave,assets,offboarding,definitions,runs]=await Promise.all([dataFor(auth.organizationId,'WORKFORCE',true),dataFor(auth.organizationId,'LEAVE',true),dataFor(auth.organizationId,'ASSETS_ACCESS',true),dataFor(auth.organizationId,'OFFBOARDING',true),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeReportDefinition" WHERE "organizationId"=$1 ORDER BY "active" DESC,"name"`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeReportRun" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 100`,auth.organizationId)]);const sensitive=await canViewSensitive(auth);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManageDefinitions:(await actor(auth)).isOwner||writableRoles.has(auth.role),canViewSensitive:sensitive},metrics:{employeeCount:workforce.length,activeEmployees:workforce.filter((r:any)=>String(r.employmentStatus||'ACTIVE')==='ACTIVE').length,pendingLeaveRequests:leave.filter((r:any)=>r.status==='PENDING').reduce((s:number,r:any)=>s+Number(r.requestCount||0),0),assignedAssets:assets.filter((r:any)=>r.employeeId&&!r.returnedAt).length,activeOffboarding:offboarding.filter((r:any)=>['PLANNED','IN_PROGRESS'].includes(r.status)).length,scheduledReports:definitions.filter((r:any)=>r.active&&r.schedule!=='NONE').length},workforceSummary:workforce.reduce((acc:any,r:any)=>{const key=r.department||'Unassigned';acc[key]=(acc[key]||0)+1;return acc},{}),leaveSummary:leave,assetSummary:assets,offboardingSummary:offboarding,definitions,runs}})}catch(e){next(e)}});

  app.post('/api/admin/employee-analytics/reports',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=reportDefinitionSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeReportDefinition" ("id","organizationId","name","description","reportType","filters","columns","schedule","recipientEmails","active","visibility","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9::jsonb,$10,$11,$12,$12)`,id,auth.organizationId,input.name,input.description,input.reportType,JSON.stringify(input.filters),JSON.stringify(input.columns),input.schedule,JSON.stringify(input.recipientEmails),input.active,input.visibility,auth.userId);await event(auth,'REPORT_DEFINITION_CREATED','REPORT_DEFINITION',id,{reportType:input.reportType});await audit?.(auth,'CREATE_EMPLOYEE_REPORT_DEFINITION','EmployeeReportDefinition',id,{reportType:input.reportType});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-analytics/reports/:reportId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const existing=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeReportDefinition" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.reportId))[0];if(!existing)return void res.status(404).json({error:'Report definition was not found'});const input=reportDefinitionSchema.parse({...existing,...req.body,filters:req.body?.filters??existing.filters,columns:req.body?.columns??existing.columns,recipientEmails:req.body?.recipientEmails??existing.recipientEmails});await prisma.$executeRawUnsafe(`UPDATE "EmployeeReportDefinition" SET "name"=$1,"description"=$2,"reportType"=$3,"filters"=$4::jsonb,"columns"=$5::jsonb,"schedule"=$6,"recipientEmails"=$7::jsonb,"active"=$8,"visibility"=$9,"updatedById"=$10,"updatedAt"=NOW() WHERE "organizationId"=$11 AND "id"=$12`,input.name,input.description,input.reportType,JSON.stringify(input.filters),JSON.stringify(input.columns),input.schedule,JSON.stringify(input.recipientEmails),input.active,input.visibility,auth.userId,auth.organizationId,existing.id);await event(auth,'REPORT_DEFINITION_UPDATED','REPORT_DEFINITION',existing.id,{reportType:input.reportType});res.json({data:{id:existing.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-analytics/export',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=exportSchema.parse(req.body);const sensitive=await canViewSensitive(auth);if(input.reportType==='COMPENSATION'&&!sensitive)return void res.status(403).json({error:'Compensation reports require elevated access'});const rows=await dataFor(auth.organizationId,input.reportType,sensitive);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeReportRun" ("id","organizationId","reportType","format","requestedById","status","rowCount","filters") VALUES ($1,$2,$3,$4,$5,'COMPLETED',$6,$7::jsonb)`,id,auth.organizationId,input.reportType,input.format,auth.userId,rows.length,JSON.stringify(input.filters));await event(auth,'REPORT_EXPORTED','REPORT_RUN',id,{reportType:input.reportType,format:input.format,rowCount:rows.length});await audit?.(auth,'EXPORT_EMPLOYEE_REPORT','EmployeeReportRun',id,{reportType:input.reportType,format:input.format,rowCount:rows.length});if(input.format==='JSON')return res.json({data:{runId:id,rows}});res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="employee-${input.reportType.toLowerCase()}-${new Date().toISOString().slice(0,10)}.csv"`);res.send(toCsv(rows))}catch(e){next(e)}});
}
