import { randomUUID, createHash } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO,UserRole.SCHEDULER,UserRole.DELEGATING_NURSE] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
const hashJson=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');

const assignmentSchema=z.object({employeeId:z.string().trim().min(1),locationId:z.string().trim().min(1),clientId:z.string().trim().optional().nullable(),assignmentType:z.enum(['PRIMARY_LOCATION','SERVICE_HOME','CLIENT','PROGRAM']),serviceTypes:z.array(z.string().trim().min(1)).max(100).default([]),startsAt:z.coerce.date().optional().nullable(),endsAt:z.coerce.date().optional().nullable(),isHouseManager:z.boolean().default(false),reason:z.string().trim().min(3).max(2000)});
const punchSchema=z.object({employeeId:z.string().trim().min(1),timeEntryId:z.string().trim().min(1),clockIn:z.coerce.date().optional().nullable(),clockOut:z.coerce.date().optional().nullable(),reason:z.string().trim().min(3).max(2000),gpsExceptionStatus:z.enum(['NONE','REVIEWED','APPROVED','DENIED']).default('NONE')});
const signoffSchema=z.object({employeeId:z.string().trim().min(1),periodStart:z.coerce.date(),periodEnd:z.coerce.date(),status:z.enum(['PENDING','APPROVED','REJECTED']),reason:z.string().trim().min(3).max(2000)});
const timelineSchema=z.object({employeeId:z.string().trim().min(1),channel:z.enum(['EMAIL','SMS','PORTAL','INTERNAL_NOTE','SYSTEM']),category:z.enum(['ONBOARDING','OFFER','SCHEDULING','TIME_OFF','TRAINING','COMPLIANCE','POLICY','CORRECTIVE_ACTION','SECURITY','GENERAL']),subject:z.string().trim().min(1).max(500),body:z.string().trim().min(1).max(12000),status:z.enum(['DRAFT','QUEUED','SENT','DELIVERED','BOUNCED','FAILED','ACKNOWLEDGED','INTERNAL']).default('INTERNAL'),externalMessageId:z.string().trim().max(500).optional().nullable(),attachmentRefs:z.array(z.string().trim().min(1)).max(100).default([]),acknowledgedAt:z.coerce.date().optional().nullable()});
const sessionSchema=z.object({employeeId:z.string().trim().min(1),sessionId:z.string().trim().min(1),action:z.enum(['REVOKE_ONE','REVOKE_ALL','DISABLE_PORTAL','ENABLE_PORTAL','REQUIRE_MFA','CLEAR_MFA']),portal:z.string().trim().max(100).optional().nullable(),reason:z.string().trim().min(3).max(2000)});
const accountSchema=z.object({employeeId:z.string().trim().min(1),username:z.string().trim().min(3).max(200).optional(),alternateEmail:z.string().email().optional(),mergeSourceUserId:z.string().trim().min(1).optional(),reason:z.string().trim().min(3).max(2000)});
const auditSchema=z.object({employeeId:z.string().trim().optional().nullable(),action:z.string().trim().min(1).max(200),resourceType:z.string().trim().min(1).max(200),resourceId:z.string().trim().optional().nullable(),reason:z.string().trim().min(3).max(2000),before:z.unknown().optional(),after:z.unknown().optional(),decision:z.enum(['ALLOW','DENY']).default('ALLOW')});

export function registerEmployee360EnterpriseGapRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWorkAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"clientId" TEXT,"assignmentType" TEXT NOT NULL,"serviceTypes" JSONB NOT NULL DEFAULT '[]'::jsonb,"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,"isHouseManager" BOOLEAN NOT NULL DEFAULT FALSE,"eligibilityStatus" TEXT NOT NULL DEFAULT 'PENDING',"eligibilityReasons" JSONB NOT NULL DEFAULT '[]'::jsonb,"reason" TEXT NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeWorkAssignment_org_idx" ON "EmployeeWorkAssignment"("organizationId","employeeId","locationId","assignmentType")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeTimeCorrection" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"timeEntryId" TEXT NOT NULL,"clockIn" TIMESTAMPTZ,"clockOut" TIMESTAMPTZ,"gpsExceptionStatus" TEXT NOT NULL DEFAULT 'NONE',"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'APPROVED',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeePayrollPeriodSignoff" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"periodStart" TIMESTAMPTZ NOT NULL,"periodEnd" TIMESTAMPTZ NOT NULL,"status" TEXT NOT NULL,"reason" TEXT NOT NULL,"decidedById" TEXT NOT NULL,"decidedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE("organizationId","employeeId","periodStart","periodEnd"))`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeUnifiedCommunication" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"channel" TEXT NOT NULL,"category" TEXT NOT NULL,"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"status" TEXT NOT NULL,"externalMessageId" TEXT,"attachmentRefs" JSONB NOT NULL DEFAULT '[]'::jsonb,"acknowledgedAt" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeUnifiedCommunication_timeline_idx" ON "EmployeeUnifiedCommunication"("organizationId","employeeId","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAccountSecurityEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"sessionId" TEXT,"action" TEXT NOT NULL,"portal" TEXT,"reason" TEXT NOT NULL,"ipAddress" TEXT,"userAgent" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAccountProfileChange" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"username" TEXT,"alternateEmail" TEXT,"mergeSourceUserId" TEXT,"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'COMPLETED',"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAuditLedger" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT NOT NULL,"actorEmail" TEXT,"actorRole" TEXT NOT NULL,"action" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"reason" TEXT NOT NULL,"before" JSONB,"after" JSONB,"decision" TEXT NOT NULL,"ipAddress" TEXT,"userAgent" TEXT,"previousHash" TEXT,"entryHash" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAuditLedger_org_idx" ON "EmployeeAuditLedger"("organizationId","employeeId","createdAt" DESC)`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{email:normalizeEmail(rows[0]?.email||auth.email),isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may perform this action'),{status:403});return a};
  const protectOwner=async(auth:AuthContext,employeeId:string)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,employeeId);if(normalizeEmail(rows[0]?.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner record cannot be changed by another user'),{status:403})};
  const ledger=async(auth:AuthContext,input:z.infer<typeof auditSchema>)=>{const a=await actor(auth);const previous=(await prisma.$queryRawUnsafe<Array<{entryHash:string}>>(`SELECT "entryHash" FROM "EmployeeAuditLedger" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1`,auth.organizationId))[0]?.entryHash??null;const payload={...input,organizationId:auth.organizationId,actorUserId:auth.userId,actorEmail:a.email,actorRole:auth.role,ipAddress:auth.ipAddress??null,userAgent:auth.userAgent??null,previousHash:previous};const entryHash=hashJson(payload);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAuditLedger" ("id","organizationId","employeeId","actorUserId","actorEmail","actorRole","action","resourceType","resourceId","reason","before","after","decision","ipAddress","userAgent","previousHash","entryHash") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13,$14,$15,$16,$17)`,randomUUID(),auth.organizationId,input.employeeId??null,auth.userId,a.email,auth.role,input.action,input.resourceType,input.resourceId??null,input.reason,JSON.stringify(input.before??null),JSON.stringify(input.after??null),input.decision,auth.ipAddress??null,auth.userAgent??null,previous,entryHash);return entryHash};

  app.get('/api/admin/employee360/enterprise-gap-dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [assignments,corrections,signoffs,communications,security,auditRows]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkAssignment" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeTimeCorrection" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeePayrollPeriodSignoff" WHERE "organizationId"=$1 ORDER BY "decidedAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeUnifiedCommunication" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccountSecurityEvent" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAuditLedger" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId)
  ]);res.json({data:{assignments,corrections,signoffs,communications,security,audit:auditRows,metrics:{blockedAssignments:assignments.filter(r=>r.eligibilityStatus==='BLOCKED').length,failedCommunications:communications.filter(r=>['FAILED','BOUNCED'].includes(r.status)).length,revocations:security.filter(r=>String(r.action).startsWith('REVOKE')).length,deniedActions:auditRows.filter(r=>r.decision==='DENY').length}}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/work-assignments',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=assignmentSchema.parse(req.body);await protectOwner(auth,input.employeeId);const compliance=await prisma.$queryRawUnsafe<any[]>(`SELECT 1 FROM "EmployeeCredential" WHERE "organizationId"=$1 AND "employeeId"=$2 AND ("status" IN ('EXPIRED','MISSING') OR ("expiresAt" IS NOT NULL AND "expiresAt"<NOW())) LIMIT 1`,auth.organizationId,input.employeeId).catch(()=>[]);const training=await prisma.$queryRawUnsafe<any[]>(`SELECT 1 FROM "EmployeeLearningAssignment" WHERE "organizationId"=$1 AND "employeeId"=$2 AND "required"=TRUE AND "status" NOT IN ('COMPLETED','EXEMPT') LIMIT 1`,auth.organizationId,input.employeeId).catch(()=>[]);const reasons=[] as string[];if(compliance.length)reasons.push('Required credential missing or expired');if(training.length)reasons.push('Mandatory training incomplete');const eligibilityStatus=reasons.length?'BLOCKED':'ELIGIBLE';const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWorkAssignment" ("id","organizationId","employeeId","locationId","clientId","assignmentType","serviceTypes","startsAt","endsAt","isHouseManager","eligibilityStatus","eligibilityReasons","reason","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12::jsonb,$13,$14)`,id,auth.organizationId,input.employeeId,input.locationId,input.clientId??null,input.assignmentType,JSON.stringify(input.serviceTypes),input.startsAt??null,input.endsAt??null,input.isHouseManager,eligibilityStatus,JSON.stringify(reasons),input.reason,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:'CREATE_WORK_ASSIGNMENT',resourceType:'EmployeeWorkAssignment',resourceId:id,reason:input.reason,after:{...input,eligibilityStatus,reasons}});res.status(201).json({data:{id,eligibilityStatus,reasons}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/time-corrections',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=punchSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeTimeCorrection" ("id","organizationId","employeeId","timeEntryId","clockIn","clockOut","gpsExceptionStatus","reason","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,id,auth.organizationId,input.employeeId,input.timeEntryId,input.clockIn??null,input.clockOut??null,input.gpsExceptionStatus,input.reason,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:'CORRECT_TIME_ENTRY',resourceType:'EmployeeTimeCorrection',resourceId:id,reason:input.reason,after:input});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/payroll-signoffs',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=signoffSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeePayrollPeriodSignoff" ("id","organizationId","employeeId","periodStart","periodEnd","status","reason","decidedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT ("organizationId","employeeId","periodStart","periodEnd") DO UPDATE SET "status"=EXCLUDED."status","reason"=EXCLUDED."reason","decidedById"=EXCLUDED."decidedById","decidedAt"=NOW()`,id,auth.organizationId,input.employeeId,input.periodStart,input.periodEnd,input.status,input.reason,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:'PAYROLL_PERIOD_SIGNOFF',resourceType:'EmployeePayrollPeriodSignoff',resourceId:id,reason:input.reason,after:input});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/communications',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=timelineSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeUnifiedCommunication" ("id","organizationId","employeeId","channel","category","subject","body","status","externalMessageId","attachmentRefs","acknowledgedAt","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12)`,id,auth.organizationId,input.employeeId,input.channel,input.category,input.subject,input.body,input.status,input.externalMessageId??null,JSON.stringify(input.attachmentRefs),input.acknowledgedAt??null,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:'CREATE_UNIFIED_COMMUNICATION',resourceType:'EmployeeUnifiedCommunication',resourceId:id,reason:'Unified communication timeline entry',after:input});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/account-security',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=sessionSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAccountSecurityEvent" ("id","organizationId","employeeId","sessionId","action","portal","reason","ipAddress","userAgent","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,auth.organizationId,input.employeeId,input.sessionId,input.action,input.portal??null,input.reason,auth.ipAddress??null,auth.userAgent??null,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:input.action,resourceType:'EmployeeAccountSecurityEvent',resourceId:id,reason:input.reason,after:input});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/account-profile',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=accountSchema.parse(req.body);await protectOwner(auth,input.employeeId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAccountProfileChange" ("id","organizationId","employeeId","username","alternateEmail","mergeSourceUserId","reason","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,id,auth.organizationId,input.employeeId,input.username??null,input.alternateEmail??null,input.mergeSourceUserId??null,input.reason,auth.userId);await ledger(auth,{employeeId:input.employeeId,action:'ACCOUNT_PROFILE_CHANGE',resourceType:'EmployeeAccountProfileChange',resourceId:id,reason:input.reason,after:input});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee360/audit-ledger',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=auditSchema.parse(req.body);const entryHash=await ledger(auth,input);await audit?.(auth,input.action,input.resourceType,input.resourceId??undefined,{reason:input.reason,decision:input.decision,entryHash});res.status(201).json({data:{entryHash}})}catch(e){next(e)}});

  app.get('/api/employee/me/enterprise360',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [assignments,communications,security]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkAssignment" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,auth.userId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeUnifiedCommunication" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC`,auth.organizationId,auth.userId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAccountSecurityEvent" WHERE "organizationId"=$1 AND "employeeId"=$2 ORDER BY "createdAt" DESC LIMIT 100`,auth.organizationId,auth.userId)
  ]);res.json({data:{assignments,communications,security}})}catch(e){next(e)}});
}
