import { createCipheriv, createDecipheriv, createHmac, randomBytes, randomInt, randomUUID, timingSafeEqual } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;sessionId?:string;ipAddress?:string;userAgent?:string};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};
type SmsLoginInput={organizationId:string;userId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};

const base32Alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const setupSchema=z.object({employeeId:z.string().trim().optional(),required:z.boolean().default(true)});
const confirmSchema=z.object({employeeId:z.string().trim().optional(),code:z.string().trim().regex(/^\d{6}$/)});
const revokeSchema=z.object({employeeId:z.string().trim().min(1),sessionId:z.string().trim().optional(),reason:z.string().trim().min(3).max(2000)});
const smsConfigSchema=z.object({employeeId:z.string().trim().min(1),phone:z.string().trim().min(10).max(32),required:z.boolean().default(true)});
const SMS_TTL_MS=5*60*1000;
const SMS_MAX_ATTEMPTS=5;

function encryptionKey(){const raw=process.env.EMPLOYEE_AUTH_ENCRYPTION_KEY_BASE64;if(!raw)throw Object.assign(new Error('EMPLOYEE_AUTH_ENCRYPTION_KEY_BASE64 is not configured'),{status:503});const key=Buffer.from(raw,'base64');if(key.length!==32)throw new Error('EMPLOYEE_AUTH_ENCRYPTION_KEY_BASE64 must decode to 32 bytes');return key}
function encrypt(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return`${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${encrypted.toString('base64')}`}
function decrypt(value:string){const [iv,tag,data]=value.split('.');const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(data,'base64')),decipher.final()]).toString('utf8')}
function base32Encode(buffer:Buffer){let bits='';for(const byte of buffer)bits+=byte.toString(2).padStart(8,'0');let result='';for(let i=0;i<bits.length;i+=5)result+=base32Alphabet[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return result}
function base32Decode(value:string){let bits='';for(const char of value.replace(/=+$/,'').toUpperCase()){const index=base32Alphabet.indexOf(char);if(index<0)throw new Error('Invalid base32 secret');bits+=index.toString(2).padStart(5,'0')}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}
function totp(secret:string,time=Date.now()){const counter=Math.floor(time/30000);const buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',base32Decode(secret)).update(buffer).digest();const offset=digest[digest.length-1]&15;const code=((digest.readUInt32BE(offset)&0x7fffffff)%1_000_000).toString().padStart(6,'0');return code}
export function verifyTotp(secret:string,code:string){for(const drift of[-1,0,1]){const expected=Buffer.from(totp(secret,Date.now()+drift*30000));const supplied=Buffer.from(code);if(expected.length===supplied.length&&timingSafeEqual(expected,supplied))return true}return false}

function normalizeSmsPhone(value?:string|null){const raw=String(value||'').trim();if(!raw)return'';const digits=raw.replace(/\D/g,'');if(digits.length===10)return`+1${digits}`;if(digits.length===11&&digits.startsWith('1'))return`+${digits}`;if(raw.startsWith('+')&&digits.length>=10&&digits.length<=15)return`+${digits}`;return''}
function maskPhone(value:string){const digits=value.replace(/\D/g,'');return digits.length>=4?`••• ••• ${digits.slice(-4)}`:'••••'}
function adminEmail(){return(process.env.ADMIN_EMAIL||'admin@sulandrahealth.com').trim().toLowerCase()}
function ownerSmsRequired(email?:string){return String(email||'').trim().toLowerCase()===adminEmail()&&String(process.env.ADMIN_SMS_MFA_REQUIRED||'').trim().toLowerCase()==='true'}
function smsPepper(){const value=process.env.EMPLOYEE_SMS_MFA_PEPPER?.trim()||process.env.JWT_SECRET?.trim();if(!value)throw Object.assign(new Error('SMS verification secret is not configured'),{status:503});return value}
function smsCodeHash(challengeId:string,code:string){return createHmac('sha256',smsPepper()).update(`${challengeId}:${code}`).digest('hex')}
function safeEqualHex(left:string,right:string){const a=Buffer.from(left,'hex');const b=Buffer.from(right,'hex');return a.length===b.length&&a.length>0&&timingSafeEqual(a,b)}
function twilioConfigured(){return Boolean(process.env.TWILIO_ACCOUNT_SID?.trim()&&process.env.TWILIO_AUTH_TOKEN?.trim()&&process.env.TWILIO_FROM_NUMBER?.trim())}
async function sendSecuritySms(to:string,body:string){const accountSid=process.env.TWILIO_ACCOUNT_SID?.trim();const authToken=process.env.TWILIO_AUTH_TOKEN?.trim();const from=process.env.TWILIO_FROM_NUMBER?.trim();if(!accountSid||!authToken||!from)throw Object.assign(new Error('SMS provider is not configured'),{status:503});const payload=new URLSearchParams({To:to,From:from,Body:body});const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(accountSid)}/Messages.json`,{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${accountSid}:${authToken}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body:payload,signal:AbortSignal.timeout(10000)});if(!response.ok){const detail=(await response.text()).slice(0,400);throw Object.assign(new Error(`SMS provider returned ${response.status}: ${detail}`),{status:503})}return response.json() as Promise<{sid?:string}>}

export async function ensureEmployeeAuthSecuritySchema(prisma:PrismaClient){
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAuthSession" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"issuedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"expiresAt" TIMESTAMPTZ NOT NULL,"revokedAt" TIMESTAMPTZ,"revokedById" TEXT,"revocationReason" TEXT,"ipAddress" TEXT,"userAgent" TEXT,"lastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAuthSession_user_idx" ON "EmployeeAuthSession"("organizationId","userId","expiresAt" DESC)`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeMfaProfile" ("organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"encryptedSecret" TEXT,"required" BOOLEAN NOT NULL DEFAULT FALSE,"verified" BOOLEAN NOT NULL DEFAULT FALSE,"recoveryCodes" JSONB NOT NULL DEFAULT '[]'::jsonb,"enrolledAt" TIMESTAMPTZ,"lastVerifiedAt" TIMESTAMPTZ,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY("organizationId","userId"))`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "EmployeeMfaProfile" ADD COLUMN IF NOT EXISTS "smsPhone" TEXT`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "EmployeeMfaProfile" ADD COLUMN IF NOT EXISTS "smsRequired" BOOLEAN NOT NULL DEFAULT FALSE`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "EmployeeMfaProfile" ADD COLUMN IF NOT EXISTS "smsConfiguredAt" TIMESTAMPTZ`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "EmployeeMfaProfile" ADD COLUMN IF NOT EXISTS "smsLastVerifiedAt" TIMESTAMPTZ`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeSmsMfaChallenge" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"phone" TEXT NOT NULL,"codeHash" TEXT NOT NULL,"expiresAt" TIMESTAMPTZ NOT NULL,"attempts" INTEGER NOT NULL DEFAULT 0,"maxAttempts" INTEGER NOT NULL DEFAULT 5,"consumedAt" TIMESTAMPTZ,"ipAddress" TEXT,"userAgent" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeSmsMfaChallenge_user_idx" ON "EmployeeSmsMfaChallenge"("organizationId","userId","createdAt" DESC)`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeePortalAccessControl" ("organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"portal" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT TRUE,"reason" TEXT,"updatedById" TEXT,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY("organizationId","userId","portal"))`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeLoginEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT,"userId" TEXT,"identifier" TEXT,"decision" TEXT NOT NULL,"reason" TEXT,"ipAddress" TEXT,"userAgent" TEXT,"sessionId" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  const configuredOwnerPhone=normalizeSmsPhone(process.env.ADMIN_MFA_PHONE);
  if(configuredOwnerPhone){await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeMfaProfile" ("organizationId","userId","smsPhone","smsRequired","smsConfiguredAt","updatedAt") SELECT u."organizationId",u."id",$1,$2,NOW(),NOW() FROM "User" u WHERE LOWER(u."email")=LOWER($3) ON CONFLICT ("organizationId","userId") DO UPDATE SET "smsPhone"=EXCLUDED."smsPhone","smsRequired"=EXCLUDED."smsRequired","smsConfiguredAt"=COALESCE("EmployeeMfaProfile"."smsConfiguredAt",NOW()),"updatedAt"=NOW()`,configuredOwnerPhone,ownerSmsRequired(adminEmail()),adminEmail()).catch(()=>undefined)}
}

export async function createEmployeeSession(prisma:PrismaClient,input:{organizationId:string;userId:string;expiresAt:Date;sessionId?:string;ipAddress?:string;userAgent?:string}){await ensureEmployeeAuthSecuritySchema(prisma);const id=input.sessionId||randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAuthSession" ("id","organizationId","userId","expiresAt","ipAddress","userAgent") VALUES ($1,$2,$3,$4,$5,$6)`,id,input.organizationId,input.userId,input.expiresAt,input.ipAddress??null,input.userAgent??null);return id}
export async function validateEmployeeSession(prisma:PrismaClient,input:{organizationId:string;userId:string;sessionId:string;portal?:string}){await ensureEmployeeAuthSecuritySchema(prisma);const session=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAuthSession" WHERE "id"=$1 AND "organizationId"=$2 AND "userId"=$3 AND "revokedAt" IS NULL AND "expiresAt">NOW() LIMIT 1`,input.sessionId,input.organizationId,input.userId))[0];if(!session)return false;const control=(await prisma.$queryRawUnsafe<any[]>(`SELECT "enabled" FROM "EmployeePortalAccessControl" WHERE "organizationId"=$1 AND "userId"=$2 AND "portal"=$3 LIMIT 1`,input.organizationId,input.userId,input.portal||'EMPLOYEE'))[0];if(control&&control.enabled===false)return false;await prisma.$executeRawUnsafe(`UPDATE "EmployeeAuthSession" SET "lastSeenAt"=NOW() WHERE "id"=$1`,input.sessionId);return true}
export async function verifyEmployeeLoginMfa(prisma:PrismaClient,organizationId:string,userId:string,code?:string){await ensureEmployeeAuthSecuritySchema(prisma);const profile=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeMfaProfile" WHERE "organizationId"=$1 AND "userId"=$2 LIMIT 1`,organizationId,userId))[0];if(!profile?.required)return{required:false,verified:true};if(!profile.verified||!profile.encryptedSecret)return{required:true,verified:false,reason:'MFA enrollment is incomplete'};if(!code||!verifyTotp(decrypt(profile.encryptedSecret),code))return{required:true,verified:false,reason:'Invalid multifactor authentication code'};await prisma.$executeRawUnsafe(`UPDATE "EmployeeMfaProfile" SET "lastVerifiedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$1 AND "userId"=$2`,organizationId,userId);return{required:true,verified:true}}

async function smsRequirement(prisma:PrismaClient,input:SmsLoginInput){await ensureEmployeeAuthSecuritySchema(prisma);const profile=(await prisma.$queryRawUnsafe<any[]>(`SELECT "smsPhone","smsRequired" FROM "EmployeeMfaProfile" WHERE "organizationId"=$1 AND "userId"=$2 LIMIT 1`,input.organizationId,input.userId))[0];const required=Boolean(profile?.smsRequired)||ownerSmsRequired(input.email);const phone=normalizeSmsPhone(profile?.smsPhone||(ownerSmsRequired(input.email)?process.env.ADMIN_MFA_PHONE:''));return{required,phone}}
export async function beginEmployeeSmsLoginMfa(prisma:PrismaClient,input:SmsLoginInput){const requirement=await smsRequirement(prisma,input);if(!requirement.required)return{required:false,verified:true};if(!requirement.phone)return{required:true,verified:false,status:503,reason:'Administrator SMS verification phone is not configured'};if(!twilioConfigured())return{required:true,verified:false,status:503,reason:'Administrator SMS verification provider is not configured'};const challengeId=randomUUID();const code=String(randomInt(100000,1000000));const expiresAt=new Date(Date.now()+SMS_TTL_MS);await prisma.$executeRawUnsafe(`UPDATE "EmployeeSmsMfaChallenge" SET "consumedAt"=NOW() WHERE "organizationId"=$1 AND "userId"=$2 AND "consumedAt" IS NULL`,input.organizationId,input.userId);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSmsMfaChallenge" ("id","organizationId","userId","phone","codeHash","expiresAt","maxAttempts","ipAddress","userAgent") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,challengeId,input.organizationId,input.userId,requirement.phone,smsCodeHash(challengeId,code),expiresAt,SMS_MAX_ATTEMPTS,input.ipAddress??null,input.userAgent??null);try{await sendSecuritySms(requirement.phone,`Sulandra Health security code: ${code}. It expires in 5 minutes. Do not share this code.`)}catch(error){await prisma.$executeRawUnsafe(`UPDATE "EmployeeSmsMfaChallenge" SET "consumedAt"=NOW() WHERE "id"=$1`,challengeId).catch(()=>undefined);throw error}return{required:true,verified:false,challengeIssued:true,challengeId,maskedPhone:maskPhone(requirement.phone),expiresIn:Math.floor(SMS_TTL_MS/1000)}}
export async function verifyEmployeeSmsLoginMfa(prisma:PrismaClient,input:SmsLoginInput&{challengeId?:string;code?:string}){const requirement=await smsRequirement(prisma,input);if(!requirement.required)return{required:false,verified:true};if(!input.challengeId||!input.code||!/^[0-9]{6}$/.test(input.code))return{required:true,verified:false,status:401,reason:'Enter the 6-digit security code sent to your phone'};const challenge=(await prisma.$queryRawUnsafe<any[]>(`SELECT "id","codeHash","expiresAt","attempts","maxAttempts","consumedAt" FROM "EmployeeSmsMfaChallenge" WHERE "id"=$1 AND "organizationId"=$2 AND "userId"=$3 LIMIT 1`,input.challengeId,input.organizationId,input.userId))[0];if(!challenge||challenge.consumedAt)return{required:true,verified:false,status:401,reason:'This security code is no longer valid. Request a new code.'};if(new Date(challenge.expiresAt).getTime()<Date.now()){await prisma.$executeRawUnsafe(`UPDATE "EmployeeSmsMfaChallenge" SET "consumedAt"=NOW() WHERE "id"=$1`,input.challengeId);return{required:true,verified:false,status:401,reason:'This security code expired. Request a new code.'}}const nextAttempts=Number(challenge.attempts||0)+1;const valid=safeEqualHex(String(challenge.codeHash||''),smsCodeHash(input.challengeId,input.code));if(!valid){await prisma.$executeRawUnsafe(`UPDATE "EmployeeSmsMfaChallenge" SET "attempts"=$2,"consumedAt"=CASE WHEN $2>="maxAttempts" THEN NOW() ELSE "consumedAt" END WHERE "id"=$1`,input.challengeId,nextAttempts);return{required:true,verified:false,status:401,reason:nextAttempts>=Number(challenge.maxAttempts||SMS_MAX_ATTEMPTS)?'Too many incorrect security codes. Request a new code.':'Invalid security code'}}await prisma.$executeRawUnsafe(`UPDATE "EmployeeSmsMfaChallenge" SET "attempts"=$2,"consumedAt"=NOW() WHERE "id"=$1`,input.challengeId,nextAttempts);await prisma.$executeRawUnsafe(`UPDATE "EmployeeMfaProfile" SET "smsLastVerifiedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$1 AND "userId"=$2`,input.organizationId,input.userId);return{required:true,verified:true}}

export async function recordLoginEvent(prisma:PrismaClient,input:{organizationId?:string|null;userId?:string|null;identifier:string;decision:'ALLOW'|'DENY';reason?:string;ipAddress?:string;userAgent?:string;sessionId?:string|null}){await ensureEmployeeAuthSecuritySchema(prisma);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeLoginEvent" ("id","organizationId","userId","identifier","decision","reason","ipAddress","userAgent","sessionId") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,randomUUID(),input.organizationId??null,input.userId??null,input.identifier,input.decision,input.reason??null,input.ipAddress??null,input.userAgent??null,input.sessionId??null)}

export function registerEmployeeAuthSecurityRoutes({app,prisma,authOf,requireRoles}:Dependencies){
  const gate=requireRoles(UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.DOO);
  app.get('/api/auth/security/me',async(_req,res,next)=>{try{await ensureEmployeeAuthSecuritySchema(prisma);const auth=authOf(res);const [sessions,mfa,portals,logins]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT "id","issuedAt","expiresAt","revokedAt","ipAddress","userAgent","lastSeenAt" FROM "EmployeeAuthSession" WHERE "organizationId"=$1 AND "userId"=$2 ORDER BY "issuedAt" DESC LIMIT 100`,auth.organizationId,auth.userId),prisma.$queryRawUnsafe<any[]>(`SELECT "required","verified","enrolledAt","lastVerifiedAt","smsRequired","smsPhone","smsConfiguredAt","smsLastVerifiedAt" FROM "EmployeeMfaProfile" WHERE "organizationId"=$1 AND "userId"=$2`,auth.organizationId,auth.userId),prisma.$queryRawUnsafe<any[]>(`SELECT "portal","enabled","reason","updatedAt" FROM "EmployeePortalAccessControl" WHERE "organizationId"=$1 AND "userId"=$2`,auth.organizationId,auth.userId),prisma.$queryRawUnsafe<any[]>(`SELECT "decision","reason","ipAddress","userAgent","createdAt" FROM "EmployeeLoginEvent" WHERE "organizationId"=$1 AND "userId"=$2 ORDER BY "createdAt" DESC LIMIT 100`,auth.organizationId,auth.userId)]);const mfaState=mfa[0]||{required:false,verified:false,smsRequired:false};if(mfaState.smsPhone)mfaState.smsPhone=maskPhone(mfaState.smsPhone);res.json({data:{sessions,mfa:mfaState,portals,logins}})}catch(error){next(error)}});
  app.post('/api/auth/security/mfa/setup',async(req,res,next)=>{try{await ensureEmployeeAuthSecuritySchema(prisma);const auth=authOf(res);const input=setupSchema.parse(req.body);const target=input.employeeId||auth.userId;if(target!==auth.userId&&!([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.DOO] as UserRole[]).includes(auth.role))return void res.status(403).json({error:'Insufficient permissions'});const secret=base32Encode(randomBytes(20));await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeMfaProfile" ("organizationId","userId","encryptedSecret","required","verified","updatedAt") VALUES ($1,$2,$3,$4,FALSE,NOW()) ON CONFLICT ("organizationId","userId") DO UPDATE SET "encryptedSecret"=EXCLUDED."encryptedSecret","required"=EXCLUDED."required","verified"=FALSE,"updatedAt"=NOW()`,auth.organizationId,target,encrypt(secret),input.required);const issuer=encodeURIComponent(process.env.ORGANIZATION_NAME||'Sulandra Health');const account=encodeURIComponent(auth.email||target);res.json({data:{secret,otpauthUrl:`otpauth://totp/${issuer}:${account}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`}})}catch(error){next(error)}});
  app.post('/api/auth/security/mfa/confirm',async(req,res,next)=>{try{await ensureEmployeeAuthSecuritySchema(prisma);const auth=authOf(res);const input=confirmSchema.parse(req.body);const target=input.employeeId||auth.userId;if(target!==auth.userId&&!([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.DOO] as UserRole[]).includes(auth.role))return void res.status(403).json({error:'Insufficient permissions'});const profile=(await prisma.$queryRawUnsafe<any[]>(`SELECT "encryptedSecret" FROM "EmployeeMfaProfile" WHERE "organizationId"=$1 AND "userId"=$2 LIMIT 1`,auth.organizationId,target))[0];if(!profile?.encryptedSecret||!verifyTotp(decrypt(profile.encryptedSecret),input.code))return void res.status(400).json({error:'Invalid authentication code'});await prisma.$executeRawUnsafe(`UPDATE "EmployeeMfaProfile" SET "verified"=TRUE,"enrolledAt"=COALESCE("enrolledAt",NOW()),"lastVerifiedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$1 AND "userId"=$2`,auth.organizationId,target);res.json({data:{verified:true}})}catch(error){next(error)}});
  app.post('/api/admin/auth/security/sms-mfa',gate,async(req,res,next)=>{try{await ensureEmployeeAuthSecuritySchema(prisma);const auth=authOf(res);const input=smsConfigSchema.parse(req.body);const phone=normalizeSmsPhone(input.phone);if(!phone)return void res.status(400).json({error:'Enter a valid mobile phone number including country code'});const target=(await prisma.$queryRawUnsafe<any[]>(`SELECT "id","role"::text AS "role" FROM "User" WHERE "id"=$1 AND "organizationId"=$2 LIMIT 1`,input.employeeId,auth.organizationId))[0];if(!target)return void res.status(404).json({error:'Employee not found'});if(!['ADMINISTRATOR','CEO','DOO'].includes(String(target.role)))return void res.status(409).json({error:'SMS login verification is reserved for privileged administrator accounts'});await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeMfaProfile" ("organizationId","userId","smsPhone","smsRequired","smsConfiguredAt","updatedAt") VALUES ($1,$2,$3,$4,NOW(),NOW()) ON CONFLICT ("organizationId","userId") DO UPDATE SET "smsPhone"=EXCLUDED."smsPhone","smsRequired"=EXCLUDED."smsRequired","smsConfiguredAt"=COALESCE("EmployeeMfaProfile"."smsConfiguredAt",NOW()),"updatedAt"=NOW()`,auth.organizationId,input.employeeId,phone,input.required);res.json({data:{employeeId:input.employeeId,smsRequired:input.required,maskedPhone:maskPhone(phone)}})}catch(error){next(error)}});
  app.post('/api/admin/auth/security/revoke',gate,async(req,res,next)=>{try{await ensureEmployeeAuthSecuritySchema(prisma);const auth=authOf(res);const input=revokeSchema.parse(req.body);if(input.sessionId)await prisma.$executeRawUnsafe(`UPDATE "EmployeeAuthSession" SET "revokedAt"=NOW(),"revokedById"=$1,"revocationReason"=$2 WHERE "organizationId"=$3 AND "userId"=$4 AND "id"=$5 AND "revokedAt" IS NULL`,auth.userId,input.reason,auth.organizationId,input.employeeId,input.sessionId);else await prisma.$executeRawUnsafe(`UPDATE "EmployeeAuthSession" SET "revokedAt"=NOW(),"revokedById"=$1,"revocationReason"=$2 WHERE "organizationId"=$3 AND "userId"=$4 AND "revokedAt" IS NULL`,auth.userId,input.reason,auth.organizationId,input.employeeId);res.json({data:{revoked:true}})}catch(error){next(error)}});
}
