import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();

const definitionSchema=z.object({name:z.string().trim().min(2).max(240),description:z.string().trim().max(8000).default(''),workflowType:z.enum(['ONBOARDING','COMPLIANCE','PERFORMANCE','LEAVE','OFFBOARDING','ASSET_RETURN','DOCUMENT_SIGNATURE','CUSTOM']),triggerType:z.enum(['MANUAL','EVENT','SCHEDULED']).default('MANUAL'),triggerEvent:z.string().trim().max(160).default(''),active:z.boolean().default(true),steps:z.array(z.object({name:z.string().trim().min(1).max(240),description:z.string().trim().max(4000).default(''),assignedRole:z.string().trim().max(120).default(''),dueOffsetHours:z.number().int().min(0).max(8760).default(0),required:z.boolean().default(true)})).min(1).max(100)});
const startSchema=z.object({employeeId:z.string().trim().optional().nullable(),referenceType:z.string().trim().max(120).default(''),referenceId:z.string().trim().max(240).default(''),notes:z.string().trim().max(8000).default('')});
const stepSchema=z.object({status:z.enum(['PENDING','IN_PROGRESS','COMPLETED','WAIVED','BLOCKED']),notes:z.string().trim().max(8000).default(''),assignedToUserId:z.string().trim().optional().nullable()});

export function registerEmployeeWorkflowAutomationRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWorkflowDefinition" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"workflowType" TEXT NOT NULL,"triggerType" TEXT NOT NULL DEFAULT 'MANUAL',"triggerEvent" TEXT NOT NULL DEFAULT '',"active" BOOLEAN NOT NULL DEFAULT TRUE,"steps" JSONB NOT NULL DEFAULT '[]'::jsonb,"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeWorkflowDefinition_org_idx" ON "EmployeeWorkflowDefinition"("organizationId","active","workflowType","name")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWorkflowInstance" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"definitionId" TEXT NOT NULL,"employeeId" TEXT,"referenceType" TEXT NOT NULL DEFAULT '',"referenceId" TEXT NOT NULL DEFAULT '',"status" TEXT NOT NULL DEFAULT 'IN_PROGRESS',"notes" TEXT NOT NULL DEFAULT '',"startedById" TEXT NOT NULL,"startedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"completedAt" TIMESTAMPTZ,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeWorkflowInstance_org_idx" ON "EmployeeWorkflowInstance"("organizationId","status","startedAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWorkflowStep" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"instanceId" TEXT NOT NULL,"stepOrder" INTEGER NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL DEFAULT '',"assignedRole" TEXT NOT NULL DEFAULT '',"assignedToUserId" TEXT,"dueAt" TIMESTAMPTZ,"required" BOOLEAN NOT NULL DEFAULT TRUE,"status" TEXT NOT NULL DEFAULT 'PENDING',"notes" TEXT NOT NULL DEFAULT '',"completedById" TEXT,"completedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeWorkflowStep_order_unique" ON "EmployeeWorkflowStep"("organizationId","instanceId","stepOrder")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeWorkflowEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor workflow access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage workflow automation'),{status:403});return a};
  const protectOwner=async(auth:AuthContext,employeeId:string|null|undefined)=>{if(!employeeId)return;const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,employeeId);if(normalizeEmail(rows[0]?.email)===OWNER_EMAIL&&!((await actor(auth)).isOwner))throw Object.assign(new Error('The Enterprise Owner workflow record cannot be changed by another user'),{status:403})};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWorkflowEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-workflows/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [definitions,instances,steps]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkflowDefinition" WHERE "organizationId"=$1 ORDER BY "active" DESC,"workflowType","name"`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT i.*,d."name" AS "definitionName",d."workflowType" FROM "EmployeeWorkflowInstance" i JOIN "EmployeeWorkflowDefinition" d ON d."id"=i."definitionId" AND d."organizationId"=i."organizationId" WHERE i."organizationId"=$1 ORDER BY i."startedAt" DESC LIMIT 300`,auth.organizationId),
    prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkflowStep" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 1000`,auth.organizationId)
  ]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{activeDefinitions:definitions.filter(r=>r.active).length,activeInstances:instances.filter(r=>r.status==='IN_PROGRESS').length,overdueSteps:steps.filter(r=>r.dueAt&&new Date(r.dueAt)<new Date()&&!['COMPLETED','WAIVED'].includes(r.status)).length,blockedSteps:steps.filter(r=>r.status==='BLOCKED').length},definitions,instances,steps}})}catch(e){next(e)}});

  app.post('/api/admin/employee-workflows/definitions',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=definitionSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWorkflowDefinition" ("id","organizationId","name","description","workflowType","triggerType","triggerEvent","active","steps","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$10)`,id,auth.organizationId,input.name,input.description,input.workflowType,input.triggerType,input.triggerEvent,input.active,JSON.stringify(input.steps),auth.userId);await event(auth,null,'WORKFLOW_DEFINITION_CREATED','WORKFLOW_DEFINITION',id,{workflowType:input.workflowType});await audit?.(auth,'CREATE_EMPLOYEE_WORKFLOW_DEFINITION','EmployeeWorkflowDefinition',id,{workflowType:input.workflowType});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-workflows/definitions/:definitionId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkflowDefinition" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.definitionId))[0];if(!current)return void res.status(404).json({error:'Workflow definition was not found'});const input=definitionSchema.parse({...current,...req.body,steps:req.body?.steps??current.steps});await prisma.$executeRawUnsafe(`UPDATE "EmployeeWorkflowDefinition" SET "name"=$1,"description"=$2,"workflowType"=$3,"triggerType"=$4,"triggerEvent"=$5,"active"=$6,"steps"=$7::jsonb,"updatedById"=$8,"updatedAt"=NOW() WHERE "organizationId"=$9 AND "id"=$10`,input.name,input.description,input.workflowType,input.triggerType,input.triggerEvent,input.active,JSON.stringify(input.steps),auth.userId,auth.organizationId,current.id);await event(auth,null,'WORKFLOW_DEFINITION_UPDATED','WORKFLOW_DEFINITION',current.id,{workflowType:input.workflowType});res.json({data:{id:current.id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-workflows/definitions/:definitionId/start',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=startSchema.parse(req.body);await protectOwner(auth,input.employeeId);const definition=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkflowDefinition" WHERE "organizationId"=$1 AND "id"=$2 AND "active"=TRUE LIMIT 1`,auth.organizationId,req.params.definitionId))[0];if(!definition)return void res.status(404).json({error:'Active workflow definition was not found'});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWorkflowInstance" ("id","organizationId","definitionId","employeeId","referenceType","referenceId","notes","startedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,id,auth.organizationId,definition.id,input.employeeId??null,input.referenceType,input.referenceId,input.notes,auth.userId);const steps=Array.isArray(definition.steps)?definition.steps:JSON.parse(definition.steps||'[]');for(let i=0;i<steps.length;i++){const step=steps[i];await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeWorkflowStep" ("id","organizationId","instanceId","stepOrder","name","description","assignedRole","dueAt","required") VALUES ($1,$2,$3,$4,$5,$6,$7,CASE WHEN $8::int>0 THEN NOW()+($8::text||' hours')::interval ELSE NULL END,$9)`,randomUUID(),auth.organizationId,id,i+1,step.name,step.description||'',step.assignedRole||'',Number(step.dueOffsetHours||0),step.required!==false)}await event(auth,input.employeeId??null,'WORKFLOW_STARTED','WORKFLOW_INSTANCE',id,{definitionId:definition.id});await audit?.(auth,'START_EMPLOYEE_WORKFLOW','EmployeeWorkflowInstance',id,{definitionId:definition.id,employeeId:input.employeeId??null});res.status(201).json({data:{id,status:'IN_PROGRESS'}})}catch(e){next(e)}});

  app.patch('/api/admin/employee-workflows/steps/:stepId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT s.*,i."employeeId",i."status" AS "instanceStatus" FROM "EmployeeWorkflowStep" s JOIN "EmployeeWorkflowInstance" i ON i."id"=s."instanceId" AND i."organizationId"=s."organizationId" WHERE s."organizationId"=$1 AND s."id"=$2 LIMIT 1`,auth.organizationId,req.params.stepId))[0];if(!current)return void res.status(404).json({error:'Workflow step was not found'});await protectOwner(auth,current.employeeId);if(auth.role===UserRole.AUDITOR)return void res.status(403).json({error:'Auditor workflow access is read only'});const input=stepSchema.parse({...current,...req.body});await prisma.$executeRawUnsafe(`UPDATE "EmployeeWorkflowStep" SET "status"=$1,"notes"=$2,"assignedToUserId"=$3,"completedById"=CASE WHEN $1='COMPLETED' THEN $4 ELSE NULL END,"completedAt"=CASE WHEN $1='COMPLETED' THEN NOW() ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "id"=$6`,input.status,input.notes,input.assignedToUserId??null,auth.userId,auth.organizationId,current.id);const open=(await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT COUNT(*)::int AS "count" FROM "EmployeeWorkflowStep" WHERE "organizationId"=$1 AND "instanceId"=$2 AND "required"=TRUE AND "status" NOT IN ('COMPLETED','WAIVED')`,auth.organizationId,current.instanceId))[0]?.count||0;if(open===0)await prisma.$executeRawUnsafe(`UPDATE "EmployeeWorkflowInstance" SET "status"='COMPLETED',"completedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$1 AND "id"=$2`,auth.organizationId,current.instanceId);await event(auth,current.employeeId,'WORKFLOW_STEP_UPDATED','WORKFLOW_STEP',current.id,{status:input.status});res.json({data:{id:current.id,status:input.status,instanceCompleted:open===0}})}catch(e){next(e)}});

  app.get('/api/employee/me/workflows',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const instances=await prisma.$queryRawUnsafe<any[]>(`SELECT i.*,d."name" AS "definitionName",d."workflowType" FROM "EmployeeWorkflowInstance" i JOIN "EmployeeWorkflowDefinition" d ON d."id"=i."definitionId" AND d."organizationId"=i."organizationId" WHERE i."organizationId"=$1 AND i."employeeId"=$2 ORDER BY i."startedAt" DESC`,auth.organizationId,auth.userId);for(const instance of instances)instance.steps=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeWorkflowStep" WHERE "organizationId"=$1 AND "instanceId"=$2 ORDER BY "stepOrder"`,auth.organizationId,instance.id);res.json({data:{instances,metrics:{active:instances.filter(r=>r.status==='IN_PROGRESS').length,completed:instances.filter(r=>r.status==='COMPLETED').length,overdueSteps:instances.flatMap(r=>r.steps).filter((s:any)=>s.dueAt&&new Date(s.dueAt)<new Date()&&!['COMPLETED','WAIVED'].includes(s.status)).length}})}catch(e){next(e)}});
}
