import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.HOUSE_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
const announcementSchema=z.object({title:z.string().trim().min(2).max(240),message:z.string().trim().min(1).max(12000),audience:z.enum(['ALL_EMPLOYEES','MANAGERS','HR_ADMIN','CUSTOM']).default('ALL_EMPLOYEES'),priority:z.enum(['NORMAL','IMPORTANT','URGENT']).default('NORMAL'),publishAt:z.coerce.date().optional().nullable(),expiresAt:z.coerce.date().optional().nullable(),requiresAcknowledgment:z.boolean().default(false),recipientUserIds:z.array(z.string().trim().min(1)).max(1000).default([])});
const notificationSchema=z.object({employeeId:z.string().trim().min(1),title:z.string().trim().min(2).max(240),message:z.string().trim().min(1).max(8000),category:z.enum(['GENERAL','COMPLIANCE','SCHEDULE','PAYROLL','BENEFITS','LEAVE','DOCUMENT','WORKFLOW','SECURITY']).default('GENERAL'),actionUrl:z.string().trim().max(1000).default(''),dueAt:z.coerce.date().optional().nullable()});

export function registerEmployeeCommunicationsNotificationsRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAnnouncement" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"audience" TEXT NOT NULL DEFAULT 'ALL_EMPLOYEES',"priority" TEXT NOT NULL DEFAULT 'NORMAL',"publishAt" TIMESTAMPTZ,"expiresAt" TIMESTAMPTZ,"requiresAcknowledgment" BOOLEAN NOT NULL DEFAULT FALSE,"recipientUserIds" JSONB NOT NULL DEFAULT '[]'::jsonb,"createdById" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeAnnouncement_org_idx" ON "EmployeeAnnouncement"("organizationId","active","publishAt","priority")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeAnnouncementAcknowledgment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"announcementId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"acknowledgedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "EmployeeAnnouncementAcknowledgment_unique" ON "EmployeeAnnouncementAcknowledgment"("organizationId","announcementId","employeeId")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeNotification" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"category" TEXT NOT NULL DEFAULT 'GENERAL',"actionUrl" TEXT NOT NULL DEFAULT '',"dueAt" TIMESTAMPTZ,"readAt" TIMESTAMPTZ,"dismissedAt" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeNotification_employee_idx" ON "EmployeeNotification"("organizationId","employeeId","readAt","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeCommunicationEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"employeeId" TEXT,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor communications access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may manage communications'),{status:403});return a};
  const event=async(auth:AuthContext,employeeId:string|null,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeCommunicationEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,employeeId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  app.get('/api/admin/employee-communications/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [announcements,notifications]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeAnnouncement" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 300`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeNotification" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 500`,auth.organizationId)]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{activeAnnouncements:announcements.filter(r=>r.active).length,urgentAnnouncements:announcements.filter(r=>r.active&&r.priority==='URGENT').length,unreadNotifications:notifications.filter(r=>!r.readAt&&!r.dismissedAt).length},announcements,notifications}})}catch(e){next(e)}});

  app.post('/api/admin/employee-communications/announcements',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=announcementSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAnnouncement" ("id","organizationId","title","message","audience","priority","publishAt","expiresAt","requiresAcknowledgment","recipientUserIds","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11)`,id,auth.organizationId,input.title,input.message,input.audience,input.priority,input.publishAt??null,input.expiresAt??null,input.requiresAcknowledgment,JSON.stringify(input.recipientUserIds),auth.userId);await event(auth,null,'ANNOUNCEMENT_CREATED','ANNOUNCEMENT',id,{priority:input.priority,audience:input.audience});await audit?.(auth,'CREATE_EMPLOYEE_ANNOUNCEMENT','EmployeeAnnouncement',id,{priority:input.priority,audience:input.audience});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.post('/api/admin/employee-communications/notifications',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=notificationSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeNotification" ("id","organizationId","employeeId","title","message","category","actionUrl","dueAt","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,id,auth.organizationId,input.employeeId,input.title,input.message,input.category,input.actionUrl,input.dueAt??null,auth.userId);await event(auth,input.employeeId,'NOTIFICATION_CREATED','NOTIFICATION',id,{category:input.category});res.status(201).json({data:{id}})}catch(e){next(e)}});

  app.get('/api/employee/me/communications',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const announcements=await prisma.$queryRawUnsafe<any[]>(`SELECT a.*,ack."acknowledgedAt" FROM "EmployeeAnnouncement" a LEFT JOIN "EmployeeAnnouncementAcknowledgment" ack ON ack."organizationId"=a."organizationId" AND ack."announcementId"=a."id" AND ack."employeeId"=$2 WHERE a."organizationId"=$1 AND a."active"=TRUE AND (a."publishAt" IS NULL OR a."publishAt"<=NOW()) AND (a."expiresAt" IS NULL OR a."expiresAt">NOW()) AND (a."audience"<>'CUSTOM' OR a."recipientUserIds" ? $2) ORDER BY CASE a."priority" WHEN 'URGENT' THEN 1 WHEN 'IMPORTANT' THEN 2 ELSE 3 END,a."createdAt" DESC`,auth.organizationId,auth.userId);const notifications=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeNotification" WHERE "organizationId"=$1 AND "employeeId"=$2 AND "dismissedAt" IS NULL ORDER BY "createdAt" DESC LIMIT 200`,auth.organizationId,auth.userId);res.json({data:{announcements,notifications,metrics:{unreadNotifications:notifications.filter(r=>!r.readAt).length,pendingAcknowledgments:announcements.filter(r=>r.requiresAcknowledgment&&!r.acknowledgedAt).length}}})}catch(e){next(e)}});

  app.post('/api/employee/me/communications/announcements/:announcementId/acknowledge',async(req,res,next)=>{try{await ready();const auth=authOf(res);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAnnouncementAcknowledgment" ("id","organizationId","announcementId","employeeId") VALUES ($1,$2,$3,$4) ON CONFLICT ("organizationId","announcementId","employeeId") DO NOTHING`,randomUUID(),auth.organizationId,req.params.announcementId,auth.userId);await event(auth,auth.userId,'ANNOUNCEMENT_ACKNOWLEDGED','ANNOUNCEMENT',req.params.announcementId);res.json({data:{acknowledged:true}})}catch(e){next(e)}});

  app.patch('/api/employee/me/communications/notifications/:notificationId',async(req,res,next)=>{try{await ready();const auth=authOf(res);const action=z.object({read:z.boolean().optional(),dismiss:z.boolean().optional()}).parse(req.body);await prisma.$executeRawUnsafe(`UPDATE "EmployeeNotification" SET "readAt"=CASE WHEN $1 THEN COALESCE("readAt",NOW()) ELSE "readAt" END,"dismissedAt"=CASE WHEN $2 THEN NOW() ELSE "dismissedAt" END WHERE "organizationId"=$3 AND "employeeId"=$4 AND "id"=$5`,action.read===true,action.dismiss===true,auth.organizationId,auth.userId,req.params.notificationId);await event(auth,auth.userId,'NOTIFICATION_UPDATED','NOTIFICATION',req.params.notificationId,action);res.json({data:{updated:true}})}catch(e){next(e)}});
}
