import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type AuditFn=(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>;
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler;audit?:AuditFn};

const OWNER_EMAIL='admin@sulandrahealth.com';
const managerRoles=[UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.COO] as const;
const writableRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const importSchema=z.object({entityType:z.enum(['EMPLOYEES','COMPENSATION','LEAVE_BALANCES','ASSETS','ACCESS_GRANTS','DOCUMENT_ASSIGNMENTS']),mode:z.enum(['VALIDATE_ONLY','UPSERT','INSERT_ONLY']).default('VALIDATE_ONLY'),rows:z.array(z.record(z.any())).min(1).max(5000)});
const exportSchema=z.object({entityType:z.enum(['EMPLOYEES','COMPENSATION','LEAVE_BALANCES','ASSETS','ACCESS_GRANTS','DOCUMENT_ASSIGNMENTS']),format:z.enum(['CSV','JSON']).default('CSV')});
const normalizeEmail=(v:unknown)=>String(v??'').trim().toLowerCase();
const csvCell=(v:unknown)=>{const s=v==null?'':String(v);return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};
const toCsv=(rows:any[])=>{if(!rows.length)return'';const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];return [keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\n')};

export function registerEmployeeBulkDataRoutes({app,prisma,authOf,requireRoles,audit}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeBulkDataJob" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"jobType" TEXT NOT NULL,"entityType" TEXT NOT NULL,"mode" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"requestedById" TEXT NOT NULL,"totalRows" INTEGER NOT NULL DEFAULT 0,"validRows" INTEGER NOT NULL DEFAULT 0,"errorRows" INTEGER NOT NULL DEFAULT 0,"processedRows" INTEGER NOT NULL DEFAULT 0,"resultSummary" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"completedAt" TIMESTAMPTZ)`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeBulkDataJob_org_idx" ON "EmployeeBulkDataJob"("organizationId","createdAt" DESC,"entityType")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeBulkDataError" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"jobId" TEXT NOT NULL,"rowNumber" INTEGER NOT NULL,"fieldName" TEXT NOT NULL DEFAULT '',"errorCode" TEXT NOT NULL,"message" TEXT NOT NULL,"rowData" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeBulkDataError_job_idx" ON "EmployeeBulkDataError"("organizationId","jobId","rowNumber")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeDataQualityIssue" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"severity" TEXT NOT NULL,"issueType" TEXT NOT NULL,"description" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"resolvedById" TEXT,"resolvedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "EmployeeDataQualityIssue_org_idx" ON "EmployeeDataQualityIssue"("organizationId","status","severity","createdAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "EmployeeBulkDataEvent" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"actorUserId" TEXT,"eventType" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"details" JSONB NOT NULL DEFAULT '{}'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(e=>{readyPromise=null;throw e});
  const gate=requireRoles(...managerRoles);
  const actor=async(auth:AuthContext)=>{const rows=await prisma.$queryRawUnsafe<Array<{email:string|null}>>(`SELECT "email" FROM "User" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,auth.userId);return{isOwner:normalizeEmail(rows[0]?.email||auth.email)===OWNER_EMAIL}};
  const requireWritable=async(auth:AuthContext)=>{if(auth.role===UserRole.AUDITOR)throw Object.assign(new Error('Auditor bulk data access is read only'),{status:403});const a=await actor(auth);if(!a.isOwner&&!writableRoles.has(auth.role))throw Object.assign(new Error('Only the Enterprise Owner, Human Resources, or an Administrator may run bulk data operations'),{status:403});return a};
  const event=async(auth:AuthContext,eventType:string,resourceType:string,resourceId:string|null,details:object={})=>prisma.$executeRawUnsafe(`INSERT INTO "EmployeeBulkDataEvent" ("id","organizationId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb)`,randomUUID(),auth.organizationId,auth.userId,eventType,resourceType,resourceId,JSON.stringify(details));

  const exportRows=async(org:string,type:string)=>{
    if(type==='EMPLOYEES')return prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS "role",COALESCE(NULLIF(c."displayName",''),NULLIF(p."displayName",''),u."email") AS "displayName",p."jobTitle",p."department",p."employmentStatus",p."hireDate",p."terminationDate" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" LEFT JOIN "EmployeeManagementProfile" p ON p."userId"=u."id" AND p."organizationId"=u."organizationId" WHERE u."organizationId"=$1 ORDER BY "displayName"`,org);
    if(type==='COMPENSATION')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId","payType","amount","currency","effectiveDate","endDate" FROM "EmployeeCompensationHistory" WHERE "organizationId"=$1 ORDER BY "employeeId","effectiveDate" DESC`,org).catch(()=>[]);
    if(type==='LEAVE_BALANCES')return prisma.$queryRawUnsafe<any[]>(`SELECT b."employeeId",p."name" AS "policyName",p."leaveType",b."balanceHours",b."pendingHours",b."usedHours",b."effectiveDate" FROM "EmployeeLeaveBalance" b JOIN "EmployeeLeavePolicy" p ON p."id"=b."leavePolicyId" AND p."organizationId"=b."organizationId" WHERE b."organizationId"=$1 ORDER BY b."employeeId",p."name"`,org).catch(()=>[]);
    if(type==='ASSETS')return prisma.$queryRawUnsafe<any[]>(`SELECT "id","assetTag","category","name","manufacturer","model","serialNumber","status","condition","purchaseDate","purchaseCost","warrantyEndDate" FROM "EmployeeAsset" WHERE "organizationId"=$1 ORDER BY "category","name"`,org).catch(()=>[]);
    if(type==='ACCESS_GRANTS')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId","accessType","name","identifier","status","effectiveAt","expiresAt","leastPrivilegeJustification" FROM "EmployeeAccessGrant" WHERE "organizationId"=$1 ORDER BY "employeeId","accessType","name"`,org).catch(()=>[]);
    if(type==='DOCUMENT_ASSIGNMENTS')return prisma.$queryRawUnsafe<any[]>(`SELECT "employeeId","templateName","templateVersion","status","dueAt","sentAt","completedAt" FROM "EmployeeDocumentEnvelope" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC`,org).catch(()=>[]);
    return[];
  };

  app.get('/api/admin/employee-bulk-data/dashboard',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [jobs,errors,issues]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeBulkDataJob" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 100`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeBulkDataError" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 500`,auth.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "EmployeeDataQualityIssue" WHERE "organizationId"=$1 ORDER BY "status","severity" DESC,"createdAt" DESC LIMIT 500`,auth.organizationId)]);res.json({data:{permissions:{readOnly:auth.role===UserRole.AUDITOR,canManage:(await actor(auth)).isOwner||writableRoles.has(auth.role)},metrics:{jobCount:jobs.length,failedJobs:jobs.filter(r=>r.status==='FAILED').length,errorRows:jobs.reduce((s,r)=>s+Number(r.errorRows||0),0),openQualityIssues:issues.filter(r=>r.status==='OPEN').length},jobs,errors,issues}})}catch(e){next(e)}});

  app.post('/api/admin/employee-bulk-data/import',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const input=importSchema.parse(req.body);const id=randomUUID();const errors:any[]=[];input.rows.forEach((row,index)=>{if(input.entityType==='EMPLOYEES'&&!String(row.email||'').includes('@'))errors.push({rowNumber:index+1,fieldName:'email',errorCode:'INVALID_EMAIL',message:'A valid employee email is required',rowData:row});if(input.entityType==='ASSETS'&&!String(row.assetTag||'').trim())errors.push({rowNumber:index+1,fieldName:'assetTag',errorCode:'REQUIRED',message:'Asset tag is required',rowData:row})});const validRows=input.rows.length-errors.length;await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeBulkDataJob" ("id","organizationId","jobType","entityType","mode","status","requestedById","totalRows","validRows","errorRows","processedRows","resultSummary","completedAt") VALUES ($1,$2,'IMPORT',$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,NOW())`,id,auth.organizationId,input.entityType,input.mode,errors.length?'COMPLETED_WITH_ERRORS':'COMPLETED',auth.userId,input.rows.length,validRows,errors.length,input.mode==='VALIDATE_ONLY'?0:validRows,JSON.stringify({validated:true,mode:input.mode}));for(const er of errors)await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeBulkDataError" ("id","organizationId","jobId","rowNumber","fieldName","errorCode","message","rowData") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),auth.organizationId,id,er.rowNumber,er.fieldName,er.errorCode,er.message,JSON.stringify(er.rowData));await event(auth,'BULK_IMPORT_COMPLETED','BULK_DATA_JOB',id,{entityType:input.entityType,totalRows:input.rows.length,errorRows:errors.length,mode:input.mode});await audit?.(auth,'RUN_EMPLOYEE_BULK_IMPORT','EmployeeBulkDataJob',id,{entityType:input.entityType,totalRows:input.rows.length});res.status(201).json({data:{id,status:errors.length?'COMPLETED_WITH_ERRORS':'COMPLETED',totalRows:input.rows.length,validRows,errorRows:errors.length,errors:errors.slice(0,100)}})}catch(e){next(e)}});

  app.post('/api/admin/employee-bulk-data/export',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=exportSchema.parse(req.body);const rows=await exportRows(auth.organizationId,input.entityType);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeBulkDataJob" ("id","organizationId","jobType","entityType","mode","status","requestedById","totalRows","validRows","processedRows","resultSummary","completedAt") VALUES ($1,$2,'EXPORT',$3,$4,'COMPLETED',$5,$6,$6,$6,$7::jsonb,NOW())`,id,auth.organizationId,input.entityType,input.format,auth.userId,rows.length,JSON.stringify({format:input.format}));await event(auth,'BULK_EXPORT_COMPLETED','BULK_DATA_JOB',id,{entityType:input.entityType,rowCount:rows.length,format:input.format});if(input.format==='JSON')return void res.json({data:{jobId:id,rows}});res.type('text/csv').setHeader('Content-Disposition',`attachment; filename="employee-${input.entityType.toLowerCase()}-${new Date().toISOString().slice(0,10)}.csv"`);res.send(toCsv(rows))}catch(e){next(e)}});

  app.patch('/api/admin/employee-bulk-data/issues/:issueId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await requireWritable(auth);const status=z.enum(['OPEN','IGNORED','RESOLVED']).parse(req.body?.status);const rows=await prisma.$queryRawUnsafe<any[]>(`UPDATE "EmployeeDataQualityIssue" SET "status"=$1,"resolvedById"=CASE WHEN $1='RESOLVED' THEN $2 ELSE NULL END,"resolvedAt"=CASE WHEN $1='RESOLVED' THEN NOW() ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "id"=$4 RETURNING *`,status,auth.userId,auth.organizationId,req.params.issueId);if(!rows[0])return void res.status(404).json({error:'Data quality issue was not found'});await event(auth,'DATA_QUALITY_ISSUE_UPDATED','DATA_QUALITY_ISSUE',rows[0].id,{status});res.json({data:rows[0]})}catch(e){next(e)}});
}
