import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import type { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
type EntityRow={id:string;code:string;displayName:string;legalName:string;status:string;isProvider:boolean;metadata:Record<string,unknown>};
const readRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','AUDITOR','HR_MANAGER','BILLING_SPECIALIST','RN','DELEGATING_NURSE','CEO','DOO']);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening Enterprise Analytics');return a.legalEntityId;};
const ensure=(a:AuthContext)=>{entity(a);if(!readRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Enterprise analytics access is required');};
const q=(name:string)=>`"${name.replaceAll('"','""')}"`;
async function tableExists(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1) AS exists`,table);return rows[0]?.exists===true;}
async function columns(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{column_name:string}>>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,table);return new Set(rows.map(r=>r.column_name));}
async function count(prisma:PrismaClient,table:string,org:string,entityId:string,where='TRUE',extra:unknown[]=[]){try{if(!(await tableExists(prisma,table)))return 0;const names=await columns(prisma,table),args:unknown[]=[];let scope='TRUE';if(names.has('organizationId')){args.push(org);scope=`${q('organizationId')}=$${args.length}`;}if(names.has('legalEntityId')){args.push(entityId);scope+=` AND ${q('legalEntityId')}=$${args.length}`;}for(const value of extra)args.push(value);const shifted=where.replace(/\$(\d+)/g,(_m,n)=>`$${Number(n)+args.length-extra.length}`);const rows=await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT count(*)::int AS count FROM ${q(table)} WHERE ${scope} AND (${shifted})`,...args);return Number(rows[0]?.count||0);}catch{return 0;}}
async function sum(prisma:PrismaClient,table:string,column:string,org:string,entityId:string,where='TRUE'){try{if(!(await tableExists(prisma,table)))return 0;const names=await columns(prisma,table);if(!names.has(column))return 0;const args:unknown[]=[];let scope='TRUE';if(names.has('organizationId')){args.push(org);scope=`${q('organizationId')}=$${args.length}`;}if(names.has('legalEntityId')){args.push(entityId);scope+=` AND ${q('legalEntityId')}=$${args.length}`;}const rows=await prisma.$queryRawUnsafe<Array<{total:string|null}>>(`SELECT COALESCE(sum(${q(column)}),0)::text AS total FROM ${q(table)} WHERE ${scope} AND (${where})`,...args);return Number(rows[0]?.total||0);}catch{return 0;}}
async function metricBundle(prisma:PrismaClient,a:AuthContext,e:EntityRow){const org=a.organizationId,id=e.id;const [clients,intakesOpen,notificationsOpen,notificationsUrgent,complianceBlockers,complianceDue60,dqOpen,dqCritical,revenueReview,revenueHeld,revenueReady,revenueReadyAmount,timeCorrections,employeeDocsReview,sclsTasks,sclsOverdue,hhReferrals,hhEpisodes,hhVisitsToday,hhVisitsOpen,nmtOrders,nmtTripsToday,nmtTripsOpen,highIncidents,carePlansReview]=await Promise.all([
 count(prisma,'ClientEnrollment',org,id,`"status" IN ('ACTIVE','PENDING','PAUSED')`),
 count(prisma,'ClientIntakeCase',org,id,`"status" IN ('DRAFT','IN_PROGRESS','SUBMITTED','REVIEW_REQUIRED')`),
 count(prisma,'EnterpriseWorkNotification',org,id,`"status" IN ('OPEN','READ')`),
 count(prisma,'EnterpriseWorkNotification',org,id,`"status" IN ('OPEN','READ') AND "priority" IN ('URGENT','CRITICAL')`),
 count(prisma,'CompanyComplianceItem',org,id,`"status" IN ('EXPIRED','SUSPENDED') OR ("expirationDate" IS NOT NULL AND "expirationDate"<CURRENT_DATE)`),
 count(prisma,'CompanyComplianceItem',org,id,`"status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE') AND "expirationDate" IS NOT NULL AND "expirationDate">=CURRENT_DATE AND "expirationDate"<=CURRENT_DATE+60`),
 count(prisma,'EnterpriseDataQualityIssue',org,id,`"status" IN ('OPEN','ACKNOWLEDGED')`),
 count(prisma,'EnterpriseDataQualityIssue',org,id,`"status" IN ('OPEN','ACKNOWLEDGED') AND "severity"='CRITICAL'`),
 count(prisma,'RevenueCycleServiceEvent',org,id,`"status"='REVIEW_REQUIRED'`),
 count(prisma,'RevenueCycleServiceEvent',org,id,`"status"='HELD'`),
 count(prisma,'RevenueCycleServiceEvent',org,id,`"status"='READY'`),
 sum(prisma,'RevenueCycleServiceEvent','estimatedAmount',org,id,`"status"='READY'`),
 count(prisma,'EmployeeTimeCorrection',org,id,`"status"='PENDING'`),
 count(prisma,'EmployeeDocumentSubmission',org,id,`"status" IN ('SUBMITTED','CHANGES_REQUESTED')`),
 count(prisma,'SpireClinicalTask',org,id,`"status" IN ('OPEN','IN_PROGRESS')`),
 count(prisma,'SpireClinicalTask',org,id,`"status" IN ('OPEN','IN_PROGRESS') AND "dueAt" IS NOT NULL AND "dueAt"<NOW()`),
 count(prisma,'HomeHealthReferral',org,id,`"status" IN ('RECEIVED','REVIEW_REQUIRED','INTAKE_CREATED','ACCEPTED')`),
 count(prisma,'HomeHealthEpisode',org,id,`"status" IN ('ACTIVE','ADMITTED','START_OF_CARE','OPEN')`),
 count(prisma,'HomeHealthVisit',org,id,`COALESCE("scheduledStart","createdAt")::date=CURRENT_DATE`),
 count(prisma,'HomeHealthVisit',org,id,`"status" IN ('SCHEDULED','CONFIRMED','IN_PROGRESS')`),
 count(prisma,'NmtTransportOrder',org,id,`"status" IN ('RECEIVED','REVIEW_REQUIRED','ACCEPTED','SCHEDULED','IN_PROGRESS')`),
 count(prisma,'NmtTrip',org,id,`COALESCE("scheduledPickupAt","createdAt")::date=CURRENT_DATE`),
 count(prisma,'NmtTrip',org,id,`"status" NOT IN ('COMPLETED','CANCELLED','NO_SHOW')`),
 count(prisma,'SpireIncident',org,id,`COALESCE("severity","priority",'') IN ('HIGH','CRITICAL','URGENT') AND "status" NOT IN ('CLOSED','RESOLVED','CANCELLED')`),
 count(prisma,'SpireCarePlan',org,id,`"status" IN ('DRAFT','IN_REVIEW','REVIEW','CHANGES_REQUESTED')`)
 ]);return{entity:{id:e.id,code:e.code,displayName:e.displayName,legalName:e.legalName,status:e.status,isProvider:e.isProvider,metadata:e.metadata},clients,intakesOpen,notifications:{open:notificationsOpen,urgent:notificationsUrgent},compliance:{blockers:complianceBlockers,due60:complianceDue60},dataQuality:{open:dqOpen,critical:dqCritical},revenue:{review:revenueReview,held:revenueHeld,ready:revenueReady,readyEstimatedAmount:revenueReadyAmount},workforce:{timeCorrectionsPending:timeCorrections,documentsReview:employeeDocsReview},scls:{tasksOpen:sclsTasks,tasksOverdue:sclsOverdue},homeHealth:{referralsOpen:hhReferrals,episodesActive:hhEpisodes,visitsToday:hhVisitsToday,visitsOpen:hhVisitsOpen},nmt:{ordersOpen:nmtOrders,tripsToday:nmtTripsToday,tripsOpen:nmtTripsOpen},spire:{highIncidentsOpen:highIncidents,carePlansReview}};}
async function dailySeries(prisma:PrismaClient,a:AuthContext,entityId:string,days:number){const start=new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10);const result:Record<string,Record<string,number>>={};for(let i=0;i<days;i++){const d=new Date(Date.parse(`${start}T00:00:00Z`)+i*86400000).toISOString().slice(0,10);result[d]={intakes:0,homeHealthVisits:0,nmtTrips:0,revenueEvents:0,incidents:0};}async function fill(table:string,dateExpr:string,key:string){try{if(!(await tableExists(prisma,table)))return;const names=await columns(prisma,table),args:unknown[]=[a.organizationId,entityId,start];let scope=`"organizationId"=$1`;if(names.has('legalEntityId'))scope+=` AND "legalEntityId"=$2`;else args.splice(1,1);const startIndex=names.has('legalEntityId')?3:2;const rows=await prisma.$queryRawUnsafe<Array<{day:string;count:number}>>(`SELECT (${dateExpr})::date::text AS day,count(*)::int AS count FROM ${q(table)} WHERE ${scope} AND (${dateExpr})::date >= $${startIndex}::date GROUP BY 1 ORDER BY 1`,...args);for(const row of rows)if(result[row.day])result[row.day][key]=Number(row.count||0);}catch{}}
 await Promise.all([fill('ClientIntakeCase','COALESCE("createdAt",NOW())','intakes'),fill('HomeHealthVisit','COALESCE("actualStart","scheduledStart","createdAt")','homeHealthVisits'),fill('NmtTrip','COALESCE("actualPickupAt","scheduledPickupAt","createdAt")','nmtTrips'),fill('RevenueCycleServiceEvent','COALESCE("serviceStart","createdAt")','revenueEvents'),fill('SpireIncident','COALESCE("occurredAt","createdAt")','incidents')]);return Object.entries(result).map(([date,metrics])=>({date,...metrics}));}
export const registerEnterpriseAnalyticsRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/enterprise-analytics/overview',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);let entities:EntityRow[];if(owner(a))entities=await prisma.$queryRawUnsafe<EntityRow[]>(`SELECT "id","code","displayName","legalName","status","isProvider","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 ORDER BY "code"`,a.organizationId);else entities=await prisma.$queryRawUnsafe<EntityRow[]>(`SELECT "id","code","displayName","legalName","status","isProvider","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));const metrics=[];for(const e of entities)metrics.push(await metricBundle(prisma,a,e));const portfolio=metrics.reduce((s,m)=>({clients:s.clients+m.clients,intakesOpen:s.intakesOpen+m.intakesOpen,notificationsOpen:s.notificationsOpen+m.notifications.open,notificationsUrgent:s.notificationsUrgent+m.notifications.urgent,complianceBlockers:s.complianceBlockers+m.compliance.blockers,dataQualityOpen:s.dataQualityOpen+m.dataQuality.open,dataQualityCritical:s.dataQualityCritical+m.dataQuality.critical,revenueReview:s.revenueReview+m.revenue.review,revenueHeld:s.revenueHeld+m.revenue.held,revenueReady:s.revenueReady+m.revenue.ready,revenueReadyEstimatedAmount:s.revenueReadyEstimatedAmount+m.revenue.readyEstimatedAmount}),{clients:0,intakesOpen:0,notificationsOpen:0,notificationsUrgent:0,complianceBlockers:0,dataQualityOpen:0,dataQualityCritical:0,revenueReview:0,revenueHeld:0,revenueReady:0,revenueReadyEstimatedAmount:0});res.json({data:{enterpriseOwner:owner(a),selectedLegalEntityId:entity(a),portfolio,entities:metrics,generatedAt:new Date().toISOString()}});}catch(e){next(e);}});
 app.get('/api/enterprise-analytics/activity',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const days=Math.min(90,Math.max(7,Number(req.query.days||30)));res.json({data:{legalEntityId:entity(a),days,series:await dailySeries(prisma,a,entity(a),days)}});}catch(e){next(e);}});
};
