import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening My Work notifications');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const clean=(v:unknown,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const actionSchema=z.object({action:z.enum(['READ','UNREAD','COMPLETE','DISMISS']),comment:z.string().trim().max(2000).optional().nullable()});
export const registerEnterpriseWorkNotificationRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/work/notifications',async(req,res,next)=>{try{const a=authOf(res);const ent=entity(a),status=clean(req.query.status,30),module=clean(req.query.module,80),limit=Math.min(500,Math.max(1,Number(req.query.limit||100)));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EnterpriseWorkNotification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ("assignedUserId"=$3 OR ($4::boolean=TRUE) OR ("assignedUserId" IS NULL AND (jsonb_array_length("audienceRoles")=0 OR "audienceRoles" ? $5))) AND ($6='' OR "status"=$6) AND ($7='' OR "module"=$7) ORDER BY CASE "priority" WHEN 'CRITICAL' THEN 0 WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 ELSE 3 END,"dueAt" NULLS LAST,"createdAt" DESC LIMIT $8`,a.organizationId,ent,a.userId,owner(a),String(a.role),status,module,limit);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/work/notifications/summary',async(_req,res,next)=>{try{const a=authOf(res),ent=entity(a);const rows=await prisma.$queryRawUnsafe<Array<{status:string;priority:string;count:number}>>(`SELECT "status","priority",count(*)::int AS count FROM "EnterpriseWorkNotification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ("assignedUserId"=$3 OR ($4::boolean=TRUE) OR ("assignedUserId" IS NULL AND (jsonb_array_length("audienceRoles")=0 OR "audienceRoles" ? $5))) GROUP BY "status","priority"`,a.organizationId,ent,a.userId,owner(a),String(a.role));const total=rows.reduce((s,r)=>s+Number(r.count||0),0),open=rows.filter(r=>['OPEN','READ'].includes(r.status)).reduce((s,r)=>s+Number(r.count||0),0),urgent=rows.filter(r=>['OPEN','READ'].includes(r.status)&&['URGENT','CRITICAL'].includes(r.priority)).reduce((s,r)=>s+Number(r.count||0),0);res.json({data:{total,open,urgent,breakdown:rows}});}catch(e){next(e);}});
  app.post('/api/work/notifications/:notificationId/action',async(req,res,next)=>{try{const a=authOf(res),ent=entity(a),i=actionSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<{id:string;assignedUserId:string|null;audienceRoles:string[];status:string;resourceType:string;resourceId:string}>>(`SELECT "id","assignedUserId","audienceRoles","status","resourceType","resourceId" FROM "EnterpriseWorkNotification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,ent,req.params.notificationId),n=rows[0];if(!n)throw httpError(404,'Work notification was not found');const roles=Array.isArray(n.audienceRoles)?n.audienceRoles:[];const allowed=n.assignedUserId===a.userId||owner(a)||(!n.assignedUserId&&(roles.length===0||roles.includes(String(a.role))));if(!allowed)throw httpError(403,'This work notification is outside your assigned scope');if(i.action==='READ')await prisma.$executeRawUnsafe(`UPDATE "EnterpriseWorkNotification" SET "status"=CASE WHEN "status"='OPEN' THEN 'READ' ELSE "status" END,"readAt"=COALESCE("readAt",NOW()),"readByUserId"=COALESCE("readByUserId",$1),"updatedAt"=NOW() WHERE "id"=$2`,a.userId,n.id);if(i.action==='UNREAD')await prisma.$executeRawUnsafe(`UPDATE "EnterpriseWorkNotification" SET "status"=CASE WHEN "status"='READ' THEN 'OPEN' ELSE "status" END,"readAt"=NULL,"readByUserId"=NULL,"updatedAt"=NOW() WHERE "id"=$1`,n.id);if(i.action==='COMPLETE')await prisma.$executeRawUnsafe(`UPDATE "EnterpriseWorkNotification" SET "status"='COMPLETED',"completedAt"=NOW(),"completedByUserId"=$1,"updatedAt"=NOW(),"metadata"="metadata"||$2::jsonb WHERE "id"=$3`,a.userId,JSON.stringify(i.comment?{completionComment:i.comment}:{}),n.id);if(i.action==='DISMISS')await prisma.$executeRawUnsafe(`UPDATE "EnterpriseWorkNotification" SET "status"='DISMISSED',"completedAt"=NOW(),"completedByUserId"=$1,"updatedAt"=NOW(),"metadata"="metadata"||$2::jsonb WHERE "id"=$3`,a.userId,JSON.stringify(i.comment?{dismissalComment:i.comment}:{}),n.id);await audit?.(a,`WORK_NOTIFICATION_${i.action}`,'EnterpriseWorkNotification',n.id,{resourceType:n.resourceType,resourceId:n.resourceId,comment:i.comment??null});res.json({data:{id:n.id,action:i.action}});}catch(e){next(e);}});
};
