import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import type { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
type Candidate={issueKey:string;module:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';resourceType:string;resourceId?:string|null;title:string;details?:string|null;actionPath?:string|null;assignedUserId?:string|null;metadata?:Record<string,unknown>};
type JsonRow={data:Record<string,unknown>};

const readRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','AUDITOR','HR_MANAGER','BILLING_SPECIALIST','RN','DELEGATING_NURSE','CEO','DOO']);
const writeRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','HR_MANAGER','BILLING_SPECIALIST','RN','DELEGATING_NURSE','CEO','DOO']);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening Data Quality');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureRead=(a:AuthContext)=>{entity(a);if(!readRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Enterprise Data Quality access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writeRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Enterprise Data Quality write access is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const now=()=>Date.now();
const ageDays=(v:unknown)=>{const t=Date.parse(String(v||''));return Number.isFinite(t)?(now()-t)/86400000:null;};
const daysUntil=(v:unknown)=>{const t=Date.parse(String(v||''));return Number.isFinite(t)?(t-now())/86400000:null;};
const upper=(v:unknown)=>String(v||'').trim().toUpperCase();
const truthy=(v:unknown)=>v===true||String(v||'').toLowerCase()==='true';
const pathFor=(table:string,row:Record<string,unknown>)=>{const id=String(row.id||'');const patientId=String(row.patientId||row.clientId||'');if(table==='ClientIntakeCase')return `/client-intake.html?caseId=${encodeURIComponent(id)}`;if(table==='CompanyComplianceItem')return '/company-compliance.html';if(table==='EmployeeTimeCorrection'||table==='EmployeeDocumentSubmission')return '/workforce-admin.html';if(table==='SpireClinicalTask')return '/scls-tasks.html';if(table==='HomeHealthReferral')return '/home-health-referrals.html';if(table==='HomeHealthEpisode'||table==='HomeHealthPlanOfCare'||table==='HomeHealthVisit')return '/home-health.html';if(table==='NmtTrip')return '/nmt-dispatch.html';if(table==='RevenueCycleServiceEvent'||table==='RevenueCycleBatch')return '/revenue-cycle.html';if(table==='SpireMedicationAdministrationQualification')return '/spire-medication-qualifications.html';if(table==='SpireCarePlan')return patientId?`/spire.html?patientId=${encodeURIComponent(patientId)}#care-plan`:'/spire.html';if(table==='SpireIncident')return patientId?`/spire.html?patientId=${encodeURIComponent(patientId)}#incidents`:'/spire.html';return '/my-work.html';};
const labelPerson=(r:Record<string,unknown>)=>[r.preferredName||r.prospectPreferredName||r.firstName||r.prospectFirstName,r.lastName||r.prospectLastName].filter(Boolean).join(' ')||String(r.patientId||r.clientId||r.userId||r.id||'record');

async function tableExists(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT to_regclass($1) IS NOT NULL AS exists`,`public.${table}`);return rows[0]?.exists===true;}
async function scopedRows(prisma:PrismaClient,a:AuthContext,table:string,limit=5000):Promise<Record<string,unknown>[]> {try{if(!(await tableExists(prisma,table)))return[];const columns=await prisma.$queryRawUnsafe<Array<{column_name:string}>>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,table),names=new Set(columns.map(c=>c.column_name));let sql=`SELECT to_jsonb(t) AS data FROM "${table.replaceAll('"','""')}" t WHERE `;const args:unknown[]=[];if(names.has('organizationId')){args.push(a.organizationId);sql+=`t."organizationId"=$${args.length}`;}else sql+='TRUE';if(names.has('legalEntityId')){args.push(entity(a));sql+=` AND t."legalEntityId"=$${args.length}`;}sql+=` LIMIT ${Math.max(1,Math.min(limit,10000))}`;const rows=await prisma.$queryRawUnsafe<JsonRow[]>(sql,...args);return rows.map(r=>r.data||{});}catch{return[];}}
async function issueEvent(prisma:PrismaClient,a:AuthContext,issueId:string,eventType:string,fromStatus:string|null,toStatus:string|null,comment:string|null,metadata:Record<string,unknown>={}){await prisma.$executeRawUnsafe(`INSERT INTO "EnterpriseDataQualityEvent"("id","organizationId","legalEntityId","issueId","eventType","actorUserId","fromStatus","toStatus","comment","metadata") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,randomUUID(),a.organizationId,entity(a),issueId,eventType,a.userId,fromStatus,toStatus,comment,JSON.stringify(metadata));}
async function upsertCandidate(prisma:PrismaClient,a:AuthContext,c:Candidate){const existing=await prisma.$queryRawUnsafe<Array<{id:string;status:string;severity:string;title:string}>>(`SELECT "id","status","severity","title" FROM "EnterpriseDataQualityIssue" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "issueKey"=$3 LIMIT 1`,a.organizationId,entity(a),c.issueKey),old=existing[0];if(!old){const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EnterpriseDataQualityIssue"("id","organizationId","legalEntityId","issueKey","module","severity","status","resourceType","resourceId","title","details","actionPath","assignedUserId","detectedBy","metadata") VALUES($1,$2,$3,$4,$5,$6,'OPEN',$7,$8,$9,$10,$11,$12,'SYSTEM_SCAN',$13::jsonb)`,id,a.organizationId,entity(a),c.issueKey,c.module,c.severity,c.resourceType,c.resourceId??null,c.title,c.details??null,c.actionPath??null,c.assignedUserId??null,JSON.stringify(c.metadata||{}));await issueEvent(prisma,a,id,'DETECTED',null,'OPEN',null,{severity:c.severity});return id;}const reopen=['RESOLVED','IGNORED'].includes(old.status);const nextStatus=reopen?'OPEN':old.status;await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityIssue" SET "module"=$1,"severity"=$2,"status"=$3,"resourceType"=$4,"resourceId"=$5,"title"=$6,"details"=$7,"actionPath"=$8,"assignedUserId"=COALESCE($9,"assignedUserId"),"lastSeenAt"=NOW(),"resolvedAt"=CASE WHEN $3='OPEN' THEN NULL ELSE "resolvedAt" END,"resolvedByUserId"=CASE WHEN $3='OPEN' THEN NULL ELSE "resolvedByUserId" END,"metadata"=$10::jsonb,"updatedAt"=NOW() WHERE "id"=$11`,c.module,c.severity,nextStatus,c.resourceType,c.resourceId??null,c.title,c.details??null,c.actionPath??null,c.assignedUserId??null,JSON.stringify(c.metadata||{}),old.id);if(reopen)await issueEvent(prisma,a,old.id,'REOPENED',old.status,'OPEN','Underlying condition was detected again.',{severity:c.severity});else if(old.severity!==c.severity||old.title!==c.title)await issueEvent(prisma,a,old.id,'UPDATED',old.status,old.status,null,{severity:c.severity});return old.id;}

function staleCandidate(table:string,row:Record<string,unknown>,condition:string,module:string,severity:Candidate['severity'],title:string,details:string):Candidate{return{issueKey:`${module}:${table}:${String(row.id||'unknown')}:${condition}`,module,severity,resourceType:table,resourceId:String(row.id||'')||null,title,details,actionPath:pathFor(table,row),assignedUserId:clean(row.assignedUserId||row.assignedCoordinatorUserId||row.responsibleUserId||row.caseManagerUserId||row.primaryNurseUserId,120)||null,metadata:{condition,status:row.status??null}};}

async function scanCandidates(prisma:PrismaClient,a:AuthContext){const candidates:Candidate[]=[];
  const intakes=await scopedRows(prisma,a,'ClientIntakeCase');for(const r of intakes){const st=upper(r.status),age=ageDays(r.updatedAt||r.createdAt);if(['SUBMITTED','REVIEW_REQUIRED'].includes(st)&&age!==null&&age>2)candidates.push(staleCandidate('ClientIntakeCase',r,'STALE_REVIEW','CLIENT_INTAKE',age>5?'HIGH':'MEDIUM',`Client Intake review is stale — ${labelPerson(r)}`,`Intake has remained ${st.replaceAll('_',' ')} for ${Math.floor(age)} days without resolution.`));if(['DRAFT','IN_PROGRESS'].includes(st)&&age!==null&&age>7)candidates.push(staleCandidate('ClientIntakeCase',r,'STALE_DRAFT','CLIENT_INTAKE',age>30?'HIGH':'MEDIUM',`Client Intake draft is aging — ${labelPerson(r)}`,`Intake has not progressed for ${Math.floor(age)} days.`));}
  const compliance=await scopedRows(prisma,a,'CompanyComplianceItem');for(const r of compliance){const st=upper(r.status),d=daysUntil(r.expirationDate);if(st==='EXPIRED'||st==='SUSPENDED'||(d!==null&&d<0))candidates.push(staleCandidate('CompanyComplianceItem',r,'EXPIRED_OR_SUSPENDED','COMPLIANCE',st==='SUSPENDED'?'CRITICAL':'CRITICAL',`Compliance blocker — ${clean(r.requirementName,300)}`,`${clean(r.requirementName,300)} is ${st||'past expiration'}${r.expirationDate?` (date ${String(r.expirationDate).slice(0,10)})`:''}.`));else if(st==='PENDING_VERIFICATION'&&d!==null&&d<=30)candidates.push(staleCandidate('CompanyComplianceItem',r,'UNVERIFIED_DUE','COMPLIANCE','HIGH',`Unverified compliance item is due — ${clean(r.requirementName,300)}`,`Verification is still pending and the tracked date is within ${Math.max(0,Math.ceil(d))} days.`));}
  const corrections=await scopedRows(prisma,a,'EmployeeTimeCorrection');for(const r of corrections){const age=ageDays(r.requestedAt||r.createdAt);if(upper(r.status)==='PENDING'&&age!==null&&age>3)candidates.push(staleCandidate('EmployeeTimeCorrection',r,'PENDING_TOO_LONG','WORKFORCE',age>7?'HIGH':'MEDIUM',`Time correction pending — ${clean(r.userId,120)}`,`${clean(r.correctionKind,120).replaceAll('_',' ')} has waited ${Math.floor(age)} days for review.`));}
  const docs=await scopedRows(prisma,a,'EmployeeDocumentSubmission');for(const r of docs){const st=upper(r.status),age=ageDays(r.updatedAt||r.submittedAt||r.createdAt),d=daysUntil(r.expirationDate);if(['SUBMITTED','CHANGES_REQUESTED'].includes(st)&&age!==null&&age>3)candidates.push(staleCandidate('EmployeeDocumentSubmission',r,'STALE_REVIEW','WORKFORCE','MEDIUM',`Employee document review is stale — ${clean(r.userId,120)}`,`${clean(r.documentType,120).replaceAll('_',' ')} has remained ${st.replaceAll('_',' ')} for ${Math.floor(age)} days.`));if(st==='APPROVED'&&d!==null&&d<0)candidates.push(staleCandidate('EmployeeDocumentSubmission',r,'APPROVED_BUT_EXPIRED','WORKFORCE','HIGH',`Approved employee credential is expired — ${clean(r.userId,120)}`,`${clean(r.documentType,120).replaceAll('_',' ')} expired ${Math.abs(Math.floor(d))} days ago.`));}
  const tasks=await scopedRows(prisma,a,'SpireClinicalTask');for(const r of tasks){const st=upper(r.status),d=daysUntil(r.dueAt);if(['OPEN','IN_PROGRESS'].includes(st)&&d!==null&&d<0)candidates.push(staleCandidate('SpireClinicalTask',r,'OVERDUE','SCLS',d<-2?'HIGH':'MEDIUM',`Overdue SCLS task — ${clean(r.title,300)}`,`Task is ${Math.abs(Math.floor(d))} day(s) past due and remains ${st.replaceAll('_',' ')}.`));}
  const intakeMap=new Map(intakes.map(r=>[String(r.id||''),r]));const referrals=await scopedRows(prisma,a,'HomeHealthReferral');for(const r of referrals){const st=upper(r.status);if(['ACCEPTED','INTAKE_CREATED','REVIEW_REQUIRED'].includes(st)){const intake=intakeMap.get(String(r.intakeCaseId||''));if(!r.intakeCaseId)candidates.push(staleCandidate('HomeHealthReferral',r,'NO_INTAKE','HOME_HEALTH','HIGH',`Home Health referral has no Client Intake — ${labelPerson(r)}`,'Referral has progressed operationally but no Client Intake is linked.'));else if(!intake||upper(intake.status)!=='APPROVED')candidates.push(staleCandidate('HomeHealthReferral',r,'INTAKE_NOT_APPROVED','HOME_HEALTH','HIGH',`Home Health referral is waiting on approved intake — ${labelPerson(r)}`,`Linked Client Intake status is ${upper(intake?.status)||'NOT FOUND'}.`));}}
  const episodes=await scopedRows(prisma,a,'HomeHealthEpisode');const pocs=await scopedRows(prisma,a,'HomeHealthPlanOfCare');const pocEpisodeIds=new Set(pocs.filter(p=>!['CLOSED','SUPERSEDED','DISCONTINUED'].includes(upper(p.status))).map(p=>String(p.episodeId||'')));for(const r of episodes){const st=upper(r.status),id=String(r.id||''),d=daysUntil(r.certificationEnd||r.certificationEndDate||r.periodEnd||r.episodeEndDate);if(['ACTIVE','ADMITTED','START_OF_CARE','OPEN'].includes(st)&&!pocEpisodeIds.has(id))candidates.push(staleCandidate('HomeHealthEpisode',r,'NO_ACTIVE_POC','HOME_HEALTH','CRITICAL',`Active Home Health episode has no active Plan of Care — ${labelPerson(r)}`,'An active episode must have a current Plan of Care before ongoing skilled service delivery.'));if(['ACTIVE','ADMITTED','START_OF_CARE','OPEN'].includes(st)&&d!==null&&d<=14)candidates.push(staleCandidate('HomeHealthEpisode',r,'CERTIFICATION_DUE','HOME_HEALTH',d<0?'CRITICAL':'HIGH',`Home Health certification period requires action — ${labelPerson(r)}`,d<0?`Certification period is ${Math.abs(Math.floor(d))} days past its tracked end date.`:`Certification period ends in ${Math.ceil(d)} days.`));}
  for(const r of pocs){const st=upper(r.status),age=ageDays(r.updatedAt||r.createdAt);if(!['SIGNED','ACTIVE','SUPERSEDED','CLOSED','DISCONTINUED'].includes(st)&&age!==null&&age>3)candidates.push(staleCandidate('HomeHealthPlanOfCare',r,'STALE_UNSIGNED','HOME_HEALTH',age>7?'HIGH':'MEDIUM','Home Health Plan of Care remains unsigned/incomplete',`Plan of Care status ${st||'UNKNOWN'} has remained unresolved for ${Math.floor(age)} days.`));}
  const trips=await scopedRows(prisma,a,'NmtTrip');for(const r of trips){const st=upper(r.status),scheduled=daysUntil(r.scheduledPickupAt||r.requestedPickupAt||r.pickupAt),closed=['COMPLETED','CANCELLED','NO_SHOW'].includes(st),driver=clean(r.driverUserId||r.assignedDriverUserId||r.driverProfileId||r.driverId,120),vehicle=clean(r.vehicleId||r.assignedVehicleId,120);if(!closed&&['SCHEDULED','DISPATCHED','ASSIGNED','IN_PROGRESS'].includes(st)&&(!driver||!vehicle))candidates.push(staleCandidate('NmtTrip',r,'MISSING_DRIVER_OR_VEHICLE','NMT','HIGH',`NMT trip is missing ${!driver&&!vehicle?'driver and vehicle':!driver?'driver':'vehicle'}`,`Trip ${clean(r.tripNumber||r.id,160)} is ${st} without all required dispatch assignments.`));if(!closed&&scheduled!==null&&scheduled<-0.25)candidates.push(staleCandidate('NmtTrip',r,'STALE_AFTER_PICKUP','NMT',scheduled<-1?'HIGH':'MEDIUM',`NMT trip remains open after scheduled pickup — ${clean(r.tripNumber||r.id,160)}`,`Trip remains ${st||'OPEN'} after its scheduled/requested pickup time.`));}
  const revenue=await scopedRows(prisma,a,'RevenueCycleServiceEvent');for(const r of revenue){const st=upper(r.status),age=ageDays(r.updatedAt||r.createdAt);if(st==='HELD'&&age!==null&&age>3)candidates.push(staleCandidate('RevenueCycleServiceEvent',r,'HELD_STALE','REVENUE_CYCLE',age>7?'HIGH':'MEDIUM',`Revenue service event has been held ${Math.floor(age)} days`,clean(r.holdReason,1000)||'Billing hold requires resolution.'));if(st==='REVIEW_REQUIRED'&&age!==null&&age>5)candidates.push(staleCandidate('RevenueCycleServiceEvent',r,'REVIEW_STALE','REVENUE_CYCLE','MEDIUM',`Revenue service event review is stale — ${clean(r.sourceModule,40)}`,`Completed service has waited ${Math.floor(age)} days for billing readiness review.`));}
  const quals=await scopedRows(prisma,a,'SpireMedicationAdministrationQualification');for(const r of quals){const st=upper(r.status),d=daysUntil(r.expiresAt);if(['EXPIRED','SUSPENDED','REVOKED'].includes(st)||(d!==null&&d<0))candidates.push(staleCandidate('SpireMedicationAdministrationQualification',r,'NOT_CURRENT','SPIRE','HIGH',`Medication administration qualification is not current — ${clean(r.userId,120)}`,`Qualification ${clean(r.qualificationType,160)} is ${st||'past expiration'}.`));}
  const carePlans=await scopedRows(prisma,a,'SpireCarePlan');for(const r of carePlans){const st=upper(r.status),age=ageDays(r.updatedAt||r.createdAt);if(['DRAFT','IN_REVIEW','REVIEW','CHANGES_REQUESTED'].includes(st)&&age!==null&&age>7)candidates.push(staleCandidate('SpireCarePlan',r,'STALE_PLAN','SPIRE',age>30?'HIGH':'MEDIUM',`Care Plan/ISP is stale — ${clean(r.planType||'Care Plan',120)}`,`Plan remains ${st.replaceAll('_',' ')} after ${Math.floor(age)} days.`));}
  const incidents=await scopedRows(prisma,a,'SpireIncident');for(const r of incidents){const st=upper(r.status),sev=upper(r.severity||r.priority||r.riskLevel),age=ageDays(r.updatedAt||r.occurredAt||r.createdAt);if(['HIGH','CRITICAL','URGENT'].includes(sev)&&!['CLOSED','RESOLVED','CANCELLED'].includes(st)&&age!==null&&age>1)candidates.push(staleCandidate('SpireIncident',r,'HIGH_PRIORITY_OPEN','SPIRE',sev==='CRITICAL'?'CRITICAL':'HIGH',`High-priority incident remains open — ${clean(r.incidentNumber||r.id,160)}`,`Incident severity is ${sev} and status remains ${st||'OPEN'} after ${Math.floor(age)} day(s).`));}
  const batches=await scopedRows(prisma,a,'RevenueCycleBatch');for(const r of batches){const age=ageDays(r.updatedAt||r.createdAt);if(upper(r.status)==='DRAFT'&&age!==null&&age>7)candidates.push(staleCandidate('RevenueCycleBatch',r,'STALE_DRAFT_BATCH','REVENUE_CYCLE','MEDIUM',`Revenue batch remains DRAFT — ${clean(r.batchNumber||r.id,160)}`,`Draft batch has not been finalized or voided for ${Math.floor(age)} days.`));}
  return candidates;
}

const actionSchema=z.object({action:z.enum(['ACKNOWLEDGE','RESOLVE','IGNORE','REOPEN','ASSIGN','COMMENT']),comment:z.string().trim().max(5000).optional().nullable(),assignedUserId:z.string().trim().max(120).optional().nullable()});
export const registerEnterpriseDataQualityRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/data-quality/context',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const company=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","code","displayName","legalName" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));res.json({data:{company:company[0]||null,role:a.role,write:writeRoles.has(String(a.role))||owner(a),scanVersion:'2026-08-10.1'}});}catch(e){next(e);}});
  app.get('/api/data-quality/issues',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const status=clean(req.query.status,40),severity=clean(req.query.severity,40),module=clean(req.query.module,80),assigned=clean(req.query.assignedUserId,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT i.*,COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e."createdAt" DESC) FROM "EnterpriseDataQualityEvent" e WHERE e."issueId"=i."id"),'[]'::jsonb) AS history FROM "EnterpriseDataQualityIssue" i WHERE i."organizationId"=$1 AND i."legalEntityId"=$2 AND ($3='' OR i."status"=$3) AND ($4='' OR i."severity"=$4) AND ($5='' OR i."module"=$5) AND ($6='' OR i."assignedUserId"=$6) ORDER BY CASE i."severity" WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,CASE i."status" WHEN 'OPEN' THEN 0 WHEN 'ACKNOWLEDGED' THEN 1 ELSE 2 END,i."lastSeenAt" DESC LIMIT 5000`,a.organizationId,entity(a),status,severity,module,assigned);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/data-quality/summary',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<{status:string;severity:string;count:number}>>(`SELECT "status","severity",count(*)::int AS count FROM "EnterpriseDataQualityIssue" WHERE "organizationId"=$1 AND "legalEntityId"=$2 GROUP BY "status","severity"`,a.organizationId,entity(a));const last=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EnterpriseDataQualityRun" WHERE "organizationId"=$1 AND "legalEntityId"=$2 ORDER BY "startedAt" DESC LIMIT 1`,a.organizationId,entity(a));const open=rows.filter(r=>['OPEN','ACKNOWLEDGED'].includes(r.status)).reduce((s,r)=>s+Number(r.count||0),0),critical=rows.filter(r=>['OPEN','ACKNOWLEDGED'].includes(r.status)&&r.severity==='CRITICAL').reduce((s,r)=>s+Number(r.count||0),0),high=rows.filter(r=>['OPEN','ACKNOWLEDGED'].includes(r.status)&&r.severity==='HIGH').reduce((s,r)=>s+Number(r.count||0),0);res.json({data:{open,critical,high,breakdown:rows,lastRun:last[0]||null}});}catch(e){next(e);}});
  app.post('/api/data-quality/scan',async(_req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const runId=randomUUID(),scanVersion='2026-08-10.1';await prisma.$executeRawUnsafe(`INSERT INTO "EnterpriseDataQualityRun"("id","organizationId","legalEntityId","startedByUserId","scanVersion","modulesScanned") VALUES($1,$2,$3,$4,$5,$6::jsonb)`,runId,a.organizationId,entity(a),a.userId,scanVersion,JSON.stringify(['CLIENT_INTAKE','COMPLIANCE','WORKFORCE','SCLS','HOME_HEALTH','NMT','REVENUE_CYCLE','SPIRE']));const candidates=await scanCandidates(prisma,a),seenKeys=[...new Set(candidates.map(c=>c.issueKey))];for(const c of candidates)await upsertCandidate(prisma,a,c);if(seenKeys.length)await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityIssue" SET "status"='RESOLVED',"resolvedAt"=NOW(),"resolvedByUserId"=$1,"resolutionNote"='Condition no longer detected by enterprise scan.',"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "detectedBy"='SYSTEM_SCAN' AND "status" IN ('OPEN','ACKNOWLEDGED') AND NOT ("issueKey"=ANY($4::text[]))`,a.userId,a.organizationId,entity(a),seenKeys);else await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityIssue" SET "status"='RESOLVED',"resolvedAt"=NOW(),"resolvedByUserId"=$1,"resolutionNote"='Condition no longer detected by enterprise scan.',"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "detectedBy"='SYSTEM_SCAN' AND "status" IN ('OPEN','ACKNOWLEDGED')`,a.userId,a.organizationId,entity(a));const counts={critical:candidates.filter(c=>c.severity==='CRITICAL').length,high:candidates.filter(c=>c.severity==='HIGH').length,medium:candidates.filter(c=>c.severity==='MEDIUM').length,low:candidates.filter(c=>c.severity==='LOW').length};await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityRun" SET "completedAt"=NOW(),"issuesFound"=$1,"criticalCount"=$2,"highCount"=$3,"mediumCount"=$4,"lowCount"=$5 WHERE "id"=$6`,candidates.length,counts.critical,counts.high,counts.medium,counts.low,runId);await audit?.(a,'RUN_ENTERPRISE_DATA_QUALITY_SCAN','EnterpriseDataQualityRun',runId,{issuesFound:candidates.length,...counts});res.json({data:{runId,scanVersion,issuesFound:candidates.length,...counts}});}catch(e){next(e);}});
  app.post('/api/data-quality/issues/:issueId/action',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=actionSchema.parse(req.body),rows=await prisma.$queryRawUnsafe<Array<{id:string;status:string;assignedUserId:string|null}>>(`SELECT "id","status","assignedUserId" FROM "EnterpriseDataQualityIssue" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.issueId),issue=rows[0];if(!issue)throw httpError(404,'Data quality issue was not found');const from=issue.status;let to=from,eventType='COMMENT';if(i.action==='ACKNOWLEDGE'){to='ACKNOWLEDGED';eventType='ACKNOWLEDGED';}if(i.action==='RESOLVE'){if(!i.comment)throw httpError(400,'Resolution note is required');to='RESOLVED';eventType='RESOLVED';}if(i.action==='IGNORE'){if(!i.comment)throw httpError(400,'Ignore rationale is required');to='IGNORED';eventType='IGNORED';}if(i.action==='REOPEN'){to='OPEN';eventType='REOPENED';}if(i.action==='ASSIGN'){if(!i.assignedUserId)throw httpError(400,'assignedUserId is required');eventType='ASSIGNED';await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityIssue" SET "assignedUserId"=$1,"updatedAt"=NOW() WHERE "id"=$2`,i.assignedUserId,issue.id);await issueEvent(prisma,a,issue.id,eventType,from,from,i.comment??null,{assignedUserId:i.assignedUserId});return void res.json({data:{id:issue.id,status:from,assignedUserId:i.assignedUserId}});}if(i.action==='COMMENT'){await issueEvent(prisma,a,issue.id,'COMMENT',from,from,i.comment??null,{});return void res.json({data:{id:issue.id,status:from}});}await prisma.$executeRawUnsafe(`UPDATE "EnterpriseDataQualityIssue" SET "status"=$1,"acknowledgedAt"=CASE WHEN $1='ACKNOWLEDGED' THEN NOW() ELSE "acknowledgedAt" END,"acknowledgedByUserId"=CASE WHEN $1='ACKNOWLEDGED' THEN $2 ELSE "acknowledgedByUserId" END,"resolvedAt"=CASE WHEN $1 IN ('RESOLVED','IGNORED') THEN NOW() WHEN $1='OPEN' THEN NULL ELSE "resolvedAt" END,"resolvedByUserId"=CASE WHEN $1 IN ('RESOLVED','IGNORED') THEN $2 WHEN $1='OPEN' THEN NULL ELSE "resolvedByUserId" END,"resolutionNote"=CASE WHEN $1 IN ('RESOLVED','IGNORED') THEN $3 WHEN $1='OPEN' THEN NULL ELSE "resolutionNote" END,"updatedAt"=NOW() WHERE "id"=$4`,to,a.userId,i.comment??null,issue.id);await issueEvent(prisma,a,issue.id,eventType,from,to,i.comment??null,{});await audit?.(a,`DATA_QUALITY_${i.action}`,'EnterpriseDataQualityIssue',issue.id,{fromStatus:from,toStatus:to,comment:i.comment??null});res.json({data:{id:issue.id,status:to}});}catch(e){next(e);}});
};
