import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
type Column={column_name:string;is_nullable:'YES'|'NO';column_default:string|null;data_type:string};
const roles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.RN,UserRole.DELEGATING_NURSE,UserRole.SCHEDULER,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select Sulandra Home Health before Start of Care');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensure=(a:AuthContext)=>{entity(a);if(!roles.has(a.role)&&!owner(a))throw httpError(403,'Home Health Start-of-Care access is required');};
const q=(name:string)=>`"${name.replaceAll('"','""')}"`;
const compact=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):v;
async function hhContext(prisma:PrismaClient,a:AuthContext){const rows=await prisma.$queryRawUnsafe<Array<{id:string;code:string;displayName:string;isProvider:boolean;metadata:Record<string,unknown>}>>(`SELECT "id","code","displayName","isProvider","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a)),row=rows[0];if(!row)throw httpError(404,'Selected company was not found');if(row.code!=='HOME_HEALTH')throw httpError(409,'Select Sulandra Home Health');const m=row.metadata&&typeof row.metadata==='object'?row.metadata:{};const operational=row.isProvider===true&&String(m.serviceOperationsStatus||'')==='ACTIVE'&&String(m.referralStatus||'')==='ACTIVE'&&String(m.licensingStatus||'')==='ACTIVE';return{...row,metadata:m,operational};}
async function blockers(prisma:PrismaClient,a:AuthContext){return prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","category","requirementName","status","expirationDate" FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "category" IN ('LICENSE','MEDICAID_PROVIDER','INSURANCE','HOME_HEALTH','ACCREDITATION') AND ("status" IN ('EXPIRED','SUSPENDED') OR ("expirationDate" IS NOT NULL AND "expirationDate"<CURRENT_DATE)) ORDER BY "category","requirementName"`,a.organizationId,entity(a));}
async function tableColumns(prisma:PrismaClient,table:string){return prisma.$queryRawUnsafe<Column[]>(`SELECT column_name,is_nullable,column_default,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position`,table);}
async function allowedStatus(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{definition:string}>>(`SELECT pg_get_constraintdef(c.oid) AS definition FROM pg_constraint c JOIN pg_class t ON t.oid=c.conrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname='public' AND t.relname=$1 AND c.contype='c' AND lower(pg_get_constraintdef(c.oid)) LIKE '%status%'`,table);const tokens=new Set<string>();for(const row of rows)for(const m of String(row.definition||'').matchAll(/'([^']+)'/g))tokens.add(m[1]);for(const candidate of ['PENDING_START_OF_CARE','PENDING','REFERRAL','ADMISSION_PENDING','ACTIVE'])if(tokens.has(candidate))return candidate;return tokens.values().next().value||'PENDING_START_OF_CARE';}
function first(data:Record<string,unknown>,...keys:string[]){for(const key of keys){const v=data[key];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return null;}
async function existingEpisode(prisma:PrismaClient,a:AuthContext,patientId:string,intakeCaseId:string,referralId:string){const cols=await tableColumns(prisma,'HomeHealthEpisode'),names=new Set(cols.map(c=>c.column_name));const conditions=['"organizationId"=$1','"legalEntityId"=$2'];const args:unknown[]=[a.organizationId,entity(a)];if(names.has('intakeCaseId')){args.push(intakeCaseId);conditions.push(`"intakeCaseId"=$${args.length}`);}else if(names.has('referralId')){args.push(referralId);conditions.push(`"referralId"=$${args.length}`);}else if(names.has('patientId')){args.push(patientId);conditions.push(`"patientId"=$${args.length}`);}else return null;const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT to_jsonb(e) AS data FROM "HomeHealthEpisode" e WHERE ${conditions.join(' AND ')} ORDER BY to_jsonb(e)->>'createdAt' DESC NULLS LAST LIMIT 1`,...args);return (rows[0]?.data as Record<string,unknown>)||null;}
async function createEpisodeDynamic(prisma:PrismaClient,a:AuthContext,referral:Record<string,unknown>,intake:Record<string,unknown>){const cols=await tableColumns(prisma,'HomeHealthEpisode');if(!cols.length)throw httpError(500,'Home Health episode schema is not available');const names=new Set(cols.map(c=>c.column_name)),patientId=String(referral.patientId||intake.patientId||''),intakeCaseId=String(referral.intakeCaseId||intake.id||''),referralId=String(referral.id||'');const episodeId=randomUUID(),episodeNumber=`HH-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,6).toUpperCase()}`;const candidate:Record<string,unknown>={id:episodeId,organizationId:a.organizationId,legalEntityId:entity(a),patientId,intakeCaseId,referralId,episodeNumber,referralNumber:referral.referralNumber,referralSourceId:referral.sourceId,referralSource:referral.sourceName||referral.referralSource,referralDate:first(referral,'referralDate','submittedAt','createdAt'),requestedStartOfCareDate:first(referral,'requestedStartOfCareDate','requestedSocDate'),startOfCareDate:null,admissionDate:null,primaryDiagnosis:first(referral,'primaryDiagnosis','primaryDiagnosisDescription','diagnosis'),primaryDiagnosisCode:first(referral,'primaryDiagnosisCode','diagnosisCode'),caseManagerUserId:null,primaryNurseUserId:null,createdByUserId:a.userId,createdById:a.userId,createdBy:a.userId,source:'HOME_HEALTH_REFERRAL_INTAKE'};
 if(names.has('status')){const col=cols.find(c=>c.column_name==='status');if(col?.is_nullable==='NO'&&!col.column_default)candidate.status=await allowedStatus(prisma,'HomeHealthEpisode');}
 const missing:string[]=[];for(const col of cols){if(col.is_nullable==='NO'&&!col.column_default&&candidate[col.column_name]===undefined)missing.push(col.column_name);}if(missing.length)throw httpError(409,'Home Health episode schema has required fields that must be completed before Start of Care',{missingRequiredColumns:missing,referralId,intakeCaseId,patientId});
 const entries=Object.entries(candidate).filter(([key,value])=>names.has(key)&&value!==undefined&&value!==null);const columns=entries.map(([key])=>q(key)),values=entries.map(([,value])=>compact(value)),placeholders=values.map((_,i)=>`$${i+1}`);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "HomeHealthEpisode"(${columns.join(',')}) VALUES(${placeholders.join(',')}) RETURNING to_jsonb("HomeHealthEpisode") AS data`,...values);return{episodeId,data:(rows[0]?.data as Record<string,unknown>)||{id:episodeId,episodeNumber}};}
export const registerHomeHealthStartOfCareRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/home-health/start-of-care-ready',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);const company=await hhContext(prisma,a),complianceBlockers=await blockers(prisma,a);const refs=await prisma.$queryRawUnsafe<Array<{data:Record<string,unknown>;intake:Record<string,unknown>|null}>>(`SELECT to_jsonb(r) AS data,to_jsonb(i) AS intake FROM "HomeHealthReferral" r LEFT JOIN "ClientIntakeCase" i ON i."organizationId"=r."organizationId" AND i."legalEntityId"=r."legalEntityId" AND i."id"=r."intakeCaseId" WHERE r."organizationId"=$1 AND r."legalEntityId"=$2 AND r."patientId" IS NOT NULL AND r."intakeCaseId" IS NOT NULL AND r."status" IN ('ACCEPTED','INTAKE_CREATED','REVIEW_REQUIRED') ORDER BY r."updatedAt" DESC,r."createdAt" DESC`,a.organizationId,entity(a));const items=[];for(const row of refs){const referral=row.data||{},intake=row.intake||{},patientId=String(referral.patientId||intake.patientId||''),intakeCaseId=String(referral.intakeCaseId||intake.id||'');const existing=patientId&&intakeCaseId?await existingEpisode(prisma,a,patientId,intakeCaseId,String(referral.id||'')):null;const reasons:string[]=[];if(!company.operational)reasons.push('Home Health legal-entity lifecycle is not operationally active');if(String(intake.status)!=='APPROVED')reasons.push(`Client Intake status is ${String(intake.status||'not available')}; APPROVED is required`);if(complianceBlockers.length)reasons.push(`${complianceBlockers.length} expired/suspended company compliance blocker(s)`);if(existing)reasons.push('A Home Health episode already exists for this referral/intake');items.push({referral,intake,existingEpisode:existing,ready:reasons.length===0,blockers:reasons});}res.json({data:{company,complianceBlockers,items}});}catch(e){next(e);}});
 app.post('/api/home-health/referrals/:referralId/start-episode',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const company=await hhContext(prisma,a);if(!company.operational)throw httpError(409,'Home Health is not operationally active yet',{metadata:company.metadata});const complianceBlockers=await blockers(prisma,a);if(complianceBlockers.length)throw httpError(409,'Start of Care is blocked by expired or suspended company compliance',{blockers:complianceBlockers});const rows=await prisma.$queryRawUnsafe<Array<{referral:Record<string,unknown>;intake:Record<string,unknown>|null}>>(`SELECT to_jsonb(r) AS referral,to_jsonb(i) AS intake FROM "HomeHealthReferral" r LEFT JOIN "ClientIntakeCase" i ON i."organizationId"=r."organizationId" AND i."legalEntityId"=r."legalEntityId" AND i."id"=r."intakeCaseId" WHERE r."organizationId"=$1 AND r."legalEntityId"=$2 AND r."id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.referralId),referral=rows[0]?.referral,intake=rows[0]?.intake;if(!referral)throw httpError(404,'Home Health referral was not found');if(!referral.patientId||!referral.intakeCaseId)throw httpError(409,'Link the patient and create the Client Intake before Start of Care');if(!intake||String(intake.status)!=='APPROVED')throw httpError(409,'Client Intake must be approved before a Home Health episode can be created',{intakeStatus:intake?.status||null,intakeCaseId:referral.intakeCaseId});const existing=await existingEpisode(prisma,a,String(referral.patientId),String(referral.intakeCaseId),String(referral.id));if(existing)return void res.status(409).json({error:'A Home Health episode already exists for this referral/intake',data:{existingEpisode:existing}});const created=await createEpisodeDynamic(prisma,a,referral,intake);const refCols=new Set((await tableColumns(prisma,'HomeHealthReferral')).map(c=>c.column_name));if(refCols.has('episodeId'))await prisma.$executeRawUnsafe(`UPDATE "HomeHealthReferral" SET "episodeId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4`,created.episodeId,a.organizationId,entity(a),req.params.referralId);await audit?.(a,'CREATE_HOME_HEALTH_EPISODE_FROM_REFERRAL','HomeHealthEpisode',created.episodeId,{referralId:req.params.referralId,intakeCaseId:referral.intakeCaseId,patientId:referral.patientId});res.status(201).json({data:{episode:created.data,referralId:req.params.referralId,intakeCaseId:referral.intakeCaseId,patientId:referral.patientId}});}catch(e){next(e);}});
};
