import { createHash, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const managers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.RN,UserRole.DELEGATING_NURSE,UserRole.CEO,UserRole.DOO]);
const clinicians=new Set<UserRole>([UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const clean=(v:unknown,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select Sulandra Home Health before using the regulated Home Health workspace');return a.legalEntityId;};
const dateOnly=(v:unknown)=>{const s=clean(v,20);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;};
const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,canonical(v)])):value;
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');

async function ensureCompany(prisma:PrismaClient,a:AuthContext){
  const rows=await prisma.$queryRawUnsafe<Array<{id:string;code:string}>>(`SELECT "id","code" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));
  if(!rows[0])throw httpError(404,'Selected company was not found');
  if(rows[0].code!=='HOME_HEALTH')throw httpError(409,'Select Sulandra Home Health to use Home Health regulated workflows');
}
async function ensureRead(prisma:PrismaClient,a:AuthContext){await ensureCompany(prisma,a);if(managers.has(a.role)||clinicians.has(a.role)||owner(a))return;throw httpError(403,'Licensed Home Health clinical access is required');}
async function ensureWrite(prisma:PrismaClient,a:AuthContext){await ensureCompany(prisma,a);if(managers.has(a.role)||owner(a))return;throw httpError(403,'Home Health management or RN access is required');}
async function episode(prisma:PrismaClient,a:AuthContext,id:string){
  const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthEpisode" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),id);
  if(!rows[0])throw httpError(404,'Home Health episode was not found');return rows[0];
}
async function appendEvent(prisma:PrismaClient,a:AuthContext,episodeId:string,eventType:string,resourceType:string,resourceId:string,details:Record<string,unknown>={}){
  await prisma.$executeRawUnsafe(`INSERT INTO "HomeHealthEpisodeEvent"("id","organizationId","legalEntityId","episodeId","actorUserId","eventType","resourceType","resourceId","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,randomUUID(),a.organizationId,entity(a),episodeId,a.userId,eventType,resourceType,resourceId,JSON.stringify(details));
}

const periodSchema=z.object({periodNumber:z.number().int().positive(),certificationType:z.enum(['INITIAL','RECERTIFICATION']).default('INITIAL'),periodStart:z.string(),periodEnd:z.string(),certifyingProviderName:z.string().trim().max(250).optional().nullable(),certifyingProviderNpi:z.string().trim().max(40).optional().nullable(),certificationStatement:z.string().trim().max(10000).optional().nullable(),faceToFaceDate:z.string().optional().nullable(),makeCurrent:z.boolean().default(true)});
const oasisSchema=z.object({assessmentResponseId:z.string().trim().min(1).max(160),reasonForAssessment:z.enum(['SOC','ROC','RECERTIFICATION','OTHER_FOLLOW_UP','TRANSFER','DISCHARGE','DEATH_AT_HOME']),targetDate:z.string(),m0090Date:z.string().optional().nullable(),certificationPeriodId:z.string().trim().max(160).optional().nullable(),correctsAssessmentId:z.string().trim().max(160).optional().nullable()});
const pocLifecycleSchema=z.object({orderLifecycleStatus:z.enum(['DRAFT','VERBAL_ORDER','WRITTEN_PENDING_SIGNATURE','SIGNED','ACTIVE','SUPERSEDED','CANCELLED']),signatureStatus:z.enum(['PENDING','SIGNED','OVERDUE','NOT_REQUIRED']).optional(),certificationPeriodId:z.string().trim().max(160).optional().nullable(),certificationStatement:z.string().trim().max(10000).optional().nullable(),certifyingProviderName:z.string().trim().max(250).optional().nullable(),certifyingProviderNpi:z.string().trim().max(40).optional().nullable(),verbalOrderObtainedAt:z.string().datetime().optional().nullable(),verbalOrderObtainedByUserId:z.string().trim().max(160).optional().nullable(),writtenOrderReceivedAt:z.string().datetime().optional().nullable(),sentForSignatureAt:z.string().datetime().optional().nullable(),signatureDueAt:z.string().datetime().optional().nullable(),physicianSignedAt:z.string().datetime().optional().nullable(),physicianSignatureMethod:z.string().trim().max(160).optional().nullable(),amendmentType:z.enum(['ADDENDUM','AMENDMENT','RECERTIFICATION']).optional().nullable(),amendmentReason:z.string().trim().max(10000).optional().nullable()});
const orderLifecycleSchema=z.object({orderType:z.enum(['PLAN_OF_CARE','VERBAL','WRITTEN','SUPPLEMENTAL','PRN','CHANGE','DISCONTINUE']).optional(),orderNumber:z.string().trim().max(160).optional().nullable(),certificationPeriodId:z.string().trim().max(160).optional().nullable(),communicationMethod:z.string().trim().max(160).optional().nullable(),verbalOrderAt:z.string().datetime().optional().nullable(),receivedByUserId:z.string().trim().max(160).optional().nullable(),sentForSignatureAt:z.string().datetime().optional().nullable(),signatureDueAt:z.string().datetime().optional().nullable(),providerSignedAt:z.string().datetime().optional().nullable(),signedByProviderName:z.string().trim().max(250).optional().nullable(),signedByProviderNpi:z.string().trim().max(40).optional().nullable(),signatureStatus:z.enum(['PENDING','SIGNED','OVERDUE','NOT_REQUIRED']).optional(),supersedesOrderId:z.string().trim().max(160).optional().nullable(),amendmentReason:z.string().trim().max(10000).optional().nullable()});
const transitionSchema=z.object({transitionType:z.enum(['START_OF_CARE','ACTIVATE','HOLD','RESUME','RECERTIFY','TRANSFER','DISCHARGE','CANCEL']),toStatus:z.enum(['PRE_ADMISSION','SOC_READY','ACTIVE','ON_HOLD','DISCHARGED','CANCELLED']),effectiveAt:z.string().datetime(),reason:z.string().trim().max(10000).optional().nullable(),destination:z.string().trim().max(1000).optional().nullable(),certificationPeriodId:z.string().trim().max(160).optional().nullable(),oasisAssessmentId:z.string().trim().max(160).optional().nullable(),details:z.record(z.unknown()).default({})});

export const registerHomeHealthRegulatedCoreRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/home-health/episodes/:episodeId/regulated-core',async(req,res,next)=>{try{
    const a=authOf(res);await ensureRead(prisma,a);const ep=await episode(prisma,a,req.params.episodeId);const eid=entity(a);
    const [periods,oasis,plans,orders,visits,transitions]=await Promise.all([
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthCertificationPeriod" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "episodeId"=$3 ORDER BY "periodNumber"`,a.organizationId,eid,req.params.episodeId),
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT o.*,s."specName",s."itemSetVersionCode",s."submissionSpecVersion",s."status" "specStatus" FROM "HomeHealthOasisAssessment" o JOIN "HomeHealthOasisSpecVersion" s ON s."id"=o."specVersionId" WHERE o."organizationId"=$1 AND o."legalEntityId"=$2 AND o."episodeId"=$3 ORDER BY o."targetDate" DESC`,a.organizationId,eid,req.params.episodeId),
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthPlanOfCare" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "episodeId"=$3 ORDER BY "version" DESC`,a.organizationId,eid,req.params.episodeId),
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthDisciplineOrder" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "episodeId"=$3 ORDER BY "createdAt" DESC`,a.organizationId,eid,req.params.episodeId),
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT v.*,evv."id" "linkedEvvVisitId",evv."status" "evvStatus",evv."transmissionState" "evvTransmissionState" FROM "HomeHealthVisit" v LEFT JOIN "SpireEvvVisit" evv ON evv."homeHealthVisitId"=v."id" WHERE v."organizationId"=$1 AND v."legalEntityId"=$2 AND v."episodeId"=$3 ORDER BY v."scheduledStart" DESC LIMIT 250`,a.organizationId,eid,req.params.episodeId),
      prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthEpisodeTransition" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "episodeId"=$3 ORDER BY "effectiveAt" DESC`,a.organizationId,eid,req.params.episodeId),
    ]);
    const blockers:string[]=[];
    if(['ACTIVE','ON_HOLD'].includes(String(ep.status))&&!ep.currentCertificationPeriodId)blockers.push('Active episode requires a current certification period');
    if(['ACTIVE','ON_HOLD'].includes(String(ep.status))&&!plans.some(p=>['ACTIVE','REVIEW'].includes(String(p.status))))blockers.push('Active episode requires a Plan of Care in review or active status');
    const overdueOrders=orders.filter(o=>String(o.signatureStatus)==='PENDING'&&o.signatureDueAt&&new Date(String(o.signatureDueAt)).getTime()<Date.now());
    if(overdueOrders.length)blockers.push(`${overdueOrders.length} provider order(s) are overdue for signature`);
    const brokenVisitLinks=visits.filter(v=>Boolean(v.evvRequired)&&!v.linkedEvvVisitId);
    if(brokenVisitLinks.length)blockers.push(`${brokenVisitLinks.length} EVV-required Home Health visit(s) are not linked to the canonical EVV record`);
    res.json({data:{episode:ep,certificationPeriods:periods,oasisAssessments:oasis,plansOfCare:plans,orders,visits,transitions,regulatedReadiness:{ready:blockers.length===0,blockers}}});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/certification-periods',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const i=periodSchema.parse(req.body);const start=dateOnly(i.periodStart),end=dateOnly(i.periodEnd);if(!start||!end||end<start)throw httpError(400,'Certification period requires valid start/end dates with end on or after start');
    const id=randomUUID();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "HomeHealthCertificationPeriod"("id","organizationId","legalEntityId","episodeId","periodNumber","certificationType","periodStart","periodEnd","status","certifyingProviderName","certifyingProviderNpi","certificationStatement","faceToFaceDate","createdById") VALUES($1,$2,$3,$4,$5,$6,$7::date,$8::date,'ACTIVE',$9,$10,$11,$12::date,$13) RETURNING *`,id,a.organizationId,entity(a),req.params.episodeId,i.periodNumber,i.certificationType,start,end,i.certifyingProviderName??null,i.certifyingProviderNpi??null,i.certificationStatement??null,dateOnly(i.faceToFaceDate)??null,a.userId);
    if(i.makeCurrent){await prisma.$executeRawUnsafe(`UPDATE "HomeHealthEpisode" SET "currentCertificationPeriodId"=$1,"certificationPeriodStart"=$2::date,"certificationPeriodEnd"=$3::date,"certifyingProviderName"=COALESCE($4,"certifyingProviderName"),"certifyingProviderNpi"=COALESCE($5,"certifyingProviderNpi"),"updatedAt"=NOW() WHERE "organizationId"=$6 AND "legalEntityId"=$7 AND "id"=$8`,id,start,end,i.certifyingProviderName??null,i.certifyingProviderNpi??null,a.organizationId,entity(a),req.params.episodeId);}
    await appendEvent(prisma,a,req.params.episodeId,i.certificationType==='RECERTIFICATION'?'RECERTIFICATION_PERIOD_CREATED':'CERTIFICATION_PERIOD_CREATED','HOME_HEALTH_CERTIFICATION_PERIOD',id,{periodNumber:i.periodNumber,start,end});await audit?.(a,'CREATE_HOME_HEALTH_CERTIFICATION_PERIOD','HomeHealthCertificationPeriod',id,{episodeId:req.params.episodeId});res.status(201).json({data:rows[0]});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/oasis',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const ep=await episode(prisma,a,req.params.episodeId);const i=oasisSchema.parse(req.body),target=dateOnly(i.targetDate);if(!target)throw httpError(400,'OASIS targetDate must be YYYY-MM-DD');
    const responses=await prisma.$queryRawUnsafe<Array<{id:string;patientId:string}>>(`SELECT "id","patientId" FROM "SpireAssessmentResponse" WHERE "organizationId"=$1 AND "patientId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,String(ep.patientId),i.assessmentResponseId);if(!responses[0])throw httpError(409,'The OASIS record must reference an existing SPIRE assessment response for this patient');
    const specs=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "HomeHealthOasisSpecVersion" WHERE "itemSetVersionCode"='E2-042026' AND "submissionSpecVersion"='3.02' AND "effectiveFrom"<=$1::date AND ("effectiveThrough" IS NULL OR "effectiveThrough">=$1::date) ORDER BY "effectiveFrom" DESC LIMIT 1`,target);if(!specs[0])throw httpError(409,'No applicable OASIS-E2 CMS specification version is registered for this target date');
    const id=randomUUID();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "HomeHealthOasisAssessment"("id","organizationId","legalEntityId","episodeId","certificationPeriodId","patientId","assessmentResponseId","specVersionId","reasonForAssessment","targetDate","m0090Date","correctsAssessmentId","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::date,$11::date,$12,$13) RETURNING *`,id,a.organizationId,entity(a),req.params.episodeId,i.certificationPeriodId??ep.currentCertificationPeriodId??null,String(ep.patientId),i.assessmentResponseId,specs[0].id,i.reasonForAssessment,target,dateOnly(i.m0090Date)??null,i.correctsAssessmentId??null,a.userId);await appendEvent(prisma,a,req.params.episodeId,'OASIS_ASSESSMENT_LINKED','HOME_HEALTH_OASIS_ASSESSMENT',id,{reasonForAssessment:i.reasonForAssessment,targetDate:target});await audit?.(a,'LINK_HOME_HEALTH_OASIS_ASSESSMENT','HomeHealthOasisAssessment',id,{episodeId:req.params.episodeId,assessmentResponseId:i.assessmentResponseId});res.status(201).json({data:rows[0]});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/snapshot',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT o.*,r."templateId",r."responses",r."status" "assessmentResponseStatus",r."completedAt",t."code" "templateCode",t."title" "templateTitle",s."specName",s."itemSetVersionCode",s."submissionSpecVersion",s."status" "specStatus" FROM "HomeHealthOasisAssessment" o JOIN "SpireAssessmentResponse" r ON r."id"=o."assessmentResponseId" LEFT JOIN "SpireAssessmentTemplate" t ON t."id"=r."templateId" JOIN "HomeHealthOasisSpecVersion" s ON s."id"=o."specVersionId" WHERE o."organizationId"=$1 AND o."legalEntityId"=$2 AND o."episodeId"=$3 AND o."id"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.episodeId,req.params.oasisId);const o=rows[0];if(!o)throw httpError(404,'OASIS assessment was not found');if(o.immutableSnapshot){res.json({data:{oasisAssessmentId:req.params.oasisId,snapshot:o.immutableSnapshot,sha256:o.snapshotSha256,immutable:true}});return;}
    const answers=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT q."code",q."section",q."label",q."required",a."valueText",a."valueNumber",a."valueBoolean",a."valueJson",a."comment" FROM "SpireAssessmentAnswer" a JOIN "SpireAssessmentQuestion" q ON q."id"=a."questionId" WHERE a."organizationId"=$1 AND a."patientId"=$2 AND a."responseId"=$3 ORDER BY q."sortOrder",q."code"`,a.organizationId,String(o.patientId),String(o.assessmentResponseId));const snapshot={schema:'SPIRE_HOME_HEALTH_OASIS_SNAPSHOT_1',capturedAt:new Date().toISOString(),episodeId:req.params.episodeId,oasisAssessmentId:req.params.oasisId,patientId:o.patientId,reasonForAssessment:o.reasonForAssessment,targetDate:o.targetDate,m0090Date:o.m0090Date,spec:{name:o.specName,itemSetVersionCode:o.itemSetVersionCode,submissionSpecVersion:o.submissionSpecVersion,status:o.specStatus},sourceAssessment:{id:o.assessmentResponseId,templateId:o.templateId,templateCode:o.templateCode,templateTitle:o.templateTitle,status:o.assessmentResponseStatus,completedAt:o.completedAt,responses:o.responses,answers}};const hash=digest(snapshot);await prisma.$executeRawUnsafe(`UPDATE "HomeHealthOasisAssessment" SET "immutableSnapshot"=$1::jsonb,"snapshotSha256"=$2,"snapshotCreatedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "id"=$5 AND "immutableSnapshot" IS NULL`,JSON.stringify(snapshot),hash,a.organizationId,entity(a),req.params.oasisId);await appendEvent(prisma,a,req.params.episodeId,'OASIS_SNAPSHOT_CREATED','HOME_HEALTH_OASIS_ASSESSMENT',req.params.oasisId,{sha256:hash});res.json({data:{oasisAssessmentId:req.params.oasisId,snapshot,sha256:hash,immutable:true}});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/validate',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT o.*,s."status" "specStatus",s."itemDefinitions",s."editRules" FROM "HomeHealthOasisAssessment" o JOIN "HomeHealthOasisSpecVersion" s ON s."id"=o."specVersionId" WHERE o."organizationId"=$1 AND o."legalEntityId"=$2 AND o."episodeId"=$3 AND o."id"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.episodeId,req.params.oasisId);const o=rows[0];if(!o)throw httpError(404,'OASIS assessment was not found');await prisma.$executeRawUnsafe(`DELETE FROM "HomeHealthOasisEditFinding" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "oasisAssessmentId"=$3 AND "status"='OPEN'`,a.organizationId,entity(a),req.params.oasisId);const findings:Array<{code:string;severity:'FATAL'|'WARNING';message:string}>=[];if(!o.immutableSnapshot)findings.push({code:'SNAPSHOT_REQUIRED',severity:'FATAL',message:'Create the immutable OASIS submission snapshot before validation'});const definitions=Array.isArray(o.itemDefinitions)?o.itemDefinitions:[];const rules=Array.isArray(o.editRules)?o.editRules:[];if(!['LOADED','VALIDATED'].includes(String(o.specStatus))||definitions.length===0||rules.length===0)findings.push({code:'CMS_SPEC_NOT_LOADED',severity:'FATAL',message:'The registered OASIS-E2 3.02 CMS specification still requires its official item definitions and edit rules to be loaded before submission validation can pass'});for(const f of findings){await prisma.$executeRawUnsafe(`INSERT INTO "HomeHealthOasisEditFinding"("id","organizationId","legalEntityId","oasisAssessmentId","ruleCode","severity","message") VALUES($1,$2,$3,$4,$5,$6,$7)`,randomUUID(),a.organizationId,entity(a),req.params.oasisId,f.code,f.severity,f.message);}const state=findings.some(f=>f.severity==='FATAL')?'FAIL':findings.length?'WARNING':'PASS';const status=state==='PASS'?'READY_TO_SUBMIT':'DRAFT';await prisma.$executeRawUnsafe(`UPDATE "HomeHealthOasisAssessment" SET "validationState"=$1,"status"=$2,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "id"=$5`,state,status,a.organizationId,entity(a),req.params.oasisId);res.json({data:{validationState:state,status,findings,submissionReady:state==='PASS'}});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/iqies-submissions',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT o.*,s."submissionSpecVersion",s."status" "specStatus" FROM "HomeHealthOasisAssessment" o JOIN "HomeHealthOasisSpecVersion" s ON s."id"=o."specVersionId" WHERE o."organizationId"=$1 AND o."legalEntityId"=$2 AND o."episodeId"=$3 AND o."id"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.episodeId,req.params.oasisId);const o=rows[0];if(!o)throw httpError(404,'OASIS assessment was not found');if(String(o.validationState)!=='PASS'||String(o.status)!=='READY_TO_SUBMIT')throw httpError(409,'OASIS must pass the loaded CMS specification validation before an iQIES submission record can be created');const id=randomUUID(),payloadHash=String(o.snapshotSha256||'');const created=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "HomeHealthIqiesSubmission"("id","organizationId","legalEntityId","oasisAssessmentId","submissionSpecVersion","environment","transportMode","status","payloadSha256","createdById") VALUES($1,$2,$3,$4,$5,'TEST','EXPORT_ONLY','QUEUED',$6,$7) RETURNING *`,id,a.organizationId,entity(a),req.params.oasisId,String(o.submissionSpecVersion),payloadHash||null,a.userId);await appendEvent(prisma,a,req.params.episodeId,'IQIES_SUBMISSION_QUEUED','HOME_HEALTH_IQIES_SUBMISSION',id,{transportMode:'EXPORT_ONLY',externalSubmission:false});res.status(201).json({data:{...created[0],externalSubmissionConfigured:false,correctFormatExporterRequired:true,message:'This queue record deliberately does not claim iQIES submission. The CMS 3.02 formatter/validation package must be loaded and verified before transport can move beyond EXPORT_ONLY.'}});
  }catch(e){next(e);}});

  app.patch('/api/home-health/episodes/:episodeId/plans/:planId/provider-order-lifecycle',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const i=pocLifecycleSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "HomeHealthPlanOfCare" SET "certificationPeriodId"=COALESCE($1,"certificationPeriodId"),"certificationStatement"=COALESCE($2,"certificationStatement"),"certifyingProviderName"=COALESCE($3,"certifyingProviderName"),"certifyingProviderNpi"=COALESCE($4,"certifyingProviderNpi"),"orderLifecycleStatus"=$5,"verbalOrderObtainedAt"=COALESCE($6::timestamptz,"verbalOrderObtainedAt"),"verbalOrderObtainedByUserId"=COALESCE($7,"verbalOrderObtainedByUserId"),"writtenOrderReceivedAt"=COALESCE($8::timestamptz,"writtenOrderReceivedAt"),"sentForSignatureAt"=COALESCE($9::timestamptz,"sentForSignatureAt"),"signatureDueAt"=COALESCE($10::timestamptz,"signatureDueAt"),"signatureStatus"=COALESCE($11,"signatureStatus"),"physicianSignedAt"=COALESCE($12::timestamptz,"physicianSignedAt"),"physicianSignatureMethod"=COALESCE($13,"physicianSignatureMethod"),"amendmentType"=COALESCE($14,"amendmentType"),"amendmentReason"=COALESCE($15,"amendmentReason"),"amendedAt"=CASE WHEN $14 IS NOT NULL THEN NOW() ELSE "amendedAt" END,"amendedById"=CASE WHEN $14 IS NOT NULL THEN $16 ELSE "amendedById" END,"updatedAt"=NOW() WHERE "organizationId"=$17 AND "legalEntityId"=$18 AND "episodeId"=$19 AND "id"=$20 RETURNING *`,i.certificationPeriodId??null,i.certificationStatement??null,i.certifyingProviderName??null,i.certifyingProviderNpi??null,i.orderLifecycleStatus,i.verbalOrderObtainedAt??null,i.verbalOrderObtainedByUserId??null,i.writtenOrderReceivedAt??null,i.sentForSignatureAt??null,i.signatureDueAt??null,i.signatureStatus??null,i.physicianSignedAt??null,i.physicianSignatureMethod??null,i.amendmentType??null,i.amendmentReason??null,a.userId,a.organizationId,entity(a),req.params.episodeId,req.params.planId);if(!rows[0])throw httpError(404,'Plan of Care was not found');await appendEvent(prisma,a,req.params.episodeId,'POC_PROVIDER_ORDER_LIFECYCLE_UPDATED','HOME_HEALTH_PLAN_OF_CARE',req.params.planId,{orderLifecycleStatus:i.orderLifecycleStatus,signatureStatus:i.signatureStatus??null});res.json({data:rows[0]});
  }catch(e){next(e);}});

  app.patch('/api/home-health/episodes/:episodeId/orders/:orderId/provider-lifecycle',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);await episode(prisma,a,req.params.episodeId);const i=orderLifecycleSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "HomeHealthDisciplineOrder" SET "certificationPeriodId"=COALESCE($1,"certificationPeriodId"),"orderNumber"=COALESCE($2,"orderNumber"),"orderType"=COALESCE($3,"orderType"),"communicationMethod"=COALESCE($4,"communicationMethod"),"verbalOrderAt"=COALESCE($5::timestamptz,"verbalOrderAt"),"receivedByUserId"=COALESCE($6,"receivedByUserId"),"sentForSignatureAt"=COALESCE($7::timestamptz,"sentForSignatureAt"),"signatureDueAt"=COALESCE($8::timestamptz,"signatureDueAt"),"providerSignedAt"=COALESCE($9::timestamptz,"providerSignedAt"),"signedByProviderName"=COALESCE($10,"signedByProviderName"),"signedByProviderNpi"=COALESCE($11,"signedByProviderNpi"),"signatureStatus"=COALESCE($12,"signatureStatus"),"supersedesOrderId"=COALESCE($13,"supersedesOrderId"),"amendmentReason"=COALESCE($14,"amendmentReason"),"updatedAt"=NOW() WHERE "organizationId"=$15 AND "legalEntityId"=$16 AND "episodeId"=$17 AND "id"=$18 RETURNING *`,i.certificationPeriodId??null,i.orderNumber??null,i.orderType??null,i.communicationMethod??null,i.verbalOrderAt??null,i.receivedByUserId??null,i.sentForSignatureAt??null,i.signatureDueAt??null,i.providerSignedAt??null,i.signedByProviderName??null,i.signedByProviderNpi??null,i.signatureStatus??null,i.supersedesOrderId??null,i.amendmentReason??null,a.organizationId,entity(a),req.params.episodeId,req.params.orderId);if(!rows[0])throw httpError(404,'Home Health discipline order was not found');await appendEvent(prisma,a,req.params.episodeId,'PROVIDER_ORDER_LIFECYCLE_UPDATED','HOME_HEALTH_DISCIPLINE_ORDER',req.params.orderId,{orderType:i.orderType??null,signatureStatus:i.signatureStatus??null});res.json({data:rows[0]});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/transitions',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const ep=await episode(prisma,a,req.params.episodeId);const i=transitionSchema.parse(req.body);const allowed:Record<string,Set<string>>={PRE_ADMISSION:new Set(['SOC_READY','ACTIVE','CANCELLED']),SOC_READY:new Set(['ACTIVE','CANCELLED']),ACTIVE:new Set(['ON_HOLD','ACTIVE','DISCHARGED','CANCELLED']),ON_HOLD:new Set(['ACTIVE','DISCHARGED','CANCELLED']),DISCHARGED:new Set(),CANCELLED:new Set()};const from=String(ep.status);if(!allowed[from]?.has(i.toStatus))throw httpError(409,`Invalid Home Health episode transition from ${from} to ${i.toStatus}`);if(i.transitionType==='RECERTIFY'&&!i.certificationPeriodId)throw httpError(400,'RECERTIFY requires the new certificationPeriodId');if(['TRANSFER','DISCHARGE'].includes(i.transitionType)&&!i.oasisAssessmentId)throw httpError(400,`${i.transitionType} requires the linked OASIS assessment record`);
    const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "HomeHealthEpisodeTransition"("id","organizationId","legalEntityId","episodeId","certificationPeriodId","transitionType","fromStatus","toStatus","effectiveAt","reason","destination","oasisAssessmentId","actorUserId","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::timestamptz,$10,$11,$12,$13,$14::jsonb)`,id,a.organizationId,entity(a),req.params.episodeId,i.certificationPeriodId??ep.currentCertificationPeriodId??null,i.transitionType,from,i.toStatus,i.effectiveAt,i.reason??null,i.destination??null,i.oasisAssessmentId??null,a.userId,JSON.stringify(i.details));await prisma.$executeRawUnsafe(`UPDATE "HomeHealthEpisode" SET "status"=$1,"currentCertificationPeriodId"=COALESCE($2,"currentCertificationPeriodId"),"dischargeDate"=CASE WHEN $3='DISCHARGE' THEN ($4::timestamptz)::date ELSE "dischargeDate" END,"dischargeReason"=CASE WHEN $3='DISCHARGE' THEN COALESCE($5,"dischargeReason") ELSE "dischargeReason" END,"holdReason"=CASE WHEN $1='ON_HOLD' THEN COALESCE($5,"holdReason") WHEN $1='ACTIVE' THEN NULL ELSE "holdReason" END,"updatedAt"=NOW() WHERE "organizationId"=$6 AND "legalEntityId"=$7 AND "id"=$8`,i.toStatus,i.certificationPeriodId??null,i.transitionType,i.effectiveAt,i.reason??null,a.organizationId,entity(a),req.params.episodeId);await appendEvent(prisma,a,req.params.episodeId,`HOME_HEALTH_${i.transitionType}`,'HOME_HEALTH_EPISODE_TRANSITION',id,{fromStatus:from,toStatus:i.toStatus,effectiveAt:i.effectiveAt});await audit?.(a,'TRANSITION_HOME_HEALTH_EPISODE','HomeHealthEpisodeTransition',id,{episodeId:req.params.episodeId,transitionType:i.transitionType,fromStatus:from,toStatus:i.toStatus});res.status(201).json({data:{id,transitionType:i.transitionType,fromStatus:from,toStatus:i.toStatus,effectiveAt:i.effectiveAt}});
  }catch(e){next(e);}});
};
