import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';
import { buildOasisSubmissionXml, validateOasisSnapshot, type OasisLocalFinding } from './home-health-oasis-engine.js';
import { assertIqiesReconciliationTransition, buildIqiesIdempotencyKey, getIqiesTransportReadiness } from './iqies-transport-boundary.js';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
type OasisRow=Record<string,unknown>&{id:string;episodeId:string;patientId:string;status:string;validationState:string;transactionMode:string;immutableSnapshot:unknown;snapshotSha256:string|null;specVersionId:string;specStatus:string;itemSetVersionCode:string;submissionSpecVersion:string;normalizedDefinitionSha256:string|null;itemDefinitions:unknown;editRules:unknown;valueSets:unknown;submissionDefinition:unknown};
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.RN,UserRole.DELEGATING_NURSE,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select Sulandra Home Health before using OASIS/iQIES workflows');return a.legalEntityId;};
const sha256=/^[a-f0-9]{64}$/i;
const reconcileSchema=z.object({status:z.enum(['SUBMITTED','ACCEPTED','REJECTED','PARTIAL','ERROR']),transportMode:z.enum(['MANUAL_UPLOAD','EXTERNAL_ADAPTER']).default('MANUAL_UPLOAD'),externalSubmissionId:z.string().trim().max(250).optional().nullable(),validationUtilityVersion:z.string().trim().max(120).optional().nullable(),ackCode:z.string().trim().max(120).optional().nullable(),ackMessage:z.string().trim().max(4000).optional().nullable(),validationReportSha256:z.string().trim().regex(sha256).optional().nullable(),responsePayload:z.record(z.unknown()).default({})});
const transactionSchema=z.object({transactionMode:z.enum(['NEW','MODIFICATION','INACTIVATION']),submissionIntentReason:z.string().trim().max(4000).optional().nullable(),correctsAssessmentId:z.string().trim().max(160).optional().nullable()});

async function ensureWrite(prisma:PrismaClient,a:AuthContext){
  const rows=await prisma.$queryRawUnsafe<Array<{code:string}>>(`SELECT "code" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));
  if(!rows[0])throw httpError(404,'Selected company was not found');
  if(rows[0].code!=='HOME_HEALTH')throw httpError(409,'Select Sulandra Home Health to use OASIS/iQIES workflows');
  if(!writers.has(a.role)&&!owner(a))throw httpError(403,'Home Health management or RN access is required');
}
async function loadOasis(prisma:PrismaClient,a:AuthContext,episodeId:string,oasisId:string){
  const rows=await prisma.$queryRawUnsafe<OasisRow[]>(`SELECT o.*,s."status" "specStatus",s."itemSetVersionCode",s."submissionSpecVersion",s."normalizedDefinitionSha256",s."itemDefinitions",s."editRules",s."valueSets",s."submissionDefinition" FROM "HomeHealthOasisAssessment" o JOIN "HomeHealthOasisSpecVersion" s ON s."id"=o."specVersionId" WHERE o."organizationId"=$1 AND o."legalEntityId"=$2 AND o."episodeId"=$3 AND o."id"=$4 LIMIT 1`,a.organizationId,entity(a),episodeId,oasisId);
  if(!rows[0])throw httpError(404,'OASIS assessment was not found');return rows[0];
}
async function event(prisma:PrismaClient,a:AuthContext,episodeId:string,eventType:string,resourceType:string,resourceId:string,details:Record<string,unknown>={}){
  await prisma.$executeRawUnsafe(`INSERT INTO "HomeHealthEpisodeEvent"("id","organizationId","legalEntityId","episodeId","actorUserId","eventType","resourceType","resourceId","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,randomUUID(),a.organizationId,entity(a),episodeId,a.userId,eventType,resourceType,resourceId,JSON.stringify(details));
}
function specRecord(o:OasisRow){return{status:o.specStatus,itemSetVersionCode:o.itemSetVersionCode,submissionSpecVersion:o.submissionSpecVersion,normalizedDefinitionSha256:o.normalizedDefinitionSha256,itemDefinitions:o.itemDefinitions,editRules:o.editRules,valueSets:o.valueSets,submissionDefinition:o.submissionDefinition};}
async function persistFindings(prisma:PrismaClient,a:AuthContext,oasisId:string,findings:OasisLocalFinding[]){
  await prisma.$executeRawUnsafe(`DELETE FROM "HomeHealthOasisEditFinding" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "oasisAssessmentId"=$3 AND "status"='OPEN'`,a.organizationId,entity(a),oasisId);
  for(const finding of findings)await prisma.$executeRawUnsafe(`INSERT INTO "HomeHealthOasisEditFinding"("id","organizationId","legalEntityId","oasisAssessmentId","ruleCode","severity","itemCode","message","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)`,randomUUID(),a.organizationId,entity(a),oasisId,finding.code,finding.severity,finding.itemCode??null,finding.message,JSON.stringify(finding.details??{}));
}

export const registerHomeHealthOasisIqiesRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/home-health/oasis/spec-status',async(_req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","specName","itemSetVersionCode","submissionSpecVersion","effectiveFrom","effectiveThrough","sourceAuthority","sourceReference","sourcePackageName","sourcePackageSha256","normalizedDefinitionSha256","status","loadedAt","validatedAt","validatorVersion",jsonb_array_length("itemDefinitions")::int "itemDefinitionCount",jsonb_array_length("editRules")::int "editRuleCount",(SELECT count(*)::int FROM jsonb_object_keys("valueSets")) "valueSetCount",jsonb_array_length(COALESCE("submissionDefinition"->'fields','[]'::jsonb))::int "submissionMappingCount" FROM "HomeHealthOasisSpecVersion" WHERE "itemSetVersionCode"='E2-042026' AND "submissionSpecVersion"='3.02' ORDER BY "effectiveFrom" DESC LIMIT 1`);const spec=rows[0]??null,adapter=getIqiesTransportReadiness(process.env);res.json({data:{spec,submissionEnabled:Boolean(spec&&spec.status==='VALIDATED'),externalIqiesAdapterConfigured:adapter.configured,externalIqiesSubmissionEnabled:adapter.submissionEnabled,iqiesAdapter:adapter,rawXmlPersisted:false}});
  }catch(e){next(e);}});

  app.patch('/api/home-health/episodes/:episodeId/oasis/:oasisId/transaction-mode',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const input=transactionSchema.parse(req.body),o=await loadOasis(prisma,a,req.params.episodeId,req.params.oasisId);if(o.immutableSnapshot)throw httpError(409,'Transaction mode cannot change after the immutable OASIS submission snapshot is created; create the proper correction/inactivation assessment instead');
    const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "HomeHealthOasisAssessment" SET "transactionMode"=$1,"submissionIntentReason"=$2,"correctsAssessmentId"=COALESCE($3,"correctsAssessmentId"),"updatedAt"=NOW() WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "episodeId"=$6 AND "id"=$7 RETURNING *`,input.transactionMode,input.submissionIntentReason??null,input.correctsAssessmentId??null,a.organizationId,entity(a),req.params.episodeId,req.params.oasisId);await event(prisma,a,req.params.episodeId,'OASIS_TRANSACTION_MODE_SET','HOME_HEALTH_OASIS_ASSESSMENT',req.params.oasisId,{transactionMode:input.transactionMode});await audit?.(a,'SET_OASIS_TRANSACTION_MODE','HomeHealthOasisAssessment',req.params.oasisId,{transactionMode:input.transactionMode});res.json({data:rows[0]});
  }catch(e){next(e);}});

  // Registered before the legacy regulated-core validator so a non-empty edit
  // array can never be mistaken for successful CMS edit execution.
  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/validate',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const o=await loadOasis(prisma,a,req.params.episodeId,req.params.oasisId);const result=validateOasisSnapshot(o.immutableSnapshot,specRecord(o),String(o.transactionMode||'NEW'));await persistFindings(prisma,a,req.params.oasisId,result.findings);const state=result.fatalCount>0?'FAIL':result.warningCount>0?'WARNING':'PASS',status=result.fatalCount>0?'DRAFT':'READY_TO_SUBMIT';await prisma.$executeRawUnsafe(`UPDATE "HomeHealthOasisAssessment" SET "validationState"=$1,"status"=$2,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "id"=$5`,state,status,a.organizationId,entity(a),req.params.oasisId);await event(prisma,a,req.params.episodeId,'OASIS_SPEC_VALIDATION_RUN','HOME_HEALTH_OASIS_ASSESSMENT',req.params.oasisId,{validationState:state,fatalCount:result.fatalCount,warningCount:result.warningCount,deferredExternalEditCount:result.deferredRuleCodes.length});res.json({data:{validationState:state,status,findings:result.findings,deferredExternalRuleCodes:result.deferredRuleCodes,submissionReady:result.fatalCount===0,finalIqiesValidationStillRequired:true}});
  }catch(e){next(e);}});

  // Intercepts the earlier queue-only endpoint. XML is generated deterministically
  // from the immutable snapshot and validated spec, returned to the authorized
  // caller, and never stored in plaintext in the database.
  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/iqies-submissions',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const o=await loadOasis(prisma,a,req.params.episodeId,req.params.oasisId);if(!o.immutableSnapshot||!o.snapshotSha256)throw httpError(409,'Create the immutable OASIS snapshot before export');const validation=validateOasisSnapshot(o.immutableSnapshot,specRecord(o),String(o.transactionMode||'NEW'));if(validation.fatalCount)throw httpError(409,'OASIS export is blocked by fatal local specification findings',validation.findings);const built=buildOasisSubmissionXml(o.immutableSnapshot,specRecord(o),String(o.transactionMode||'NEW'));const maxUploadBytes=5*1024*1024;if(built.bytes>maxUploadBytes)throw httpError(413,'Generated OASIS XML exceeds the current iQIES 5 MB upload limit');const idempotencyKey=buildIqiesIdempotencyKey({organizationId:a.organizationId,legalEntityId:entity(a),oasisAssessmentId:req.params.oasisId,transactionMode:String(o.transactionMode||'NEW'),payloadSha256:built.sha256}),adapter=getIqiesTransportReadiness(process.env);const id=randomUUID(),fileName=`oasis-${req.params.oasisId}-${Date.now()}.xml`;const created=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "HomeHealthIqiesSubmission"("id","organizationId","legalEntityId","oasisAssessmentId","submissionSpecVersion","environment","transportMode","status","fileName","payloadSha256","payloadBytes","recordCount","exportMetadata","sourceSnapshotSha256","specDefinitionSha256","exportedAt","createdById") VALUES($1,$2,$3,$4,$5,'TEST','EXPORT_ONLY','EXPORTED',$6,$7,$8,1,$9::jsonb,$10,$11,NOW(),$12) RETURNING *`,id,a.organizationId,entity(a),req.params.oasisId,String(o.submissionSpecVersion),fileName,built.sha256,built.bytes,JSON.stringify({mimeType:'application/xml',rawPayloadPersisted:false,idempotencyKey,deferredExternalEditCount:built.deferredRuleCodes.length,finalIqiesValidationRequired:true}),o.snapshotSha256,o.normalizedDefinitionSha256,a.userId);await event(prisma,a,req.params.episodeId,'IQIES_XML_EXPORTED','HOME_HEALTH_IQIES_SUBMISSION',id,{fileName,payloadSha256:built.sha256,payloadBytes:built.bytes,idempotencyKey,rawPayloadPersisted:false});await audit?.(a,'EXPORT_OASIS_IQIES_XML','HomeHealthIqiesSubmission',id,{oasisAssessmentId:req.params.oasisId,payloadSha256:built.sha256,payloadBytes:built.bytes,idempotencyKey});res.status(201).json({data:{submission:created[0],file:{name:fileName,mimeType:'application/xml',content:built.xml,sha256:built.sha256,bytes:built.bytes},externalSubmissionConfigured:adapter.configured,externalSubmissionEnabled:adapter.submissionEnabled,transportMode:'EXPORT_ONLY',idempotencyKey,finalIqiesValidationStillRequired:true,deferredExternalRuleCodes:built.deferredRuleCodes}});
  }catch(e){next(e);}});

  app.post('/api/home-health/episodes/:episodeId/oasis/:oasisId/iqies-submissions/:submissionId/reconcile',async(req,res,next)=>{try{
    const a=authOf(res);await ensureWrite(prisma,a);const input=reconcileSchema.parse(req.body),o=await loadOasis(prisma,a,req.params.episodeId,req.params.oasisId);const existing=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "HomeHealthIqiesSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "oasisAssessmentId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.oasisId,req.params.submissionId);if(!existing[0])throw httpError(404,'iQIES submission record was not found');const nowStatus=input.status;assertIqiesReconciliationTransition(existing[0].status,nowStatus);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "HomeHealthIqiesSubmission" SET "transportMode"=$1,"status"=$2,"externalSubmissionId"=COALESCE($3,"externalSubmissionId"),"validationUtilityVersion"=COALESCE($4,"validationUtilityVersion"),"ackCode"=COALESCE($5,"ackCode"),"ackMessage"=COALESCE($6,"ackMessage"),"validationReportSha256"=COALESCE($7,"validationReportSha256"),"responsePayload"=$8::jsonb,"submittedAt"=CASE WHEN $2 IN ('SUBMITTED','ACCEPTED','REJECTED','PARTIAL') THEN COALESCE("submittedAt",NOW()) ELSE "submittedAt" END,"acknowledgedAt"=CASE WHEN $2 IN ('ACCEPTED','REJECTED','PARTIAL') THEN NOW() ELSE "acknowledgedAt" END,"responseReceivedAt"=NOW(),"resolvedAt"=CASE WHEN $2 IN ('ACCEPTED','REJECTED','ERROR') THEN NOW() ELSE NULL END,"lastError"=CASE WHEN $2 IN ('REJECTED','ERROR') THEN COALESCE($6,$5,'iQIES submission error') ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$9 AND "legalEntityId"=$10 AND "oasisAssessmentId"=$11 AND "id"=$12 RETURNING *`,input.transportMode,nowStatus,input.externalSubmissionId??null,input.validationUtilityVersion??null,input.ackCode??null,input.ackMessage??null,input.validationReportSha256??null,JSON.stringify(input.responsePayload),a.organizationId,entity(a),req.params.oasisId,req.params.submissionId);const oasisStatus=nowStatus==='ACCEPTED'?'ACCEPTED':['REJECTED','ERROR'].includes(nowStatus)?'REJECTED':'SUBMITTED';await prisma.$executeRawUnsafe(`UPDATE "HomeHealthOasisAssessment" SET "status"=$1,"submittedAt"=CASE WHEN $1 IN ('SUBMITTED','ACCEPTED','REJECTED') THEN COALESCE("submittedAt",NOW()) ELSE "submittedAt" END,"acceptedAt"=CASE WHEN $1='ACCEPTED' THEN NOW() ELSE "acceptedAt" END,"rejectedAt"=CASE WHEN $1='REJECTED' THEN NOW() ELSE "rejectedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4`,oasisStatus,a.organizationId,entity(a),req.params.oasisId);await event(prisma,a,req.params.episodeId,`IQIES_${nowStatus}`,'HOME_HEALTH_IQIES_SUBMISSION',req.params.submissionId,{status:nowStatus,transportMode:input.transportMode,externalSubmissionId:input.externalSubmissionId??null});await audit?.(a,'RECONCILE_IQIES_SUBMISSION','HomeHealthIqiesSubmission',req.params.submissionId,{oasisAssessmentId:o.id,status:nowStatus,transportMode:input.transportMode});res.json({data:{submission:rows[0],oasisStatus}});
  }catch(e){next(e);}});
};
