import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';
import { getSecureObject, putSecureObject, scanBufferForMalware } from './secure-object-storage.js';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};

const managerRoles=[UserRole.ADMINISTRATOR,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO] as const;
const contentSchema=z.object({
  slotKey:z.string().trim().min(2).max(80),
  kind:z.enum(['HERO','NEWS','SIDE','MESSAGE','RESOURCE']).default('NEWS'),
  eyebrow:z.string().trim().max(120).default(''),
  title:z.string().trim().min(1).max(300),
  body:z.string().trim().max(8000).default(''),
  externalImageUrl:z.string().trim().max(2000).default(''),
  linkUrl:z.string().trim().max(2000).default(''),
  linkLabel:z.string().trim().max(120).default(''),
  sortOrder:z.number().int().min(0).max(10000).default(0),
  durationMs:z.number().int().min(2000).max(120000).default(8000),
  active:z.boolean().default(true),
  startsAt:z.coerce.date().optional().nullable(),
  endsAt:z.coerce.date().optional().nullable(),
});
const settingsSchema=z.object({heroAutoplay:z.boolean().default(true),heroIntervalMs:z.number().int().min(2000).max(120000).default(8000),newsAutoplay:z.boolean().default(false),newsIntervalMs:z.number().int().min(2000).max(120000).default(10000)});
const imageSchema=z.object({fileName:z.string().trim().min(1).max(240),mimeType:z.string().trim().regex(/^image\//),contentBase64:z.string().min(1).max(25_000_000)});

export function registerIntranetContentRoutes({app,prisma,authOf,requireRoles}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "IntranetContentItem" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"slotKey" TEXT NOT NULL,"kind" TEXT NOT NULL,"eyebrow" TEXT NOT NULL DEFAULT '',"title" TEXT NOT NULL,"body" TEXT NOT NULL DEFAULT '',"imageObjectKey" TEXT,"imageMimeType" TEXT,"externalImageUrl" TEXT NOT NULL DEFAULT '',"linkUrl" TEXT NOT NULL DEFAULT '',"linkLabel" TEXT NOT NULL DEFAULT '',"sortOrder" INTEGER NOT NULL DEFAULT 0,"durationMs" INTEGER NOT NULL DEFAULT 8000,"active" BOOLEAN NOT NULL DEFAULT TRUE,"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "IntranetContentItem_org_slot_idx" ON "IntranetContentItem"("organizationId","slotKey","active","sortOrder")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "IntranetContentSettings" ("organizationId" TEXT PRIMARY KEY,"heroAutoplay" BOOLEAN NOT NULL DEFAULT TRUE,"heroIntervalMs" INTEGER NOT NULL DEFAULT 8000,"newsAutoplay" BOOLEAN NOT NULL DEFAULT FALSE,"newsIntervalMs" INTEGER NOT NULL DEFAULT 10000,"updatedById" TEXT,"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  })().catch(error=>{readyPromise=null;throw error});
  const gate=requireRoles(...managerRoles);
  const rowsForOrg=(organizationId:string,activeOnly=false)=>prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "IntranetContentItem" WHERE "organizationId"=$1 ${activeOnly?'AND "active"=TRUE AND ("startsAt" IS NULL OR "startsAt"<=NOW()) AND ("endsAt" IS NULL OR "endsAt">NOW())':''} ORDER BY "slotKey","sortOrder","createdAt"`,organizationId);
  const settingsForOrg=async(organizationId:string)=>{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "IntranetContentSettings" WHERE "organizationId"=$1 LIMIT 1`,organizationId);return rows[0]||{heroAutoplay:true,heroIntervalMs:8000,newsAutoplay:false,newsIntervalMs:10000}};

  app.get('/api/employee/intranet/content',async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [items,settings]=await Promise.all([rowsForOrg(auth.organizationId,true),settingsForOrg(auth.organizationId)]);res.json({data:{items:items.map(item=>({...item,imageUrl:item.imageObjectKey?`/api/employee/intranet/content/${item.id}/image`:item.externalImageUrl||''})),settings}})}catch(error){next(error)}});
  app.get('/api/employee/intranet/content/:itemId/image',async(req,res,next)=>{try{await ready();const auth=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT "imageObjectKey","imageMimeType" FROM "IntranetContentItem" WHERE "organizationId"=$1 AND "id"=$2 AND "active"=TRUE LIMIT 1`,auth.organizationId,req.params.itemId);const row=rows[0];if(!row?.imageObjectKey)return void res.status(404).json({error:'Intranet image was not found'});const buffer=await getSecureObject(row.imageObjectKey);res.setHeader('Content-Type',row.imageMimeType||'image/jpeg');res.setHeader('Cache-Control','private, max-age=300');res.send(buffer)}catch(error){next(error)}});

  app.get('/api/admin/intranet/content',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const [items,settings]=await Promise.all([rowsForOrg(auth.organizationId),settingsForOrg(auth.organizationId)]);res.json({data:{items:items.map(item=>({...item,imageUrl:item.imageObjectKey?`/api/employee/intranet/content/${item.id}/image`:item.externalImageUrl||''})),settings}})}catch(error){next(error)}});
  app.post('/api/admin/intranet/content',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=contentSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "IntranetContentItem" ("id","organizationId","slotKey","kind","eyebrow","title","body","externalImageUrl","linkUrl","linkLabel","sortOrder","durationMs","active","startsAt","endsAt","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16)`,id,auth.organizationId,input.slotKey,input.kind,input.eyebrow,input.title,input.body,input.externalImageUrl,input.linkUrl,input.linkLabel,input.sortOrder,input.durationMs,input.active,input.startsAt??null,input.endsAt??null,auth.userId);res.status(201).json({data:{id}})}catch(error){next(error)}});
  app.patch('/api/admin/intranet/content/:itemId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=contentSchema.partial().parse(req.body);const current=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "IntranetContentItem" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.itemId))[0];if(!current)return void res.status(404).json({error:'Intranet content item was not found'});await prisma.$executeRawUnsafe(`UPDATE "IntranetContentItem" SET "slotKey"=$1,"kind"=$2,"eyebrow"=$3,"title"=$4,"body"=$5,"externalImageUrl"=$6,"linkUrl"=$7,"linkLabel"=$8,"sortOrder"=$9,"durationMs"=$10,"active"=$11,"startsAt"=$12,"endsAt"=$13,"updatedById"=$14,"updatedAt"=NOW() WHERE "organizationId"=$15 AND "id"=$16`,input.slotKey??current.slotKey,input.kind??current.kind,input.eyebrow??current.eyebrow,input.title??current.title,input.body??current.body,input.externalImageUrl??current.externalImageUrl,input.linkUrl??current.linkUrl,input.linkLabel??current.linkLabel,input.sortOrder??current.sortOrder,input.durationMs??current.durationMs,input.active??current.active,input.startsAt===undefined?current.startsAt:input.startsAt,input.endsAt===undefined?current.endsAt:input.endsAt,auth.userId,auth.organizationId,current.id);res.json({data:{id:current.id}})}catch(error){next(error)}});
  app.delete('/api/admin/intranet/content/:itemId',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);await prisma.$executeRawUnsafe(`UPDATE "IntranetContentItem" SET "active"=FALSE,"updatedById"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "id"=$3`,auth.userId,auth.organizationId,req.params.itemId);res.json({data:{id:req.params.itemId,active:false}})}catch(error){next(error)}});
  app.post('/api/admin/intranet/content/:itemId/image',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=imageSchema.parse(req.body);const item=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "IntranetContentItem" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.itemId))[0];if(!item)return void res.status(404).json({error:'Intranet content item was not found'});const buffer=Buffer.from(input.contentBase64.replace(/^data:[^;]+;base64,/,''),'base64');if(buffer.length>8*1024*1024)return void res.status(413).json({error:'Intranet images must be 8 MB or smaller'});const scan=await scanBufferForMalware(buffer);if(scan.status==='INFECTED')return void res.status(422).json({error:'The uploaded image failed malware scanning'});if(scan.status==='UNAVAILABLE'&&process.env.EMPLOYEE_OBJECT_SCAN_FAIL_OPEN!=='true')return void res.status(503).json({error:'Image scanning is temporarily unavailable'});const key=`intranet/${auth.organizationId}/${item.id}/${Date.now()}-${input.fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await putSecureObject({key,body:buffer,contentType:input.mimeType,metadata:{purpose:'intranet-content',item:item.id}});await prisma.$executeRawUnsafe(`UPDATE "IntranetContentItem" SET "imageObjectKey"=$1,"imageMimeType"=$2,"externalImageUrl"='',"updatedById"=$3,"updatedAt"=NOW() WHERE "organizationId"=$4 AND "id"=$5`,key,input.mimeType,auth.userId,auth.organizationId,item.id);res.json({data:{id:item.id,imageUrl:`/api/employee/intranet/content/${item.id}/image`}})}catch(error){next(error)}});
  app.put('/api/admin/intranet/settings',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=settingsSchema.parse(req.body);await prisma.$executeRawUnsafe(`INSERT INTO "IntranetContentSettings" ("organizationId","heroAutoplay","heroIntervalMs","newsAutoplay","newsIntervalMs","updatedById") VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT ("organizationId") DO UPDATE SET "heroAutoplay"=EXCLUDED."heroAutoplay","heroIntervalMs"=EXCLUDED."heroIntervalMs","newsAutoplay"=EXCLUDED."newsAutoplay","newsIntervalMs"=EXCLUDED."newsIntervalMs","updatedById"=EXCLUDED."updatedById","updatedAt"=NOW()`,auth.organizationId,input.heroAutoplay,input.heroIntervalMs,input.newsAutoplay,input.newsIntervalMs,auth.userId);res.json({data:input})}catch(error){next(error)}});
}
