import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';
import { putSecureObject } from './secure-object-storage.js';

const require = createRequire(import.meta.url);
const nodemailer = require('nodemailer') as typeof import('nodemailer');

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string|null};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};
type AgentActionType='PUBLISH_INTRAnet_CONTENT'|'GENERATE_INTRAnet_MEME'|'SEND_ANNOUNCEMENT'|'SEND_NOTIFICATION'|'SEND_EMAIL'|'REQUEST_CODE_CHANGE';
type AgentActionRow={id:string;conversationId:string;actionType:AgentActionType;status:string;risk:string;changeClass:string;approvalRequired:boolean;summary:string;payload:Record<string,unknown>|string;result:Record<string,unknown>|string;createdAt:Date|string;executedAt?:Date|string|null};
type OpenAIResponse={output_text?:string;output?:Array<{type?:string;name?:string;arguments?:string;call_id?:string;content?:Array<{type?:string;text?:string}>}>;error?:{message?:string}};

const adminRoles=[UserRole.ADMINISTRATOR,UserRole.CEO,UserRole.DOO,UserRole.COO,UserRole.HR_MANAGER] as const;
const chatSchema=z.object({conversationId:z.string().uuid().optional(),message:z.string().trim().min(1).max(12000)});
const actionDecisionSchema=z.object({note:z.string().trim().max(2000).optional().default('')});
const clean=(value:unknown,max=12000)=>String(value??'').trim().slice(0,max);
const redact=(value:string)=>value
  .replace(/\bBearer\s+[A-Za-z0-9._~-]{12,}\b/gi,'Bearer [REDACTED_TOKEN]')
  .replace(/\b(api[_ -]?key|access[_ -]?token|secret|password|mfa|otp)\s*[:=]\s*[^\s,;]+/gi,'$1=[REDACTED]')
  .replace(/\bsk-[A-Za-z0-9_-]{12,}\b/g,'[REDACTED_KEY]')
  .replace(/\b\d{3}-\d{2}-\d{4}\b/g,'[REDACTED_SSN]');
const obj=(value:unknown):Record<string,unknown>=>{if(value&&typeof value==='object'&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==='string'){try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}}catch{return{}}}return{}};
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const model=()=>process.env.IT_AGENT_OPENAI_MODEL?.trim()||process.env.SIA_OPENAI_MODEL?.trim()||'gpt-5.6-terra';
const openAIKey=()=>process.env.OPENAI_API_KEY?.trim()||'';

const actionPolicy=(name:string,args:Record<string,unknown>)=>{
  if(name==='request_code_change')return{actionType:'REQUEST_CODE_CHANGE' as AgentActionType,risk:'HIGH',changeClass:'NEW_SYSTEM_CHANGE',approvalRequired:true,summary:clean(args.summary||args.request,500)};
  if(name==='send_employee_email')return{actionType:'SEND_EMAIL' as AgentActionType,risk:String(args.audience||'').toUpperCase()==='ALL_EMPLOYEES'?'MEDIUM':'LOW',changeClass:'ADMIN_COMMUNICATION',approvalRequired:false,summary:`Send employee email: ${clean(args.subject,180)}`};
  if(name==='send_employee_announcement')return{actionType:'SEND_ANNOUNCEMENT' as AgentActionType,risk:String(args.priority||'').toUpperCase()==='URGENT'?'MEDIUM':'LOW',changeClass:'ADMIN_COMMUNICATION',approvalRequired:false,summary:`Publish employee announcement: ${clean(args.title,180)}`};
  if(name==='send_employee_notification')return{actionType:'SEND_NOTIFICATION' as AgentActionType,risk:'LOW',changeClass:'ADMIN_COMMUNICATION',approvalRequired:false,summary:`Send employee notification: ${clean(args.title,180)}`};
  if(name==='post_intranet_meme')return{actionType:'GENERATE_INTRAnet_MEME' as AgentActionType,risk:'LOW',changeClass:'CONTENT_CHANGE',approvalRequired:false,summary:`Generate and post intranet meme/card: ${clean(args.title,180)}`};
  return{actionType:'PUBLISH_INTRAnet_CONTENT' as AgentActionType,risk:'LOW',changeClass:'CONTENT_CHANGE',approvalRequired:false,summary:`Publish intranet content: ${clean(args.title,180)}`};
};

const tools=[
  {type:'function',name:'publish_intranet_content',description:'Propose publishing a real card, message, resource, hero, or news item to the Sulandra intranet. Use for cards, alerts, quick links, and content posts.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['HERO','NEWS','SIDE','MESSAGE','RESOURCE']},slotKey:{type:'string'},eyebrow:{type:'string'},title:{type:'string'},body:{type:'string'},linkUrl:{type:'string'},linkLabel:{type:'string'},externalImageUrl:{type:'string'}},required:['kind','slotKey','eyebrow','title','body','linkUrl','linkLabel','externalImageUrl']}},
  {type:'function',name:'post_intranet_meme',description:'Propose generating an original workplace-safe image/meme with GPT Image 2 and publishing it as an intranet news or side card. Never copy copyrighted meme artwork or protected characters.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{title:{type:'string'},caption:{type:'string'},imagePrompt:{type:'string'},kind:{type:'string',enum:['NEWS','SIDE','HERO']},slotKey:{type:'string'},linkUrl:{type:'string'},linkLabel:{type:'string'}},required:['title','caption','imagePrompt','kind','slotKey','linkUrl','linkLabel']}},
  {type:'function',name:'send_employee_announcement',description:'Propose a real in-app employee announcement using the existing Sulandra communications system.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{title:{type:'string'},message:{type:'string'},audience:{type:'string',enum:['ALL_EMPLOYEES','MANAGERS','HR_ADMIN','CUSTOM']},priority:{type:'string',enum:['NORMAL','IMPORTANT','URGENT']},requiresAcknowledgment:{type:'boolean'},recipientUserIds:{type:'array',items:{type:'string'}}},required:['title','message','audience','priority','requiresAcknowledgment','recipientUserIds']}},
  {type:'function',name:'send_employee_notification',description:'Propose a real targeted in-app notification to one employee.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{employeeId:{type:'string'},title:{type:'string'},message:{type:'string'},category:{type:'string',enum:['GENERAL','COMPLIANCE','SCHEDULE','PAYROLL','BENEFITS','LEAVE','DOCUMENT','WORKFLOW','SECURITY']},actionUrl:{type:'string'}},required:['employeeId','title','message','category','actionUrl']}},
  {type:'function',name:'send_employee_email',description:'Propose sending a real email through Sulandra SMTP. Use ALL_EMPLOYEES, MANAGERS, HR_ADMIN, or CUSTOM user IDs. This always waits for the administrator to press Execute in the workbench.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{audience:{type:'string',enum:['ALL_EMPLOYEES','MANAGERS','HR_ADMIN','CUSTOM']},recipientUserIds:{type:'array',items:{type:'string'}},subject:{type:'string'},message:{type:'string'}},required:['audience','recipientUserIds','subject','message']}},
  {type:'function',name:'request_code_change',description:'Use for requests that require changing source code, UI buttons, routes, permissions, configuration, deployments, or data-repair logic. This creates a controlled engineering/approval handoff; do not pretend the code was changed.',strict:true,parameters:{type:'object',additionalProperties:false,properties:{summary:{type:'string'},request:{type:'string'},target:{type:'string'},reason:{type:'string'}},required:['summary','request','target','reason']}},
];

const extractText=(payload:OpenAIResponse)=>{
  const chunks:string[]=[];
  for(const item of payload.output||[])if(item.type==='message')for(const part of item.content||[])if(part.type==='output_text'&&part.text)chunks.push(part.text);
  return clean(chunks.join('\n')||payload.output_text||'',12000);
};

async function askOpenAI(history:Array<{role:string;content:string}>,context:string){
  const key=openAIKey();if(!key)throw httpError(503,'The IT Agent AI service is not configured on this API deployment.');
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({
    model:model(),
    instructions:`You are the privileged Sulandra IT Agent inside the Administrator IT Solutions workbench. You are not the employee-facing SIA support chat. Help the authorized administrator operate Sulandra safely.\n\nYou can propose real tool actions for intranet content, original memes/cards, employee announcements, targeted notifications, employee email, and controlled code/system-change requests. Tool calls create reviewable proposals; never say a side effect happened until a trusted execution result says it did. For a request to add or modify a button, page, route, backend behavior, permissions, configuration, database logic, GitHub code, or Railway deployment, use request_code_change. New system/code changes require approval and a trusted coding worker; never fabricate a commit, PR, or deployment.\n\nKeep clinical/patient content, secrets, credentials, passwords, tokens, MFA values, payroll decisions, and cross-tenant data out of prompts and actions. Prefer concise operational replies.\n\nCurrent trusted read-only IT context:\n${context}`,
    input:history.map(item=>({role:item.role,content:[{type:'input_text',text:redact(item.content)}]})),
    tools,
    tool_choice:'auto',
  })});
  const payload=await response.json() as OpenAIResponse;
  if(!response.ok)throw httpError(502,payload.error?.message||`OpenAI request failed (${response.status})`);
  return payload;
}

async function sendMail(recipients:string[],subject:string,message:string){
  const host=process.env.SMTP_HOST;const port=Number(process.env.SMTP_PORT||587);const user=process.env.SMTP_USER;const pass=process.env.SMTP_PASS;
  if(!host||!user||!pass)throw httpError(503,'Sulandra SMTP is not configured on this API deployment.');
  if(!recipients.length)throw httpError(409,'No eligible employee email recipients were found.');
  const transporter=nodemailer.createTransport({host,port,secure:port===465,auth:{user,pass},connectionTimeout:10000,greetingTimeout:10000,socketTimeout:20000});
  await transporter.sendMail({from:{name:'Sulandra Health IT Solutions',address:(process.env.FROM_EMAIL||process.env.SMTP_FROM||user).trim()},replyTo:user.trim(),to:recipients,subject:clean(subject,240),text:clean(message,12000),html:`<div style="font-family:Segoe UI,Arial,sans-serif;color:#18324a;line-height:1.6"><h2 style="color:#082f5b">${clean(subject,240).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}</h2><p>${clean(message,12000).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c)).replace(/\n/g,'<br>')}</p><p style="color:#64748b;font-size:12px">Sent by Sulandra Health IT Solutions.</p></div>`});
}

export function registerITAgentWorkbenchRoutes({app,prisma,authOf,requireRoles}:Dependencies){
  const gate=requireRoles(...adminRoles);
  let init:Promise<void>|null=null;
  const ready=()=>init??=(async()=>{
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ITAgentConversation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"title" TEXT NOT NULL DEFAULT 'IT Agent session',"status" TEXT NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ITAgentConversation_user_idx" ON "ITAgentConversation"("organizationId","userId","updatedAt" DESC)`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ITAgentMessage" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" TEXT NOT NULL,"content" TEXT NOT NULL,"model" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ITAgentMessage_conversation_idx" ON "ITAgentMessage"("organizationId","conversationId","createdAt")`);
    await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ITAgentAction" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"requestedByUserId" TEXT NOT NULL,"actionType" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PROPOSED',"risk" TEXT NOT NULL,"changeClass" TEXT NOT NULL,"approvalRequired" BOOLEAN NOT NULL DEFAULT FALSE,"summary" TEXT NOT NULL,"payload" JSONB NOT NULL DEFAULT '{}'::jsonb,"result" JSONB NOT NULL DEFAULT '{}'::jsonb,"executedByUserId" TEXT,"executedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ITAgentAction_queue_idx" ON "ITAgentAction"("organizationId","status","createdAt" DESC)`);
  })().catch(error=>{init=null;throw error});

  const ownedConversation=async(auth:AuthContext,id:string)=>{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "ITAgentConversation" WHERE "organizationId"=$1 AND "userId"=$2 AND "id"=$3 LIMIT 1`,auth.organizationId,auth.userId,id);return rows[0]||null};
  const context=async(auth:AuthContext)=>{const [tickets,approvals,handoffs,actions]=await Promise.all([
    prisma.$queryRawUnsafe<any[]>(`SELECT "status","priority",COUNT(*)::int AS count FROM "EmployeeSupportRequest" WHERE "organizationId"=$1 GROUP BY "status","priority"`,auth.organizationId).catch(()=>[]),
    prisma.$queryRawUnsafe<any[]>(`SELECT "status","risk",COUNT(*)::int AS count FROM "ITRemediationApproval" WHERE "organizationId"=$1 GROUP BY "status","risk"`,auth.organizationId).catch(()=>[]),
    prisma.$queryRawUnsafe<any[]>(`SELECT "status","changeClass",COUNT(*)::int AS count FROM "ITAgentHandoff" WHERE "organizationId"=$1 GROUP BY "status","changeClass"`,auth.organizationId).catch(()=>[]),
    prisma.$queryRawUnsafe<any[]>(`SELECT "actionType","status",COUNT(*)::int AS count FROM "ITAgentAction" WHERE "organizationId"=$1 GROUP BY "actionType","status"`,auth.organizationId).catch(()=>[]),
  ]);return JSON.stringify({tickets,approvals,handoffs,agentActions:actions,openAIConfigured:Boolean(openAIKey()),smtpConfigured:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS),githubCodingWorkerConfigured:Boolean(process.env.SULANDRA_GITHUB_TOKEN||process.env.GITHUB_TOKEN),railwayEvidence:'Read-only production evidence is correlated by the IT operations workflow; code/deploy mutations require a trusted worker and approval.'})};

  app.get('/api/it-solutions/agent/status',gate,async(_req,res,next)=>{try{await ready();res.json({data:{online:Boolean(openAIKey()),model:model(),capabilities:{intranetContent:true,intranetMeme:Boolean(openAIKey()),announcements:true,notifications:true,email:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS),codeChangeRequests:true,codingWorkerConnected:Boolean(process.env.SULANDRA_GITHUB_TOKEN||process.env.GITHUB_TOKEN)}}})}catch(error){next(error)}});

  app.get('/api/it-solutions/agent/actions',gate,async(_req,res,next)=>{try{await ready();const auth=authOf(res);const rows=await prisma.$queryRawUnsafe<AgentActionRow[]>(`SELECT * FROM "ITAgentAction" WHERE "organizationId"=$1 ORDER BY "createdAt" DESC LIMIT 100`,auth.organizationId);res.json({data:{actions:rows.map(row=>({...row,payload:obj(row.payload),result:obj(row.result)}))}})}catch(error){next(error)}});

  app.post('/api/it-solutions/agent/chat',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=chatSchema.parse(req.body);let conversationId=input.conversationId;let conversation=conversationId?await ownedConversation(auth,conversationId):null;if(conversationId&&!conversation)return void res.status(404).json({error:'IT Agent conversation was not found'});if(!conversation){conversationId=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "ITAgentConversation" ("id","organizationId","userId","title") VALUES ($1,$2,$3,$4)`,conversationId,auth.organizationId,auth.userId,clean(input.message,100));}
    await prisma.$executeRawUnsafe(`INSERT INTO "ITAgentMessage" ("id","organizationId","conversationId","userId","role","content") VALUES ($1,$2,$3,$4,'user',$5)`,randomUUID(),auth.organizationId,conversationId,auth.userId,redact(input.message));
    const historyRows=await prisma.$queryRawUnsafe<Array<{role:string;content:string}>>(`SELECT "role","content" FROM "ITAgentMessage" WHERE "organizationId"=$1 AND "conversationId"=$2 ORDER BY "createdAt" DESC LIMIT 20`,auth.organizationId,conversationId);const history=historyRows.reverse();
    const payload=await askOpenAI(history,await context(auth));const proposals:any[]=[];
    for(const item of payload.output||[]){if(item.type!=='function_call'||!item.name)continue;let args:Record<string,unknown>={};try{args=JSON.parse(item.arguments||'{}')}catch{continue}const policy=actionPolicy(item.name,args);const actionId=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "ITAgentAction" ("id","organizationId","conversationId","requestedByUserId","actionType","risk","changeClass","approvalRequired","summary","payload") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,actionId,auth.organizationId,conversationId,auth.userId,policy.actionType,policy.risk,policy.changeClass,policy.approvalRequired,policy.summary,JSON.stringify({...args,toolName:item.name}));proposals.push({id:actionId,...policy,payload:args,status:'PROPOSED'});}
    let reply=extractText(payload);if(!reply&&proposals.length)reply=`I prepared ${proposals.length} action${proposals.length===1?'':'s'} for your review. Nothing has been executed yet.`;if(!reply)reply='I reviewed the request but did not create an executable action. Tell me the exact Sulandra target and desired result.';
    await prisma.$executeRawUnsafe(`INSERT INTO "ITAgentMessage" ("id","organizationId","conversationId","userId","role","content","model") VALUES ($1,$2,$3,$4,'assistant',$5,$6)`,randomUUID(),auth.organizationId,conversationId,auth.userId,reply,model());await prisma.$executeRawUnsafe(`UPDATE "ITAgentConversation" SET "updatedAt"=NOW() WHERE "id"=$1`,conversationId);res.json({data:{conversationId,reply,proposals,model:model()}})}catch(error){next(error)}});

  app.post('/api/it-solutions/agent/actions/:actionId/reject',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=actionDecisionSchema.parse(req.body);const count=await prisma.$executeRawUnsafe(`UPDATE "ITAgentAction" SET "status"='REJECTED',"result"=$1::jsonb,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "id"=$3 AND "status"='PROPOSED'`,JSON.stringify({note:input.note||'Rejected by administrator'}),auth.organizationId,req.params.actionId);if(!count)return void res.status(409).json({error:'Action is no longer pending review'});res.json({data:{id:req.params.actionId,status:'REJECTED'}})}catch(error){next(error)}});

  app.post('/api/it-solutions/agent/actions/:actionId/execute',gate,async(req,res,next)=>{try{await ready();const auth=authOf(res);const input=actionDecisionSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<AgentActionRow[]>(`SELECT * FROM "ITAgentAction" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,auth.organizationId,req.params.actionId);const action=rows[0];if(!action)return void res.status(404).json({error:'IT Agent action was not found'});if(action.status!=='PROPOSED')return void res.status(409).json({error:`Action is ${action.status}, not PROPOSED`});const payload=obj(action.payload);let result:Record<string,unknown>={};let finalStatus='EXECUTED';

    if(action.actionType==='PUBLISH_INTRAnet_CONTENT'||action.actionType==='GENERATE_INTRAnet_MEME'){
      const id=randomUUID();let imageObjectKey:string|null=null;let externalImageUrl=clean(payload.externalImageUrl,2000);
      if(action.actionType==='GENERATE_INTRAnet_MEME'){
        const key=openAIKey();if(!key)throw httpError(503,'OpenAI is required to generate an intranet meme image.');const imageResponse=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-image-2',prompt:`Create an original, workplace-safe internal-company meme/card image for Sulandra Health. No copyrighted characters, logos, or copied meme templates. ${clean(payload.imagePrompt,3000)}. Caption idea: ${clean(payload.caption,1000)}`,size:'1024x1024',quality:'medium',output_format:'png'})});const imagePayload=await imageResponse.json() as any;if(!imageResponse.ok)throw httpError(502,imagePayload?.error?.message||'Image generation failed');const base64=imagePayload?.data?.[0]?.b64_json;if(!base64)throw httpError(502,'Image generation returned no image data');const buffer=Buffer.from(base64,'base64');imageObjectKey=`intranet/${auth.organizationId}/${id}/it-agent-${Date.now()}.png`;await putSecureObject({key:imageObjectKey,body:buffer,contentType:'image/png',metadata:{purpose:'it-agent-intranet-content',actionId:action.id}});externalImageUrl='';}
      await prisma.$executeRawUnsafe(`INSERT INTO "IntranetContentItem" ("id","organizationId","slotKey","kind","eyebrow","title","body","imageObjectKey","imageMimeType","externalImageUrl","linkUrl","linkLabel","sortOrder","durationMs","active","createdById","updatedById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,0,8000,TRUE,$13,$13)`,id,auth.organizationId,clean(payload.slotKey,80)||`it-agent-${Date.now()}`,clean(payload.kind,20)||'NEWS',clean(payload.eyebrow,120)||'IT Agent',clean(payload.title,300),clean(payload.body||payload.caption,8000),imageObjectKey,imageObjectKey?'image/png':null,externalImageUrl,clean(payload.linkUrl,2000),clean(payload.linkLabel,120),auth.userId);result={resourceType:'IntranetContentItem',resourceId:id,published:true,imageGenerated:Boolean(imageObjectKey)};
    } else if(action.actionType==='SEND_ANNOUNCEMENT'){
      const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeAnnouncement" ("id","organizationId","title","message","audience","priority","requiresAcknowledgment","recipientUserIds","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)`,id,auth.organizationId,clean(payload.title,240),clean(payload.message,12000),clean(payload.audience,40)||'ALL_EMPLOYEES',clean(payload.priority,40)||'NORMAL',payload.requiresAcknowledgment===true,JSON.stringify(Array.isArray(payload.recipientUserIds)?payload.recipientUserIds:[]),auth.userId);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeCommunicationEvent" ("id","organizationId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,'ANNOUNCEMENT_CREATED','ANNOUNCEMENT',$4,$5::jsonb)`,randomUUID(),auth.organizationId,auth.userId,id,JSON.stringify({source:'IT_AGENT'}));result={resourceType:'EmployeeAnnouncement',resourceId:id,published:true};
    } else if(action.actionType==='SEND_NOTIFICATION'){
      const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeNotification" ("id","organizationId","employeeId","title","message","category","actionUrl","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,id,auth.organizationId,clean(payload.employeeId,160),clean(payload.title,240),clean(payload.message,8000),clean(payload.category,40)||'GENERAL',clean(payload.actionUrl,1000),auth.userId);await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeCommunicationEvent" ("id","organizationId","employeeId","actorUserId","eventType","resourceType","resourceId","details") VALUES ($1,$2,$3,$4,'NOTIFICATION_CREATED','NOTIFICATION',$5,$6::jsonb)`,randomUUID(),auth.organizationId,clean(payload.employeeId,160),auth.userId,id,JSON.stringify({source:'IT_AGENT'}));result={resourceType:'EmployeeNotification',resourceId:id,sent:true};
    } else if(action.actionType==='SEND_EMAIL'){
      const audience=clean(payload.audience,40);const custom=Array.isArray(payload.recipientUserIds)?payload.recipientUserIds.map(v=>clean(v,160)).filter(Boolean):[];const managerRoleNames=['ADMINISTRATOR','PROGRAM_MANAGER','HR_MANAGER','HOUSE_MANAGER','CEO','COO','DOO'];const hrRoles=['ADMINISTRATOR','HR_MANAGER','CEO','COO','DOO'];let query=`SELECT "id","email","role"::text AS role FROM "User" WHERE "organizationId"=$1 AND COALESCE("email",'')<>''`;const args:any[]=[auth.organizationId];if(audience==='CUSTOM'){query+=' AND "id"=ANY($2::text[])';args.push(custom)}else if(audience==='MANAGERS'){query+=' AND "role"::text=ANY($2::text[])';args.push(managerRoleNames)}else if(audience==='HR_ADMIN'){query+=' AND "role"::text=ANY($2::text[])';args.push(hrRoles)}const recipients=await prisma.$queryRawUnsafe<Array<{email:string}>>(query,...args);const emails=[...new Set(recipients.map(row=>clean(row.email,320).toLowerCase()).filter(Boolean))];await sendMail(emails,clean(payload.subject,240),clean(payload.message,12000));result={sent:true,recipientCount:emails.length,audience};
    } else if(action.actionType==='REQUEST_CODE_CHANGE'){
      const ticketId=`itagent-${randomUUID()}`;const approvalId=randomUUID();const handoffId=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "ITRemediationApproval" ("id","organizationId","legalEntityId","ticketId","requestedByUserId","actionType","summary","risk","changeClass","requiresApproval","status") VALUES ($1,$2,$3,$4,$5,'CODE_CHANGE',$6,'HIGH','NEW_SYSTEM_CHANGE',TRUE,'PENDING')`,approvalId,auth.organizationId,auth.legalEntityId??null,ticketId,auth.userId,clean(payload.summary||payload.request,3000));await prisma.$executeRawUnsafe(`INSERT INTO "ITAgentHandoff" ("id","organizationId","legalEntityId","ticketId","conversationId","employeeId","diagnosis","engineeringNeed","changeClass","status") VALUES ($1,$2,$3,$4,$5,$6,$7,'CODE_PATCH','NEW_SYSTEM_CHANGE','WAITING_APPROVAL') ON CONFLICT ("organizationId","ticketId") DO NOTHING`,handoffId,auth.organizationId,auth.legalEntityId??null,ticketId,action.conversationId,auth.userId,clean(payload.request,4000));finalStatus='WAITING_APPROVAL';result={ticketId,approvalId,handoffId,approvalRequired:true,codingWorkerConnected:Boolean(process.env.SULANDRA_GITHUB_TOKEN||process.env.GITHUB_TOKEN),message:(process.env.SULANDRA_GITHUB_TOKEN||process.env.GITHUB_TOKEN)?'Code change is queued behind administrator approval for the trusted coding worker.':'Code change is recorded and waiting for approval. The deployed Sulandra API does not yet have a GitHub coding-worker credential, so it will not fabricate a commit or deployment.'};
    }
    await prisma.$executeRawUnsafe(`UPDATE "ITAgentAction" SET "status"=$1,"result"=$2::jsonb,"executedByUserId"=$3,"executedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$4 AND "id"=$5`,finalStatus,JSON.stringify({...result,note:input.note||''}),auth.userId,auth.organizationId,action.id);res.json({data:{id:action.id,status:finalStatus,result}})}catch(error){next(error)}});
}
