import { randomBytes, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.ADMINISTRATIVE_ASSISTANT,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select Sulandra NMT Services first');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureAdmin=(a:AuthContext)=>{if(!adminRoles.has(a.role)&&!owner(a))throw httpError(403,'NMT dispatch administration access is required');entity(a);};
const text=(v:unknown,max=4000)=>typeof v==='string'?v.trim().slice(0,max):'';
const asObject=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const activeLifecycle=(m:Record<string,unknown>)=>String(m.serviceOperationsStatus||'')==='ACTIVE'&&String(m.referralStatus||'')==='ACTIVE'&&String(m.licensingStatus||'')==='ACTIVE';
const tripNumber=()=>`TRIP-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomBytes(4).toString('hex').toUpperCase()}`;
const vehicleSchema=z.object({vehicleNumber:z.string().trim().min(1).max(80),year:z.number().int().min(1980).max(2100).optional().nullable(),make:z.string().trim().max(120).optional().nullable(),model:z.string().trim().max(120).optional().nullable(),color:z.string().trim().max(80).optional().nullable(),vin:z.string().trim().max(80).optional().nullable(),licensePlate:z.string().trim().max(80).optional().nullable(),licenseState:z.string().trim().max(40).optional().nullable(),serviceLevels:z.array(z.enum(['AMBULATORY','WHEELCHAIR','BARIATRIC_WHEELCHAIR','STRETCHER','OTHER'])).min(1).default(['AMBULATORY']),wheelchairCapacity:z.number().int().min(0).max(20).default(0),ambulatoryCapacity:z.number().int().min(0).max(30).default(1),liftEquipped:z.boolean().default(false),bariatricCapable:z.boolean().default(false),inspectionExpiresAt:z.string().trim().max(20).optional().nullable(),registrationExpiresAt:z.string().trim().max(20).optional().nullable(),insuranceExpiresAt:z.string().trim().max(20).optional().nullable(),notes:z.string().trim().max(4000).optional().nullable()});
const driverSchema=z.object({userId:z.string().trim().max(120).optional().nullable(),displayName:z.string().trim().min(2).max(250),phone:z.string().trim().max(80).optional().nullable(),email:z.string().trim().email().max(250).optional().nullable(),licenseNumber:z.string().trim().max(120).optional().nullable(),licenseState:z.string().trim().max(40).optional().nullable(),licenseExpiresAt:z.string().trim().max(20).optional().nullable(),certifications:z.record(z.unknown()).optional().default({}),notes:z.string().trim().max(4000).optional().nullable()});
const scheduleSchema=z.object({scheduledPickupAt:z.string().datetime(),scheduledArrivalAt:z.string().datetime().optional().nullable(),driverId:z.string().trim().min(1).optional().nullable(),vehicleId:z.string().trim().min(1).optional().nullable(),dispatcherNotes:z.string().trim().max(5000).optional().nullable()});
const statusSchema=z.object({status:z.enum(['DISPATCHED','EN_ROUTE_TO_PICKUP','ARRIVED_PICKUP','RIDER_ON_BOARD','EN_ROUTE_TO_DESTINATION','ARRIVED_DESTINATION','COMPLETED','NO_SHOW','CANCELLED']),notes:z.string().trim().max(5000).optional().nullable(),reason:z.string().trim().max(5000).optional().nullable(),odometer:z.number().min(0).max(9999999).optional().nullable(),latitude:z.number().min(-90).max(90).optional().nullable(),longitude:z.number().min(-180).max(180).optional().nullable()});
async function lifecycle(prisma:PrismaClient,a:AuthContext){const rows=await prisma.$queryRawUnsafe<Array<{code:string;displayName:string;metadata:Record<string,unknown>}>>(`SELECT "code","displayName","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));const row=rows[0];if(!row)throw httpError(404,'Selected company was not found');if(row.code!=='NMT')throw httpError(409,'Select Sulandra NMT Services to use NMT dispatch');const metadata=asObject(row.metadata);return{...row,metadata,operational:activeLifecycle(metadata)};}
async function trip(prisma:PrismaClient,a:AuthContext,id:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT t.*,o."orderNumber",o."riderFirstName",o."riderLastName",o."pickupName",o."pickupStreet",o."pickupCity",o."pickupState",o."pickupPostalCode",o."pickupUnitRoom",o."dropoffName",o."dropoffStreet",o."dropoffCity",o."dropoffState",o."dropoffPostalCode",o."dropoffUnitRoom",o."serviceLevel",d."displayName" AS "driverName",d."userId" AS "driverUserId",v."vehicleNumber" FROM "NmtTrip" t JOIN "NmtTransportOrder" o ON o."id"=t."orderId" LEFT JOIN "NmtDriverProfile" d ON d."id"=t."driverId" LEFT JOIN "NmtVehicle" v ON v."id"=t."vehicleId" WHERE t."organizationId"=$1 AND t."legalEntityId"=$2 AND t."id"=$3 LIMIT 1`,a.organizationId,entity(a),id);if(!rows[0])throw httpError(404,'NMT trip was not found');return rows[0];}
async function event(prisma:PrismaClient,a:AuthContext,tripId:string,eventType:string,fromStatus:string|null,toStatus:string|null,details:Record<string,unknown>,lat?:number|null,long?:number|null){await prisma.$executeRawUnsafe(`INSERT INTO "NmtTripEvent"("id","organizationId","legalEntityId","tripId","actorUserId","eventType","fromStatus","toStatus","details","latitude","longitude") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,randomUUID(),a.organizationId,entity(a),tripId,a.userId,eventType,fromStatus,toStatus,JSON.stringify(details),lat??null,long??null);}
export const registerNmtDispatchRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/admin/nmt/vehicles',async(_req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);await lifecycle(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "NmtVehicle" WHERE "organizationId"=$1 AND "legalEntityId"=$2 ORDER BY "active" DESC,"vehicleNumber"`,a.organizationId,entity(a));res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/admin/nmt/vehicles',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);await lifecycle(prisma,a);const i=vehicleSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "NmtVehicle"("id","organizationId","legalEntityId","vehicleNumber","year","make","model","color","vin","licensePlate","licenseState","serviceLevels","wheelchairCapacity","ambulatoryCapacity","liftEquipped","bariatricCapable","inspectionExpiresAt","registrationExpiresAt","insuranceExpiresAt","notes","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::text[],$13,$14,$15,$16,$17::date,$18::date,$19::date,$20,$21) RETURNING *`,randomUUID(),a.organizationId,entity(a),i.vehicleNumber,i.year??null,i.make??null,i.model??null,i.color??null,i.vin??null,i.licensePlate??null,i.licenseState??null,i.serviceLevels,i.wheelchairCapacity,i.ambulatoryCapacity,i.liftEquipped,i.bariatricCapable,i.inspectionExpiresAt||null,i.registrationExpiresAt||null,i.insuranceExpiresAt||null,i.notes??null,a.userId);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/admin/nmt/drivers',async(_req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);await lifecycle(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "NmtDriverProfile" WHERE "organizationId"=$1 AND "legalEntityId"=$2 ORDER BY "active" DESC,"displayName"`,a.organizationId,entity(a));res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/admin/nmt/drivers',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);await lifecycle(prisma,a);const i=driverSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "NmtDriverProfile"("id","organizationId","legalEntityId","userId","displayName","phone","email","licenseNumber","licenseState","licenseExpiresAt","certifications","notes","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::date,$11::jsonb,$12,$13) RETURNING *`,randomUUID(),a.organizationId,entity(a),i.userId??null,i.displayName,i.phone??null,i.email??null,i.licenseNumber??null,i.licenseState??null,i.licenseExpiresAt||null,JSON.stringify(i.certifications),i.notes??null,a.userId);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/admin/nmt/trips',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);await lifecycle(prisma,a);const date=text(req.query.date,20);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT t.*,o."orderNumber",o."riderFirstName",o."riderLastName",o."pickupName",o."dropoffName",o."serviceLevel",d."displayName" AS "driverName",v."vehicleNumber" FROM "NmtTrip" t JOIN "NmtTransportOrder" o ON o."id"=t."orderId" LEFT JOIN "NmtDriverProfile" d ON d."id"=t."driverId" LEFT JOIN "NmtVehicle" v ON v."id"=t."vehicleId" WHERE t."organizationId"=$1 AND t."legalEntityId"=$2 AND ($3='' OR t."scheduledPickupAt"::date=$3::date) ORDER BY t."scheduledPickupAt"`,a.organizationId,entity(a),date);res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/admin/nmt/orders/:orderId/schedule',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const life=await lifecycle(prisma,a),i=scheduleSchema.parse(req.body);const orders=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "NmtTransportOrder" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.orderId);const o=orders[0];if(!o)throw httpError(404,'NMT order was not found');if(String(o.mode)==='OPERATIONAL'&&!life.operational)throw httpError(409,'Operational NMT trips remain blocked while NMT is pre-launch');if(String(o.mode)==='OPERATIONAL'&&!['ACCEPTED','SCHEDULED'].includes(String(o.status)))throw httpError(409,'Accept the NMT order before scheduling it');if(i.driverId){const d=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "NmtDriverProfile" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 AND "active"=TRUE LIMIT 1`,a.organizationId,entity(a),i.driverId);if(!d[0])throw httpError(404,'Active NMT driver was not found');}if(i.vehicleId){const v=await prisma.$queryRawUnsafe<Array<{id:string;serviceLevels:string[]}>>(`SELECT "id","serviceLevels" FROM "NmtVehicle" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 AND "active"=TRUE LIMIT 1`,a.organizationId,entity(a),i.vehicleId);if(!v[0])throw httpError(404,'Active NMT vehicle was not found');if(!v[0].serviceLevels.includes(String(o.serviceLevel)))throw httpError(409,'Selected vehicle is not configured for this transportation service level');}const id=randomUUID(),number=tripNumber();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "NmtTrip"("id","organizationId","legalEntityId","orderId","patientId","mode","status","tripNumber","scheduledPickupAt","scheduledArrivalAt","driverId","vehicleId","dispatcherUserId","dispatcherNotes") VALUES($1,$2,$3,$4,$5,$6,'SCHEDULED',$7,$8::timestamptz,$9::timestamptz,$10,$11,$12,$13) RETURNING *`,id,a.organizationId,entity(a),req.params.orderId,o.patientId??null,o.mode,number,i.scheduledPickupAt,i.scheduledArrivalAt??null,i.driverId??null,i.vehicleId??null,a.userId,i.dispatcherNotes??null);await prisma.$executeRawUnsafe(`UPDATE "NmtTransportOrder" SET "status"='SCHEDULED',"scheduledTripId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4`,id,a.organizationId,entity(a),req.params.orderId);await event(prisma,a,id,'TRIP_SCHEDULED',null,'SCHEDULED',{orderId:req.params.orderId,tripNumber:number,driverId:i.driverId??null,vehicleId:i.vehicleId??null});res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/nmt/my-trips',async(_req,res,next)=>{try{const a=authOf(res);entity(a);await lifecycle(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT t.*,o."orderNumber",o."riderFirstName",o."riderLastName",o."pickupName",o."pickupStreet",o."pickupCity",o."pickupState",o."pickupPostalCode",o."pickupUnitRoom",o."dropoffName",o."dropoffStreet",o."dropoffCity",o."dropoffState",o."dropoffPostalCode",o."dropoffUnitRoom",o."serviceLevel",v."vehicleNumber" FROM "NmtTrip" t JOIN "NmtDriverProfile" d ON d."id"=t."driverId" JOIN "NmtTransportOrder" o ON o."id"=t."orderId" LEFT JOIN "NmtVehicle" v ON v."id"=t."vehicleId" WHERE t."organizationId"=$1 AND t."legalEntityId"=$2 AND d."userId"=$3 AND t."status" NOT IN ('COMPLETED','CANCELLED','NO_SHOW') ORDER BY t."scheduledPickupAt"`,a.organizationId,entity(a),a.userId);res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/nmt/trips/:tripId/status',async(req,res,next)=>{try{const a=authOf(res);entity(a);await lifecycle(prisma,a);const i=statusSchema.parse(req.body),t=await trip(prisma,a,req.params.tripId);const admin=adminRoles.has(a.role)||owner(a),assigned=String(t.driverUserId||'')===a.userId;if(!admin&&!assigned)throw httpError(403,'This trip is not assigned to you');const from=String(t.status);const allowed:Record<string,string[]>={SCHEDULED:['DISPATCHED','CANCELLED'],DISPATCHED:['EN_ROUTE_TO_PICKUP','CANCELLED'],EN_ROUTE_TO_PICKUP:['ARRIVED_PICKUP','CANCELLED'],ARRIVED_PICKUP:['RIDER_ON_BOARD','NO_SHOW','CANCELLED'],RIDER_ON_BOARD:['EN_ROUTE_TO_DESTINATION'],EN_ROUTE_TO_DESTINATION:['ARRIVED_DESTINATION'],ARRIVED_DESTINATION:['COMPLETED']};if(!(allowed[from]||[]).includes(i.status))throw httpError(409,`Trip cannot move from ${from} to ${i.status}`);const timestampColumn:Record<string,string>={ARRIVED_PICKUP:'arrivedPickupAt',RIDER_ON_BOARD:'riderOnBoardAt',ARRIVED_DESTINATION:'arrivedDestinationAt',COMPLETED:'completedAt',NO_SHOW:'noShowAt',CANCELLED:'cancelledAt'};const column=timestampColumn[i.status];if(column)await prisma.$executeRawUnsafe(`UPDATE "NmtTrip" SET "status"=$1,"${column}"=NOW(),"driverNotes"=COALESCE($2,"driverNotes"),"cancellationReason"=CASE WHEN $1='CANCELLED' THEN $3 ELSE "cancellationReason" END,"noShowReason"=CASE WHEN $1='NO_SHOW' THEN $3 ELSE "noShowReason" END,"odometerStart"=CASE WHEN $1 IN ('EN_ROUTE_TO_PICKUP','DISPATCHED') AND $4::numeric IS NOT NULL THEN COALESCE("odometerStart",$4::numeric) ELSE "odometerStart" END,"odometerEnd"=CASE WHEN $1='COMPLETED' AND $4::numeric IS NOT NULL THEN $4::numeric ELSE "odometerEnd" END,"actualMiles"=CASE WHEN $1='COMPLETED' AND $4::numeric IS NOT NULL AND "odometerStart" IS NOT NULL THEN GREATEST(0,$4::numeric-"odometerStart") ELSE "actualMiles" END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "legalEntityId"=$6 AND "id"=$7`,i.status,i.notes??null,i.reason??null,i.odometer??null,a.organizationId,entity(a),req.params.tripId);else await prisma.$executeRawUnsafe(`UPDATE "NmtTrip" SET "status"=$1,"driverNotes"=COALESCE($2,"driverNotes"),"odometerStart"=CASE WHEN $1 IN ('EN_ROUTE_TO_PICKUP','DISPATCHED') AND $3::numeric IS NOT NULL THEN COALESCE("odometerStart",$3::numeric) ELSE "odometerStart" END,"updatedAt"=NOW() WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "id"=$6`,i.status,i.notes??null,i.odometer??null,a.organizationId,entity(a),req.params.tripId);await event(prisma,a,req.params.tripId,'TRIP_STATUS_CHANGED',from,i.status,{reason:i.reason??null,notes:i.notes??null,odometer:i.odometer??null},i.latitude,i.longitude);if(i.status==='COMPLETED')await prisma.$executeRawUnsafe(`UPDATE "NmtTransportOrder" SET "status"='COMPLETED',"updatedAt"=NOW() WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3`,a.organizationId,entity(a),t.orderId);res.json({data:{id:req.params.tripId,status:i.status}});}catch(e){next(e);}});
};
