import type express from 'express';
import type { PrismaClient } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:string;email?:string;legalEntityId?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
type ComplianceRow={id:string;requirementName:string;status:string;expirationDate:string|null;responsibleUserId:string|null;metadata:Record<string,unknown>};
const writeMethods=new Set(['POST','PUT','PATCH']);
const staffKeys=new Set(['assignedUserId','providerUserId','caseManagerUserId','primaryNurseUserId','clinicianUserId','staffUserId']);
const driverUserKeys=new Set(['driverUserId','assignedDriverUserId']);
const driverProfileKeys=new Set(['driverProfileId','driverId']);
const vehicleKeys=new Set(['vehicleId','assignedVehicleId']);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
function collect(value:unknown,keys:Set<string>,out=new Set<string>()):Set<string>{if(!value||typeof value!=='object')return out;if(Array.isArray(value)){for(const x of value)collect(x,keys,out);return out;}for(const [key,v] of Object.entries(value as Record<string,unknown>)){if(keys.has(key)&&typeof v==='string'&&v.trim())out.add(v.trim());if(v&&typeof v==='object')collect(v,keys,out);}return out;}
function expired(row:ComplianceRow){if(['EXPIRED','SUSPENDED'].includes(String(row.status)))return true;if(!row.expirationDate)return false;const d=new Date(String(row.expirationDate).slice(0,10)+'T23:59:59Z');return !Number.isNaN(d.getTime())&&d.getTime()<Date.now();}
function unverified(row:ComplianceRow){return ['PENDING_VERIFICATION','RENEWAL_IN_PROGRESS'].includes(String(row.status));}
async function rowsForStaff(prisma:PrismaClient,a:AuthContext,entityId:string,userIds:string[],sourceTable:string){if(!userIds.length)return[];return prisma.$queryRawUnsafe<ComplianceRow[]>(`SELECT "id","requirementName","status","expirationDate"::text,"responsibleUserId","metadata" FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "metadata"->>'sourceTable'=$3 AND "responsibleUserId"=ANY($4::text[]) AND "status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE')`,a.organizationId,entityId,sourceTable,userIds);}
async function rowsForSourceIds(prisma:PrismaClient,a:AuthContext,entityId:string,sourceTable:string,ids:string[],vehicleMode=false){if(!ids.length)return[];return prisma.$queryRawUnsafe<ComplianceRow[]>(`SELECT "id","requirementName","status","expirationDate"::text,"responsibleUserId","metadata" FROM "CompanyComplianceItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "metadata"->>'sourceTable'=$3 AND ("metadata"->>'sourceRecordId'=ANY($4::text[]) OR "metadata"->>'parentDriverProfileId'=ANY($4::text[]) OR ($5::boolean=TRUE AND "metadata"->>'vehicleId'=ANY($4::text[]))) AND "status" NOT IN ('CLOSED','SUPERSEDED','NOT_APPLICABLE')`,a.organizationId,entityId,sourceTable,ids,vehicleMode);}
function setWarning(res:express.Response,rows:ComplianceRow[]){const pending=rows.filter(unverified);if(!pending.length)return;res.setHeader('X-Sulandra-Compliance-Warning',pending.map(r=>r.requirementName).slice(0,5).join(' | '));}
function rejectIfExpired(rows:ComplianceRow[],label:string){const blockers=rows.filter(expired);if(blockers.length)throw httpError(409,`${label} assignment is blocked by expired or suspended compliance`,{blockers:blockers.map(r=>({id:r.id,requirementName:r.requirementName,status:r.status,expirationDate:r.expirationDate})),action:'Resolve the compliance item and underlying credential before assigning operational work.'});}
export const registerOperationalComplianceBoundary=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
  app.use('/api/home-health',async(req,res,next)=>{try{if(!writeMethods.has(req.method)||!/visit|schedule|episode|assignment/i.test(req.path))return next();const a=authOf(res),entityId=a.legalEntityId||String(req.headers['x-legal-entity-id']||'');if(!entityId)return next();const users=[...collect(req.body,staffKeys)];if(!users.length)return next();const rows=await rowsForStaff(prisma,a,entityId,users,'HomeHealthStaffProfile');rejectIfExpired(rows,'Home Health staff');setWarning(res,rows);next();}catch(e){next(e);}});
  app.use('/api/nmt',async(req,res,next)=>{try{if(!writeMethods.has(req.method)||!/trip|dispatch|schedule/i.test(req.path))return next();const a=authOf(res),entityId=a.legalEntityId||String(req.headers['x-legal-entity-id']||'');if(!entityId)return next();const driverUsers=[...collect(req.body,driverUserKeys)],driverProfiles=[...collect(req.body,driverProfileKeys)],vehicles=[...collect(req.body,vehicleKeys)];const rows=[...(await rowsForStaff(prisma,a,entityId,driverUsers,'NmtDriverProfile')),...(await rowsForSourceIds(prisma,a,entityId,'NmtDriverProfile',driverProfiles)),...(await rowsForSourceIds(prisma,a,entityId,'NmtVehicle',vehicles,true))];rejectIfExpired(rows,'NMT driver/vehicle');setWarning(res,rows);next();}catch(e){next(e);}});
  app.use('/api/admin/nmt',async(req,res,next)=>{try{if(!writeMethods.has(req.method)||!/trip|dispatch|schedule/i.test(req.path))return next();const a=authOf(res),entityId=a.legalEntityId||String(req.headers['x-legal-entity-id']||'');if(!entityId)return next();const driverUsers=[...collect(req.body,driverUserKeys)],driverProfiles=[...collect(req.body,driverProfileKeys)],vehicles=[...collect(req.body,vehicleKeys)];const rows=[...(await rowsForStaff(prisma,a,entityId,driverUsers,'NmtDriverProfile')),...(await rowsForSourceIds(prisma,a,entityId,'NmtDriverProfile',driverProfiles)),...(await rowsForSourceIds(prisma,a,entityId,'NmtVehicle',vehicles,true))];rejectIfExpired(rows,'NMT driver/vehicle');setWarning(res,rows);next();}catch(e){next(e);}});
};
