import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import type { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
type Check={key:string;category:string;label:string;status:'PASS'|'WARN'|'BLOCKED';details:string;actionPath?:string;metric?:number|string};
type EntityRow={id:string;code:string;displayName:string;legalName:string;status:string;isProvider:boolean;metadata:Record<string,unknown>};
const roles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','AUDITOR','HR_MANAGER','BILLING_SPECIALIST','RN','DELEGATING_NURSE','CEO','DOO']);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before Platform Readiness');return a.legalEntityId;};
const ensure=(a:AuthContext)=>{entity(a);if(!roles.has(String(a.role))&&!owner(a))throw httpError(403,'Platform readiness access is required');};
const q=(n:string)=>`"${n.replaceAll('"','""')}"`;
async function tableExists(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1) AS exists`,table);return rows[0]?.exists===true;}
async function count(prisma:PrismaClient,table:string,org:string,entityId:string,where='TRUE'){try{if(!(await tableExists(prisma,table)))return 0;const cols=await prisma.$queryRawUnsafe<Array<{column_name:string}>>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,table),names=new Set(cols.map(c=>c.column_name)),args:unknown[]=[];let scope='TRUE';if(names.has('organizationId')){args.push(org);scope=`"organizationId"=$${args.length}`;}if(names.has('legalEntityId')){args.push(entityId);scope+=` AND "legalEntityId"=$${args.length}`;}const rows=await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT count(*)::int AS count FROM ${q(table)} WHERE ${scope} AND (${where})`,...args);return Number(rows[0]?.count||0);}catch{return 0;}}
const moduleTables:Record<string,string[]>={
 SULANDRA_HEALTH:['LegalEntity','CompanyDocument','CompanyComplianceItem','EnterpriseWorkNotification','EnterpriseDataQualityIssue','SecurityAccessReviewCampaign','RevenueCycleServiceEvent'],
 SCLS:['SpirePatient','ClientEnrollment','ClientIntakeCase','SpireClinicalTask','SpireHouseShiftHandoff','SpireHouseLogEvent','SpireMedicationAdministrationQualification','SpireCarePlan','RevenueCycleServiceEvent'],
 HOME_HEALTH:['HomeHealthReferral','ClientIntakeCase','HomeHealthStaffProfile','HomeHealthEpisode','HomeHealthPlanOfCare','HomeHealthDisciplineOrder','HomeHealthVisit','RevenueCycleServiceEvent'],
 NMT:['NmtReferralFacility','NmtTransportOrder','NmtDriverProfile','NmtVehicle','NmtTrip','RevenueCycleServiceEvent']
};
async function entityChecks(prisma:PrismaClient,a:AuthContext,e:EntityRow):Promise<Check[]>{const checks:Check[]=[];const required=moduleTables[e.code]||moduleTables.SULANDRA_HEALTH;const missing:string[]=[];for(const table of required)if(!(await tableExists(prisma,table)))missing.push(table);checks.push({key:'required-tables',category:'Platform',label:'Required operating data model',status:missing.length?'BLOCKED':'PASS',details:missing.length?`Missing required tables: ${missing.join(', ')}`:`All ${required.length} required module tables are present.`});
 const m=e.metadata&&typeof e.metadata==='object'?e.metadata:{};if(e.code!=='SULANDRA_HEALTH'){const lifecycle={licensing:String(m.licensingStatus||'UNKNOWN'),provider:String(m.providerEnrollmentStatus||m.medicaidEnrollmentStatus||'UNKNOWN'),operations:String(m.serviceOperationsStatus||'UNKNOWN'),referrals:String(m.referralStatus||'UNKNOWN')},blocked=Object.entries(lifecycle).filter(([,v])=>!['ACTIVE','APPROVED','COMPLETE','ENROLLED','OPEN'].includes(v));checks.push({key:'entity-lifecycle',category:'Legal Entity',label:'Licensing / provider / operations lifecycle',status:blocked.length?'BLOCKED':'PASS',details:blocked.length?blocked.map(([k,v])=>`${k}: ${v}`).join(' · '):'Lifecycle metadata indicates operational readiness.'});}else checks.push({key:'entity-lifecycle',category:'Legal Entity',label:'Holding company governance lifecycle',status:e.status==='ACTIVE'?'PASS':'WARN',details:`Legal entity status: ${e.status}.`});
 const compliance=await count(prisma,'CompanyComplianceItem',a.organizationId,e.id,`"status" IN ('EXPIRED','SUSPENDED') OR ("expirationDate" IS NOT NULL AND "expirationDate"<CURRENT_DATE)`);checks.push({key:'compliance-blockers',category:'Compliance',label:'Expired / suspended compliance blockers',status:compliance?'BLOCKED':'PASS',details:compliance?`${compliance} active compliance blocker(s) require resolution.`:'No expired or suspended compliance blockers detected.',metric:compliance,actionPath:'/company-compliance.html'});
 const pendingEvidence=await count(prisma,'CompanyComplianceItem',a.organizationId,e.id,`"status"='PENDING_VERIFICATION'`);checks.push({key:'compliance-verification',category:'Compliance',label:'Pending compliance verification',status:pendingEvidence?'WARN':'PASS',details:pendingEvidence?`${pendingEvidence} compliance item(s) still require verification/evidence.`:'No pending compliance verification items.',metric:pendingEvidence,actionPath:'/compliance-evidence.html'});
 const critical=await count(prisma,'EnterpriseDataQualityIssue',a.organizationId,e.id,`"status" IN ('OPEN','ACKNOWLEDGED') AND "severity"='CRITICAL'`),high=await count(prisma,'EnterpriseDataQualityIssue',a.organizationId,e.id,`"status" IN ('OPEN','ACKNOWLEDGED') AND "severity"='HIGH'`);checks.push({key:'data-quality',category:'Data Quality',label:'Critical / high data-quality findings',status:critical?'BLOCKED':high?'WARN':'PASS',details:`${critical} critical · ${high} high unresolved finding(s).`,metric:critical+high,actionPath:'/data-quality.html'});
 const urgent=await count(prisma,'EnterpriseWorkNotification',a.organizationId,e.id,`"status" IN ('OPEN','READ') AND "priority" IN ('URGENT','CRITICAL')`);checks.push({key:'urgent-work',category:'Operations',label:'Urgent / critical open work',status:urgent?'WARN':'PASS',details:urgent?`${urgent} urgent/critical operational notification(s) are open.`:'No urgent/critical work notifications are open.',metric:urgent,actionPath:'/notifications.html'});
 const accessReviews=await count(prisma,'SecurityAccessReviewCampaign',a.organizationId,e.id,`"status"='IN_PROGRESS' AND ("dueAt" IS NULL OR "dueAt"<=NOW()+INTERVAL '30 days')`);checks.push({key:'access-review',category:'Security',label:'Open access-review campaigns',status:accessReviews?'WARN':'PASS',details:accessReviews?`${accessReviews} access review campaign(s) remain in progress.`:'No active access review campaigns require closure.',metric:accessReviews,actionPath:'/security-audit.html'});
 const held=await count(prisma,'RevenueCycleServiceEvent',a.organizationId,e.id,`"status"='HELD'`),review=await count(prisma,'RevenueCycleServiceEvent',a.organizationId,e.id,`"status"='REVIEW_REQUIRED'`);checks.push({key:'revenue-cycle',category:'Revenue Cycle',label:'Billing readiness queue',status:held?'WARN':'PASS',details:`${held} held · ${review} awaiting review service event(s).`,metric:held+review,actionPath:'/revenue-cycle.html'});
 if(e.code==='SCLS'){const overdue=await count(prisma,'SpireClinicalTask',a.organizationId,e.id,`"status" IN ('OPEN','IN_PROGRESS') AND "dueAt" IS NOT NULL AND "dueAt"<NOW()`),medExpired=await count(prisma,'SpireMedicationAdministrationQualification',a.organizationId,e.id,`"status" IN ('EXPIRED','SUSPENDED','REVOKED') OR ("expiresAt" IS NOT NULL AND "expiresAt"<NOW())`);checks.push({key:'scls-tasks',category:'SCLS',label:'Overdue residential/clinical tasks',status:overdue?'WARN':'PASS',details:overdue?`${overdue} SCLS task(s) are overdue.`:'No overdue SCLS tasks.',metric:overdue,actionPath:'/scls-tasks.html'});checks.push({key:'med-quals',category:'SCLS',label:'Medication administration qualifications',status:medExpired?'BLOCKED':'PASS',details:medExpired?`${medExpired} medication qualification(s) are expired/suspended/revoked.`:'No expired medication qualification records detected.',metric:medExpired,actionPath:'/spire-medication-qualifications.html'});}
 if(e.code==='HOME_HEALTH'){const referrals=await count(prisma,'HomeHealthReferral',a.organizationId,e.id,`"status" IN ('ACCEPTED','INTAKE_CREATED','REVIEW_REQUIRED')`),episodes=await count(prisma,'HomeHealthEpisode',a.organizationId,e.id,`"status" IN ('ACTIVE','ADMITTED','START_OF_CARE','OPEN')`),pocReview=await count(prisma,'HomeHealthPlanOfCare',a.organizationId,e.id,`"status" NOT IN ('SIGNED','ACTIVE','SUPERSEDED','CLOSED','DISCONTINUED')`);checks.push({key:'hh-soc',category:'Home Health',label:'Start-of-Care handoff queue',status:referrals?'WARN':'PASS',details:`${referrals} referral(s) are in accepted/intake/review workflow. ${episodes} active episode(s).`,metric:referrals,actionPath:'/home-health-start-of-care.html'});checks.push({key:'hh-poc',category:'Home Health',label:'Plan of Care review queue',status:pocReview?'WARN':'PASS',details:pocReview?`${pocReview} Plan of Care record(s) are not signed/active.`:'No unsigned/incomplete Plan of Care records detected.',metric:pocReview,actionPath:'/home-health.html'});}
 if(e.code==='NMT'){const openTrips=await count(prisma,'NmtTrip',a.organizationId,e.id,`"status" NOT IN ('COMPLETED','CANCELLED','NO_SHOW')`),orders=await count(prisma,'NmtTransportOrder',a.organizationId,e.id,`"status" IN ('RECEIVED','REVIEW_REQUIRED','ACCEPTED','SCHEDULED','IN_PROGRESS')`);checks.push({key:'nmt-dispatch',category:'NMT',label:'Transport order / trip queue',status:openTrips||orders?'WARN':'PASS',details:`${orders} open transport order(s) · ${openTrips} open trip(s).`,metric:orders+openTrips,actionPath:'/nmt-dispatch.html'});}
 return checks;}
export const registerPlatformReadinessRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;app.get('/api/platform-readiness',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);let entities:EntityRow[];if(owner(a))entities=await prisma.$queryRawUnsafe<EntityRow[]>(`SELECT "id","code","displayName","legalName","status","isProvider","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 ORDER BY "code"`,a.organizationId);else entities=await prisma.$queryRawUnsafe<EntityRow[]>(`SELECT "id","code","displayName","legalName","status","isProvider","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));const results=[];for(const e of entities){const checks=await entityChecks(prisma,a,e),blocked=checks.filter(c=>c.status==='BLOCKED').length,warnings=checks.filter(c=>c.status==='WARN').length;results.push({entity:e,checks,blocked,warnings,passed:checks.filter(c=>c.status==='PASS').length,structuralReady:checks.find(c=>c.key==='required-tables')?.status==='PASS',operationalReady:blocked===0});}const totals=results.reduce((s,r)=>({blocked:s.blocked+r.blocked,warnings:s.warnings+r.warnings,passed:s.passed+r.passed}),{blocked:0,warnings:0,passed:0});res.json({data:{generatedAt:new Date().toISOString(),enterpriseOwner:owner(a),selectedLegalEntityId:entity(a),totals,entities:results}});}catch(e){next(e);}});};
