import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const roles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const managers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.RN,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select SCLS before using residential tasks');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const elevated=(a:AuthContext)=>owner(a)||managers.has(a.role)||a.role===UserRole.AUDITOR;
const canCreate=(a:AuthContext)=>owner(a)||managers.has(a.role)||a.role===UserRole.HOUSE_MANAGER;
const ensure=(a:AuthContext)=>{entity(a);if(!roles.has(a.role)&&!owner(a))throw httpError(403,'SCLS task access is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
async function ensureScls(prisma:PrismaClient,a:AuthContext){const rows=await prisma.$queryRawUnsafe<Array<{code:string}>>(`SELECT "code" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));if(rows[0]?.code!=='SCLS')throw httpError(409,'Select Sulandra Community Living Services (SCLS)');}
async function homeAllowed(prisma:PrismaClient,a:AuthContext,homeId:string|null){if(!homeId||elevated(a))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeHomeAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "homeId"=$4) AS allowed`,a.organizationId,entity(a),a.userId,homeId);return rows[0]?.allowed===true;}
async function clientAllowed(prisma:PrismaClient,a:AuthContext,clientId:string|null){if(!clientId||elevated(a))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "clientId"=$4 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,entity(a),a.userId,clientId);return rows[0]?.allowed===true;}
async function task(prisma:PrismaClient,a:AuthContext,id:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireClinicalTask" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),id),row=rows[0];if(!row)throw httpError(404,'SCLS task was not found');if(!(await homeAllowed(prisma,a,row.homeId?String(row.homeId):null))||!(await clientAllowed(prisma,a,row.clientId?String(row.clientId):null)))throw httpError(403,'This task is outside your assigned SCLS scope');return row;}
async function event(prisma:PrismaClient,a:AuthContext,taskId:string,eventType:string,fromStatus:string|null,toStatus:string|null,comment:string|null,metadata:Record<string,unknown>={}){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalTaskEvent"("id","organizationId","legalEntityId","taskId","eventType","fromStatus","toStatus","actorUserId","comment","metadata") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,randomUUID(),a.organizationId,entity(a),taskId,eventType,fromStatus,toStatus,a.userId,comment,JSON.stringify(metadata));}
const createSchema=z.object({homeId:z.string().trim().max(120).optional().nullable(),clientId:z.string().trim().max(120).optional().nullable(),taskType:z.string().trim().min(1).max(120),title:z.string().trim().min(2).max(300),instructions:z.string().trim().max(5000).optional().nullable(),priority:z.enum(['ROUTINE','HIGH','URGENT']).default('ROUTINE'),dueAt:z.string().datetime().optional().nullable(),assignedUserId:z.string().trim().max(120).optional().nullable()});
const actionSchema=z.object({action:z.enum(['START','COMPLETE','CANCEL','REOPEN','ASSIGN','COMMENT']),comment:z.string().trim().max(5000).optional().nullable(),assignedUserId:z.string().trim().max(120).optional().nullable()});

export const registerSclsTaskRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/scls/tasks',async(req,res,next)=>{try{const a=authOf(res);ensure(a);await ensureScls(prisma,a);const homeId=clean(req.query.homeId,120),status=clean(req.query.status,40),mine=String(req.query.mine||'')==='true';const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT t.*,p."firstName",p."preferredName",p."lastName",h."name" AS "homeName",COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e."createdAt" DESC) FROM "SpireClinicalTaskEvent" e WHERE e."taskId"=t."id"),'[]'::jsonb) AS events FROM "SpireClinicalTask" t LEFT JOIN "SpirePatient" p ON p."organizationId"=t."organizationId" AND p."id"=t."clientId" LEFT JOIN "SpireHome" h ON h."organizationId"=t."organizationId" AND h."id"=t."homeId" WHERE t."organizationId"=$1 AND t."legalEntityId"=$2 AND ($3='' OR t."homeId"=$3) AND ($4='' OR t."status"=$4) AND ($5::boolean=FALSE OR t."assignedUserId"=$6) ORDER BY CASE t."status" WHEN 'OPEN' THEN 0 WHEN 'IN_PROGRESS' THEN 1 ELSE 2 END,CASE t."priority" WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,t."dueAt" NULLS LAST,t."createdAt" DESC LIMIT 1000`,a.organizationId,entity(a),homeId,status,mine,a.userId);const allowed=[];for(const row of rows)if((await homeAllowed(prisma,a,row.homeId?String(row.homeId):null))&&(await clientAllowed(prisma,a,row.clientId?String(row.clientId):null)))allowed.push(row);res.json({data:allowed});}catch(e){next(e);}});
 app.post('/api/scls/tasks',async(req,res,next)=>{try{const a=authOf(res);ensure(a);await ensureScls(prisma,a);if(!canCreate(a))throw httpError(403,'Task creation requires house-manager or SCLS management access');const i=createSchema.parse(req.body);if(!i.homeId&&!i.clientId)throw httpError(400,'A house or resident is required');if(i.homeId&&!(await homeAllowed(prisma,a,i.homeId)))throw httpError(403,'You cannot create tasks for this home');if(i.clientId&&!(await clientAllowed(prisma,a,i.clientId)))throw httpError(403,'You cannot create tasks for this client');if(i.clientId){const enrolled=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "ClientEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "clientId"=$3 AND "status" IN ('PENDING','ACTIVE','PAUSED') LIMIT 1`,a.organizationId,entity(a),i.clientId);if(!enrolled[0])throw httpError(409,'Client is not actively enrolled with SCLS');}const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalTask"("id","organizationId","legalEntityId","clientId","homeId","taskType","title","instructions","priority","status","dueAt","assignedUserId","createdByUserId") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'OPEN',$10::timestamptz,$11,$12)`,id,a.organizationId,entity(a),i.clientId??null,i.homeId??null,i.taskType,i.title,i.instructions??null,i.priority,i.dueAt??null,i.assignedUserId??null,a.userId);await event(prisma,a,id,'CREATED',null,'OPEN',i.instructions??null,{homeId:i.homeId??null,clientId:i.clientId??null,assignedUserId:i.assignedUserId??null});await audit?.(a,'CREATE_SCLS_TASK','SpireClinicalTask',id,{homeId:i.homeId??null,clientId:i.clientId??null,title:i.title});res.status(201).json({data:{id,status:'OPEN'}});}catch(e){next(e);}});
 app.post('/api/scls/tasks/:taskId/action',async(req,res,next)=>{try{const a=authOf(res);ensure(a);await ensureScls(prisma,a);if(a.role===UserRole.AUDITOR)throw httpError(403,'Auditor task access is read-only');const current=await task(prisma,a,req.params.taskId),i=actionSchema.parse(req.body),from=String(current.status),comment=i.comment??null;let to=from,eventType='COMMENT';if(i.action==='START'){if(from!=='OPEN')throw httpError(409,'Only open tasks can be started');to='IN_PROGRESS';eventType='STARTED';}if(i.action==='COMPLETE'){if(!['OPEN','IN_PROGRESS'].includes(from))throw httpError(409,'Only open or in-progress tasks can be completed');to='COMPLETED';eventType='COMPLETED';}if(i.action==='CANCEL'){if(!canCreate(a))throw httpError(403,'Task cancellation requires house-manager or SCLS management access');if(['COMPLETED','CANCELLED'].includes(from))throw httpError(409,'This task is already closed');to='CANCELLED';eventType='CANCELLED';}if(i.action==='REOPEN'){if(!managers.has(a.role)&&!owner(a))throw httpError(403,'Task reopening requires SCLS management access');if(!['COMPLETED','CANCELLED'].includes(from))throw httpError(409,'Only closed tasks can be reopened');to='OPEN';eventType='REOPENED';}if(i.action==='ASSIGN'){if(!canCreate(a))throw httpError(403,'Task assignment requires house-manager or SCLS management access');if(!i.assignedUserId)throw httpError(400,'assignedUserId is required');eventType='ASSIGNED';await prisma.$executeRawUnsafe(`UPDATE "SpireClinicalTask" SET "assignedUserId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4`,i.assignedUserId,a.organizationId,entity(a),req.params.taskId);await event(prisma,a,req.params.taskId,eventType,from,from,comment,{assignedUserId:i.assignedUserId});return void res.json({data:{id:req.params.taskId,status:from,assignedUserId:i.assignedUserId}});}if(i.action==='COMMENT'){eventType='COMMENT';await event(prisma,a,req.params.taskId,eventType,from,from,comment,{});return void res.json({data:{id:req.params.taskId,status:from}});}await prisma.$executeRawUnsafe(`UPDATE "SpireClinicalTask" SET "status"=$1,"completedAt"=CASE WHEN $1='COMPLETED' THEN NOW() ELSE NULL END,"completedByUserId"=CASE WHEN $1='COMPLETED' THEN $2 ELSE NULL END,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "id"=$5`,to,a.userId,a.organizationId,entity(a),req.params.taskId);await event(prisma,a,req.params.taskId,eventType,from,to,comment,{});await audit?.(a,`SCLS_TASK_${i.action}`,'SpireClinicalTask',req.params.taskId,{fromStatus:from,toStatus:to,comment});res.json({data:{id:req.params.taskId,status:to}});}catch(e){next(e);}});
};
