import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const accessRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const managementRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.RN,UserRole.CEO,UserRole.DOO]);
const staffManagementRoles=new Set<UserRole>([...managementRoles,UserRole.HOUSE_MANAGER]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select Sulandra Community Living Services before using Residential Operations');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const elevated=(a:AuthContext)=>owner(a)||managementRoles.has(a.role)||a.role===UserRole.AUDITOR;
const ensure=(a:AuthContext)=>{entity(a);if(!accessRoles.has(a.role)&&!owner(a))throw httpError(403,'SCLS residential access is required');};
const ensureManager=(a:AuthContext)=>{ensure(a);if(!managementRoles.has(a.role)&&!owner(a))throw httpError(403,'Residential management access is required');};
const ensureStaffManager=(a:AuthContext)=>{ensure(a);if(!staffManagementRoles.has(a.role)&&!owner(a))throw httpError(403,'House staff management access is required');};
const clean=(v:unknown,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
async function context(prisma:PrismaClient,a:AuthContext){const rows=await prisma.$queryRawUnsafe<Array<{id:string;code:string;displayName:string;metadata:Record<string,unknown>}>>(`SELECT "id","code","displayName","metadata" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));const row=rows[0];if(!row)throw httpError(404,'Selected company was not found');if(row.code!=='SCLS')throw httpError(409,'Select Sulandra Community Living Services (SCLS) to use Residential Operations');return row;}
async function canAccessHome(prisma:PrismaClient,a:AuthContext,homeId:string){if(elevated(a))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT (EXISTS(SELECT 1 FROM "SpireHome" h WHERE h."organizationId"=$1 AND h."legalEntityId"=$2 AND h."id"=$4 AND h."managerUserId"=$3 AND h."active"=TRUE) OR EXISTS(SELECT 1 FROM "SpireEmployeeHomeAssignment" e WHERE e."organizationId"=$1 AND e."legalEntityId"=$2 AND e."userId"=$3 AND e."homeId"=$4)) AS allowed`,a.organizationId,entity(a),a.userId,homeId);return rows[0]?.allowed===true;}
async function requireHome(prisma:PrismaClient,a:AuthContext,homeId:string){ensure(a);await context(prisma,a);if(!(await canAccessHome(prisma,a,homeId)))throw httpError(403,'This SCLS home is outside your assigned residential scope');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireHome" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),homeId);if(!rows[0])throw httpError(404,'SCLS home was not found');return rows[0];}
const homeSchema=z.object({name:z.string().trim().min(2).max(250),address:z.string().trim().max(1000).optional().nullable(),homeType:z.enum(['GROUP_HOME','SHARED_LIVING','SUPPORTED_LIVING','RESPITE','OTHER']).default('GROUP_HOME'),phone:z.string().trim().max(80).optional().nullable(),capacity:z.number().int().min(1).max(100).optional().nullable(),managerUserId:z.string().trim().max(120).optional().nullable(),timezone:z.string().trim().max(100).default('America/New_York'),emergencyInstructions:z.string().trim().max(10000).optional().nullable(),houseNotes:z.string().trim().max(10000).optional().nullable()});
const placementSchema=z.object({patientId:z.string().trim().min(1).max(120),roomLabel:z.string().trim().max(120).optional().nullable(),bedLabel:z.string().trim().max(120).optional().nullable(),placementNotes:z.string().trim().max(5000).optional().nullable(),startsAt:z.string().datetime().optional().nullable(),primary:z.boolean().default(true)});
const staffSchema=z.object({userId:z.string().trim().min(1).max(120)});
const handoffSchema=z.object({shiftType:z.enum(['DAY','EVENING','NIGHT','CUSTOM']),shiftStart:z.string().datetime(),shiftEnd:z.string().datetime().optional().nullable(),staffingSummary:z.string().trim().max(10000).optional().nullable(),residentSummary:z.string().trim().max(15000).optional().nullable(),medicationExceptions:z.string().trim().max(10000).optional().nullable(),healthChanges:z.string().trim().max(10000).optional().nullable(),behaviorSafetyChanges:z.string().trim().max(10000).optional().nullable(),appointmentsTransportation:z.string().trim().max(10000).optional().nullable(),unfinishedTasks:z.string().trim().max(10000).optional().nullable(),houseEnvironment:z.string().trim().max(10000).optional().nullable(),followUpRequired:z.string().trim().max(10000).optional().nullable(),status:z.enum(['DRAFT','SIGNED']).default('DRAFT'),signatureAttestation:z.string().trim().max(4000).optional().nullable()});
const logSchema=z.object({eventType:z.enum(['SHIFT_NOTE','HOUSE_ACTIVITY','APPOINTMENT','TRANSPORTATION','HEALTH_CHANGE','BEHAVIOR_SAFETY','MEDICATION_EXCEPTION','MAINTENANCE','STAFFING','EMERGENCY','OTHER']),occurredAt:z.string().datetime().optional().nullable(),title:z.string().trim().min(2).max(300),details:z.string().trim().min(2).max(15000),residentId:z.string().trim().max(120).optional().nullable(),severity:z.enum(['INFO','WATCH','HIGH','CRITICAL']).default('INFO'),requiresFollowUp:z.boolean().default(false),followUpOwnerUserId:z.string().trim().max(120).optional().nullable()});
async function residentSnapshot(prisma:PrismaClient,a:AuthContext,patientId:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT p."id",p."medicalRecordNumber",p."firstName",p."lastName",p."preferredName",p."dateOfBirth",
 COALESCE((SELECT jsonb_agg(jsonb_build_object('label',f."label",'severity',f."severity",'details',f."details") ORDER BY CASE f."severity" WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,f."createdAt" DESC) FROM "SpirePatientFlag" f WHERE f."organizationId"=p."organizationId" AND f."patientId"=p."id" AND f."active"=TRUE),'[]'::jsonb) AS flags,
 (SELECT jsonb_build_object('temperature',v."temperature",'pulse',v."pulse",'respirations',v."respirations",'systolic',v."systolic",'diastolic',v."diastolic",'spo2',v."spo2",'weight',v."weight",'oxygen',v."oxygen",'recordedAt',v."recordedAt") FROM "SpireVitalSign" v WHERE v."organizationId"=p."organizationId" AND v."patientId"=p."id" ORDER BY v."recordedAt" DESC LIMIT 1) AS "latestVitals",
 COALESCE((SELECT jsonb_agg(jsonb_build_object('id',m."id",'name',m."name",'dose',m."dose",'route',m."route",'frequency',m."frequency",'instructions',m."instructions",'dueTimes',m."dueTimes",'schedules',COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledTime',s."scheduledTime",'windowBeforeMinutes',s."windowBeforeMinutes",'windowAfterMinutes',s."windowAfterMinutes") ORDER BY s."scheduledTime") FROM "SpireMedicationSchedule" s WHERE s."organizationId"=m."organizationId" AND s."medicationOrderId"=m."id" AND s."active"=TRUE),'[]'::jsonb),'administrations',COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledFor',ma."scheduledFor",'status',ma."status",'administeredAt',ma."administeredAt",'administeredById',ma."administeredById") ORDER BY ma."createdAt") FROM "SpireMedicationAdministrationEvent" ma WHERE ma."organizationId"=m."organizationId" AND ma."medicationOrderId"=m."id" AND COALESCE(ma."scheduledFor",ma."createdAt")::date=CURRENT_DATE),'[]'::jsonb))) FROM "SpireMedicationOrder" m WHERE m."organizationId"=p."organizationId" AND m."patientId"=p."id" AND m."status"='ACTIVE'),'[]'::jsonb) AS medications,
 COALESCE((SELECT jsonb_agg(jsonb_build_object('id',d."id",'dueAt',d."dueAt",'reason',d."reason",'templateTitle',t."title") ORDER BY d."dueAt") FROM "SpireClinicalReassessmentDue" d LEFT JOIN "SpireAssessmentTemplate" t ON t."id"=d."assessmentTemplateId" AND t."organizationId"=d."organizationId" WHERE d."organizationId"=p."organizationId" AND d."patientId"=p."id" AND d."status"='OPEN' AND d."dueAt"<NOW()+INTERVAL '24 hours'),'[]'::jsonb) AS "dueAssessments",
 (SELECT jsonb_build_object('id',cp."id",'status',cp."status",'title',cp."title",'annualReviewDate',cp."annualReviewDate") FROM "SpireCarePlan" cp WHERE cp."organizationId"=p."organizationId" AND cp."legalEntityId"=$3 AND cp."patientId"=p."id" ORDER BY CASE cp."status" WHEN 'ACTIVE' THEN 0 ELSE 1 END,cp."version" DESC LIMIT 1) AS "carePlan"
 FROM "SpirePatient" p WHERE p."organizationId"=$1 AND p."id"=$2 LIMIT 1`,a.organizationId,patientId,entity(a));return rows[0]||null;}

export const registerSclsResidentialRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/scls/residential/context',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);const company=await context(prisma,a);res.json({data:{company,role:a.role,elevated:elevated(a),canManageStaff:owner(a)||staffManagementRoles.has(a.role)}});}catch(e){next(e);}});
 app.get('/api/scls/residential/homes',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);await context(prisma,a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT h.*,
 (SELECT count(*)::int FROM "SpirePatientHomeAssignment" p WHERE p."organizationId"=h."organizationId" AND p."legalEntityId"=h."legalEntityId" AND p."homeId"=h."id" AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS "residentCount",
 (SELECT count(*)::int FROM "SpireEmployeeHomeAssignment" e WHERE e."organizationId"=h."organizationId" AND e."legalEntityId"=h."legalEntityId" AND e."homeId"=h."id") AS "staffCount",
 (SELECT count(*)::int FROM "SpireClinicalTask" t WHERE t."organizationId"=h."organizationId" AND t."homeId"=h."id" AND t."status" IN ('OPEN','IN_PROGRESS')) AS "openTaskCount"
 FROM "SpireHome" h WHERE h."organizationId"=$1 AND h."legalEntityId"=$2 AND h."active"=TRUE AND ($3::boolean=TRUE OR h."managerUserId"=$4 OR EXISTS(SELECT 1 FROM "SpireEmployeeHomeAssignment" a WHERE a."organizationId"=h."organizationId" AND a."legalEntityId"=h."legalEntityId" AND a."userId"=$4 AND a."homeId"=h."id")) ORDER BY h."name"`,a.organizationId,entity(a),elevated(a),a.userId);res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);await context(prisma,a);const i=homeSchema.parse(req.body),id=randomUUID();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireHome"("id","organizationId","legalEntityId","name","address","homeType","phone","capacity","managerUserId","timezone","emergencyInstructions","houseNotes","active") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,TRUE) RETURNING *`,id,a.organizationId,entity(a),i.name,i.address??null,i.homeType,i.phone??null,i.capacity??null,i.managerUserId??null,i.timezone,i.emergencyInstructions??null,i.houseNotes??null);await audit?.(a,'CREATE_SCLS_HOME','SpireHome',id,{name:i.name});res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.get('/api/scls/residential/homes/:homeId',async(req,res,next)=>{try{const a=authOf(res);const home=await requireHome(prisma,a,req.params.homeId);const placements=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT pa."patientId",pa."roomLabel",pa."bedLabel",pa."placementNotes",pa."startsAt",pa."primary" FROM "SpirePatientHomeAssignment" pa JOIN "ClientEnrollment" ce ON ce."organizationId"=pa."organizationId" AND ce."legalEntityId"=pa."legalEntityId" AND ce."clientId"=pa."patientId" AND ce."status" IN ('PENDING','ACTIVE','PAUSED') WHERE pa."organizationId"=$1 AND pa."legalEntityId"=$2 AND pa."homeId"=$3 AND (pa."endsAt" IS NULL OR pa."endsAt">NOW()) ORDER BY pa."primary" DESC,pa."startsAt"`,a.organizationId,entity(a),req.params.homeId);const residents=[];for(const placement of placements){const patient=await residentSnapshot(prisma,a,String(placement.patientId));if(patient)residents.push({...patient,placement});}const [staff,tasks,handoffs,logs,appointments]=await Promise.all([
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireEmployeeHomeAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "homeId"=$3 ORDER BY "assignedAt"`,a.organizationId,entity(a),req.params.homeId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireClinicalTask" WHERE "organizationId"=$1 AND ("homeId"=$2 OR "clientId"=ANY($3::text[])) AND "status" IN ('OPEN','IN_PROGRESS') ORDER BY CASE "priority" WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,"dueAt" NULLS LAST,"createdAt"`,a.organizationId,req.params.homeId,placements.map(x=>String(x.patientId))),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireHouseShiftHandoff" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "homeId"=$3 ORDER BY "shiftStart" DESC LIMIT 30`,a.organizationId,entity(a),req.params.homeId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireHouseLogEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "homeId"=$3 ORDER BY "occurredAt" DESC LIMIT 200`,a.organizationId,entity(a),req.params.homeId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT a."id",a."patientId",a."startsAt",a."endsAt",a."status",a."appointmentType",a."locationId",p."firstName",p."preferredName",p."lastName" FROM "SpireAppointment" a JOIN "SpirePatient" p ON p."organizationId"=a."organizationId" AND p."id"=a."patientId" WHERE a."organizationId"=$1 AND a."patientId"=ANY($2::text[]) AND a."startsAt">=NOW() AND a."startsAt"<NOW()+INTERVAL '7 days' ORDER BY a."startsAt"`,a.organizationId,placements.map(x=>String(x.patientId)))
 ]);res.json({data:{home,residents,staff,tasks,handoffs,logs,appointments}});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes/:homeId/residents',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);await requireHome(prisma,a,req.params.homeId);const i=placementSchema.parse(req.body);const enrolled=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "ClientEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "clientId"=$3 AND "status" IN ('PENDING','ACTIVE','PAUSED') LIMIT 1`,a.organizationId,entity(a),i.patientId);if(!enrolled[0])throw httpError(409,'The client must have an active SCLS enrollment before residential placement');if(i.primary)await prisma.$executeRawUnsafe(`UPDATE "SpirePatientHomeAssignment" SET "endsAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "primary"=TRUE AND ("endsAt" IS NULL OR "endsAt">NOW())`,a.organizationId,entity(a),i.patientId);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpirePatientHomeAssignment"("id","organizationId","legalEntityId","patientId","homeId","primary","startsAt","roomLabel","bedLabel","placementNotes") VALUES($1,$2,$3,$4,$5,$6,COALESCE($7::timestamptz,NOW()),$8,$9,$10)`,id,a.organizationId,entity(a),i.patientId,req.params.homeId,i.primary,i.startsAt??null,i.roomLabel??null,i.bedLabel??null,i.placementNotes??null);await audit?.(a,'PLACE_SCLS_RESIDENT','SpirePatientHomeAssignment',id,{homeId:req.params.homeId,patientId:i.patientId,roomLabel:i.roomLabel??null});res.status(201).json({data:{id,patientId:i.patientId}});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes/:homeId/residents/:patientId/end',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);await requireHome(prisma,a,req.params.homeId);const reason=clean(req.body?.reason,3000)||null;const count=await prisma.$executeRawUnsafe(`UPDATE "SpirePatientHomeAssignment" SET "endsAt"=NOW(),"placementNotes"=CASE WHEN $1::text IS NULL THEN "placementNotes" ELSE concat_ws(E'\n',"placementNotes",concat('Placement ended: ',$1)) END,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "homeId"=$4 AND "patientId"=$5 AND ("endsAt" IS NULL OR "endsAt">NOW())`,reason,a.organizationId,entity(a),req.params.homeId,req.params.patientId);if(!count)throw httpError(404,'Active residential placement was not found');await audit?.(a,'END_SCLS_RESIDENT_PLACEMENT','SpirePatientHomeAssignment',req.params.patientId,{homeId:req.params.homeId,reason});res.json({data:{patientId:req.params.patientId,ended:true}});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes/:homeId/staff',async(req,res,next)=>{try{const a=authOf(res);ensureStaffManager(a);await requireHome(prisma,a,req.params.homeId);const i=staffSchema.parse(req.body);const existing=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireEmployeeHomeAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "homeId"=$4 LIMIT 1`,a.organizationId,entity(a),i.userId,req.params.homeId);if(existing[0])return void res.json({data:{id:existing[0].id,existing:true}});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireEmployeeHomeAssignment"("id","organizationId","legalEntityId","userId","homeId","assignedByUserId") VALUES($1,$2,$3,$4,$5,$6)`,id,a.organizationId,entity(a),i.userId,req.params.homeId,a.userId);await audit?.(a,'ASSIGN_SCLS_HOME_STAFF','SpireEmployeeHomeAssignment',id,{homeId:req.params.homeId,userId:i.userId});res.status(201).json({data:{id}});}catch(e){next(e);}});
 app.delete('/api/scls/residential/homes/:homeId/staff/:userId',async(req,res,next)=>{try{const a=authOf(res);ensureStaffManager(a);await requireHome(prisma,a,req.params.homeId);const count=await prisma.$executeRawUnsafe(`DELETE FROM "SpireEmployeeHomeAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "homeId"=$3 AND "userId"=$4`,a.organizationId,entity(a),req.params.homeId,req.params.userId);if(!count)throw httpError(404,'Home staff assignment was not found');await audit?.(a,'REMOVE_SCLS_HOME_STAFF','SpireEmployeeHomeAssignment',req.params.userId,{homeId:req.params.homeId});res.json({data:{userId:req.params.userId,removed:true}});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes/:homeId/handoffs',async(req,res,next)=>{try{const a=authOf(res);await requireHome(prisma,a,req.params.homeId);if(a.role===UserRole.AUDITOR)throw httpError(403,'Auditor access is read-only');const i=handoffSchema.parse(req.body);if(i.status==='SIGNED'&&(!i.signatureAttestation||i.signatureAttestation.length<10))throw httpError(400,'Signature attestation is required to sign a shift handoff');const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireHouseShiftHandoff"("id","organizationId","legalEntityId","homeId","shiftType","shiftStart","shiftEnd","status","staffingSummary","residentSummary","medicationExceptions","healthChanges","behaviorSafetyChanges","appointmentsTransportation","unfinishedTasks","houseEnvironment","followUpRequired","createdByUserId","signedByUserId","signedAt","signatureAttestation") VALUES($1,$2,$3,$4,$5,$6::timestamptz,$7::timestamptz,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,CASE WHEN $8='SIGNED' THEN $18 ELSE NULL END,CASE WHEN $8='SIGNED' THEN NOW() ELSE NULL END,$19)`,id,a.organizationId,entity(a),req.params.homeId,i.shiftType,i.shiftStart,i.shiftEnd??null,i.status,i.staffingSummary??null,i.residentSummary??null,i.medicationExceptions??null,i.healthChanges??null,i.behaviorSafetyChanges??null,i.appointmentsTransportation??null,i.unfinishedTasks??null,i.houseEnvironment??null,i.followUpRequired??null,a.userId,i.signatureAttestation??null);await audit?.(a,'CREATE_SCLS_SHIFT_HANDOFF','SpireHouseShiftHandoff',id,{homeId:req.params.homeId,status:i.status,shiftType:i.shiftType});res.status(201).json({data:{id,status:i.status}});}catch(e){next(e);}});
 app.post('/api/scls/residential/homes/:homeId/logs',async(req,res,next)=>{try{const a=authOf(res);await requireHome(prisma,a,req.params.homeId);if(a.role===UserRole.AUDITOR)throw httpError(403,'Auditor access is read-only');const i=logSchema.parse(req.body),id=randomUUID();if(i.residentId){const placement=await prisma.$queryRawUnsafe<Array<{patientId:string}>>(`SELECT "patientId" FROM "SpirePatientHomeAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "homeId"=$3 AND "patientId"=$4 AND ("endsAt" IS NULL OR "endsAt">NOW()) LIMIT 1`,a.organizationId,entity(a),req.params.homeId,i.residentId);if(!placement[0])throw httpError(409,'Resident is not currently placed in this home');}await prisma.$executeRawUnsafe(`INSERT INTO "SpireHouseLogEvent"("id","organizationId","legalEntityId","homeId","eventType","occurredAt","title","details","residentId","severity","requiresFollowUp","followUpOwnerUserId","createdByUserId") VALUES($1,$2,$3,$4,$5,COALESCE($6::timestamptz,NOW()),$7,$8,$9,$10,$11,$12,$13)`,id,a.organizationId,entity(a),req.params.homeId,i.eventType,i.occurredAt??null,i.title,i.details,i.residentId??null,i.severity,i.requiresFollowUp,i.followUpOwnerUserId??null,a.userId);await audit?.(a,'CREATE_SCLS_HOUSE_LOG','SpireHouseLogEvent',id,{homeId:req.params.homeId,eventType:i.eventType,residentId:i.residentId??null,severity:i.severity});res.status(201).json({data:{id}});}catch(e){next(e);}});
};
