import { createHash, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import type { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
type FeedItem={source:string;id:string;actorUserId:string|null;actorEmail:string|null;action:string;resourceType:string|null;resourceId:string|null;patientId:string|null;timestamp:string;details:unknown};
type JsonRow={data:Record<string,unknown>};
const readRoles=new Set(['ADMINISTRATOR','PROGRAM_MANAGER','AUDITOR','HR_MANAGER','CEO','DOO']);
const writeRoles=new Set(['ADMINISTRATOR','HR_MANAGER','PROGRAM_MANAGER','CEO','DOO']);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening Security & Audit');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureRead=(a:AuthContext)=>{entity(a);if(!readRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Security & Audit access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writeRoles.has(String(a.role))&&!owner(a))throw httpError(403,'Security access-review administration is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const q=(name:string)=>`"${name.replaceAll('"','""')}"`;
const csvCell=(v:unknown)=>{const s=typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;};
async function tableExists(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{exists:boolean}>>(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1) AS exists`,table);return rows[0]?.exists===true;}
async function tableColumns(prisma:PrismaClient,table:string){const rows=await prisma.$queryRawUnsafe<Array<{column_name:string}>>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,table);return new Set(rows.map(r=>r.column_name));}
async function scopedJson(prisma:PrismaClient,a:AuthContext,table:string,limit=1000){try{if(!(await tableExists(prisma,table)))return[];const cols=await tableColumns(prisma,table),args:unknown[]=[];let where='TRUE';if(cols.has('organizationId')){args.push(a.organizationId);where=`t."organizationId"=$${args.length}`;}if(cols.has('legalEntityId')){args.push(entity(a));where+=` AND t."legalEntityId"=$${args.length}`;}const rows=await prisma.$queryRawUnsafe<JsonRow[]>(`SELECT to_jsonb(t) AS data FROM ${q(table)} t WHERE ${where} LIMIT ${Math.min(Math.max(limit,1),5000)}`,...args);return rows.map(r=>r.data||{});}catch{return[];}}
const sourceConfigs=[
 ['SpireChartAccessEvent','SPIRE_CHART_ACCESS'],['SpireClinicalAuditEvent','SPIRE_CLINICAL'],['ClientIntakeEvent','CLIENT_INTAKE'],['SpireClinicalTaskEvent','SCLS_TASK'],['SpireHouseLogEvent','SCLS_HOUSE'],['HomeHealthEpisodeEvent','HOME_HEALTH'],['NmtTransportOrderEvent','NMT_ORDER'],['NmtTripEvent','NMT_TRIP'],['CompanyComplianceEvent','COMPLIANCE'],['RevenueCycleEvent','REVENUE_CYCLE'],['EnterpriseDataQualityEvent','DATA_QUALITY'],['SecurityAccessReviewEvent','ACCESS_REVIEW'],['SpireMedicationQualificationEvent','MEDICATION_QUALIFICATION'],['AuditLog','ENTERPRISE_AUDIT']
] as const;
function normalize(source:string,r:Record<string,unknown>):FeedItem|null{const timestamp=String(r.createdAt||r.timestamp||r.occurredAt||r.accessedAt||r.updatedAt||'');if(!timestamp)return null;const id=String(r.id||`${source}:${timestamp}`),actor=clean(r.actorUserId||r.userId||r.changedByUserId||r.createdByUserId||r.reviewedByUserId||r.exportedByUserId||r.actorId,160)||null,email=clean(r.actorEmail||r.email,250)||null,action=clean(r.action||r.eventType||r.activity||r.operation||r.type,200)||'EVENT',resourceType=clean(r.resourceType||r.entityType||r.objectType,160)||source,resourceId=clean(r.resourceId||r.patientId||r.clientId||r.intakeCaseId||r.taskId||r.episodeId||r.orderId||r.tripId||r.complianceItemId||r.issueId||r.campaignId,160)||null,patientId=clean(r.patientId||r.clientId,160)||null;return{source,id,actorUserId:actor,actorEmail:email,action,resourceType,resourceId,patientId,timestamp,details:r.details??r.metadata??r.afterValue??r.beforeValue??null};}
async function feed(prisma:PrismaClient,a:AuthContext,filters:{from?:string;to?:string;actor?:string;source?:string;q?:string;limit?:number}){const all:FeedItem[]=[];for(const [table,source] of sourceConfigs){if(filters.source&&filters.source!==source)continue;for(const row of await scopedJson(prisma,a,table,Math.min(filters.limit||1000,2000))){const item=normalize(source,row);if(item)all.push(item);}}const from=filters.from?Date.parse(filters.from):null,to=filters.to?Date.parse(filters.to):null,query=String(filters.q||'').toLowerCase(),actor=String(filters.actor||'').toLowerCase();return all.filter(item=>{const t=Date.parse(item.timestamp);if(from&&Number.isFinite(t)&&t<from)return false;if(to&&Number.isFinite(t)&&t>to)return false;if(actor&&!`${item.actorUserId||''} ${item.actorEmail||''}`.toLowerCase().includes(actor))return false;if(query&&!JSON.stringify(item).toLowerCase().includes(query))return false;return true;}).sort((x,y)=>Date.parse(y.timestamp)-Date.parse(x.timestamp)).slice(0,Math.min(Math.max(filters.limit||1000,1),5000));}
async function activeUserIds(prisma:PrismaClient,a:AuthContext){const ids=new Set<string>();for(const table of ['SpireChartAccessEvent','SpireClinicalAuditEvent','ClientIntakeEvent','SpireClinicalTaskEvent','HomeHealthStaffProfile','HomeHealthVisit','NmtDriverProfile','EmployeeTimePunch','EmployeeTimesheet','EmployeeDocumentSubmission','SpireMedicationAdministrationQualification'])for(const row of await scopedJson(prisma,a,table,5000)){for(const key of ['actorUserId','userId','employeeUserId','assignedUserId','providerUserId','createdByUserId']){const v=clean(row[key],160);if(v)ids.add(v);}}return [...ids];}
async function directory(prisma:PrismaClient,a:AuthContext,userIds:string[]){const byId=new Map<string,Record<string,unknown>>();const candidateTables=['UserAccount','EmployeeAccount','Employee','Staff','User'];for(const table of candidateTables){if(!(await tableExists(prisma,table)))continue;const cols=await tableColumns(prisma,table),idColumn=['id','userId','employeeUserId'].find(c=>cols.has(c));if(!idColumn)continue;try{const args:unknown[]=[userIds];let where=`t.${q(idColumn)}=ANY($1::text[])`;if(cols.has('organizationId')){args.push(a.organizationId);where+=` AND t."organizationId"=$${args.length}`;}const rows=await prisma.$queryRawUnsafe<JsonRow[]>(`SELECT to_jsonb(t) AS data FROM ${q(table)} t WHERE ${where} LIMIT 5000`,...args);for(const wrap of rows){const r=wrap.data||{},id=clean(r[idColumn],160);if(id&&!byId.has(id))byId.set(id,{...r,_directorySource:table});}}catch{}}
 return byId;}
async function activitySnapshot(prisma:PrismaClient,a:AuthContext,userId:string){try{const rows=await prisma.$queryRawUnsafe<Array<{chartAccess:number;clinicalActions:number;lastChartAccess:string|null}>>(`SELECT (SELECT count(*)::int FROM "SpireChartAccessEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "actorUserId"=$3) AS "chartAccess",(SELECT count(*)::int FROM "SpireClinicalAuditEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "actorUserId"=$3) AS "clinicalActions",(SELECT max("createdAt")::text FROM "SpireChartAccessEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "actorUserId"=$3) AS "lastChartAccess"`,a.organizationId,entity(a),userId);return rows[0]||{chartAccess:0,clinicalActions:0,lastChartAccess:null};}catch{return{chartAccess:0,clinicalActions:0,lastChartAccess:null};}}
async function reviewEvent(prisma:PrismaClient,a:AuthContext,campaignId:string,itemId:string|null,eventType:string,details:Record<string,unknown>={}){await prisma.$executeRawUnsafe(`INSERT INTO "SecurityAccessReviewEvent"("id","organizationId","legalEntityId","campaignId","itemId","eventType","actorUserId","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),a.organizationId,entity(a),campaignId,itemId,eventType,a.userId,JSON.stringify(details));}
const campaignSchema=z.object({title:z.string().trim().min(3).max(300),reviewType:z.enum(['PERIODIC','ROLE_CHANGE','TERMINATION','PRIVILEGED_ACCESS','INCIDENT_FOLLOW_UP','OTHER']).default('PERIODIC'),periodStart:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),periodEnd:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),dueAt:z.string().datetime().optional().nullable(),instructions:z.string().trim().max(5000).optional().nullable(),userIds:z.array(z.string().trim().min(1)).max(5000).optional()});
const decisionSchema=z.object({decision:z.enum(['APPROVE_CURRENT','CHANGE_REQUIRED','REMOVE_ACCESS','NOT_APPLICABLE']),requiredAction:z.string().trim().max(5000).optional().nullable(),reviewNote:z.string().trim().max(5000).optional().nullable()});
export const registerSecurityAuditRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/security-audit/context',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const company=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","code","displayName","legalName" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));res.json({data:{company:company[0]||null,role:a.role,write:writeRoles.has(String(a.role))||owner(a),enterpriseOwner:owner(a)}});}catch(e){next(e);}});
 app.get('/api/security-audit/feed',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await feed(prisma,a,{from:clean(req.query.from,40)||undefined,to:clean(req.query.to,40)||undefined,actor:clean(req.query.actor,250)||undefined,source:clean(req.query.source,80)||undefined,q:clean(req.query.q,500)||undefined,limit:Number(req.query.limit||1000)});res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/security-audit/chart-access-summary',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);if(!(await tableExists(prisma,'SpireChartAccessEvent')))return void res.json({data:[]});const days=Math.min(365,Math.max(1,Number(req.query.days||30)));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "actorUserId","actorEmail",count(*)::int AS "accessCount",count(DISTINCT "patientId")::int AS "distinctPatients",max("createdAt") AS "lastAccess",count(*) FILTER(WHERE "action" ILIKE '%DOWNLOAD%' OR "action" ILIKE '%EXPORT%')::int AS "downloadExportCount" FROM "SpireChartAccessEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "createdAt">=NOW()-($3::text||' days')::interval GROUP BY "actorUserId","actorEmail" ORDER BY "accessCount" DESC`,a.organizationId,entity(a),String(days));res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/security-audit/access-candidates',async(_req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const ids=await activeUserIds(prisma,a),dir=await directory(prisma,a,ids),items=[];for(const id of ids){const d=dir.get(id)||{},activity=await activitySnapshot(prisma,a,id);items.push({userId:id,userDisplayName:clean(d.displayName||d.fullName,250)||[d.firstName,d.lastName].filter(Boolean).join(' ')||clean(d.name,250)||id,email:clean(d.email,250)||null,role:clean(d.role,120)||null,status:clean(d.status,80)||null,directorySource:d._directorySource||null,activity});}items.sort((x,y)=>String(x.userDisplayName).localeCompare(String(y.userDisplayName)));res.json({data:items});}catch(e){next(e);}});
 app.get('/api/security-audit/campaigns',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c.*,COALESCE((SELECT jsonb_agg(to_jsonb(i) ORDER BY i."createdAt") FROM "SecurityAccessReviewItem" i WHERE i."campaignId"=c."id"),'[]'::jsonb) AS items FROM "SecurityAccessReviewCampaign" c WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 ORDER BY c."createdAt" DESC LIMIT 500`,a.organizationId,entity(a));res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/security-audit/campaigns',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=campaignSchema.parse(req.body),available=await activeUserIds(prisma,a),ids=[...new Set(i.userIds?.length?i.userIds:available)];if(!ids.length)throw httpError(409,'No active users were found in the selected company audit/activity records');const dir=await directory(prisma,a,ids),campaignId=randomUUID();await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`INSERT INTO "SecurityAccessReviewCampaign"("id","organizationId","legalEntityId","title","status","reviewType","periodStart","periodEnd","dueAt","instructions","createdByUserId") VALUES($1,$2,$3,$4,'DRAFT',$5,$6::date,$7::date,$8::timestamptz,$9,$10)`,campaignId,a.organizationId,entity(a),i.title,i.reviewType,i.periodStart??null,i.periodEnd??null,i.dueAt??null,i.instructions??null,a.userId);for(const userId of ids){const d=dir.get(userId)||{},activity=await activitySnapshot(prisma,a,userId),display=clean(d.displayName||d.fullName,250)||[d.firstName,d.lastName].filter(Boolean).join(' ')||clean(d.name,250)||userId;await tx.$executeRawUnsafe(`INSERT INTO "SecurityAccessReviewItem"("id","organizationId","legalEntityId","campaignId","userId","userDisplayName","email","roleSnapshot","accessSnapshot","activitySnapshot") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb)`,randomUUID(),a.organizationId,entity(a),campaignId,userId,display,clean(d.email,250)||null,clean(d.role,120)||null,JSON.stringify({status:d.status??null,directorySource:d._directorySource??null}),JSON.stringify(activity));}});await reviewEvent(prisma,a,campaignId,null,'CAMPAIGN_CREATED',{reviewType:i.reviewType,userCount:ids.length});await audit?.(a,'CREATE_ACCESS_REVIEW_CAMPAIGN','SecurityAccessReviewCampaign',campaignId,{userCount:ids.length,reviewType:i.reviewType});res.status(201).json({data:{id:campaignId,status:'DRAFT',userCount:ids.length}});}catch(e){next(e);}});
 app.post('/api/security-audit/campaigns/:campaignId/start',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const count=await prisma.$executeRawUnsafe(`UPDATE "SecurityAccessReviewCampaign" SET "status"='IN_PROGRESS',"startedAt"=NOW(),"startedByUserId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4 AND "status"='DRAFT'`,a.userId,a.organizationId,entity(a),req.params.campaignId);if(!count)throw httpError(409,'Only DRAFT access reviews can be started');await reviewEvent(prisma,a,req.params.campaignId,null,'CAMPAIGN_STARTED',{});res.json({data:{id:req.params.campaignId,status:'IN_PROGRESS'}});}catch(e){next(e);}});
 app.post('/api/security-audit/campaigns/:campaignId/items/:itemId/review',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const i=decisionSchema.parse(req.body);if(['CHANGE_REQUIRED','REMOVE_ACCESS'].includes(i.decision)&&!i.requiredAction)throw httpError(400,'A required access action must be documented for this decision');const rows=await prisma.$queryRawUnsafe<Array<{id:string;decision:string;userId:string}>>(`SELECT i."id",i."decision",i."userId" FROM "SecurityAccessReviewItem" i JOIN "SecurityAccessReviewCampaign" c ON c."id"=i."campaignId" WHERE i."organizationId"=$1 AND i."legalEntityId"=$2 AND i."campaignId"=$3 AND i."id"=$4 AND c."status"='IN_PROGRESS' LIMIT 1`,a.organizationId,entity(a),req.params.campaignId,req.params.itemId),item=rows[0];if(!item)throw httpError(404,'Access review item was not found in an active campaign');await prisma.$executeRawUnsafe(`UPDATE "SecurityAccessReviewItem" SET "decision"=$1,"requiredAction"=$2,"reviewNote"=$3,"reviewedAt"=NOW(),"reviewedByUserId"=$4,"updatedAt"=NOW() WHERE "id"=$5`,i.decision,i.requiredAction??null,i.reviewNote??null,a.userId,item.id);await reviewEvent(prisma,a,req.params.campaignId,item.id,'ITEM_REVIEWED',{fromDecision:item.decision,toDecision:i.decision,userId:item.userId,requiredAction:i.requiredAction??null});res.json({data:{id:item.id,decision:i.decision}});}catch(e){next(e);}});
 app.post('/api/security-audit/campaigns/:campaignId/items/:itemId/complete-action',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const note=z.string().trim().min(5).max(5000).parse(req.body?.note),rows=await prisma.$queryRawUnsafe<Array<{id:string;decision:string;requiredAction:string|null;userId:string}>>(`SELECT "id","decision","requiredAction","userId" FROM "SecurityAccessReviewItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "campaignId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity(a),req.params.campaignId,req.params.itemId),item=rows[0];if(!item)throw httpError(404,'Access review item was not found');if(!['CHANGE_REQUIRED','REMOVE_ACCESS'].includes(item.decision))throw httpError(409,'This review item does not have an outstanding access change/removal action');await prisma.$executeRawUnsafe(`UPDATE "SecurityAccessReviewItem" SET "actionCompletedAt"=NOW(),"actionCompletedByUserId"=$1,"actionCompletionNote"=$2,"updatedAt"=NOW() WHERE "id"=$3`,a.userId,note,item.id);await reviewEvent(prisma,a,req.params.campaignId,item.id,'REQUIRED_ACTION_COMPLETED',{userId:item.userId,decision:item.decision,requiredAction:item.requiredAction,note});res.json({data:{id:item.id,actionCompleted:true}});}catch(e){next(e);}});
 app.post('/api/security-audit/campaigns/:campaignId/complete',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const rows=await prisma.$queryRawUnsafe<Array<{decision:string;actionCompletedAt:string|null}>>(`SELECT "decision","actionCompletedAt"::text FROM "SecurityAccessReviewItem" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "campaignId"=$3`,a.organizationId,entity(a),req.params.campaignId);if(!rows.length)throw httpError(409,'Access review campaign has no items');const pending=rows.filter(r=>r.decision==='PENDING'),unresolved=rows.filter(r=>['CHANGE_REQUIRED','REMOVE_ACCESS'].includes(r.decision)&&!r.actionCompletedAt);if(pending.length||unresolved.length)throw httpError(409,'Access review cannot be completed until every user is reviewed and all required access actions are documented complete',{pendingReviews:pending.length,unresolvedActions:unresolved.length});const count=await prisma.$executeRawUnsafe(`UPDATE "SecurityAccessReviewCampaign" SET "status"='COMPLETED',"completedAt"=NOW(),"completedByUserId"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "id"=$4 AND "status"='IN_PROGRESS'`,a.userId,a.organizationId,entity(a),req.params.campaignId);if(!count)throw httpError(409,'Only IN_PROGRESS access reviews can be completed');await reviewEvent(prisma,a,req.params.campaignId,null,'CAMPAIGN_COMPLETED',{reviewedItems:rows.length});await audit?.(a,'COMPLETE_ACCESS_REVIEW_CAMPAIGN','SecurityAccessReviewCampaign',req.params.campaignId,{reviewedItems:rows.length});res.json({data:{id:req.params.campaignId,status:'COMPLETED'}});}catch(e){next(e);}});
 app.get('/api/security-audit/export.csv',async(req,res,next)=>{try{const a=authOf(res);ensureRead(a);const filters={from:clean(req.query.from,40)||undefined,to:clean(req.query.to,40)||undefined,actor:clean(req.query.actor,250)||undefined,source:clean(req.query.source,80)||undefined,q:clean(req.query.q,500)||undefined,limit:5000},rows=await feed(prisma,a,filters),headers=['timestamp','source','actorUserId','actorEmail','action','resourceType','resourceId','patientId','details'],csv=[headers.join(','),...rows.map(r=>[r.timestamp,r.source,r.actorUserId,r.actorEmail,r.action,r.resourceType,r.resourceId,r.patientId,r.details].map(csvCell).join(','))].join('\n'),sha=createHash('sha256').update(csv).digest('hex'),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SecurityAuditExport"("id","organizationId","legalEntityId","exportType","format","filterSnapshot","rowCount","sha256","exportedByUserId") VALUES($1,$2,$3,'UNIFIED_AUDIT','CSV',$4::jsonb,$5,$6,$7)`,id,a.organizationId,entity(a),JSON.stringify(filters),rows.length,sha,a.userId);await audit?.(a,'EXPORT_UNIFIED_SECURITY_AUDIT','SecurityAuditExport',id,{rowCount:rows.length,sha256:sha});res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="security-audit-${new Date().toISOString().slice(0,10)}.csv"`);res.setHeader('X-Sulandra-SHA256',sha);res.setHeader('Cache-Control','private, no-store');res.send(csv);}catch(e){next(e);}});
};
