import type { Express, RequestHandler, Response } from 'express';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { PrismaClient, UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(res:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};

const US_STATES=new Set(['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC']);
const homeSchema=z.object({
  name:z.string().trim().min(2).max(160),
  streetAddress:z.string().trim().min(3).max(220),
  city:z.string().trim().min(2).max(120),
  state:z.string().trim().transform(v=>v.toUpperCase()).refine(v=>US_STATES.has(v),'Select a valid state'),
  zipCode:z.string().trim().regex(/^\d{5}(?:-\d{4})?$/,'Enter a valid ZIP code'),
  latitude:z.number().finite().min(-90).max(90).optional().nullable(),
  longitude:z.number().finite().min(-180).max(180).optional().nullable(),
  geofenceRadiusMeters:z.number().int().min(50).max(5000).default(250),
});
const geocodeSchema=z.object({streetAddress:z.string().trim().min(3).max(220),city:z.string().trim().min(2).max(120),state:z.string().trim().transform(v=>v.toUpperCase()).refine(v=>US_STATES.has(v)),zipCode:z.string().trim().regex(/^\d{5}(?:-\d{4})?$/)});
const assignmentSchema=z.object({employeeId:z.string().trim().min(1),isManager:z.boolean().default(false)});
const clientAssignmentSchema=z.object({clientId:z.string().trim().min(1)});
const fullAddress=(x:{streetAddress:string;city:string;state:string;zipCode:string})=>`${x.streetAddress}, ${x.city}, ${x.state} ${x.zipCode}`;

const ensureSchema=async(prisma:PrismaClient)=>{
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TimeAttendanceLocation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"address" TEXT NOT NULL,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"geofenceRadiusMeters" INTEGER NOT NULL DEFAULT 250,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "TimeAttendanceLocation" ADD COLUMN IF NOT EXISTS "streetAddress" TEXT`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "TimeAttendanceLocation" ADD COLUMN IF NOT EXISTS "city" TEXT`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "TimeAttendanceLocation" ADD COLUMN IF NOT EXISTS "state" TEXT`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "TimeAttendanceLocation" ADD COLUMN IF NOT EXISTS "zipCode" TEXT`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "TA_location_org_name_uq" ON "TimeAttendanceLocation"("organizationId","name")`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TimeAttendanceLocationAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"isManager" BOOLEAN NOT NULL DEFAULT FALSE,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "TA_location_assignment_uq" ON "TimeAttendanceLocationAssignment"("organizationId","locationId","employeeId")`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ServiceHomeClientAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"clientId" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "service_home_client_uq" ON "ServiceHomeClientAssignment"("organizationId","locationId","clientId")`);
};
const rowName=(row:any)=>row?.displayName||row?.fullName||[row?.firstName,row?.lastName].filter(Boolean).join(' ')||row?.preferredName||row?.name||row?.email||row?.id||'Client';

export function registerServiceHomeManagementRoutes({app,prisma,authOf,requireRoles}:Dependencies){
  let readyPromise:Promise<void>|null=null;
  const ready=()=>readyPromise??=(ensureSchema(prisma).catch(error=>{readyPromise=null;throw error}));
  const global=requireRoles(UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.SCHEDULER,UserRole.CEO,UserRole.COO);
  const managers=requireRoles(UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.SCHEDULER,UserRole.CEO,UserRole.COO,UserRole.HOUSE_MANAGER);
  const isGlobal=(role:UserRole)=>['ADMINISTRATOR','PROGRAM_MANAGER','HR_MANAGER','SCHEDULER','CEO','COO'].includes(String(role));
  const canManage=async(a:AuthContext,id:string)=>isGlobal(a.role)||!!(await prisma.$queryRawUnsafe<any[]>(`SELECT 1 FROM "TimeAttendanceLocationAssignment" WHERE "organizationId"=$1 AND "locationId"=$2 AND "employeeId"=$3 AND "isManager"=TRUE AND "active"=TRUE LIMIT 1`,a.organizationId,id,a.userId))[0];

  app.post('/api/admin/service-homes/geocode',managers,async(req,res,next)=>{try{
    const input=geocodeSchema.parse(req.body);
    const params=new URLSearchParams({street:input.streetAddress,city:input.city,state:input.state,zip:input.zipCode,benchmark:'Public_AR_Current',format:'json'});
    const response=await fetch(`https://geocoding.geo.census.gov/geocoder/locations/address?${params.toString()}`,{headers:{Accept:'application/json','User-Agent':'SulandraHealth-ServiceHomes/1.0 admin@sulandrahealth.com'}});
    if(!response.ok)return res.status(502).json({error:'The address mapping service is temporarily unavailable'});
    const body:any=await response.json();
    const match=body?.result?.addressMatches?.[0];
    if(!match?.coordinates)return res.status(404).json({error:'No exact GPS match was found. Confirm the street, city, state, and ZIP code, or use Current GPS.'});
    res.json({data:{latitude:Number(match.coordinates.y),longitude:Number(match.coordinates.x),matchedAddress:String(match.matchedAddress||fullAddress(input)),source:'US_CENSUS_GEOCODER'}});
  }catch(e){next(e)}});

  app.get('/api/admin/service-homes',managers,async(_req,res,next)=>{try{await ready();const a=authOf(res);const select=`SELECT l.*,COALESCE(NULLIF(l."streetAddress",''),l."address") AS "streetAddress",COALESCE(l."city",'') AS "city",COALESCE(l."state",'') AS "state",COALESCE(l."zipCode",'') AS "zipCode",(SELECT COUNT(*)::int FROM "TimeAttendanceLocationAssignment" x WHERE x."organizationId"=l."organizationId" AND x."locationId"=l."id" AND x."active"=TRUE) AS "employeeCount",(SELECT COUNT(*)::int FROM "ServiceHomeClientAssignment" c WHERE c."organizationId"=l."organizationId" AND c."locationId"=l."id" AND c."active"=TRUE) AS "clientCount" FROM "TimeAttendanceLocation" l`;const homes=isGlobal(a.role)?await prisma.$queryRawUnsafe<any[]>(`${select} WHERE l."organizationId"=$1 AND l."active"=TRUE ORDER BY l."name"`,a.organizationId):await prisma.$queryRawUnsafe<any[]>(`${select} JOIN "TimeAttendanceLocationAssignment" m ON m."organizationId"=l."organizationId" AND m."locationId"=l."id" WHERE l."organizationId"=$1 AND l."active"=TRUE AND m."employeeId"=$2 AND m."isManager"=TRUE AND m."active"=TRUE ORDER BY l."name"`,a.organizationId,a.userId);res.json({data:homes})}catch(e){next(e)}});
  app.post('/api/admin/service-homes',global,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=homeSchema.parse(req.body);const address=fullAddress(input);const rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO "TimeAttendanceLocation" ("id","organizationId","name","address","streetAddress","city","state","zipCode","latitude","longitude","geofenceRadiusMeters") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,randomUUID(),a.organizationId,input.name,address,input.streetAddress,input.city,input.state,input.zipCode,input.latitude??null,input.longitude??null,input.geofenceRadiusMeters);res.status(201).json({data:rows[0]})}catch(e){next(e)}});
  app.patch('/api/admin/service-homes/:id',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);if(!(await canManage(a,req.params.id)))return res.status(403).json({error:'You may manage only assigned service homes'});const input=homeSchema.parse(req.body);const address=fullAddress(input);const rows=await prisma.$queryRawUnsafe<any[]>(`UPDATE "TimeAttendanceLocation" SET "name"=$1,"address"=$2,"streetAddress"=$3,"city"=$4,"state"=$5,"zipCode"=$6,"latitude"=$7,"longitude"=$8,"geofenceRadiusMeters"=$9,"updatedAt"=NOW() WHERE "id"=$10 AND "organizationId"=$11 RETURNING *`,input.name,address,input.streetAddress,input.city,input.state,input.zipCode,input.latitude??null,input.longitude??null,input.geofenceRadiusMeters,req.params.id,a.organizationId);if(!rows[0])return res.status(404).json({error:'Service home not found'});await prisma.$executeRawUnsafe(`UPDATE "TimeAttendanceShift" SET "location"=$1,"latitude"=$2,"longitude"=$3,"geofenceRadiusMeters"=$4 WHERE "organizationId"=$5 AND "locationId"=$6`,input.name,input.latitude??null,input.longitude??null,input.geofenceRadiusMeters,a.organizationId,req.params.id).catch(()=>undefined);res.json({data:rows[0]})}catch(e){next(e)}});
  app.delete('/api/admin/service-homes/:id',global,async(req,res,next)=>{try{await ready();const a=authOf(res);await prisma.$executeRawUnsafe(`UPDATE "TimeAttendanceLocation" SET "active"=FALSE,"updatedAt"=NOW() WHERE "id"=$1 AND "organizationId"=$2`,req.params.id,a.organizationId);await prisma.$executeRawUnsafe(`UPDATE "TimeAttendanceLocationAssignment" SET "active"=FALSE,"updatedAt"=NOW() WHERE "locationId"=$1 AND "organizationId"=$2`,req.params.id,a.organizationId);await prisma.$executeRawUnsafe(`UPDATE "ServiceHomeClientAssignment" SET "active"=FALSE,"updatedAt"=NOW() WHERE "locationId"=$1 AND "organizationId"=$2`,req.params.id,a.organizationId);res.status(204).end()}catch(e){next(e)}});

  app.get('/api/admin/service-homes/directory/employees',global,async(_req,res,next)=>{try{const a=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE u."organizationId"=$1 ORDER BY COALESCE(NULLIF(c."displayName",''),u."email")`,a.organizationId);res.json({data:rows})}catch(e){next(e)}});
  app.get('/api/admin/service-homes/directory/clients',global,async(_req,res,next)=>{try{const a=authOf(res);const exists=(await prisma.$queryRawUnsafe<any[]>(`SELECT to_regclass('public."Client"') AS table_name`))[0]?.table_name;if(!exists)return res.json({data:[]});const raw=await prisma.$queryRawUnsafe<any[]>(`SELECT to_jsonb(c) AS row FROM "Client" c WHERE c."organizationId"=$1 ORDER BY c."createdAt" DESC`,a.organizationId).catch(async()=>prisma.$queryRawUnsafe<any[]>(`SELECT to_jsonb(c) AS row FROM "Client" c WHERE c."organizationId"=$1`,a.organizationId));res.json({data:raw.map(x=>({id:String(x.row.id),displayName:rowName(x.row),...x.row}))})}catch(e){next(e)}});
  app.get('/api/admin/service-homes/:id/assignments',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);if(!(await canManage(a,req.params.id)))return res.status(403).json({error:'You may manage only assigned service homes'});const [employees,clientLinks]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName",x."isManager" FROM "TimeAttendanceLocationAssignment" x JOIN "User" u ON u."id"=x."employeeId" LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE x."organizationId"=$1 AND x."locationId"=$2 AND x."active"=TRUE ORDER BY COALESCE(NULLIF(c."displayName",''),u."email")`,a.organizationId,req.params.id),prisma.$queryRawUnsafe<any[]>(`SELECT "clientId" FROM "ServiceHomeClientAssignment" WHERE "organizationId"=$1 AND "locationId"=$2 AND "active"=TRUE`,a.organizationId,req.params.id)]);let clients:any[]=[];const exists=(await prisma.$queryRawUnsafe<any[]>(`SELECT to_regclass('public."Client"') AS table_name`))[0]?.table_name;if(exists&&clientLinks.length){const ids=clientLinks.map(x=>x.clientId);const raw=await prisma.$queryRawUnsafe<any[]>(`SELECT to_jsonb(c) AS row FROM "Client" c WHERE c."id"=ANY($1::text[])`,ids).catch(()=>[]);clients=raw.map(x=>({id:String(x.row.id),displayName:rowName(x.row),...x.row}))}res.json({data:{employees,clients}})}catch(e){next(e)}});
  app.post('/api/admin/service-homes/:id/employees',global,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=assignmentSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO "TimeAttendanceLocationAssignment" ("id","organizationId","locationId","employeeId","isManager") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("organizationId","locationId","employeeId") DO UPDATE SET "isManager"=EXCLUDED."isManager","active"=TRUE,"updatedAt"=NOW() RETURNING *`,randomUUID(),a.organizationId,req.params.id,input.employeeId,input.isManager);res.status(201).json({data:rows[0]})}catch(e){next(e)}});
  app.delete('/api/admin/service-homes/:id/employees/:employeeId',global,async(req,res,next)=>{try{await ready();const a=authOf(res);await prisma.$executeRawUnsafe(`UPDATE "TimeAttendanceLocationAssignment" SET "active"=FALSE,"isManager"=FALSE,"updatedAt"=NOW() WHERE "organizationId"=$1 AND "locationId"=$2 AND "employeeId"=$3`,a.organizationId,req.params.id,req.params.employeeId);res.status(204).end()}catch(e){next(e)}});
  app.post('/api/admin/service-homes/:id/clients',global,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=clientAssignmentSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO "ServiceHomeClientAssignment" ("id","organizationId","locationId","clientId") VALUES ($1,$2,$3,$4) ON CONFLICT ("organizationId","locationId","clientId") DO UPDATE SET "active"=TRUE,"updatedAt"=NOW() RETURNING *`,randomUUID(),a.organizationId,req.params.id,input.clientId);res.status(201).json({data:rows[0]})}catch(e){next(e)}});
  app.delete('/api/admin/service-homes/:id/clients/:clientId',global,async(req,res,next)=>{try{await ready();const a=authOf(res);await prisma.$executeRawUnsafe(`UPDATE "ServiceHomeClientAssignment" SET "active"=FALSE,"updatedAt"=NOW() WHERE "organizationId"=$1 AND "locationId"=$2 AND "clientId"=$3`,a.organizationId,req.params.id,req.params.clientId);res.status(204).end()}catch(e){next(e)}});
}
