import { randomUUID } from 'node:crypto';
import type { Express, RequestHandler, Response } from 'express';
import { PrismaClient, UserRole } from '@prisma/client';
import { z } from 'zod';
import { SULANDRA_CANONICAL_SYSTEM_MAP } from './sia-system-map.js';
import { ensureSIACopilotProfile, serializeSIACopilotProfile } from './sia-copilot-profile.js';
import { classifySiaMode } from './sia-mode-router.js';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string|null;enterpriseOwner?:boolean;ipAddress?:string;userAgent?:string};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(response:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};
const allRoles=Object.values(UserRole) as UserRole[];
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.CEO,UserRole.COO]);
const chatSchema=z.object({conversationId:z.string().uuid().optional(),message:z.string().trim().min(1).max(12000),context:z.object({page:z.string().max(240).optional(),application:z.string().max(160).optional(),clientLocalDateTime:z.string().max(180).optional(),clientTimeZone:z.string().max(120).optional()}).optional()});
const ticketSchema=z.object({conversationId:z.string().uuid().optional(),subject:z.string().trim().min(3).max(240),description:z.string().trim().min(5).max(12000),category:z.enum(['ACCOUNT','PASSWORD','MFA','PORTAL','DEVICE','NETWORK','SCHEDULING','PAYROLL','BENEFITS','DOCUMENTS','TRAINING','OTHER']).default('OTHER'),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL'),engineeringNeed:z.enum(['CODE_PATCH','CONFIG_REPAIR','DEPLOYMENT_REPAIR','DATA_REPAIR']),diagnosis:z.string().trim().min(5).max(4000),changeClass:z.enum(['ESTABLISHED_OPERATION_REPAIR','NEW_SYSTEM_CHANGE']).default('ESTABLISHED_OPERATION_REPAIR')});
const openAIConfigured=()=>Boolean(process.env.OPENAI_API_KEY?.trim());
const openAIModel=()=>process.env.SIA_OPENAI_MODEL?.trim()||'gpt-5.6-terra';
const redact=(value:string)=>value.replace(/\bsk-[A-Za-z0-9_-]{12,}\b/g,'[REDACTED_KEY]').replace(/\bBearer\s+[A-Za-z0-9._~-]{16,}\b/gi,'Bearer [REDACTED_TOKEN]').replace(/\b(api[_ -]?key|access[_ -]?token|secret|password|mfa|otp)\s*[:=]\s*[^\s,;]+/gi,'$1=[REDACTED]').replace(/\b\d{3}-\d{2}-\d{4}\b/g,'[REDACTED_SSN]');
let readyPromise:Promise<void>|null=null;
const ensureStorage=(prisma:PrismaClient)=>readyPromise??=(async()=>{await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SIAConversation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"title" TEXT NOT NULL DEFAULT 'Ask SIA',"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SIAMessage" ("id" TEXT PRIMARY KEY,"conversationId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" TEXT NOT NULL,"content" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "SIAMessage_conversation_idx" ON "SIAMessage"("conversationId","createdAt")`);})().catch(e=>{readyPromise=null;throw e});

const systemInstructions=(auth:AuthContext,mode:string)=>`You are SIA, the Sulandra Intelligent Assistant and first-line IT support for Sulandra. Current authenticated role: ${auth.role}. Current mode: ${mode}.\n${SULANDRA_CANONICAL_SYSTEM_MAP}\nYou should guide employees through nearly all normal Sulandra workflows, navigation, access, and troubleshooting before creating any engineering ticket. Diagnose the affected application, page, workflow step, expected behavior, actual behavior, and non-sensitive evidence. Never ask for passwords, MFA codes, tokens, patient identifiers, raw clinical content, or secrets. Do not create an engineering ticket merely because the employee asks. Only recommend engineering handoff when the evidence indicates a code patch, configuration repair, deployment repair, or data repair is required. For an already-established operation that is broken, classify it as ESTABLISHED_OPERATION_REPAIR. For genuinely new functionality or materially new system behavior, classify it as NEW_SYSTEM_CHANGE and explain that approval is required before production. Never claim that GitHub, Railway, permissions, or production were changed unless a trusted backend action result proves it.`;

export function registerSIARoutes({app,prisma,authOf,requireRoles}:Dependencies){const gate=requireRoles(...allRoles);
app.get('/api/sia/status',gate,async(_req,res,next)=>{try{const auth=authOf(res);res.json({data:{configured:openAIConfigured(),model:openAIModel(),role:auth.role,adminAccess:adminRoles.has(auth.role),itSolutions:'/it-solutions.html'}})}catch(e){next(e)}});
app.get('/api/sia/conversations',gate,async(_req,res,next)=>{try{await ensureStorage(prisma);const auth=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "SIAConversation" WHERE "organizationId"=$1 AND "userId"=$2 ORDER BY "updatedAt" DESC LIMIT 50`,auth.organizationId,auth.userId);res.json({data:{conversations:rows}})}catch(e){next(e)}});
app.get('/api/sia/conversations/:id/messages',gate,async(req,res,next)=>{try{await ensureStorage(prisma);const auth=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT "id","role","content","createdAt" FROM "SIAMessage" WHERE "organizationId"=$1 AND "userId"=$2 AND "conversationId"=$3 ORDER BY "createdAt" ASC LIMIT 500`,auth.organizationId,auth.userId,req.params.id);res.json({data:{messages:rows}})}catch(e){next(e)}});
app.post('/api/sia/chat',gate,async(req,res,next)=>{try{await ensureStorage(prisma);const auth=authOf(res);const input=chatSchema.parse(req.body);const routing=classifySiaMode({message:input.message,page:input.context?.page,application:input.context?.application});if(routing.blockBeforeModel)return void res.status(400).json({error:'Remove secrets or protected identifiers before using Ask SIA.'});const conversationId=input.conversationId||randomUUID();if(!input.conversationId)await prisma.$executeRawUnsafe(`INSERT INTO "SIAConversation" ("id","organizationId","userId","title") VALUES ($1,$2,$3,$4)`,conversationId,auth.organizationId,auth.userId,redact(input.message).slice(0,120));const userMessage=redact(input.message);await prisma.$executeRawUnsafe(`INSERT INTO "SIAMessage" ("id","conversationId","organizationId","userId","role","content") VALUES ($1,$2,$3,$4,'user',$5)`,randomUUID(),conversationId,auth.organizationId,auth.userId,userMessage);const profile=await ensureSIACopilotProfile(prisma,auth,{page:input.context?.page,application:input.context?.application});let reply='Ask SIA is available, but the AI service is not configured on this environment.';if(openAIConfigured()){const contextLines=[...serializeSIACopilotProfile(profile),`serverNowUtc: ${new Date().toISOString()}`,`clientLocalDateTime: ${input.context?.clientLocalDateTime||'NOT_SUPPLIED'}`,`clientTimeZone: ${input.context?.clientTimeZone||'NOT_SUPPLIED'}`].join('\n');const body:any={model:openAIModel(),input:[{role:'system',content:[{type:'input_text',text:systemInstructions(auth,routing.mode)}]},{role:'system',content:[{type:'input_text',text:contextLines}]},{role:'user',content:[{type:'input_text',text:userMessage}]}]};if(routing.allowLiveWebSearch)body.tools=[{type:'web_search'}];const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`OpenAI HTTP ${response.status}`);reply=String(payload.output_text||payload.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||'').join('\n')||'').trim()||'I could not generate a response.';}await prisma.$executeRawUnsafe(`INSERT INTO "SIAMessage" ("id","conversationId","organizationId","userId","role","content") VALUES ($1,$2,$3,$4,'assistant',$5)`,randomUUID(),conversationId,auth.organizationId,auth.userId,reply);await prisma.$executeRawUnsafe(`UPDATE "SIAConversation" SET "updatedAt"=NOW() WHERE "id"=$1`,conversationId);res.json({data:{conversationId,reply,mode:routing.mode,modeLabel:routing.modeLabel,ticketPolicy:{diagnoseFirst:true,engineeringOnly:true}}})}catch(e){next(e)}});
app.post('/api/sia/tickets',gate,async(req,res,next)=>{try{await ensureStorage(prisma);const auth=authOf(res);const input=ticketSchema.parse(req.body);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeSupportRequest" ("id","organizationId","legalEntityId","employeeId","category","priority","subject","description","status","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'OPEN',NOW(),NOW())`,id,auth.organizationId,auth.legalEntityId??null,auth.userId,input.category,input.priority,input.subject,redact(input.description));res.status(201).json({data:{ticketId:id,conversationId:input.conversationId||null,engineeringNeed:input.engineeringNeed,diagnosis:redact(input.diagnosis),changeClass:input.changeClass,requiresApproval:input.changeClass==='NEW_SYSTEM_CHANGE',next:'/api/it-solutions/agent-handoffs'}})}catch(e){next(e)}});
}