import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const licensedMedicationRoles=new Set<UserRole>([UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE]);
const elevatedRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const selectedEntity=(a:AuthContext)=>{if(!a.legalEntityId)throw Object.assign(new Error('Select a Sulandra company before documenting medications'),{status:409});return a.legalEntityId;};
const elevated=(a:AuthContext)=>a.enterpriseOwner===true||elevatedRoles.has(a.role)||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
async function medicationAuthorized(prisma:PrismaClient,a:AuthContext){if(licensedMedicationRoles.has(a.role))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireMedicationAdministrationQualification" q WHERE q."organizationId"=$1 AND q."legalEntityId"=$2 AND q."userId"=$3 AND q."status"='ACTIVE' AND q."revokedAt" IS NULL AND q."effectiveAt"<=NOW() AND (q."expiresAt" IS NULL OR q."expiresAt">NOW())) AS allowed`,a.organizationId,selectedEntity(a),a.userId);return rows[0]?.allowed===true;}
async function patientAllowed(prisma:PrismaClient,a:AuthContext,patientId:string){const entity=selectedEntity(a);const enrolled=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "ClientEnrollment" e WHERE e."organizationId"=$1 AND e."legalEntityId"=$2 AND e."clientId"=$3 AND e."status" IN ('PENDING','ACTIVE','PAUSED')) AS allowed`,a.organizationId,entity,patientId);if(enrolled[0]?.allowed!==true)return false;if(elevated(a))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(
  SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."legalEntityId"=$2 AND x."userId"=$3 AND x."clientId"=$4
  UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW())
  UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$3 AND g."scopeType"='CLIENT' AND g."clientId"=$4 AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())
) AS allowed`,a.organizationId,entity,a.userId,patientId);return rows[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string,write=false){if(!clinicalRoles.has(a.role)&&a.enterpriseOwner!==true)throw Object.assign(new Error('SPIRE medication access is required'),{status:403});selectedEntity(a);if(!(await patientAllowed(prisma,a,patientId)))throw Object.assign(new Error('This chart is outside your authorized medication scope for the selected company'),{status:403});if(write&&!(await medicationAuthorized(prisma,a)))throw Object.assign(new Error('Medication administration is blocked. A licensed nursing role or an active verified medication-administration qualification is required for this company.'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,resourceId?:string){await prisma.$executeRawUnsafe(`INSERT INTO "SpireChartAccessEvent" ("organizationId","legalEntityId","patientId","actorUserId","actorEmail","action","resourceType","resourceId","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,$6,'MEDICATION',$7,$8,$9)`,a.organizationId,selectedEntity(a),patientId,a.userId,a.email??null,action,resourceId??null,a.ipAddress??null,a.userAgent??null);}

const eventSchema=z.object({medicationOrderId:z.string().min(1),scheduledFor:z.string().datetime().optional().nullable(),status:z.enum(['GIVEN','REFUSED','HELD','NOT_GIVEN','MISSED','PRN_GIVEN']),administeredDose:z.string().optional().nullable(),administeredRoute:z.string().optional().nullable(),reason:z.string().optional().nullable(),note:z.string().optional().nullable(),prnIndication:z.string().optional().nullable(),barcodeValue:z.string().optional().nullable(),controlledQuantity:z.number().optional().nullable(),witnessUserId:z.string().optional().nullable()});
const effectivenessSchema=z.object({effectiveness:z.string().min(1).max(2000)});

export const registerSpireEmarRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{
 const{authOf}=deps;
 app.get('/api/spire/patients/:patientId/medications/active',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledTime',s."scheduledTime",'windowBeforeMinutes',s."windowBeforeMinutes",'windowAfterMinutes',s."windowAfterMinutes") ORDER BY s."scheduledTime") FROM "SpireMedicationSchedule" s WHERE s."organizationId"=m."organizationId" AND s."medicationOrderId"=m."id" AND s."active"=TRUE),'[]'::jsonb) schedules,(SELECT e."status" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministrationStatus",(SELECT e."administeredAt" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministeredAt" FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND COALESCE(to_jsonb(m)->>'patientId',to_jsonb(m)->>'clientId')=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId);await audit(prisma,a,patientId,'VIEW_ACTIVE_MEDICATIONS');res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/emar',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const date=String(req.query.date||new Date().toISOString().slice(0,10));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m."id" AS "medicationOrderId",m."name",m."dose",m."route",m."frequency",m."instructions",m."dueTimes",m."status",COALESCE((SELECT jsonb_agg(jsonb_build_object('id',a2."id",'scheduledFor',a2."scheduledFor",'status',a2."status",'administeredAt',a2."administeredAt",'administeredById',a2."administeredByUserId",'reason',a2."resultNote",'note',a2."resultNote") ORDER BY a2."scheduledFor") FROM "SpireMedicationAdministration" a2 WHERE a2."organizationId"=m."organizationId" AND a2."medicationOrderId"=m."id" AND a2."scheduledFor"::date=$3::date),'[]'::jsonb) administrations FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND COALESCE(to_jsonb(m)->>'patientId',to_jsonb(m)->>'clientId')=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId,date);await audit(prisma,a,patientId,'VIEW_EMAR');res.json({data:{date,medications:rows,medicationAdministrationAuthorized:await medicationAuthorized(prisma,a)}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/emar/events',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=eventSchema.parse(req.body);const med=await prisma.$queryRawUnsafe<Array<{id:string;name:string;dose:string;route:string}>>(`SELECT "id","name","dose","route" FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND COALESCE(to_jsonb(m)->>'patientId',to_jsonb(m)->>'clientId')=$2 AND m."id"=$3 AND m."status"='ACTIVE'`,a.organizationId,patientId,b.medicationOrderId);if(!med[0])throw Object.assign(new Error('Active medication order not found'),{status:404});if(['REFUSED','HELD','NOT_GIVEN','MISSED'].includes(b.status)&&!String(b.reason||'').trim())throw Object.assign(new Error('A reason is required when medication is not administered'),{status:400});if(b.status==='PRN_GIVEN'&&!String(b.prnIndication||'').trim())throw Object.assign(new Error('PRN indication is required'),{status:400});const scheduled=b.scheduledFor?new Date(b.scheduledFor):null;const statusMap:Record<string,string>={GIVEN:'GIVEN',REFUSED:'REFUSED',HELD:'HELD',NOT_GIVEN:'MISSED',MISSED:'MISSED',PRN_GIVEN:'GIVEN'};let administrationId:string|undefined;if(scheduled){const existing=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireMedicationAdministration" WHERE "organizationId"=$1 AND "medicationOrderId"=$2 AND "scheduledFor"=$3 LIMIT 1`,a.organizationId,b.medicationOrderId,scheduled);administrationId=existing[0]?.id;}if(administrationId){await prisma.$executeRawUnsafe(`UPDATE "SpireMedicationAdministration" SET "status"=$1,"administeredAt"=CASE WHEN $1='GIVEN' THEN NOW() ELSE "administeredAt" END,"administeredByUserId"=$2,"resultNote"=$3,"updatedAt"=NOW() WHERE "id"=$4`,statusMap[b.status]||'MISSED',a.userId,[b.reason,b.note,b.prnIndication].filter(Boolean).join(' — ')||null,administrationId);}else{administrationId=crypto.randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationAdministration" ("id","organizationId","clientId","medicationOrderId","scheduledFor","status","administeredAt","administeredByUserId","resultNote","createdAt","updatedAt") VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $6='GIVEN' THEN NOW() ELSE NULL END,$7,$8,NOW(),NOW())`,administrationId,a.organizationId,patientId,b.medicationOrderId,scheduled??new Date(),statusMap[b.status]||'MISSED',a.userId,[b.reason,b.note,b.prnIndication].filter(Boolean).join(' — ')||null);}await audit(prisma,a,patientId,`EMAR_${b.status}`,administrationId);res.status(201).json({data:{id:administrationId,status:b.status,legalEntityId:selectedEntity(a)}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/emar/events/:eventId/effectiveness',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=effectivenessSchema.parse(req.body);const count=await prisma.$executeRawUnsafe(`UPDATE "SpireMedicationAdministration" SET "resultNote"=CONCAT_WS(' — ',NULLIF("resultNote",''),$1),"updatedAt"=NOW() WHERE "organizationId"=$2 AND "clientId"=$3 AND "id"=$4`,b.effectiveness,a.organizationId,patientId,req.params.eventId);if(!count)throw Object.assign(new Error('Administration event not found in the selected company'),{status:404});await audit(prisma,a,patientId,'DOCUMENT_PRN_EFFECTIVENESS',req.params.eventId);res.json({data:{ok:true}});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/medications/reconciliation',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT r.*,COALESCE((SELECT jsonb_agg(i ORDER BY i."createdAt") FROM "SpireMedicationReconciliationItem" i WHERE i."organizationId"=r."organizationId" AND i."reconciliationId"=r."id"),'[]'::jsonb) items FROM "SpireMedicationReconciliation" r WHERE r."organizationId"=$1 AND r."patientId"=$2 ORDER BY r."createdAt" DESC LIMIT 20`,a.organizationId,patientId);res.json({data:rows});}catch(e){next(e);}});
};
