import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { createHash, randomBytes } from 'node:crypto';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const text=(v:unknown,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const list=(v:unknown)=>Array.isArray(v)?v:[];
const err=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{const id=text(a.legalEntityId,120);if(!id)throw err(409,'Select a Sulandra company before using SPIRE integrations');return id;};
const ensureAdmin=(a:AuthContext)=>{if(!adminRoles.has(a.role)&&String(a.email||'').toLowerCase()!=='admin@sulandrahealth.com')throw err(403,'Integration administration is restricted');};
const ensureClinical=(a:AuthContext)=>{if(!clinicalRoles.has(a.role))throw err(403,'SPIRE clinical access is required');};
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const json=(v:unknown)=>JSON.stringify(v??{});

async function patientAllowed(prisma:PrismaClient,a:AuthContext,patientId:string){
  ensureClinical(a); const eid=entity(a);
  if(adminRoles.has(a.role)||a.role===UserRole.AUDITOR) return true;
  const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(
    SELECT 1 FROM "SpireEmployeeClientAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "clientId"=$4
    UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW())
  ) AS allowed`,a.organizationId,eid,a.userId,patientId);
  return rows[0]?.allowed===true;
}
async function audit(prisma:PrismaClient,a:AuthContext,action:string,type:string,id:string,data:unknown={}){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)`,a.organizationId,a.legalEntityId??null,a.userId,a.email??null,action,type,id,json(data),a.ipAddress??null,a.userAgent??null);}

export const registerSpireExternalConnectivityRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
  app.get('/api/spire/integrations/endpoints',async(_req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe(`SELECT "id","kind","name","baseUrl","protocol","status","credentialRef","capabilities","config","lastHealthAt","lastHealthStatus","legalEntityId" FROM "SpireIntegrationEndpoint" WHERE "organizationId"=$1 AND ("legalEntityId" IS NULL OR "legalEntityId"=$2) ORDER BY "kind","name"`,a.organizationId,a.legalEntityId??null);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/spire/integrations/endpoints',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const kind=text(req.body?.kind,40),name=text(req.body?.name,140),protocol=text(req.body?.protocol,40),baseUrl=text(req.body?.baseUrl,1000)||null,credentialRef=text(req.body?.credentialRef,250)||null;if(!kind||!name||!protocol)throw err(400,'kind, name and protocol are required');if(credentialRef&&/secret|token|password|key/i.test(credentialRef)===false)throw err(400,'credentialRef must identify a secret-manager/environment key, not contain a credential value');const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireIntegrationEndpoint"("organizationId","legalEntityId","kind","name","baseUrl","protocol","status","credentialRef","capabilities","config","createdById") VALUES($1,$2,$3,$4,$5,$6,'CONFIGURED',$7,$8::jsonb,$9::jsonb,$10) RETURNING "id"`,a.organizationId,a.legalEntityId??null,kind,name,baseUrl,protocol,credentialRef,json(list(req.body?.capabilities)),json(obj(req.body?.config)),a.userId);const id=rows[0].id;await audit(prisma,a,'CREATE_INTEGRATION_ENDPOINT','INTEGRATION_ENDPOINT',id,{kind,name,protocol,baseUrl,credentialRef});res.status(201).json({data:{id}});}catch(e){next(e);}});
  app.post('/api/spire/integrations/endpoints/:endpointId/health',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIntegrationEndpoint" WHERE "organizationId"=$1 AND "id"=$2`,a.organizationId,req.params.endpointId);if(!rows[0])throw err(404,'Integration endpoint not found');const endpoint=rows[0];const baseUrl=text(endpoint.baseUrl,1000);if(!baseUrl)throw err(409,'Endpoint has no base URL');let status='ERROR',detail='unreachable';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);const response=await fetch(baseUrl,{method:'HEAD',signal:controller.signal,redirect:'manual'}).catch(()=>null);clearTimeout(timer);if(response){status=response.status<500?'ACTIVE':'DEGRADED';detail=`HTTP ${response.status}`;}}catch{}await prisma.$executeRawUnsafe(`UPDATE "SpireIntegrationEndpoint" SET "lastHealthAt"=NOW(),"lastHealthStatus"=$1,"status"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "id"=$3`,status,a.organizationId,req.params.endpointId);await audit(prisma,a,'CHECK_INTEGRATION_HEALTH','INTEGRATION_ENDPOINT',req.params.endpointId,{status,detail});res.json({data:{status,detail}});}catch(e){next(e);}});

  app.get('/api/spire/patients/:patientId/imaging/studies',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;if(!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireImagingStudyLink" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "studyDate" DESC NULLS LAST`,a.organizationId,entity(a),patientId);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/spire/patients/:patientId/lis/records',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;if(!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireLabInterfaceRecord" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "receivedAt" DESC`,a.organizationId,entity(a),patientId);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/spire/patients/:patientId/device-feeds',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;if(!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireDeviceFeedRegistration" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "lastSeenAt" DESC NULLS LAST`,a.organizationId,entity(a),patientId);res.json({data:rows});}catch(e){next(e);}});

  app.get('/api/spire/revenue/x12',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireX12Transaction" WHERE "organizationId"=$1 AND ("legalEntityId" IS NULL OR "legalEntityId"=$2) ORDER BY "createdAt" DESC LIMIT 500`,a.organizationId,a.legalEntityId??null);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/spire/revenue/x12',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const transactionSet=text(req.body?.transactionSet,10),direction=text(req.body?.direction,20);if(!transactionSet||!direction)throw err(400,'transactionSet and direction are required');const payload=text(req.body?.payload,5_000_000);const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireX12Transaction"("organizationId","legalEntityId","endpointId","patientId","transactionSet","direction","controlNumber","claimId","status","payloadSha256","metadata") VALUES($1,$2,$3,$4,$5,$6,$7,$8,'QUEUED',$9,$10::jsonb) RETURNING "id"`,a.organizationId,a.legalEntityId??null,text(req.body?.endpointId,120)||null,text(req.body?.patientId,120)||null,transactionSet,direction,text(req.body?.controlNumber,120)||null,text(req.body?.claimId,120)||null,payload?sha(payload):null,json(obj(req.body?.metadata)));const id=rows[0].id;await audit(prisma,a,'QUEUE_X12_TRANSACTION','X12_TRANSACTION',id,{transactionSet,direction});res.status(201).json({data:{id,status:'QUEUED'}});}catch(e){next(e);}});

  app.get('/api/spire/patients/:patientId/erx',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;if(!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireErxTransaction" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC`,a.organizationId,entity(a),patientId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/spire/patients/:patientId/pdmp/query',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;if(!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');if(![UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE,UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO].includes(a.role as any))throw err(403,'PDMP query is restricted');const purpose=text(req.body?.purpose,500);if(!purpose)throw err(400,'Purpose is required');const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpirePdmpQuery"("organizationId","legalEntityId","patientId","endpointId","requestedById","purpose") VALUES($1,$2,$3,$4,$5,$6) RETURNING "id"`,a.organizationId,entity(a),patientId,text(req.body?.endpointId,120)||null,a.userId,purpose);await audit(prisma,a,'REQUEST_PDMP_QUERY','PDMP_QUERY',rows[0].id,{patientId,purpose});res.status(202).json({data:{id:rows[0].id,status:'REQUESTED'}});}catch(e){next(e);}});

  app.post('/api/spire/telehealth/sessions',async(req,res,next)=>{try{const a=authOf(res);ensureClinical(a);const patientId=text(req.body?.patientId,120)||null;if(patientId&&!(await patientAllowed(prisma,a,patientId)))throw err(403,'Chart access denied');if(req.body?.consentRecorded!==true)throw err(400,'Telehealth consent must be recorded before creating the session');const roomKey=randomBytes(18).toString('base64url');const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireTelehealthSession"("organizationId","legalEntityId","patientId","encounterId","endpointId","roomKey","status","consentRecordedAt","transportMode","region","createdById") VALUES($1,$2,$3,$4,$5,$6,'SCHEDULED',NOW(),'SFU',$7,$8) RETURNING "id"`,a.organizationId,entity(a),patientId,text(req.body?.encounterId,120)||null,text(req.body?.endpointId,120)||null,roomKey,text(req.body?.region,80)||null,a.userId);await audit(prisma,a,'CREATE_TELEHEALTH_SESSION','TELEHEALTH_SESSION',rows[0].id,{patientId});res.status(201).json({data:{id:rows[0].id,roomKey}});}catch(e){next(e);}});

  app.get('/api/spire/smart/clients',async(_req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireSmartClient" WHERE "organizationId"=$1 ORDER BY "name"`,a.organizationId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/spire/smart/clients',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const clientId=text(req.body?.clientId,160),name=text(req.body?.name,200);if(!clientId||!name)throw err(400,'clientId and name are required');const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireSmartClient"("organizationId","legalEntityId","clientId","name","redirectUris","launchUris","allowedScopes","tokenEndpointAuthMethod","jwksUri","createdById") VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8,$9,$10) RETURNING "id"`,a.organizationId,a.legalEntityId??null,clientId,name,json(list(req.body?.redirectUris)),json(list(req.body?.launchUris)),json(list(req.body?.allowedScopes)),text(req.body?.tokenEndpointAuthMethod,80)||'private_key_jwt',text(req.body?.jwksUri,1000)||null,a.userId);await audit(prisma,a,'REGISTER_SMART_CLIENT','SMART_CLIENT',rows[0].id,{clientId,name});res.status(201).json({data:{id:rows[0].id}});}catch(e){next(e);}});

  app.post('/api/spire/mobile/push/register',async(req,res,next)=>{try{const a=authOf(res);const token=text(req.body?.token,4096),platform=text(req.body?.platform,20),provider=text(req.body?.provider,20);if(!token||!platform||!provider)throw err(400,'token, platform and provider are required');const tokenHash=sha(token);const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpirePushDevice"("organizationId","legalEntityId","userId","platform","provider","tokenHash","tokenCiphertext","appBundleId","environment") VALUES($1,$2,$3,$4,$5,$6,NULL,$7,$8) ON CONFLICT ("organizationId","userId","provider","tokenHash") DO UPDATE SET "status"='ACTIVE',"lastSeenAt"=NOW(),"updatedAt"=NOW() RETURNING "id"`,a.organizationId,a.legalEntityId??null,a.userId,platform,provider,tokenHash,text(req.body?.appBundleId,250)||null,text(req.body?.environment,40)||'PRODUCTION');res.status(201).json({data:{id:rows[0].id}});}catch(e){next(e);}});
  app.get('/api/spire/mobile/builds',async(_req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "SpireMobileBuild" ORDER BY "createdAt" DESC LIMIT 100`);res.json({data:rows});}catch(e){next(e);}});
};
