import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type Deps={authOf:(res:express.Response)=>AuthContext};
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const nurseRoles=new Set<UserRole>([...adminRoles,UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE]);
const directCareRoles=new Set<UserRole>([...nurseRoles,UserRole.DSP,UserRole.HOUSE_MANAGER]);
const ensure=(ok:boolean,msg:string,status=403)=>{if(!ok)throw Object.assign(new Error(msg),{status})};
const isAdmin=(a:AuthContext)=>adminRoles.has(a.role)||['admin@sulandrahealth.com','doo@sulandrahealth.com'].includes(String(a.email||'').toLowerCase());
const audit=async(prisma:PrismaClient,a:AuthContext,action:string,type:string,id?:string,clientId?:string,before?:unknown,after?:unknown)=>prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","beforeValue","afterValue","ipAddress","userAgent","createdAt") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12,NOW())`,randomUUID(),a.organizationId,a.userId,a.email??null,clientId??null,action,type,id??null,before==null?null:JSON.stringify(before),after==null?null:JSON.stringify(after),a.ipAddress??null,a.userAgent??null);
const access=async(prisma:PrismaClient,a:AuthContext,clientId:string)=>{if(isAdmin(a))return true;const r=await prisma.$queryRawUnsafe<Array<{ok:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" WHERE "organizationId"=$1 AND "userId"=$2 AND "clientId"=$3 UNION ALL SELECT 1 FROM "SpireEmployeeHomeAssignment" h JOIN "SpireClientProfile" c ON c."organizationId"=h."organizationId" AND c."homeId"=h."homeId" WHERE h."organizationId"=$1 AND h."userId"=$2 AND c."clientId"=$3 AND c."active"=TRUE) AS ok`,a.organizationId,a.userId,clientId);return r[0]?.ok===true};
const requireClient=async(prisma:PrismaClient,a:AuthContext,id:string)=>{ensure(directCareRoles.has(a.role)||isAdmin(a),'Clinical chart permission is required');ensure(await access(prisma,a,id),'This client is not assigned to the signed-in employee')};

const eventSchema=z.object({clientId:z.string().min(1),templateKey:z.string().min(1).max(120),rowKey:z.string().min(1).max(160),eventTime:z.coerce.date(),value:z.record(z.unknown()),note:z.string().max(4000).optional(),lateEntryReason:z.string().max(1000).optional(),source:z.string().max(80).default('WEB')});
const catalogSchema=z.object({clientId:z.string().min(1),moduleKey:z.string().min(1).max(120),active:z.boolean(),configuration:z.record(z.unknown()).default({})});
const mappingSchema=z.object({clientId:z.string().min(1),sourceSubmissionId:z.string().min(1).max(250),fields:z.record(z.unknown())});
const templateSchema=z.object({key:z.string().min(1).max(120),name:z.string().min(1).max(200),category:z.string().min(1).max(120),definition:z.record(z.unknown()),active:z.boolean().default(true)});

export const registerSpireCareWorkstationRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{
 const {authOf}=deps;
 app.get('/api/spire/clients/:clientId/intake-map',async(req,res,next)=>{try{const a=authOf(res);await requireClient(prisma,a,req.params.clientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "domain","fieldKey","value","sourceSubmissionId","sourceField","importedAt","reviewedByUserId","updatedAt" FROM "SpireIntakeMappedField" WHERE "organizationId"=$1 AND "clientId"=$2 ORDER BY "domain","fieldKey"`,a.organizationId,req.params.clientId);res.json({data:rows})}catch(e){next(e)}});
 app.put('/api/admin/spire/intake-map',async(req,res,next)=>{try{const a=authOf(res);ensure(isAdmin(a),'Spire administrator permission is required');const p=mappingSchema.parse(req.body);const entries=Object.entries(p.fields);for(const [compound,value] of entries){const [domain,fieldKey]=compound.includes('.')?compound.split('.',2):['GENERAL',compound];await prisma.$executeRawUnsafe(`INSERT INTO "SpireIntakeMappedField"("id","organizationId","clientId","domain","fieldKey","value","sourceSubmissionId","sourceField","importedAt","reviewedByUserId","createdAt","updatedAt") VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,NOW(),$9,NOW(),NOW()) ON CONFLICT("organizationId","clientId","domain","fieldKey") DO UPDATE SET "value"=EXCLUDED."value","sourceSubmissionId"=EXCLUDED."sourceSubmissionId","sourceField"=EXCLUDED."sourceField","reviewedByUserId"=EXCLUDED."reviewedByUserId","updatedAt"=NOW()`,randomUUID(),a.organizationId,p.clientId,domain,fieldKey,JSON.stringify(value),p.sourceSubmissionId,compound,a.userId)}await audit(prisma,a,'INTAKE_MAPPING_APPLIED','SpireIntakeMappedField',undefined,p.clientId,undefined,{sourceSubmissionId:p.sourceSubmissionId,fieldCount:entries.length});res.json({data:{clientId:p.clientId,fieldCount:entries.length}})}catch(e){next(e)}});
 app.get('/api/spire/clients/:clientId/catalog',async(req,res,next)=>{try{const a=authOf(res);await requireClient(prisma,a,req.params.clientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c."moduleKey",c."name",c."category",COALESCE(s."active",FALSE) AS "active",COALESCE(s."configuration",'{}'::jsonb) AS "configuration" FROM "SpireClinicalCatalog" c LEFT JOIN "SpireClientClinicalModule" s ON s."organizationId"=$1 AND s."clientId"=$2 AND s."moduleKey"=c."moduleKey" WHERE c."active"=TRUE ORDER BY c."category",c."name"`,a.organizationId,req.params.clientId);res.json({data:rows})}catch(e){next(e)}});
 app.put('/api/spire/client-catalog',async(req,res,next)=>{try{const a=authOf(res);ensure(nurseRoles.has(a.role)||isAdmin(a),'Nursing permission is required');const p=catalogSchema.parse(req.body);await requireClient(prisma,a,p.clientId);await prisma.$executeRawUnsafe(`INSERT INTO "SpireClientClinicalModule"("id","organizationId","clientId","moduleKey","active","configuration","createdByUserId","createdAt","updatedAt") VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,NOW(),NOW()) ON CONFLICT("organizationId","clientId","moduleKey") DO UPDATE SET "active"=EXCLUDED."active","configuration"=EXCLUDED."configuration","updatedAt"=NOW()`,randomUUID(),a.organizationId,p.clientId,p.moduleKey,p.active,JSON.stringify(p.configuration),a.userId);await audit(prisma,a,p.active?'CLINICAL_MODULE_ACTIVATED':'CLINICAL_MODULE_DEACTIVATED','SpireClientClinicalModule',p.moduleKey,p.clientId,undefined,p);res.json({data:p})}catch(e){next(e)}});
 app.get('/api/spire/clients/:clientId/flowsheet/:templateKey',async(req,res,next)=>{try{const a=authOf(res);await requireClient(prisma,a,req.params.clientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","rowKey","eventTime","value","note","lateEntryReason","source","createdAt","signedAt","authorUserId","amendsEventId" FROM "SpireFlowsheetEvent" WHERE "organizationId"=$1 AND "clientId"=$2 AND "templateKey"=$3 ORDER BY "eventTime","createdAt"`,a.organizationId,req.params.clientId,req.params.templateKey);res.json({data:rows})}catch(e){next(e)}});
 app.post('/api/spire/flowsheet-events',async(req,res,next)=>{try{const a=authOf(res);const p=eventSchema.parse(req.body);await requireClient(prisma,a,p.clientId);const now=new Date();if(p.eventTime.getTime()<now.getTime()-5*60*1000)ensure(Boolean(p.lateEntryReason?.trim()),'A late-entry reason is required when charting a past time',400);const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireFlowsheetEvent"("id","organizationId","clientId","templateKey","rowKey","eventTime","value","note","lateEntryReason","source","authorUserId","createdAt","signedAt") VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,NOW(),NOW())`,id,a.organizationId,p.clientId,p.templateKey,p.rowKey,p.eventTime,JSON.stringify(p.value),p.note??null,p.lateEntryReason??null,p.source,a.userId);await audit(prisma,a,'FLOWSHEET_EVENT_SIGNED','SpireFlowsheetEvent',id,p.clientId,undefined,p);res.status(201).json({data:{id,...p,createdAt:new Date().toISOString(),authorUserId:a.userId}})}catch(e){next(e)}});
 app.post('/api/spire/flowsheet-events/:id/amend',async(req,res,next)=>{try{const a=authOf(res);const original=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireFlowsheetEvent" WHERE "id"=$1 AND "organizationId"=$2`,req.params.id,a.organizationId);ensure(original.length===1,'Original flowsheet event not found',404);const clientId=String(original[0].clientId);await requireClient(prisma,a,clientId);const p=eventSchema.parse({...req.body,clientId});const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireFlowsheetEvent"("id","organizationId","clientId","templateKey","rowKey","eventTime","value","note","lateEntryReason","source","authorUserId","createdAt","signedAt","amendsEventId") VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,NOW(),NOW(),$12)`,id,a.organizationId,clientId,p.templateKey,p.rowKey,p.eventTime,JSON.stringify(p.value),p.note??null,p.lateEntryReason??'Correction/addendum',p.source,a.userId,req.params.id);await audit(prisma,a,'FLOWSHEET_EVENT_AMENDED','SpireFlowsheetEvent',id,clientId,original[0],p);res.status(201).json({data:{id,amendsEventId:req.params.id}})}catch(e){next(e)}});
 app.get('/api/admin/spire/flowsheet-templates',async(_req,res,next)=>{try{const a=authOf(res);ensure(isAdmin(a),'Spire administrator permission is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "key","name","category","definition","active","version","updatedAt" FROM "SpireFlowsheetTemplate" WHERE "organizationId"=$1 ORDER BY "category","name"`,a.organizationId);res.json({data:rows})}catch(e){next(e)}});
 app.put('/api/admin/spire/flowsheet-templates',async(req,res,next)=>{try{const a=authOf(res);ensure(isAdmin(a),'Spire administrator permission is required');const p=templateSchema.parse(req.body);const before=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireFlowsheetTemplate" WHERE "organizationId"=$1 AND "key"=$2`,a.organizationId,p.key);await prisma.$executeRawUnsafe(`INSERT INTO "SpireFlowsheetTemplate"("id","organizationId","key","name","category","definition","active","version","createdByUserId","createdAt","updatedAt") VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,1,$8,NOW(),NOW()) ON CONFLICT("organizationId","key") DO UPDATE SET "name"=EXCLUDED."name","category"=EXCLUDED."category","definition"=EXCLUDED."definition","active"=EXCLUDED."active","version"="SpireFlowsheetTemplate"."version"+1,"updatedAt"=NOW()`,randomUUID(),a.organizationId,p.key,p.name,p.category,JSON.stringify(p.definition),p.active,a.userId);await audit(prisma,a,'FLOWSHEET_TEMPLATE_UPDATED','SpireFlowsheetTemplate',p.key,undefined,before[0],p);res.json({data:p})}catch(e){next(e)}});
 app.get('/api/spire/clients/:clientId/compliance-readiness',async(req,res,next)=>{try{const a=authOf(res);await requireClient(prisma,a,req.params.clientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "domain","requirementKey","label","status","evidenceCount","lastEvidenceAt","notes" FROM "SpireComplianceRequirementStatus" WHERE "organizationId"=$1 AND "clientId"=$2 ORDER BY "domain","label"`,a.organizationId,req.params.clientId);res.json({data:rows})}catch(e){next(e)}});
};
