import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinical=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const selectedEntity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening SPIRE');return a.legalEntityId;};
const ensure=(a:AuthContext)=>{if(!clinical.has(a.role)&&a.enterpriseOwner!==true&&String(a.email||'').toLowerCase()!=='admin@sulandrahealth.com')throw httpError(403,'SPIRE clinical access is required');selectedEntity(a);};
const safeName=(v:string)=>v.replace(/[\r\n"]/g,'_').replace(/[\\/]/g,'_').slice(0,300)||'intake-document';
async function log(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,resourceId?:string){await prisma.$executeRawUnsafe(`INSERT INTO "SpireChartAccessEvent"("organizationId","legalEntityId","patientId","actorUserId","actorEmail","action","resourceType","resourceId","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,$6,'ADMISSION_HISTORY',$7,$8,$9)`,a.organizationId,selectedEntity(a),patientId,a.userId,a.email??null,action,resourceId??null,a.ipAddress??null,a.userAgent??null);}

export const registerSpireAdmissionHistoryRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
  app.get('/api/spire/patients/:patientId/admission-history',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const patientId=req.params.patientId;const cases=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT intake."id",intake."legalEntityId",entity."code" AS "companyCode",entity."displayName" AS "companyName",intake."serviceType",intake."programCode",intake."referralSource",intake."referralDate",intake."approvedAt",intake."approvedById",intake."reviewNotes",intake."createdAt" FROM "ClientIntakeCase" intake JOIN "LegalEntity" entity ON entity."organizationId"=intake."organizationId" AND entity."id"=intake."legalEntityId" WHERE intake."organizationId"=$1 AND intake."patientId"=$2 AND intake."status"='APPROVED' ORDER BY intake."approvedAt" DESC NULLS LAST,intake."createdAt" DESC`,a.organizationId,patientId);const out=[];for(const c of cases){const caseId=String(c.id);const[sections,attachments,signatures]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "sectionKey","sectionTitle","sectionGroup","status","payload","completedAt","reviewState","reviewComment","updatedAt" FROM "ClientIntakeSection" WHERE "organizationId"=$1 AND "intakeCaseId"=$2 AND "status" IN ('COMPLETE','NOT_APPLICABLE') ORDER BY "createdAt","sectionKey"`,a.organizationId,caseId),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","sectionKey","documentType","title","originalFileName","mimeType","sizeBytes","sha256","expirationDate","notes","createdAt" FROM "ClientIntakeAttachment" WHERE "organizationId"=$1 AND "intakeCaseId"=$2 AND "status"='ACTIVE' ORDER BY "createdAt" DESC`,a.organizationId,caseId),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "signatureType","signerName","signerRelationship","signatureMethod","attestation","signedAt" FROM "ClientIntakeSignature" WHERE "organizationId"=$1 AND "intakeCaseId"=$2 AND "revokedAt" IS NULL ORDER BY "signedAt" DESC`,a.organizationId,caseId)]);out.push({...c,sections,attachments,signatures});}await log(prisma,a,patientId,'VIEW_ADMISSION_HISTORY');res.json({data:{patientId,selectedLegalEntityId:selectedEntity(a),admissions:out}});}catch(e){next(e);}});

  app.get('/api/spire/patients/:patientId/admission-history/:caseId/attachments/:attachmentId/download',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const patientId=req.params.patientId;const rows=await prisma.$queryRawUnsafe<Array<{id:string;originalFileName:string;mimeType:string;sizeBytes:number;sha256:string;content:Buffer;sourceLegalEntityId:string;companyName:string}>>(`SELECT attachment."id",attachment."originalFileName",attachment."mimeType",attachment."sizeBytes",attachment."sha256",attachment."content",intake."legalEntityId" AS "sourceLegalEntityId",entity."displayName" AS "companyName" FROM "ClientIntakeAttachment" attachment JOIN "ClientIntakeCase" intake ON intake."id"=attachment."intakeCaseId" AND intake."organizationId"=attachment."organizationId" JOIN "LegalEntity" entity ON entity."organizationId"=intake."organizationId" AND entity."id"=intake."legalEntityId" WHERE attachment."organizationId"=$1 AND intake."patientId"=$2 AND intake."id"=$3 AND attachment."id"=$4 AND intake."status"='APPROVED' AND attachment."status"='ACTIVE' LIMIT 1`,a.organizationId,patientId,req.params.caseId,req.params.attachmentId);const x=rows[0];if(!x)throw httpError(404,'Approved intake document was not found');await log(prisma,a,patientId,'DOWNLOAD_ADMISSION_DOCUMENT',x.id);res.setHeader('Content-Type',x.mimeType||'application/octet-stream');res.setHeader('Content-Length',String(x.sizeBytes));res.setHeader('Content-Disposition',`attachment; filename="${safeName(x.originalFileName)}"`);res.setHeader('X-Sulandra-Source-Entity',x.sourceLegalEntityId);res.setHeader('Cache-Control','private, no-store');res.send(x.content);}catch(e){next(e);}});
};
