import { createHash, randomUUID } from 'node:crypto';
import type { Express, Response } from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string};
type Deps={authOf:(response:Response)=>AuthContext};
const readers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const owner=(a:AuthContext)=>String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before OhioITMS handoff');return a.legalEntityId;};
const ensureRead=(a:AuthContext)=>{entity(a);if(!readers.has(a.role)&&!owner(a))throw httpError(403,'Incident compliance access is required');};
const ensureWrite=(a:AuthContext)=>{ensureRead(a);if(!writers.has(a.role)&&!owner(a))throw httpError(403,'Incident handoff write access is required');};
const clean=(v:unknown,max=5000)=>String(v??'').trim().slice(0,max);
const handoffSchema=z.object({notes:z.string().trim().max(5000).optional().nullable()});
const eventSchema=z.object({eventType:z.enum(['SUBMITTED_TO_COUNTY_BOARD','COUNTY_BOARD_ACKNOWLEDGED','OITMS_REFERENCE_RECORDED','RETURNED_FOR_CORRECTION','RESUBMITTED_TO_COUNTY_BOARD','CLOSURE_RECOMMENDED','CLOSED_EXTERNALLY']),occurredAt:z.string().datetime(),submissionMethod:z.enum(['COUNTY_BOARD_PORTAL','SECURE_EMAIL','FAX','PHONE_CONFIRMED','IN_PERSON','OTHER']).optional().nullable(),externalReference:z.string().trim().max(500).optional().nullable(),evidenceDocumentId:z.string().trim().max(300).optional().nullable(),notes:z.string().trim().max(5000).optional().nullable(),payload:z.record(z.unknown()).default({})}).superRefine((v,ctx)=>{if(['SUBMITTED_TO_COUNTY_BOARD','COUNTY_BOARD_ACKNOWLEDGED','RESUBMITTED_TO_COUNTY_BOARD','OITMS_REFERENCE_RECORDED','CLOSED_EXTERNALLY'].includes(v.eventType)&&!v.externalReference&&!v.evidenceDocumentId)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Record an external reference or evidence document ID for this handoff event'});if(v.eventType==='OITMS_REFERENCE_RECORDED'&&!v.externalReference)ctx.addIssue({code:z.ZodIssueCode.custom,message:'The actual OITMS reference assigned externally is required'});});

async function allowed(p:PrismaClient,a:AuthContext,pid:string){if([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO].includes(a.role)||owner(a))return true;const rows=await p.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" ph JOIN "SpireEmployeeHomeAssignment" eh ON eh."organizationId"=ph."organizationId" AND eh."homeId"=ph."homeId" WHERE ph."organizationId"=$1 AND eh."userId"=$2 AND ph."patientId"=$3 AND (ph."endsAt" IS NULL OR ph."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,pid);return rows[0]?.allowed===true;}
async function requirePatient(p:PrismaClient,a:AuthContext,pid:string,write=false){write?ensureWrite(a):ensureRead(a);if(!(await allowed(p,a,pid)))throw httpError(403,'This chart is outside your authorized clinical scope');}
async function currentCase(p:PrismaClient,a:AuthContext,pid:string,incidentId:string){const rows=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c.*,i."incidentNumber",i."incidentType",i."occurredAt",i."location",i."description",i."injuryDetails",i."immediateActions",i."reportedByUserId",i."createdAt" AS "incidentCreatedAt" FROM "SpireIncidentRegulatoryCase" c JOIN "SpireIncident" i ON i."id"=c."incidentId" AND i."organizationId"=c."organizationId" AND i."legalEntityId"=c."legalEntityId" WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."patientId"=$3 AND c."incidentId"=$4 LIMIT 1`,a.organizationId,entity(a),pid,incidentId);if(!rows[0])throw httpError(409,'Classify this incident in the Ohio regulatory workflow before creating an OITMS handoff');if(String(rows[0].classification)!=='MUI')throw httpError(409,'Only a classified MUI belongs in the OhioITMS handoff workflow. UI incidents remain in the provider UI log.');return rows[0];}
async function packageSnapshot(p:PrismaClient,a:AuthContext,pid:string,incidentId:string){const c=await currentCase(p,a,pid,incidentId);const caseId=String(c.id);const [deadlines,regEvents,witnesses,notifications,investigations]=await Promise.all([
 p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentRegulatoryDeadline" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "regulatoryCaseId"=$3 ORDER BY "dueAt" NULLS LAST,"deadlineType"`,a.organizationId,entity(a),caseId),
 p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentRegulatoryEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "regulatoryCaseId"=$3 ORDER BY "createdAt"`,a.organizationId,entity(a),caseId),
 p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentWitness" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,incidentId),
 p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentNotification" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,incidentId),
 p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentInvestigation" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,incidentId),
 ]);
 return{generatedAt:new Date().toISOString(),handoffBoundary:{handoffMode:'COUNTY_BOARD_FOR_OITMS',liveOitmsIntegrationConfigured:false,directOitmsSubmissionPerformed:false,providerObligation:'Submit required MUI incident report/forms to the county board using the means identified by the county board; record externally assigned OITMS references only after receipt.',authority:'Ohio Administrative Code 5123-17-02',authorityUrl:'https://codes.ohio.gov/ohio-administrative-code/rule-5123-17-02'},regulatoryCase:c,deadlines,regulatoryEvents:regEvents,witnesses,notifications,investigations};
}
async function handoff(p:PrismaClient,a:AuthContext,pid:string,incidentId:string,handoffId:string){const rows=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentOitmsHandoff" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "incidentId"=$4 AND "id"=$5 LIMIT 1`,a.organizationId,entity(a),pid,incidentId,handoffId);if(!rows[0])throw httpError(404,'OhioITMS handoff package was not found');return rows[0];}
async function events(p:PrismaClient,a:AuthContext,handoffId:string){return p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentOitmsHandoffEvent" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "handoffId"=$3 ORDER BY "occurredAt","createdAt"`,a.organizationId,entity(a),handoffId);}
const latestType=(rows:Array<Record<string,unknown>>)=>String(rows.at(-1)?.eventType||'PACKAGE_GENERATED');
function validateTransition(previous:string,next:string){const allowed:Record<string,string[]>={PACKAGE_GENERATED:['SUBMITTED_TO_COUNTY_BOARD','RETURNED_FOR_CORRECTION'],SUBMITTED_TO_COUNTY_BOARD:['COUNTY_BOARD_ACKNOWLEDGED','OITMS_REFERENCE_RECORDED','RETURNED_FOR_CORRECTION'],COUNTY_BOARD_ACKNOWLEDGED:['OITMS_REFERENCE_RECORDED','RETURNED_FOR_CORRECTION','CLOSURE_RECOMMENDED'],OITMS_REFERENCE_RECORDED:['RETURNED_FOR_CORRECTION','CLOSURE_RECOMMENDED','CLOSED_EXTERNALLY'],RETURNED_FOR_CORRECTION:['RESUBMITTED_TO_COUNTY_BOARD'],RESUBMITTED_TO_COUNTY_BOARD:['COUNTY_BOARD_ACKNOWLEDGED','OITMS_REFERENCE_RECORDED','RETURNED_FOR_CORRECTION'],CLOSURE_RECOMMENDED:['CLOSED_EXTERNALLY','RETURNED_FOR_CORRECTION'],CLOSED_EXTERNALLY:[]};if(!(allowed[previous]||[]).includes(next))throw httpError(409,`Cannot record ${next} after ${previous}. Generate a new corrected package when the frozen package no longer represents the submitted evidence.`);}

export const registerSpireIncidentOitmsHandoffRoutes=(app:Express,p:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/incidents/regulatory/oitms/boundary',async(_req,res,next)=>{try{const a=authOf(res);ensureRead(a);res.json({data:{system:'Ohio incident tracking and monitoring system (OITMS)',mode:'COUNTY_BOARD_HANDOFF',liveOitmsIntegrationConfigured:false,directOitmsSubmissionEnabled:false,externalCredentialsConfigured:false,authority:'Ohio Administrative Code 5123-17-02',authorityUrl:'https://codes.ohio.gov/ohio-administrative-code/rule-5123-17-02',warning:'SPIRE prepares and audits provider handoff evidence. It does not claim a public DODD OITMS provider API or submit directly to OITMS.'}});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/incidents/:incidentId/regulatory/oitms',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(p,a,pid);const c=await currentCase(p,a,pid,req.params.incidentId);const rows=await p.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentOitmsHandoff" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "incidentId"=$4 ORDER BY "generatedAt" DESC`,a.organizationId,entity(a),pid,req.params.incidentId),data=[];for(const row of rows){const history=await events(p,a,String(row.id));data.push({...row,currentStatus:latestType(history),events:history});}res.json({data:{regulatoryCaseId:c.id,classification:c.classification,muiCategory:c.muiCategory,muiType:c.muiType,handoffs:data,liveOitmsIntegrationConfigured:false}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/regulatory/oitms/handoffs',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(p,a,pid,true);const i=handoffSchema.parse(req.body),snapshot=await packageSnapshot(p,a,pid,req.params.incidentId),caseId=String((snapshot.regulatoryCase as Record<string,unknown>).id),text=JSON.stringify(snapshot),packageSha256=createHash('sha256').update(text).digest('hex'),id=randomUUID(),handoffNumber=`MUI-HANDOFF-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,8).toUpperCase()}`;await p.$executeRawUnsafe(`INSERT INTO "SpireIncidentOitmsHandoff"("id","organizationId","legalEntityId","patientId","incidentId","regulatoryCaseId","handoffNumber","generatedByUserId","packageSha256","packageSnapshot","notes") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11)`,id,a.organizationId,entity(a),pid,req.params.incidentId,caseId,handoffNumber,a.userId,packageSha256,text,i.notes??null);await p.$executeRawUnsafe(`INSERT INTO "SpireIncidentOitmsHandoffEvent"("organizationId","legalEntityId","handoffId","eventType","occurredAt","notes","payload","actorUserId") VALUES($1,$2,$3,'PACKAGE_GENERATED',NOW(),$4,$5::jsonb,$6)`,a.organizationId,entity(a),id,i.notes??null,JSON.stringify({packageSha256,handoffNumber}),a.userId);res.status(201).json({data:{id,handoffNumber,packageSha256,currentStatus:'PACKAGE_GENERATED',handoffMode:'COUNTY_BOARD_FOR_OITMS',liveOitmsIntegrationConfigured:false,immutablePackage:true}});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/incidents/:incidentId/regulatory/oitms/handoffs/:handoffId/package.json',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(p,a,pid);const row=await handoff(p,a,pid,req.params.incidentId,req.params.handoffId);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${String(row.handoffNumber).replace(/[^A-Za-z0-9_-]/g,'_')}.json"`);res.setHeader('Cache-Control','private, no-store');res.send(JSON.stringify({handoffNumber:row.handoffNumber,packageSha256:row.packageSha256,generatedAt:row.generatedAt,authority:row.authority,authorityUrl:row.authorityUrl,packageSnapshot:row.packageSnapshot},null,2));}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/regulatory/oitms/handoffs/:handoffId/events',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(p,a,pid,true);const row=await handoff(p,a,pid,req.params.incidentId,req.params.handoffId),i=eventSchema.parse(req.body),history=await events(p,a,String(row.id)),previous=latestType(history);validateTransition(previous,i.eventType);const id=randomUUID();await p.$executeRawUnsafe(`INSERT INTO "SpireIncidentOitmsHandoffEvent"("id","organizationId","legalEntityId","handoffId","eventType","occurredAt","submissionMethod","externalReference","evidenceDocumentId","notes","payload","actorUserId") VALUES($1,$2,$3,$4,$5,$6::timestamptz,$7,$8,$9,$10,$11::jsonb,$12)`,id,a.organizationId,entity(a),String(row.id),i.eventType,i.occurredAt,i.submissionMethod??null,i.externalReference??null,i.evidenceDocumentId??null,i.notes??null,JSON.stringify(i.payload),a.userId);if(i.eventType==='OITMS_REFERENCE_RECORDED'){const c=await currentCase(p,a,pid,req.params.incidentId),before=clean(c.oitmsReference,500)||null;await p.$executeRawUnsafe(`UPDATE "SpireIncidentRegulatoryCase" SET "oitmsReference"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "patientId"=$4 AND "incidentId"=$5`,i.externalReference,a.organizationId,entity(a),pid,req.params.incidentId);await p.$executeRawUnsafe(`INSERT INTO "SpireIncidentRegulatoryEvent"("organizationId","legalEntityId","patientId","incidentId","regulatoryCaseId","eventType","beforeValue","afterValue","reason","actorUserId") VALUES($1,$2,$3,$4,$5,'OITMS_REFERENCE_SYNCED',$6::jsonb,$7::jsonb,$8,$9)`,a.organizationId,entity(a),pid,req.params.incidentId,String(c.id),JSON.stringify(before),JSON.stringify(i.externalReference),i.notes??'Externally assigned OITMS reference recorded from handoff evidence',a.userId);}res.status(201).json({data:{id,eventType:i.eventType,previousStatus:previous,currentStatus:i.eventType,externalReference:i.externalReference??null,evidenceDocumentId:i.evidenceDocumentId??null,directOitmsSubmissionPerformed:false}});}catch(e){next(e);}});
};
