import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writeRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const text=(v:unknown,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown)=>v===''||v===null||v===undefined?null:(Number.isFinite(Number(v))?Number(v):null);
const int=(v:unknown)=>{const n=num(v);return n===null?null:Math.trunc(n);};
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const list=(v:unknown)=>Array.isArray(v)?v:[];
const err=(status:number,message:string)=>Object.assign(new Error(message),{status});
const isAdmin=(a:AuthContext)=>adminRoles.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{const id=text(a.legalEntityId,120);if(!id)throw err(409,'Select a Sulandra company before using SPIRE specialty care');return id;};
const ensureClinical=(a:AuthContext)=>{if(!clinicalRoles.has(a.role))throw err(403,'SPIRE clinical access is required');};
const ensureWrite=(a:AuthContext)=>{ensureClinical(a);if(!writeRoles.has(a.role))throw err(403,'This SPIRE role is read-only');};
async function allowed(prisma:PrismaClient,a:AuthContext,patientId:string){const eid=entity(a);const enrolled=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "ClientEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "clientId"=$3 AND "status" IN ('PENDING','ACTIVE','PAUSED')) AS allowed`,a.organizationId,eid,patientId);if(enrolled[0]?.allowed!==true)return false;if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(
SELECT 1 FROM "SpireEmployeeClientAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "clientId"=$4
UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW())
UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$3 AND g."scopeType"='CLIENT' AND g."clientId"=$4 AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())) AS allowed`,a.organizationId,eid,a.userId,patientId);return rows[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string,write=false){write?ensureWrite(a):ensureClinical(a);if(!(await allowed(prisma,a,patientId)))throw err(403,'This chart is outside your authorized clinical scope');}
async function audit(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,type:string,id:string,data:unknown={}){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,a.organizationId,entity(a),a.userId,a.email??null,patientId,action,type,id,JSON.stringify(data??{}),a.ipAddress??null,a.userAgent??null);}
async function episodeExists(prisma:PrismaClient,a:AuthContext,patientId:string,episodeId:string){if(!episodeId)return true;const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireSpecialtyEpisode" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$4`,a.organizationId,entity(a),patientId,episodeId);return Boolean(rows[0]);}

export const registerSpireSpecialtyCareParityRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
app.get('/api/spire/patients/:patientId/specialty-care/overview',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const eid=entity(a);const [episodes,observations,procedures,pregnancies,oncology,dialysis,transplant,genomics,dental,eye,derm,ortho,endoscopy,cardiology]=await Promise.all([
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireSpecialtyEpisode" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY CASE "status" WHEN 'ACTIVE' THEN 0 WHEN 'PLANNED' THEN 1 ELSE 2 END,"startedAt" DESC LIMIT 200`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireSpecialtyObservation" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "observedAt" DESC LIMIT 500`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireSpecialtyProcedureReport" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "performedAt" DESC LIMIT 250`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT p.*,COALESCE((SELECT jsonb_agg(l ORDER BY l."occurredAt") FROM "SpireLaborEvent" l WHERE l."pregnancyEpisodeId"=p."id"),'[]'::jsonb) AS "laborEvents" FROM "SpirePregnancyEpisode" p WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND p."patientId"=$3 ORDER BY p."createdAt" DESC LIMIT 25`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT p.*,COALESCE((SELECT jsonb_agg(c ORDER BY c."cycleNumber",c."dayNumber") FROM "SpireOncologyCycle" c WHERE c."treatmentPlanId"=p."id"),'[]'::jsonb) AS cycles,COALESCE((SELECT jsonb_agg(ad ORDER BY ad."createdAt" DESC) FROM "SpireOncologyAdministration" ad WHERE ad."treatmentPlanId"=p."id"),'[]'::jsonb) AS administrations FROM "SpireOncologyTreatmentPlan" p WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND p."patientId"=$3 ORDER BY p."createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireDialysisTreatment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "startedAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireTransplantEpisode" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireGenomicResult" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "resultedAt" DESC NULLS LAST,"createdAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireDentalFinding" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "recordedAt" DESC LIMIT 250`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireOphthalmologyExam" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "examinedAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireDermatologyLesion" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "recordedAt" DESC LIMIT 250`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireOrthopedicAssessment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "recordedAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireEndoscopyReport" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "performedAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireCardiologyProcedureReport" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "performedAt" DESC LIMIT 100`,a.organizationId,eid,patientId)
]);res.json({data:{episodes,observations,procedures,pregnancies,oncologyPlans:oncology,dialysisTreatments:dialysis,transplantEpisodes:transplant,genomicResults:genomics,dentalFindings:dental,ophthalmologyExams:eye,dermatologyLesions:derm,orthopedicAssessments:ortho,endoscopyReports:endoscopy,cardiologyReports:cardiology}});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/specialty-care/episodes',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const specialty=text(req.body?.specialty,80).toUpperCase(),title=text(req.body?.title,250),episodeType=text(req.body?.episodeType,120);if(!specialty||!title||!episodeType)throw err(400,'Specialty, episode type and title are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireSpecialtyEpisode"("organizationId","legalEntityId","patientId","encounterId","specialty","episodeType","title","status","diagnosis","primaryProviderUserId","careTeam","metadata","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.encounterId,120)||null,specialty,episodeType,title,text(req.body?.status,30)||'ACTIVE',text(req.body?.diagnosis,1000)||null,text(req.body?.primaryProviderUserId,120)||null,JSON.stringify(list(req.body?.careTeam)),JSON.stringify(obj(req.body?.metadata)),a.userId);await audit(prisma,a,patientId,'CREATE_SPECIALTY_EPISODE','SPECIALTY_EPISODE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.patch('/api/spire/patients/:patientId/specialty-care/episodes/:episodeId',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const status=text(req.body?.status,30).toUpperCase();if(!['PLANNED','ACTIVE','ON_HOLD','COMPLETE','CANCELLED'].includes(status))throw err(400,'Valid specialty episode status is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireSpecialtyEpisode" SET "status"=$1,"diagnosis"=COALESCE($2,"diagnosis"),"endedAt"=CASE WHEN $1 IN ('COMPLETE','CANCELLED') THEN NOW() ELSE "endedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "patientId"=$5 AND "id"=$6 RETURNING *`,status,text(req.body?.diagnosis,1000)||null,a.organizationId,entity(a),patientId,req.params.episodeId);if(!rows[0])throw err(404,'Specialty episode not found');await audit(prisma,a,patientId,'UPDATE_SPECIALTY_EPISODE','SPECIALTY_EPISODE',req.params.episodeId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/observations',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const specialty=text(req.body?.specialty,80).toUpperCase(),observationType=text(req.body?.observationType,160);if(!specialty||!observationType)throw err(400,'Specialty and observation type are required');const episodeId=text(req.body?.episodeId,120);if(!(await episodeExists(prisma,a,patientId,episodeId)))throw err(404,'Specialty episode not found');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireSpecialtyObservation"("organizationId","legalEntityId","patientId","episodeId","encounterId","specialty","observationType","bodySite","laterality","value","numericValue","unit","interpretation","details","observedAt","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,COALESCE($15,NOW()),$16) RETURNING *`,a.organizationId,entity(a),patientId,episodeId||null,text(req.body?.encounterId,120)||null,specialty,observationType,text(req.body?.bodySite,120)||null,text(req.body?.laterality,30)||null,text(req.body?.value,1000)||null,num(req.body?.numericValue),text(req.body?.unit,60)||null,text(req.body?.interpretation,1000)||null,JSON.stringify(obj(req.body?.details)),req.body?.observedAt?new Date(String(req.body.observedAt)):null,a.userId);await audit(prisma,a,patientId,'RECORD_SPECIALTY_OBSERVATION','SPECIALTY_OBSERVATION',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/procedure-reports',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const specialty=text(req.body?.specialty,80).toUpperCase(),procedureName=text(req.body?.procedureName,250);if(!specialty||!procedureName)throw err(400,'Specialty and procedure name are required');const episodeId=text(req.body?.episodeId,120);if(!(await episodeExists(prisma,a,patientId,episodeId)))throw err(404,'Specialty episode not found');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireSpecialtyProcedureReport"("organizationId","legalEntityId","patientId","episodeId","encounterId","specialty","procedureName","bodySite","laterality","indication","findings","impression","complications","performedAt","performedById","structuredData","status") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,COALESCE($14,NOW()),$15,$16::jsonb,$17) RETURNING *`,a.organizationId,entity(a),patientId,episodeId||null,text(req.body?.encounterId,120)||null,specialty,procedureName,text(req.body?.bodySite,120)||null,text(req.body?.laterality,30)||null,text(req.body?.indication,3000)||null,text(req.body?.findings,10000)||null,text(req.body?.impression,5000)||null,text(req.body?.complications,3000)||null,req.body?.performedAt?new Date(String(req.body.performedAt)):null,text(req.body?.performedById,120)||a.userId,JSON.stringify(obj(req.body?.structuredData)),text(req.body?.status,30)||'FINAL');await audit(prisma,a,patientId,'CREATE_SPECIALTY_PROCEDURE_REPORT','SPECIALTY_PROCEDURE_REPORT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/specialty-care/pregnancies',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePregnancyEpisode"("organizationId","legalEntityId","patientId","specialtyEpisodeId","gravida","para","estimatedDueDate","lastMenstrualPeriod","gestationalAgeAtStart","pregnancyStatus","riskFactors","fetusCount","prenatalSummary","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.specialtyEpisodeId,120)||null,int(req.body?.gravida),int(req.body?.para),req.body?.estimatedDueDate?new Date(String(req.body.estimatedDueDate)):null,req.body?.lastMenstrualPeriod?new Date(String(req.body.lastMenstrualPeriod)):null,text(req.body?.gestationalAgeAtStart,80)||null,text(req.body?.pregnancyStatus,40)||'PREGNANT',JSON.stringify(list(req.body?.riskFactors)),int(req.body?.fetusCount)||1,text(req.body?.prenatalSummary,10000)||null,a.userId);await audit(prisma,a,patientId,'CREATE_PREGNANCY_EPISODE','PREGNANCY_EPISODE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/pregnancies/:pregnancyId/labor-events',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const eventType=text(req.body?.eventType,120);if(!eventType)throw err(400,'Labor event type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireLaborEvent"("organizationId","legalEntityId","patientId","pregnancyEpisodeId","eventType","cervicalDilationCm","effacementPercent","station","fetalHeartRate","contractionPattern","membraneStatus","details","occurredAt","recordedById") SELECT $1,$2,$3,"id",$4,$5,$6,$7,$8,$9,$10,$11::jsonb,COALESCE($12,NOW()),$13 FROM "SpirePregnancyEpisode" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$14 RETURNING *`,a.organizationId,entity(a),patientId,eventType,num(req.body?.cervicalDilationCm),int(req.body?.effacementPercent),text(req.body?.station,30)||null,int(req.body?.fetalHeartRate),text(req.body?.contractionPattern,1000)||null,text(req.body?.membraneStatus,120)||null,JSON.stringify(obj(req.body?.details)),req.body?.occurredAt?new Date(String(req.body.occurredAt)):null,a.userId,req.params.pregnancyId);if(!rows[0])throw err(404,'Pregnancy episode not found');await audit(prisma,a,patientId,'RECORD_LABOR_EVENT','LABOR_EVENT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/specialty-care/oncology/plans',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const diagnosis=text(req.body?.diagnosis,1000),regimenName=text(req.body?.regimenName,250);if(!diagnosis||!regimenName)throw err(400,'Oncology diagnosis and regimen are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOncologyTreatmentPlan"("organizationId","legalEntityId","patientId","specialtyEpisodeId","diagnosis","stage","intent","protocolName","regimenName","status","cycleCount","startDate","endDate","treatmentParameters","verification","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'PLANNED',$10,$11,$12,$13::jsonb,$14::jsonb,$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.specialtyEpisodeId,120)||null,diagnosis,text(req.body?.stage,120)||null,text(req.body?.intent,120)||null,text(req.body?.protocolName,250)||null,regimenName,int(req.body?.cycleCount),req.body?.startDate?new Date(String(req.body.startDate)):null,req.body?.endDate?new Date(String(req.body.endDate)):null,JSON.stringify(obj(req.body?.treatmentParameters)),JSON.stringify(obj(req.body?.verification)),a.userId);await audit(prisma,a,patientId,'CREATE_ONCOLOGY_PLAN','ONCOLOGY_TREATMENT_PLAN',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/oncology/plans/:planId/approve',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);if(![UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE,UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO].includes(a.role))throw err(403,'Clinical approval privileges are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireOncologyTreatmentPlan" SET "status"='ACTIVE',"approvedById"=$1,"approvedAt"=NOW(),"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "patientId"=$4 AND "id"=$5 AND "status"='PLANNED' RETURNING *`,a.userId,a.organizationId,entity(a),patientId,req.params.planId);if(!rows[0])throw err(404,'Planned oncology treatment plan not found');await audit(prisma,a,patientId,'APPROVE_ONCOLOGY_PLAN','ONCOLOGY_TREATMENT_PLAN',req.params.planId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/oncology/plans/:planId/cycles',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const cycle=int(req.body?.cycleNumber);if(!cycle||cycle<1)throw err(400,'Cycle number is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOncologyCycle"("organizationId","legalEntityId","patientId","treatmentPlanId","cycleNumber","dayNumber","scheduledAt","status","preTreatmentChecklist","labsReviewed","parametersMet","holdReason") SELECT $1,$2,$3,"id",$4,$5,$6,$7,$8::jsonb,$9,$10,$11 FROM "SpireOncologyTreatmentPlan" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$12 AND "status" IN ('ACTIVE','ON_HOLD') RETURNING *`,a.organizationId,entity(a),patientId,cycle,int(req.body?.dayNumber)||1,req.body?.scheduledAt?new Date(String(req.body.scheduledAt)):null,text(req.body?.status,30)||'PLANNED',JSON.stringify(obj(req.body?.preTreatmentChecklist)),req.body?.labsReviewed===true,typeof req.body?.parametersMet==='boolean'?req.body.parametersMet:null,text(req.body?.holdReason,2000)||null,req.params.planId);if(!rows[0])throw err(404,'Active oncology plan not found');await audit(prisma,a,patientId,'CREATE_ONCOLOGY_CYCLE','ONCOLOGY_CYCLE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/oncology/plans/:planId/administrations',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const agent=text(req.body?.agentName,250),dose=text(req.body?.dose,120);if(!agent||!dose)throw err(400,'Oncology agent and dose are required');const verifiedBy=text(req.body?.verifiedById,120);if(!verifiedBy)throw err(400,'Independent verifier is required before treatment administration');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOncologyAdministration"("organizationId","legalEntityId","patientId","treatmentPlanId","cycleId","agentName","dose","route","status","startedAt","verifiedById","administeredById","details") SELECT $1,$2,$3,"id",$4,$5,$6,$7,'STARTED',NOW(),$8,$9,$10::jsonb FROM "SpireOncologyTreatmentPlan" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$11 AND "status"='ACTIVE' RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.cycleId,120)||null,agent,dose,text(req.body?.route,80)||null,verifiedBy,a.userId,JSON.stringify(obj(req.body?.details)),req.params.planId);if(!rows[0])throw err(404,'Active oncology plan not found');await audit(prisma,a,patientId,'START_ONCOLOGY_ADMINISTRATION','ONCOLOGY_ADMINISTRATION',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/specialty-care/dialysis',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const treatmentType=text(req.body?.treatmentType,120);if(!treatmentType)throw err(400,'Dialysis treatment type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireDialysisTreatment"("organizationId","legalEntityId","patientId","specialtyEpisodeId","treatmentType","accessType","preWeight","postWeight","targetWeight","ultrafiltrationGoalMl","ultrafiltrationRemovedMl","dialysate","startedAt","completedAt","status","complications","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,COALESCE($13,NOW()),$14,$15,$16,$17) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.specialtyEpisodeId,120)||null,treatmentType,text(req.body?.accessType,120)||null,num(req.body?.preWeight),num(req.body?.postWeight),num(req.body?.targetWeight),num(req.body?.ultrafiltrationGoalMl),num(req.body?.ultrafiltrationRemovedMl),JSON.stringify(obj(req.body?.dialysate)),req.body?.startedAt?new Date(String(req.body.startedAt)):null,req.body?.completedAt?new Date(String(req.body.completedAt)):null,text(req.body?.status,30)||'IN_PROGRESS',text(req.body?.complications,5000)||null,a.userId);await audit(prisma,a,patientId,'RECORD_DIALYSIS_TREATMENT','DIALYSIS_TREATMENT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/transplant',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const organ=text(req.body?.organ,120);if(!organ)throw err(400,'Transplant organ is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireTransplantEpisode"("organizationId","legalEntityId","patientId","specialtyEpisodeId","organ","phase","listingStatus","listingDate","transplantDate","donorType","center","compatibility","immunosuppression","status","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14,$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.specialtyEpisodeId,120)||null,organ,text(req.body?.phase,80)||'EVALUATION',text(req.body?.listingStatus,120)||null,req.body?.listingDate?new Date(String(req.body.listingDate)):null,req.body?.transplantDate?new Date(String(req.body.transplantDate)):null,text(req.body?.donorType,120)||null,text(req.body?.center,250)||null,JSON.stringify(obj(req.body?.compatibility)),JSON.stringify(obj(req.body?.immunosuppression)),text(req.body?.status,30)||'ACTIVE',a.userId);await audit(prisma,a,patientId,'CREATE_TRANSPLANT_EPISODE','TRANSPLANT_EPISODE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/genomics',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const testName=text(req.body?.testName,250);if(!testName)throw err(400,'Genomic test name is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireGenomicResult"("organizationId","legalEntityId","patientId","specialtyEpisodeId","testName","gene","variant","zygosity","classification","clinicalSignificance","pharmacogenomicImplication","tumorBiomarker","resultedAt","laboratory","structuredData") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.specialtyEpisodeId,120)||null,testName,text(req.body?.gene,120)||null,text(req.body?.variant,500)||null,text(req.body?.zygosity,80)||null,text(req.body?.classification,120)||null,text(req.body?.clinicalSignificance,5000)||null,text(req.body?.pharmacogenomicImplication,5000)||null,req.body?.tumorBiomarker===true,req.body?.resultedAt?new Date(String(req.body.resultedAt)):null,text(req.body?.laboratory,250)||null,JSON.stringify(obj(req.body?.structuredData)));await audit(prisma,a,patientId,'RECORD_GENOMIC_RESULT','GENOMIC_RESULT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/specialty-care/dental',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const findingType=text(req.body?.findingType,160);if(!findingType)throw err(400,'Dental finding type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireDentalFinding"("organizationId","legalEntityId","patientId","episodeId","toothNumber","surface","findingType","status","periodontalData","treatmentPlan","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,text(req.body?.toothNumber,20)||null,text(req.body?.surface,40)||null,findingType,text(req.body?.status,80)||null,JSON.stringify(obj(req.body?.periodontalData)),text(req.body?.treatmentPlan,5000)||null,a.userId);await audit(prisma,a,patientId,'RECORD_DENTAL_FINDING','DENTAL_FINDING',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/ophthalmology',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const examType=text(req.body?.examType,160);if(!examType)throw err(400,'Eye exam type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOphthalmologyExam"("organizationId","legalEntityId","patientId","episodeId","examType","visualAcuityRight","visualAcuityLeft","iopRight","iopLeft","refraction","anteriorSegment","posteriorSegment","impression","examinedAt","examinedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12::jsonb,$13,COALESCE($14,NOW()),$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,examType,text(req.body?.visualAcuityRight,80)||null,text(req.body?.visualAcuityLeft,80)||null,num(req.body?.iopRight),num(req.body?.iopLeft),JSON.stringify(obj(req.body?.refraction)),JSON.stringify(obj(req.body?.anteriorSegment)),JSON.stringify(obj(req.body?.posteriorSegment)),text(req.body?.impression,5000)||null,req.body?.examinedAt?new Date(String(req.body.examinedAt)):null,a.userId);await audit(prisma,a,patientId,'RECORD_OPHTHALMOLOGY_EXAM','OPHTHALMOLOGY_EXAM',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/dermatology',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const bodySite=text(req.body?.bodySite,160);if(!bodySite)throw err(400,'Dermatology body site is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireDermatologyLesion"("organizationId","legalEntityId","patientId","episodeId","bodySite","laterality","lesionType","sizeMm","description","assessment","plan","mediaItemId","specimenId","status","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,bodySite,text(req.body?.laterality,30)||null,text(req.body?.lesionType,160)||null,num(req.body?.sizeMm),text(req.body?.description,5000)||null,text(req.body?.assessment,5000)||null,text(req.body?.plan,5000)||null,text(req.body?.mediaItemId,120)||null,text(req.body?.specimenId,120)||null,text(req.body?.status,40)||'ACTIVE',a.userId);await audit(prisma,a,patientId,'RECORD_DERMATOLOGY_LESION','DERMATOLOGY_LESION',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/orthopedics',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const bodyRegion=text(req.body?.bodyRegion,160);if(!bodyRegion)throw err(400,'Orthopedic body region is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOrthopedicAssessment"("organizationId","legalEntityId","patientId","episodeId","bodyRegion","laterality","injuryMechanism","rangeOfMotion","strength","neurovascular","specialTests","proms","assessment","plan","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10,$11::jsonb,$12::jsonb,$13,$14,$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,bodyRegion,text(req.body?.laterality,30)||null,text(req.body?.injuryMechanism,2000)||null,JSON.stringify(obj(req.body?.rangeOfMotion)),JSON.stringify(obj(req.body?.strength)),text(req.body?.neurovascular,2000)||null,JSON.stringify(obj(req.body?.specialTests)),JSON.stringify(obj(req.body?.proms)),text(req.body?.assessment,5000)||null,text(req.body?.plan,5000)||null,a.userId);await audit(prisma,a,patientId,'RECORD_ORTHOPEDIC_ASSESSMENT','ORTHOPEDIC_ASSESSMENT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/endoscopy',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const procedureType=text(req.body?.procedureType,160);if(!procedureType)throw err(400,'Endoscopy procedure type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireEndoscopyReport"("organizationId","legalEntityId","patientId","episodeId","procedureType","indication","extent","prepQuality","findings","interventions","specimens","impression","recommendations","performedAt","performedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12,$13,COALESCE($14,NOW()),$15) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,procedureType,text(req.body?.indication,3000)||null,text(req.body?.extent,500)||null,text(req.body?.prepQuality,120)||null,JSON.stringify(list(req.body?.findings)),JSON.stringify(list(req.body?.interventions)),JSON.stringify(list(req.body?.specimens)),text(req.body?.impression,5000)||null,text(req.body?.recommendations,5000)||null,req.body?.performedAt?new Date(String(req.body.performedAt)):null,a.userId);await audit(prisma,a,patientId,'CREATE_ENDOSCOPY_REPORT','ENDOSCOPY_REPORT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/specialty-care/cardiology',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const procedureType=text(req.body?.procedureType,160);if(!procedureType)throw err(400,'Cardiology procedure type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireCardiologyProcedureReport"("organizationId","legalEntityId","patientId","episodeId","procedureType","indication","accessSite","hemodynamics","coronaryFindings","interventions","impression","performedAt","performedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11,COALESCE($12,NOW()),$13) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.episodeId,120)||null,procedureType,text(req.body?.indication,3000)||null,text(req.body?.accessSite,160)||null,JSON.stringify(obj(req.body?.hemodynamics)),JSON.stringify(obj(req.body?.coronaryFindings)),JSON.stringify(list(req.body?.interventions)),text(req.body?.impression,5000)||null,req.body?.performedAt?new Date(String(req.body.performedAt)):null,a.userId);await audit(prisma,a,patientId,'CREATE_CARDIOLOGY_REPORT','CARDIOLOGY_PROCEDURE_REPORT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
};
