import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinical=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const admins=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const ensure=(a:AuthContext)=>{if(!clinical.has(a.role))throw Object.assign(new Error('Spire clinical access is required'),{status:403});};
const ensureWrite=(a:AuthContext)=>{ensure(a);if(!writers.has(a.role))throw Object.assign(new Error('This Spire role is read-only'),{status:403});};
const isAdmin=(a:AuthContext)=>admins.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
const selectedEntity=(a:AuthContext)=>{if(!a.legalEntityId)throw Object.assign(new Error('Select a Sulandra company before documenting incidents'),{status:409});return a.legalEntityId;};
const text=(v:unknown,m=20000)=>typeof v==='string'?v.trim().slice(0,m):'';
async function allowed(prisma:PrismaClient,a:AuthContext,pid:string){if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const r=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND h."userId"=$2 AND p."patientId"=$3 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,pid);return r[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,pid:string,write=false){write?ensureWrite(a):ensure(a);selectedEntity(a);if(!(await allowed(prisma,a,pid)))throw Object.assign(new Error('This chart is outside your authorized clinical scope'),{status:403});}
async function requireIncidentOwner(prisma:PrismaClient,a:AuthContext,pid:string,incidentId:string){const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireIncident" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,selectedEntity(a),pid,incidentId);if(!rows[0])throw Object.assign(new Error('This incident belongs to a different company or was not found'),{status:409});}
async function audit(prisma:PrismaClient,a:AuthContext,pid:string,action:string,type:string,id:string,after:unknown){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,a.organizationId,selectedEntity(a),a.userId,a.email??null,pid,action,type,id,JSON.stringify(after??{}),a.ipAddress??null,a.userAgent??null);}
const incidentNumber=()=>`INC-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
export const registerSpireIncidentManagementRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/patients/:patientId/incidents',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT i.*,(SELECT COUNT(*)::int FROM "SpireIncidentCorrectiveAction" c WHERE c."organizationId"=i."organizationId" AND c."incidentId"=i."id" AND c."status"<>'COMPLETED') AS "openCorrectiveActions",(SELECT COUNT(*)::int FROM "SpireIncidentFollowUp" f WHERE f."organizationId"=i."organizationId" AND f."incidentId"=i."id" AND f."status"<>'COMPLETED') AS "openFollowUps" FROM "SpireIncident" i WHERE i."organizationId"=$1 AND i."patientId"=$2 ORDER BY COALESCE(i."occurredAt",i."createdAt") DESC`,a.organizationId,pid);res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/incidents/:incidentId',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);const id=req.params.incidentId;const base=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncident" WHERE "organizationId"=$1 AND "patientId"=$2 AND "id"=$3`,a.organizationId,pid,id);if(!base[0])throw Object.assign(new Error('Incident not found'),{status:404});const[witnesses,notifications,investigations,actions,followups,attachments]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentWitness" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,id),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentNotification" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,id),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentInvestigation" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,id),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentCorrectiveAction" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt"`,a.organizationId,id),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentFollowUp" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "dueAt" NULLS LAST`,a.organizationId,id),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireIncidentAttachment" WHERE "organizationId"=$1 AND "incidentId"=$2 ORDER BY "createdAt" DESC`,a.organizationId,id)]);res.json({data:{incident:base[0],witnesses,notifications,investigations,correctiveActions:actions,followUps:followups,attachments,selectedLegalEntityId:selectedEntity(a)}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const type=text(req.body?.incidentType,120),description=text(req.body?.description),entity=selectedEntity(a);if(!type||!description)throw Object.assign(new Error('Incident type and description are required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncident"("organizationId","legalEntityId","patientId","incidentNumber","incidentType","severity","occurredAt","location","description","immediateActions","injuryDetails","medicalAttentionRequired","hospitalTransfer","lawEnforcementNotified","doddReportable","doddCategory","status","reportedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,'OPEN',$17) RETURNING *`,a.organizationId,entity,pid,incidentNumber(),type,text(req.body?.severity,40)||'ROUTINE',req.body?.occurredAt||new Date().toISOString(),text(req.body?.location,250)||null,description,text(req.body?.immediateActions),text(req.body?.injuryDetails),Boolean(req.body?.medicalAttentionRequired),Boolean(req.body?.hospitalTransfer),Boolean(req.body?.lawEnforcementNotified),Boolean(req.body?.doddReportable),text(req.body?.doddCategory,120)||null,a.userId);const row=rows[0];await audit(prisma,a,pid,'CREATE_INCIDENT','INCIDENT',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/witnesses',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const name=text(req.body?.witnessName,250),entity=selectedEntity(a);if(!name)throw Object.assign(new Error('Witness name is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncidentWitness"("organizationId","legalEntityId","patientId","incidentId","witnessName","witnessRole","contactInfo","statement","statementTakenAt","statementTakenById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW(),$9) RETURNING *`,a.organizationId,entity,pid,req.params.incidentId,name,text(req.body?.witnessRole,120)||null,text(req.body?.contactInfo,250)||null,text(req.body?.statement),a.userId);const row=rows[0];await audit(prisma,a,pid,'ADD_INCIDENT_WITNESS','INCIDENT_WITNESS',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/notifications',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const recipientType=text(req.body?.recipientType,80),entity=selectedEntity(a);if(!recipientType)throw Object.assign(new Error('Recipient type is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncidentNotification"("organizationId","legalEntityId","patientId","incidentId","recipientType","recipientName","recipientContact","method","status","notifiedAt","notifiedById","notes") VALUES($1,$2,$3,$4,$5,$6,$7,$8,'COMPLETED',NOW(),$9,$10) RETURNING *`,a.organizationId,entity,pid,req.params.incidentId,recipientType,text(req.body?.recipientName,250)||null,text(req.body?.recipientContact,250)||null,text(req.body?.method,80)||'PHONE',a.userId,text(req.body?.notes));const row=rows[0];await audit(prisma,a,pid,'DOCUMENT_INCIDENT_NOTIFICATION','INCIDENT_NOTIFICATION',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/investigations',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const entity=selectedEntity(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncidentInvestigation"("organizationId","legalEntityId","patientId","incidentId","investigatorUserId","status","summary","findings","rootCause","contributingFactors") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,a.organizationId,entity,pid,req.params.incidentId,text(req.body?.investigatorUserId,100)||a.userId,text(req.body?.status,40)||'OPEN',text(req.body?.summary),text(req.body?.findings),text(req.body?.rootCause),text(req.body?.contributingFactors));const row=rows[0];await audit(prisma,a,pid,'CREATE_INCIDENT_INVESTIGATION','INCIDENT_INVESTIGATION',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/corrective-actions',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const title=text(req.body?.title,250),entity=selectedEntity(a);if(!title)throw Object.assign(new Error('Corrective action title is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncidentCorrectiveAction"("organizationId","legalEntityId","patientId","incidentId","title","description","ownerUserId","dueDate","status") VALUES($1,$2,$3,$4,$5,$6,$7,$8,'OPEN') RETURNING *`,a.organizationId,entity,pid,req.params.incidentId,title,text(req.body?.description),text(req.body?.ownerUserId,100)||null,req.body?.dueDate||null);const row=rows[0];await audit(prisma,a,pid,'CREATE_INCIDENT_CORRECTIVE_ACTION','INCIDENT_CORRECTIVE_ACTION',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/follow-ups',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const followUpType=text(req.body?.followUpType,120),entity=selectedEntity(a);if(!followUpType)throw Object.assign(new Error('Follow-up type is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireIncidentFollowUp"("organizationId","legalEntityId","patientId","incidentId","followUpType","dueAt","status","details") VALUES($1,$2,$3,$4,$5,$6,'OPEN',$7) RETURNING *`,a.organizationId,entity,pid,req.params.incidentId,followUpType,req.body?.dueAt||null,text(req.body?.details));const row=rows[0];await audit(prisma,a,pid,'CREATE_INCIDENT_FOLLOW_UP','INCIDENT_FOLLOW_UP',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/incidents/:incidentId/close',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);await requireIncidentOwner(prisma,a,pid,req.params.incidentId);const reason=text(req.body?.reason),entity=selectedEntity(a);if(!reason)throw Object.assign(new Error('Closure summary is required'),{status:400});const open=await prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT ((SELECT COUNT(*) FROM "SpireIncidentCorrectiveAction" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "incidentId"=$3 AND "status"<>'COMPLETED')+(SELECT COUNT(*) FROM "SpireIncidentFollowUp" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "incidentId"=$3 AND "status"<>'COMPLETED'))::int AS count`,a.organizationId,entity,req.params.incidentId);if((open[0]?.count||0)>0)throw Object.assign(new Error('Incident cannot be closed while corrective actions or follow-ups remain open'),{status:409});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireIncident" SET "status"='CLOSED',"investigationSummary"=COALESCE(NULLIF($1,''),"investigationSummary"),"closedAt"=NOW(),"closedById"=$2,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "patientId"=$5 AND "id"=$6 RETURNING *`,reason,a.userId,a.organizationId,entity,pid,req.params.incidentId);if(!rows[0])throw Object.assign(new Error('Incident not found in the selected company'),{status:404});await audit(prisma,a,pid,'CLOSE_INCIDENT','INCIDENT',String(rows[0].id),rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
};