import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { createHash, randomBytes } from 'node:crypto';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
type PortalSession={id:string;organizationId:string;legalEntityId:string;patientId:string;accessType:string;displayName:string|null;relationship:string|null;expiresAt:Date};
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writeRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const text=(v:unknown,max=10000)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown)=>v===''||v===null||v===undefined?null:(Number.isFinite(Number(v))?Number(v):null);
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const list=(v:unknown)=>Array.isArray(v)?v:[];
const err=(status:number,message:string)=>Object.assign(new Error(message),{status});
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const newToken=()=>randomBytes(32).toString('base64url');
const isAdmin=(a:AuthContext)=>adminRoles.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
const entity=(a:AuthContext)=>{const id=text(a.legalEntityId,120);if(!id)throw err(409,'Select a Sulandra company before using SPIRE patient engagement');return id;};
const ensureClinical=(a:AuthContext)=>{if(!clinicalRoles.has(a.role))throw err(403,'SPIRE clinical access is required');};
const ensureWrite=(a:AuthContext)=>{ensureClinical(a);if(!writeRoles.has(a.role))throw err(403,'This SPIRE role is read-only');};
async function allowed(prisma:PrismaClient,a:AuthContext,patientId:string){const eid=entity(a);const enrolled=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "ClientEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "clientId"=$3 AND "status" IN ('PENDING','ACTIVE','PAUSED')) AS allowed`,a.organizationId,eid,patientId);if(enrolled[0]?.allowed!==true)return false;if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "clientId"=$4 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW()) UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$3 AND g."scopeType"='CLIENT' AND g."clientId"=$4 AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())) AS allowed`,a.organizationId,eid,a.userId,patientId);return rows[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string,write=false){write?ensureWrite(a):ensureClinical(a);if(!(await allowed(prisma,a,patientId)))throw err(403,'This chart is outside your authorized clinical scope');}
async function audit(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,type:string,id:string,data:unknown={}){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,a.organizationId,entity(a),a.userId,a.email??null,patientId,action,type,id,JSON.stringify(data??{}),a.ipAddress??null,a.userAgent??null);}
async function portalSession(prisma:PrismaClient,req:express.Request):Promise<PortalSession>{const authorization=String(req.headers.authorization||'');const raw=authorization.toLowerCase().startsWith('bearer ')?authorization.slice(7).trim():'';if(!raw)throw err(401,'Patient portal session is required');const rows=await prisma.$queryRawUnsafe<PortalSession[]>(`SELECT "id","organizationId","legalEntityId","patientId","accessType","displayName","relationship","expiresAt" FROM "SpirePatientPortalSession" WHERE "tokenHash"=$1 AND "revokedAt" IS NULL AND "expiresAt">NOW() LIMIT 1`,hash(raw));if(!rows[0])throw err(401,'Patient portal session is invalid or expired');await prisma.$executeRawUnsafe(`UPDATE "SpirePatientPortalSession" SET "lastSeenAt"=NOW() WHERE "id"=$1`,rows[0].id);return rows[0];}

export const registerSpirePatientEngagementParityRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
app.get('/api/spire/patients/:patientId/patient-engagement/overview',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const eid=entity(a);const [invites,proxies,requests,messages,checkins,telehealth,rpm,readings,alerts,education]=await Promise.all([
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","email","phone","proxyName","proxyRelationship","accessType","expiresAt","usedAt","revokedAt","createdAt" FROM "SpirePatientPortalInvite" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientProxyRelationship" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientRequest" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY CASE "status" WHEN 'NEW' THEN 0 WHEN 'IN_PROGRESS' THEN 1 ELSE 2 END,"createdAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientPortalMessage" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireDigitalCheckIn" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "startedAt" DESC LIMIT 25`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireTelehealthSession" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "scheduledAt" DESC NULLS LAST,"createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT e.*,COALESCE((SELECT jsonb_agg(d ORDER BY d."pairedAt" DESC) FROM "SpireRemoteMonitoringDevice" d WHERE d."enrollmentId"=e."id"),'[]'::jsonb) AS devices FROM "SpireRemoteMonitoringEnrollment" e WHERE e."organizationId"=$1 AND e."legalEntityId"=$2 AND e."patientId"=$3 ORDER BY e."createdAt" DESC LIMIT 50`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireRemoteMonitoringReading" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "recordedAt" DESC LIMIT 250`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireRemoteMonitoringAlert" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY CASE "status" WHEN 'OPEN' THEN 0 WHEN 'ACKNOWLEDGED' THEN 1 ELSE 2 END,"triggeredAt" DESC LIMIT 100`,a.organizationId,eid,patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientEducationAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "assignedAt" DESC LIMIT 100`,a.organizationId,eid,patientId)
]);res.json({data:{invites,proxies,requests,messages,checkins,telehealthSessions:telehealth,rpmEnrollments:rpm,rpmReadings:readings,rpmAlerts:alerts,education}});}catch(e){next(e);}});

app.post('/api/spire/patients/:patientId/patient-engagement/invites',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const accessType=text(req.body?.accessType,20).toUpperCase()||'PATIENT';if(!['PATIENT','PROXY'].includes(accessType))throw err(400,'Portal access type must be PATIENT or PROXY');if(accessType==='PROXY'&&!text(req.body?.proxyName,250))throw err(400,'Proxy name is required');const raw=newToken(),expiresHours=Math.min(Math.max(Number(req.body?.expiresHours)||72,1),168);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientPortalInvite"("organizationId","legalEntityId","patientId","email","phone","proxyName","proxyRelationship","accessType","tokenHash","expiresAt","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW()+($10||' hours')::interval,$11) RETURNING "id","email","phone","proxyName","proxyRelationship","accessType","expiresAt","createdAt"`,a.organizationId,entity(a),patientId,text(req.body?.email,320)||null,text(req.body?.phone,80)||null,text(req.body?.proxyName,250)||null,text(req.body?.proxyRelationship,120)||null,accessType,hash(raw),String(expiresHours),a.userId);await audit(prisma,a,patientId,'CREATE_PATIENT_PORTAL_INVITE','PATIENT_PORTAL_INVITE',String(rows[0].id),rows[0]);res.status(201).json({data:{...rows[0],inviteToken:raw,invitePath:`/patient-portal.html?invite=${encodeURIComponent(raw)}`}});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/proxies',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const proxyName=text(req.body?.proxyName,250),relationship=text(req.body?.relationship,120);if(!proxyName||!relationship)throw err(400,'Proxy name and relationship are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientProxyRelationship"("organizationId","legalEntityId","patientId","proxyName","relationship","email","phone","permissions","verifiedById","verificationMethod") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10) RETURNING *`,a.organizationId,entity(a),patientId,proxyName,relationship,text(req.body?.email,320)||null,text(req.body?.phone,80)||null,JSON.stringify(list(req.body?.permissions)),a.userId,text(req.body?.verificationMethod,250)||'Staff verified');await audit(prisma,a,patientId,'CREATE_PATIENT_PROXY','PATIENT_PROXY',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/messages',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const subject=text(req.body?.subject,250),body=text(req.body?.body,10000);if(!subject||!body)throw err(400,'Message subject and body are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientPortalMessage"("organizationId","legalEntityId","patientId","direction","subject","body","category","status","senderUserId","inReplyToId") VALUES($1,$2,$3,'TO_PATIENT',$4,$5,$6,'SENT',$7,$8) RETURNING *`,a.organizationId,entity(a),patientId,subject,body,text(req.body?.category,120)||'CLINICAL',a.userId,text(req.body?.inReplyToId,120)||null);await audit(prisma,a,patientId,'SEND_PATIENT_PORTAL_MESSAGE','PATIENT_PORTAL_MESSAGE',String(rows[0].id),{subject,category:rows[0].category});res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.patch('/api/spire/patients/:patientId/patient-engagement/requests/:requestId',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const status=text(req.body?.status,30).toUpperCase();if(!['NEW','IN_PROGRESS','WAITING','COMPLETE','DECLINED','CANCELLED'].includes(status))throw err(400,'Valid request status is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpirePatientRequest" SET "status"=$1,"assignedToUserId"=COALESCE($2,"assignedToUserId"),"response"=COALESCE($3,"response"),"respondedAt"=CASE WHEN $1 IN ('COMPLETE','DECLINED') THEN NOW() ELSE "respondedAt" END,"respondedById"=CASE WHEN $1 IN ('COMPLETE','DECLINED') THEN $4 ELSE "respondedById" END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "legalEntityId"=$6 AND "patientId"=$7 AND "id"=$8 RETURNING *`,status,text(req.body?.assignedToUserId,120)||null,text(req.body?.response,10000)||null,a.userId,a.organizationId,entity(a),patientId,req.params.requestId);if(!rows[0])throw err(404,'Patient request not found');await audit(prisma,a,patientId,'UPDATE_PATIENT_REQUEST','PATIENT_REQUEST',req.params.requestId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/telehealth',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const joinCode=newToken();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireTelehealthSession"("organizationId","legalEntityId","patientId","appointmentId","encounterId","status","joinCodeHash","scheduledAt","createdById") VALUES($1,$2,$3,$4,$5,'SCHEDULED',$6,$7,$8) RETURNING "id","patientId","appointmentId","encounterId","status","scheduledAt","createdAt"`,a.organizationId,entity(a),patientId,text(req.body?.appointmentId,120)||null,text(req.body?.encounterId,120)||null,hash(joinCode),req.body?.scheduledAt?new Date(String(req.body.scheduledAt)):null,a.userId);await audit(prisma,a,patientId,'CREATE_TELEHEALTH_SESSION','TELEHEALTH_SESSION',String(rows[0].id),rows[0]);res.status(201).json({data:{...rows[0],joinCode}});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/rpm/enrollments',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const programName=text(req.body?.programName,250);if(!programName)throw err(400,'Remote monitoring program name is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireRemoteMonitoringEnrollment"("organizationId","legalEntityId","patientId","programName","condition","thresholds","careTeam","createdById") VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8) RETURNING *`,a.organizationId,entity(a),patientId,programName,text(req.body?.condition,1000)||null,JSON.stringify(obj(req.body?.thresholds)),JSON.stringify(list(req.body?.careTeam)),a.userId);await audit(prisma,a,patientId,'CREATE_RPM_ENROLLMENT','RPM_ENROLLMENT',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/rpm/devices',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const deviceType=text(req.body?.deviceType,160);if(!deviceType)throw err(400,'Remote monitoring device type is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireRemoteMonitoringDevice"("organizationId","legalEntityId","patientId","enrollmentId","deviceType","manufacturer","model","serialNumber","sourceSystem") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,a.organizationId,entity(a),patientId,text(req.body?.enrollmentId,120)||null,deviceType,text(req.body?.manufacturer,200)||null,text(req.body?.model,160)||null,text(req.body?.serialNumber,160)||null,text(req.body?.sourceSystem,160)||null);await audit(prisma,a,patientId,'PAIR_RPM_DEVICE','RPM_DEVICE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.patch('/api/spire/patients/:patientId/patient-engagement/rpm/alerts/:alertId',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const status=text(req.body?.status,30).toUpperCase();if(!['ACKNOWLEDGED','RESOLVED'].includes(status))throw err(400,'RPM alert status must be ACKNOWLEDGED or RESOLVED');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireRemoteMonitoringAlert" SET "status"=$1,"acknowledgedAt"=CASE WHEN $1='ACKNOWLEDGED' THEN NOW() ELSE COALESCE("acknowledgedAt",NOW()) END,"acknowledgedById"=CASE WHEN $1='ACKNOWLEDGED' THEN $2 ELSE COALESCE("acknowledgedById",$2) END,"resolvedAt"=CASE WHEN $1='RESOLVED' THEN NOW() ELSE "resolvedAt" END,"resolvedById"=CASE WHEN $1='RESOLVED' THEN $2 ELSE "resolvedById" END,"resolution"=CASE WHEN $1='RESOLVED' THEN $3 ELSE "resolution" END WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "patientId"=$6 AND "id"=$7 RETURNING *`,status,a.userId,text(req.body?.resolution,5000)||null,a.organizationId,entity(a),patientId,req.params.alertId);if(!rows[0])throw err(404,'RPM alert not found');await audit(prisma,a,patientId,`RPM_ALERT_${status}`,'RPM_ALERT',req.params.alertId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
app.post('/api/spire/patients/:patientId/patient-engagement/education',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const title=text(req.body?.title,250);if(!title)throw err(400,'Education title is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientEducationAssignment"("organizationId","legalEntityId","patientId","title","content","contentUrl","assignedById") VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,a.organizationId,entity(a),patientId,title,text(req.body?.content,20000)||null,text(req.body?.contentUrl,2000)||null,a.userId);await audit(prisma,a,patientId,'ASSIGN_PATIENT_EDUCATION','PATIENT_EDUCATION',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});

app.post('/public/spire/patient-portal/exchange',async(req,res,next)=>{try{const inviteToken=text(req.body?.inviteToken,500);if(!inviteToken)throw err(400,'Invite token is required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientPortalInvite" WHERE "tokenHash"=$1 AND "usedAt" IS NULL AND "revokedAt" IS NULL AND "expiresAt">NOW() FOR UPDATE`,hash(inviteToken));const invite=rows[0];if(!invite)throw err(401,'Invite is invalid, expired or already used');const sessionToken=newToken(),displayName=invite.accessType==='PROXY'?String(invite.proxyName||'Proxy'):null;const result=await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`UPDATE "SpirePatientPortalInvite" SET "usedAt"=NOW() WHERE "id"=$1`,invite.id);const sessions=await tx.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientPortalSession"("organizationId","legalEntityId","patientId","accessType","displayName","relationship","tokenHash","expiresAt") VALUES($1,$2,$3,$4,$5,$6,$7,NOW()+INTERVAL '12 hours') RETURNING "id","patientId","accessType","displayName","relationship","expiresAt"`,invite.organizationId,invite.legalEntityId,invite.patientId,invite.accessType,displayName,invite.proxyRelationship??null,hash(sessionToken));if(invite.accessType==='PROXY'&&invite.proxyName){await tx.$executeRawUnsafe(`INSERT INTO "SpirePatientProxyRelationship"("organizationId","legalEntityId","patientId","proxyName","relationship","email","phone","permissions","verifiedById","verificationMethod") SELECT $1,$2,$3,$4,$5,$6,$7,'["PORTAL"]'::jsonb,$8,'Portal invite verified' WHERE NOT EXISTS(SELECT 1 FROM "SpirePatientProxyRelationship" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND lower("proxyName")=lower($4) AND "status"='ACTIVE')`,invite.organizationId,invite.legalEntityId,invite.patientId,invite.proxyName,invite.proxyRelationship||'Proxy',invite.email??null,invite.phone??null,invite.createdById??null);}return sessions[0];});res.json({data:{...result,sessionToken}});}catch(e){next(e);}});
app.get('/public/spire/patient-portal/home',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const [patient,appointments,results,medications,allergies,requests,messages,checkins,telehealth,rpm,alerts,education]=await Promise.all([
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","firstName","preferredName","lastName","dateOfBirth","medicalRecordNumber" FROM "SpirePatient" WHERE "organizationId"=$1 AND "id"=$2`,s.organizationId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","startsAt","endsAt","status","appointmentType","reason","locationId","providerUserId" FROM "SpireAppointment" WHERE "organizationId"=$1 AND "patientId"=$2 AND "startsAt">=NOW()-INTERVAL '1 day' ORDER BY "startsAt" LIMIT 50`,s.organizationId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","category","testName","status","resultedAt","source" FROM "SpireResult" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status" IN ('FINAL','CORRECTED') ORDER BY "resultedAt" DESC LIMIT 100`,s.organizationId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","name","dose","route","frequency","instructions","status","startDate","endDate" FROM "SpireMedicationOrder" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' ORDER BY "name"`,s.organizationId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "substance","reaction","severity" FROM "SpirePatientAllergy" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' ORDER BY "substance"`,s.organizationId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpirePatientRequest" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 100`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","direction","subject","body","category","status","portalDisplayName","inReplyToId","createdAt","readAt" FROM "SpirePatientPortalMessage" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC LIMIT 100`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireDigitalCheckIn" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "startedAt" DESC LIMIT 25`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","appointmentId","status","scheduledAt","patientJoinedAt","startedAt","endedAt","consentAt" FROM "SpireTelehealthSession" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "scheduledAt" DESC NULLS LAST LIMIT 50`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","programName","condition","status","startedAt","thresholds" FROM "SpireRemoteMonitoringEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "createdAt" DESC`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","alertType","severity","reason","status","triggeredAt" FROM "SpireRemoteMonitoringAlert" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "status"<>'RESOLVED' ORDER BY "triggeredAt" DESC`,s.organizationId,s.legalEntityId,s.patientId),
prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","title","content","contentUrl","status","assignedAt","viewedAt","acknowledgedAt","response" FROM "SpirePatientEducationAssignment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 ORDER BY "assignedAt" DESC LIMIT 100`,s.organizationId,s.legalEntityId,s.patientId)
]);res.json({data:{session:{accessType:s.accessType,displayName:s.displayName,relationship:s.relationship,expiresAt:s.expiresAt},patient:patient[0]??null,appointments,results,medications,allergies,requests,messages,checkins,telehealthSessions:telehealth,rpmEnrollments:rpm,rpmAlerts:alerts,education}});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/requests',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const requestType=text(req.body?.requestType,120),subject=text(req.body?.subject,250);if(!requestType||!subject)throw err(400,'Request type and subject are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientRequest"("organizationId","legalEntityId","patientId","requestType","subject","body","priority","requestedFor","source") VALUES($1,$2,$3,$4,$5,$6,$7,$8,'PORTAL') RETURNING *`,s.organizationId,s.legalEntityId,s.patientId,requestType,subject,text(req.body?.body,10000)||null,text(req.body?.priority,30)||'NORMAL',req.body?.requestedFor?new Date(String(req.body.requestedFor)):null);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/messages',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const subject=text(req.body?.subject,250),body=text(req.body?.body,10000);if(!subject||!body)throw err(400,'Message subject and body are required');const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpirePatientPortalMessage"("organizationId","legalEntityId","patientId","direction","subject","body","category","status","portalDisplayName","inReplyToId") VALUES($1,$2,$3,'FROM_PATIENT',$4,$5,$6,'SENT',$7,$8) RETURNING *`,s.organizationId,s.legalEntityId,s.patientId,subject,body,text(req.body?.category,120)||'PATIENT_MESSAGE',s.displayName||s.accessType,text(req.body?.inReplyToId,120)||null);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/check-in',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireDigitalCheckIn"("organizationId","legalEntityId","patientId","appointmentId","status","demographicsConfirmed","medicationsConfirmed","allergiesConfirmed","consentsConfirmed","questionnaire","completedAt") VALUES($1,$2,$3,$4,'COMPLETE',$5,$6,$7,$8,$9::jsonb,NOW()) RETURNING *`,s.organizationId,s.legalEntityId,s.patientId,text(req.body?.appointmentId,120)||null,req.body?.demographicsConfirmed===true,req.body?.medicationsConfirmed===true,req.body?.allergiesConfirmed===true,req.body?.consentsConfirmed===true,JSON.stringify(obj(req.body?.questionnaire)));res.status(201).json({data:rows[0]});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/rpm/readings',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const readingType=text(req.body?.readingType,120).toUpperCase();if(!readingType)throw err(400,'Reading type is required');const enrollmentId=text(req.body?.enrollmentId,120);const enrollments=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireRemoteMonitoringEnrollment" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$4 AND "status"='ACTIVE'`,s.organizationId,s.legalEntityId,s.patientId,enrollmentId);if(!enrollments[0])throw err(404,'Active remote monitoring enrollment not found');const readingRows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireRemoteMonitoringReading"("organizationId","legalEntityId","patientId","enrollmentId","deviceId","readingType","value","numericValue","unit","recordedAt","source","quality","rawData") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'PATIENT_PORTAL',$11,$12::jsonb) RETURNING *`,s.organizationId,s.legalEntityId,s.patientId,enrollmentId,text(req.body?.deviceId,120)||null,readingType,text(req.body?.value,1000)||null,num(req.body?.numericValue),text(req.body?.unit,60)||null,req.body?.recordedAt?new Date(String(req.body.recordedAt)):new Date(),text(req.body?.quality,80)||null,JSON.stringify(obj(req.body?.rawData)));const reading=readingRows[0],thresholds=obj(enrollments[0].thresholds),rule=obj(thresholds[readingType]),n=Number(reading.numericValue);let alert=null;if(Number.isFinite(n)&&((rule.min!==undefined&&n<Number(rule.min))||(rule.max!==undefined&&n>Number(rule.max)))){const reason=`${readingType} value ${n}${reading.unit?` ${reading.unit}`:''} is outside configured range ${rule.min??'—'} to ${rule.max??'—'}`;const alerts=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireRemoteMonitoringAlert"("organizationId","legalEntityId","patientId","enrollmentId","readingId","alertType","severity","reason") VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,s.organizationId,s.legalEntityId,s.patientId,enrollmentId,reading.id,`THRESHOLD_${readingType}`,text(rule.severity,30)||'HIGH',reason);alert=alerts[0];}res.status(201).json({data:{reading,alert}});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/education/:assignmentId/acknowledge',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpirePatientEducationAssignment" SET "status"='ACKNOWLEDGED',"viewedAt"=COALESCE("viewedAt",NOW()),"acknowledgedAt"=NOW(),"response"=$1 WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "patientId"=$4 AND "id"=$5 RETURNING *`,text(req.body?.response,5000)||null,s.organizationId,s.legalEntityId,s.patientId,req.params.assignmentId);if(!rows[0])throw err(404,'Education assignment not found');res.json({data:rows[0]});}catch(e){next(e);}});
app.post('/public/spire/patient-portal/telehealth/:sessionId/join',async(req,res,next)=>{try{const s=await portalSession(prisma,req);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireTelehealthSession" SET "status"=CASE WHEN "status"='SCHEDULED' THEN 'WAITING' ELSE "status" END,"patientJoinedAt"=COALESCE("patientJoinedAt",NOW()),"consentAt"=CASE WHEN $1 THEN COALESCE("consentAt",NOW()) ELSE "consentAt" END,"deviceCheck"=$2::jsonb,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "patientId"=$5 AND "id"=$6 AND "status" IN ('SCHEDULED','WAITING','IN_PROGRESS') RETURNING "id","status","scheduledAt","patientJoinedAt","consentAt","deviceCheck"`,req.body?.consent===true,JSON.stringify(obj(req.body?.deviceCheck)),s.organizationId,s.legalEntityId,s.patientId,req.params.sessionId);if(!rows[0])throw err(404,'Available telehealth session not found');res.json({data:rows[0]});}catch(e){next(e);}});
};
