import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const writeRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const ensureWrite=(a:AuthContext)=>{if(!writeRoles.has(a.role))throw Object.assign(new Error('Spire order-entry permission is required'),{status:403});};
const isAdmin=(a:AuthContext)=>adminRoles.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
async function allowed(prisma:PrismaClient,a:AuthContext,patientId:string){if(isAdmin(a))return true;const r=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND h."userId"=$2 AND p."patientId"=$3 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,patientId);return r[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string){ensureWrite(a);if(!(await allowed(prisma,a,patientId)))throw Object.assign(new Error('This chart is outside your authorized clinical scope'),{status:403});}
const draftSchema=z.object({encounterId:z.string().optional().nullable(),orderType:z.enum(['MEDICATION','LAB','IMAGING','REFERRAL','SERVICE','CLINICAL']),name:z.string().min(1),priority:z.enum(['ROUTINE','HIGH','URGENT']).default('ROUTINE'),instructions:z.string().optional().nullable(),diagnosisIds:z.array(z.string()).default([]),dose:z.string().optional(),route:z.string().optional(),frequency:z.string().optional(),startDate:z.string().optional(),endDate:z.string().optional(),overrideReason:z.string().optional()});

export const registerSpireOrderComposerRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{
 const {authOf}=deps;
 app.get('/api/spire/patients/:patientId/order-composer/context',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const [allergies,diagnoses,activeOrders,favorites,sets]=await Promise.all([
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","substance","reaction","severity" FROM "SpirePatientAllergy" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' ORDER BY "substance"`,a.organizationId,patientId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","codeSystem","code","display" FROM "SpirePatientDiagnosis" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' ORDER BY "display"`,a.organizationId,patientId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","orderType","name","status","priority","orderedAt" FROM "SpireOrder" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status" IN ('PENDING','ACTIVE','IN_PROGRESS') ORDER BY "orderedAt" DESC`,a.organizationId,patientId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","orderType","name","defaults" FROM "SpireOrderFavorite" WHERE "organizationId"=$1 AND "userId"=$2 ORDER BY "name"`,a.organizationId,a.userId),
 prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT s."id",s."name",s."description",s."category",COALESCE(jsonb_agg(jsonb_build_object('id',i."id",'sequence',i."sequence",'orderType',i."orderType",'name',i."name",'defaults',i."defaults",'required',i."required") ORDER BY i."sequence") FILTER (WHERE i."id" IS NOT NULL),'[]'::jsonb) items FROM "SpireOrderSet" s LEFT JOIN "SpireOrderSetItem" i ON i."organizationId"=s."organizationId" AND i."orderSetId"=s."id" WHERE s."organizationId"=$1 AND s."active"=TRUE GROUP BY s."id" ORDER BY s."name"`,a.organizationId)
 ]);res.json({data:{allergies,diagnoses,activeOrders,favorites,orderSets:sets}});}catch(e){next(e);}});

 app.post('/api/spire/patients/:patientId/order-composer/check',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const d=draftSchema.parse(req.body);const duplicates=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","orderType","name","status" FROM "SpireOrder" WHERE "organizationId"=$1 AND "patientId"=$2 AND lower("name")=lower($3) AND "status" IN ('PENDING','ACTIVE','IN_PROGRESS')`,a.organizationId,patientId,d.name);const allergies=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","substance","reaction","severity" FROM "SpirePatientAllergy" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' AND (lower($3) LIKE '%'||lower("substance")||'%' OR lower("substance") LIKE '%'||lower($3)||'%')`,a.organizationId,patientId,d.name);const alerts=[...duplicates.map(x=>({type:'DUPLICATE_ORDER',severity:'HIGH',message:`Possible duplicate active order: ${String(x.name||d.name)}`,resource:x})),...allergies.map(x=>({type:'ALLERGY_MATCH',severity:'CRITICAL',message:`Order name matches documented allergy: ${String(x.substance||'')}`,resource:x}))];res.json({data:{alerts,requiresOverride:alerts.some(x=>x.severity==='CRITICAL')}});}catch(e){next(e);}});

 app.post('/api/spire/patients/:patientId/order-composer/place',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const d=draftSchema.parse(req.body);const allergy=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","substance","reaction","severity" FROM "SpirePatientAllergy" WHERE "organizationId"=$1 AND "patientId"=$2 AND "status"='ACTIVE' AND (lower($3) LIKE '%'||lower("substance")||'%' OR lower("substance") LIKE '%'||lower($3)||'%')`,a.organizationId,patientId,d.name);if(allergy.length&&!d.overrideReason)throw Object.assign(new Error('A documented allergy warning requires an override reason before this order can be placed'),{status:409});let orderId:string;
 if(d.orderType==='MEDICATION'){if(!d.dose||!d.route||!d.frequency)throw Object.assign(new Error('Medication dose, route and frequency are required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireMedicationOrder"("organizationId","patientId","encounterId","name","dose","route","frequency","instructions","status","startDate","endDate","orderedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,'ACTIVE',COALESCE($9::date,CURRENT_DATE),$10::date,$11) RETURNING "id"`,a.organizationId,patientId,d.encounterId||null,d.name,d.dose,d.route,d.frequency,d.instructions||null,d.startDate||null,d.endDate||null,a.userId);orderId=rows[0].id;}else{const rows=await prisma.$queryRawUnsafe<Array<{id:string}>>(`INSERT INTO "SpireOrder"("organizationId","patientId","encounterId","orderType","name","instructions","priority","status","orderedById") VALUES($1,$2,$3,$4,$5,$6,$7,'PENDING',$8) RETURNING "id"`,a.organizationId,patientId,d.encounterId||null,d.orderType,d.name,d.instructions||null,d.priority,a.userId);orderId=rows[0].id;for(const diagnosisId of d.diagnosisIds)await prisma.$executeRawUnsafe(`INSERT INTO "SpireOrderDiagnosisLink"("organizationId","orderId","diagnosisId") VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,a.organizationId,orderId,diagnosisId);}
 if(allergy.length&&d.overrideReason)for(const x of allergy)await prisma.$executeRawUnsafe(`INSERT INTO "SpireOrderSafetyOverride"("organizationId","patientId","orderId","alertType","alertKey","severity","reason","overriddenById") VALUES($1,$2,$3,'ALLERGY_MATCH',$4,'CRITICAL',$5,$6)`,a.organizationId,patientId,orderId,String(x.id||x.substance||'allergy'),d.overrideReason,a.userId);
 await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("organizationId","patientId","actorUserId","action","resourceType","resourceId","details") VALUES($1,$2,$3,'PLACE_ORDER','ORDER',$4,$5::jsonb)`,a.organizationId,patientId,a.userId,orderId,JSON.stringify({orderType:d.orderType,name:d.name,priority:d.priority,diagnosisIds:d.diagnosisIds}));res.status(201).json({data:{id:orderId,orderType:d.orderType}});}catch(e){next(e);}});

 app.post('/api/spire/order-composer/favorites',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const body=z.object({orderType:z.string().min(1),name:z.string().min(1),defaults:z.record(z.unknown()).default({})}).parse(req.body);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireOrderFavorite"("organizationId","userId","orderType","name","defaults") VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT("organizationId","userId","orderType","name") DO UPDATE SET "defaults"=EXCLUDED."defaults","updatedAt"=NOW() RETURNING *`,a.organizationId,a.userId,body.orderType,body.name,JSON.stringify(body.defaults));res.status(201).json({data:rows[0]});}catch(e){next(e);}});
};
