import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const licensedMedicationRoles=new Set<UserRole>([UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE]);
const elevatedRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const selectedEntity=(a:AuthContext)=>{if(!a.legalEntityId)throw Object.assign(new Error('Select a Sulandra company before documenting medications'),{status:409});return a.legalEntityId;};
const elevated=(a:AuthContext)=>a.enterpriseOwner===true||elevatedRoles.has(a.role)||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
async function medicationAuthorized(prisma:PrismaClient,a:AuthContext){if(licensedMedicationRoles.has(a.role))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireMedicationAdministrationQualification" q WHERE q."organizationId"=$1 AND q."legalEntityId"=$2 AND q."userId"=$3 AND q."status"='ACTIVE' AND q."revokedAt" IS NULL AND q."effectiveAt"<=NOW() AND (q."expiresAt" IS NULL OR q."expiresAt">NOW())) AS allowed`,a.organizationId,selectedEntity(a),a.userId);return rows[0]?.allowed===true;}
async function patientAllowed(prisma:PrismaClient,a:AuthContext,patientId:string){const entity=selectedEntity(a);const enrolled=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "ClientEnrollment" e WHERE e."organizationId"=$1 AND e."legalEntityId"=$2 AND e."clientId"=$3 AND e."status" IN ('PENDING','ACTIVE','PAUSED')) AS allowed`,a.organizationId,entity,patientId);if(enrolled[0]?.allowed!==true)return false;if(elevated(a))return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(
  SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."legalEntityId"=$2 AND x."userId"=$3 AND x."clientId"=$4
  UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW())
  UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$3 AND g."scopeType"='CLIENT' AND g."clientId"=$4 AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())
) AS allowed`,a.organizationId,entity,a.userId,patientId);return rows[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string,write=false){if(!clinicalRoles.has(a.role)&&a.enterpriseOwner!==true)throw Object.assign(new Error('SPIRE medication access is required'),{status:403});selectedEntity(a);if(!(await patientAllowed(prisma,a,patientId)))throw Object.assign(new Error('This chart is outside your authorized medication scope for the selected company'),{status:403});if(write&&!(await medicationAuthorized(prisma,a)))throw Object.assign(new Error('Medication administration is blocked. A licensed nursing role or an active verified medication-administration qualification is required for this company.'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,resourceId?:string){await prisma.$executeRawUnsafe(`INSERT INTO "SpireChartAccessEvent" ("organizationId","legalEntityId","patientId","actorUserId","actorEmail","action","resourceType","resourceId","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,$6,'MEDICATION',$7,$8,$9)`,a.organizationId,selectedEntity(a),patientId,a.userId,a.email??null,action,resourceId??null,a.ipAddress??null,a.userAgent??null);}

const eventSchema=z.object({medicationOrderId:z.string().min(1),scheduledFor:z.string().datetime().optional().nullable(),status:z.enum(['GIVEN','REFUSED','HELD','NOT_GIVEN','MISSED','PRN_GIVEN']),administeredDose:z.string().optional().nullable(),administeredRoute:z.string().optional().nullable(),reason:z.string().optional().nullable(),note:z.string().optional().nullable(),prnIndication:z.string().optional().nullable(),barcodeValue:z.string().optional().nullable(),controlledQuantity:z.number().optional().nullable(),witnessUserId:z.string().optional().nullable()});
const effectivenessSchema=z.object({effectiveness:z.string().min(1).max(2000)});

export const registerSpireEmarRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{
 const{authOf}=deps;
 app.get('/api/spire/patients/:patientId/medications/active',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledTime',s."scheduledTime",'windowBeforeMinutes',s."windowBeforeMinutes",'windowAfterMinutes',s."windowAfterMinutes") ORDER BY s."scheduledTime") FROM "SpireMedicationSchedule" s WHERE s."organizationId"=m."organizationId" AND s."medicationOrderId"=m."id" AND s."active"=TRUE),'[]'::jsonb) schedules,(SELECT e."status" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministrationStatus",(SELECT e."administeredAt" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministeredAt" FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND m."patientId"=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId);await audit(prisma,a,patientId,'VIEW_ACTIVE_MEDICATIONS');res.json({data:rows});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/emar',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const date=String(req.query.date||new Date().toISOString().slice(0,10));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m."id" AS "medicationOrderId",m."name",m."dose",m."route",m."frequency",m."instructions",m."dueTimes",m."status",COALESCE((SELECT jsonb_agg(jsonb_build_object('id',e."id",'legalEntityId',e."legalEntityId",'scheduledFor',e."scheduledFor",'status',e."status",'administeredAt',e."administeredAt",'administeredById',e."administeredById",'reason',e."reason",'note',e."note",'prnIndication',e."prnIndication",'effectiveness',e."effectiveness") ORDER BY e."createdAt") FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" AND COALESCE(e."scheduledFor",e."createdAt")::date=$3::date),'[]'::jsonb) administrations FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND m."patientId"=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId,date);await audit(prisma,a,patientId,'VIEW_EMAR');res.json({data:{date,medications:rows,medicationAdministrationAuthorized:await medicationAuthorized(prisma,a)}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/emar/events',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=eventSchema.parse(req.body);const med=await prisma.$queryRawUnsafe<Array<{id:string;name:string;dose:string;route:string}>>(`SELECT "id","name","dose","route" FROM "SpireMedicationOrder" WHERE "organizationId"=$1 AND "patientId"=$2 AND "id"=$3 AND "status"='ACTIVE'`,a.organizationId,patientId,b.medicationOrderId);if(!med[0])throw Object.assign(new Error('Active medication order not found'),{status:404});if(['REFUSED','HELD','NOT_GIVEN','MISSED'].includes(b.status)&&!String(b.reason||'').trim())throw Object.assign(new Error('A reason is required when medication is not administered'),{status:400});if(b.status==='PRN_GIVEN'&&!String(b.prnIndication||'').trim())throw Object.assign(new Error('PRN indication is required'),{status:400});const id=crypto.randomUUID(),entity=selectedEntity(a);await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationAdministrationEvent" ("id","organizationId","legalEntityId","patientId","medicationOrderId","scheduledFor","status","administeredDose","administeredRoute","administeredAt","administeredById","reason","note","prnIndication","barcodeValue") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CASE WHEN $7 IN ('GIVEN','PRN_GIVEN') THEN NOW() ELSE NULL END,$10,$11,$12,$13,$14)`,id,a.organizationId,entity,patientId,b.medicationOrderId,b.scheduledFor?new Date(b.scheduledFor):null,b.status,b.administeredDose??med[0].dose,b.administeredRoute??med[0].route,a.userId,b.reason??null,b.note??null,b.prnIndication??null,b.barcodeValue??null);if(b.controlledQuantity!=null)await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationControlledLog" ("organizationId","legalEntityId","patientId","medicationOrderId","administrationEventId","action","quantity","witnessUserId","actorUserId","note") VALUES($1,$2,$3,$4,$5,'ADMINISTER',$6,$7,$8,$9)`,a.organizationId,entity,patientId,b.medicationOrderId,id,b.controlledQuantity,b.witnessUserId??null,a.userId,b.note??null);await audit(prisma,a,patientId,`EMAR_${b.status}`,id);res.status(201).json({data:{id,status:b.status,legalEntityId:entity}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/emar/events/:eventId/effectiveness',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=effectivenessSchema.parse(req.body);const count=await prisma.$executeRawUnsafe(`UPDATE "SpireMedicationAdministrationEvent" SET "effectiveness"=$1,"effectivenessRecordedAt"=NOW(),"effectivenessRecordedById"=$2,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "legalEntityId"=$4 AND "patientId"=$5 AND "id"=$6`,b.effectiveness,a.userId,a.organizationId,selectedEntity(a),patientId,req.params.eventId);if(!count)throw Object.assign(new Error('Administration event not found in the selected company'),{status:404});await audit(prisma,a,patientId,'DOCUMENT_PRN_EFFECTIVENESS',req.params.eventId);res.json({data:{ok:true}});}catch(e){next(e);}});
 app.get('/api/spire/patients/:patientId/medications/reconciliation',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT r.*,COALESCE((SELECT jsonb_agg(i ORDER BY i."createdAt") FROM "SpireMedicationReconciliationItem" i WHERE i."organizationId"=r."organizationId" AND i."reconciliationId"=r."id"),'[]'::jsonb) items FROM "SpireMedicationReconciliation" r WHERE r."organizationId"=$1 AND r."patientId"=$2 ORDER BY r."createdAt" DESC LIMIT 20`,a.organizationId,patientId);res.json({data:rows});}catch(e){next(e);}});
};
