import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinicalRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const medicationWriteRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const isAdmin=(a:AuthContext)=>[UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO].includes(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
async function patientAllowed(prisma:PrismaClient,a:AuthContext,patientId:string){if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const rows=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND h."userId"=$2 AND p."patientId"=$3 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,patientId);return rows[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,patientId:string,write=false){if(!clinicalRoles.has(a.role)||write&&!medicationWriteRoles.has(a.role))throw Object.assign(new Error('Spire medication access is required'),{status:403});if(!(await patientAllowed(prisma,a,patientId)))throw Object.assign(new Error('This chart is outside your authorized clinical scope'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,patientId:string,action:string,resourceId?:string){await prisma.$executeRawUnsafe(`INSERT INTO "SpireChartAccessEvent" ("organizationId","patientId","actorUserId","actorEmail","action","resourceType","resourceId","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,'MEDICATION',$6,$7,$8)`,a.organizationId,patientId,a.userId,a.email??null,action,resourceId??null,a.ipAddress??null,a.userAgent??null);}

const eventSchema=z.object({medicationOrderId:z.string().min(1),scheduledFor:z.string().datetime().optional().nullable(),status:z.enum(['GIVEN','REFUSED','HELD','NOT_GIVEN','MISSED','PRN_GIVEN']),administeredDose:z.string().optional().nullable(),administeredRoute:z.string().optional().nullable(),reason:z.string().optional().nullable(),note:z.string().optional().nullable(),prnIndication:z.string().optional().nullable(),barcodeValue:z.string().optional().nullable(),controlledQuantity:z.number().optional().nullable(),witnessUserId:z.string().optional().nullable()});
const effectivenessSchema=z.object({effectiveness:z.string().min(1).max(2000)});

export const registerSpireEmarRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{
  const {authOf}=deps;
  app.get('/api/spire/patients/:patientId/medications/active',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledTime',s."scheduledTime",'windowBeforeMinutes',s."windowBeforeMinutes",'windowAfterMinutes',s."windowAfterMinutes") ORDER BY s."scheduledTime") FROM "SpireMedicationSchedule" s WHERE s."organizationId"=m."organizationId" AND s."medicationOrderId"=m."id" AND s."active"=TRUE),'[]'::jsonb) schedules,(SELECT e."status" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministrationStatus",(SELECT e."administeredAt" FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" ORDER BY e."createdAt" DESC LIMIT 1) AS "lastAdministeredAt" FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND m."patientId"=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId);await audit(prisma,a,patientId,'VIEW_ACTIVE_MEDICATIONS');res.json({data:rows});}catch(e){next(e)}});

  app.get('/api/spire/patients/:patientId/emar',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const date=String(req.query.date||new Date().toISOString().slice(0,10));const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT m."id" AS "medicationOrderId",m."name",m."dose",m."route",m."frequency",m."instructions",m."dueTimes",m."status",COALESCE((SELECT jsonb_agg(jsonb_build_object('id',e."id",'scheduledFor',e."scheduledFor",'status',e."status",'administeredAt',e."administeredAt",'administeredById',e."administeredById",'reason',e."reason",'note',e."note",'prnIndication',e."prnIndication",'effectiveness',e."effectiveness") ORDER BY e."createdAt") FROM "SpireMedicationAdministrationEvent" e WHERE e."organizationId"=m."organizationId" AND e."medicationOrderId"=m."id" AND COALESCE(e."scheduledFor",e."createdAt")::date=$3::date),'[]'::jsonb) administrations FROM "SpireMedicationOrder" m WHERE m."organizationId"=$1 AND m."patientId"=$2 AND m."status"='ACTIVE' ORDER BY m."name"`,a.organizationId,patientId,date);await audit(prisma,a,patientId,'VIEW_EMAR');res.json({data:{date,medications:rows}});}catch(e){next(e)}});

  app.post('/api/spire/patients/:patientId/emar/events',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=eventSchema.parse(req.body);const med=await prisma.$queryRawUnsafe<Array<{id:string;name:string;dose:string;route:string}>>(`SELECT "id","name","dose","route" FROM "SpireMedicationOrder" WHERE "organizationId"=$1 AND "patientId"=$2 AND "id"=$3 AND "status"='ACTIVE'`,a.organizationId,patientId,b.medicationOrderId);if(!med[0])throw Object.assign(new Error('Active medication order not found'),{status:404});if(['REFUSED','HELD','NOT_GIVEN','MISSED'].includes(b.status)&&!String(b.reason||'').trim())throw Object.assign(new Error('A reason is required when medication is not administered'),{status:400});if(b.status==='PRN_GIVEN'&&!String(b.prnIndication||'').trim())throw Object.assign(new Error('PRN indication is required'),{status:400});const id=crypto.randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationAdministrationEvent" ("id","organizationId","patientId","medicationOrderId","scheduledFor","status","administeredDose","administeredRoute","administeredAt","administeredById","reason","note","prnIndication","barcodeValue") VALUES($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $6 IN ('GIVEN','PRN_GIVEN') THEN NOW() ELSE NULL END,$9,$10,$11,$12,$13)`,id,a.organizationId,patientId,b.medicationOrderId,b.scheduledFor?new Date(b.scheduledFor):null,b.status,b.administeredDose??med[0].dose,b.administeredRoute??med[0].route,a.userId,b.reason??null,b.note??null,b.prnIndication??null,b.barcodeValue??null);if(b.controlledQuantity!=null)await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationControlledLog" ("organizationId","patientId","medicationOrderId","administrationEventId","action","quantity","witnessUserId","actorUserId","note") VALUES($1,$2,$3,$4,'ADMINISTER',$5,$6,$7,$8)`,a.organizationId,patientId,b.medicationOrderId,id,b.controlledQuantity,b.witnessUserId??null,a.userId,b.note??null);await audit(prisma,a,patientId,`EMAR_${b.status}`,id);res.status(201).json({data:{id,status:b.status}});}catch(e){next(e)}});

  app.post('/api/spire/patients/:patientId/emar/events/:eventId/effectiveness',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId,true);const b=effectivenessSchema.parse(req.body);const count=await prisma.$executeRawUnsafe(`UPDATE "SpireMedicationAdministrationEvent" SET "effectiveness"=$1,"effectivenessRecordedAt"=NOW(),"effectivenessRecordedById"=$2,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "patientId"=$4 AND "id"=$5`,b.effectiveness,a.userId,a.organizationId,patientId,req.params.eventId);if(!count)throw Object.assign(new Error('Administration event not found'),{status:404});await audit(prisma,a,patientId,'DOCUMENT_PRN_EFFECTIVENESS',req.params.eventId);res.json({data:{ok:true}});}catch(e){next(e)}});

  app.get('/api/spire/patients/:patientId/medications/reconciliation',async(req,res,next)=>{try{const a=authOf(res),patientId=req.params.patientId;await requirePatient(prisma,a,patientId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT r.*,COALESCE((SELECT jsonb_agg(i ORDER BY i."createdAt") FROM "SpireMedicationReconciliationItem" i WHERE i."organizationId"=r."organizationId" AND i."reconciliationId"=r."id"),'[]'::jsonb) items FROM "SpireMedicationReconciliation" r WHERE r."organizationId"=$1 AND r."patientId"=$2 ORDER BY r."createdAt" DESC LIMIT 20`,a.organizationId,patientId);res.json({data:rows});}catch(e){next(e)}});
};