import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinical=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const admins=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const text=(v:unknown,m=2000)=>typeof v==='string'?v.trim().slice(0,m):'';
const ensure=(a:AuthContext)=>{if(!clinical.has(a.role))throw Object.assign(new Error('Spire clinical access is required'),{status:403});};
const ensureWrite=(a:AuthContext)=>{ensure(a);if(!writers.has(a.role))throw Object.assign(new Error('Scheduling write access is required'),{status:403});};
const isAdmin=(a:AuthContext)=>admins.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
async function allowed(prisma:PrismaClient,a:AuthContext,pid:string){if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const r=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND h."userId"=$2 AND p."patientId"=$3 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,pid);return r[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,pid:string,write=false){write?ensureWrite(a):ensure(a);if(!(await allowed(prisma,a,pid)))throw Object.assign(new Error('This chart is outside your authorized clinical scope'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,pid:string,action:string,type:string,id:string,after:unknown){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)`,a.organizationId,a.userId,a.email??null,pid,action,type,id,JSON.stringify(after??{}),a.ipAddress??null,a.userAgent??null);}
const statusStamp:Record<string,string>={CHECKED_IN:'checkInAt',ROOMED:'roomedAt',IN_PROGRESS:'visitStartedAt',CHECKED_OUT:'checkOutAt',CANCELLED:'cancelledAt',NO_SHOW:'noShowAt'};
export const registerSpireSchedulingRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/scheduling/day',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const date=text(req.query.date,10)||new Date().toISOString().slice(0,10);const provider=text(req.query.provider,120);const location=text(req.query.location,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT ap.*,p."firstName",p."preferredName",p."lastName",p."medicalRecordNumber",COALESCE(t."status",CASE WHEN ap."transportationRequired" THEN 'PENDING' ELSE 'NOT_REQUIRED' END) AS "transportationStatus",COALESCE((SELECT count(*) FROM "SpireAppointmentPreparation" q WHERE q."appointmentId"=ap."id" AND q."organizationId"=ap."organizationId" AND q."required"=TRUE AND q."status"<>'DONE'),0)::int AS "openPrepItems" FROM "SpireAppointment" ap JOIN "SpirePatient" p ON p."id"=ap."patientId" AND p."organizationId"=ap."organizationId" LEFT JOIN "SpireAppointmentTransportation" t ON t."appointmentId"=ap."id" AND t."organizationId"=ap."organizationId" WHERE ap."organizationId"=$1 AND ap."startsAt">=$2::date AND ap."startsAt"<$2::date+INTERVAL '1 day' AND ($3='' OR ap."providerUserId"=$3) AND ($4='' OR ap."locationId"=$4) ORDER BY ap."startsAt"`,a.organizationId,date,provider,location);const out=[];for(const r of rows)if(await allowed(prisma,a,String(r.patientId)))out.push({...r,patientName:[r.preferredName||r.firstName,r.lastName].filter(Boolean).join(' ')});res.json({data:{date,appointments:out}});}catch(e){next(e);}});
 app.get('/api/spire/scheduling/context',async(req,res,next)=>{try{const a=authOf(res);ensure(a);const [providers,resources,waitlist]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT DISTINCT "providerUserId" FROM "SpireAppointment" WHERE "organizationId"=$1 AND "providerUserId" IS NOT NULL ORDER BY "providerUserId"`,a.organizationId),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireScheduleResource" WHERE "organizationId"=$1 AND "active"=TRUE ORDER BY "resourceType","name"`,a.organizationId),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT w.*,p."firstName",p."preferredName",p."lastName" FROM "SpireAppointmentWaitlist" w JOIN "SpirePatient" p ON p."id"=w."patientId" AND p."organizationId"=w."organizationId" WHERE w."organizationId"=$1 AND w."status"='OPEN' ORDER BY CASE w."priority" WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,w."createdAt"`,a.organizationId)]);res.json({data:{providers:providers.map(x=>x.providerUserId),resources,waitlist:waitlist.map(x=>({...x,patientName:[x.preferredName||x.firstName,x.lastName].filter(Boolean).join(' ')}))}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/appointments',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const startsAt=text(req.body?.startsAt,60);if(!startsAt)throw Object.assign(new Error('Appointment start time is required'),{status:400});const duration=Math.max(5,Math.min(480,Number(req.body?.durationMinutes||30)));const endsAt=req.body?.endsAt||new Date(new Date(startsAt).getTime()+duration*60000).toISOString();const conflict=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireAppointment" WHERE "organizationId"=$1 AND "status" NOT IN ('CANCELLED','NO_SHOW') AND (($2<>'' AND "providerUserId"=$2) OR ($3<>'' AND "resourceId"=$3)) AND tstzrange("startsAt",COALESCE("endsAt","startsAt"+INTERVAL '30 minutes'),'[)') && tstzrange($4::timestamptz,$5::timestamptz,'[)') LIMIT 1`,a.organizationId,text(req.body?.providerUserId,120),text(req.body?.resourceId,120),startsAt,endsAt);if(conflict[0])throw Object.assign(new Error('The provider or resource is already booked during this time'),{status:409});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAppointment"("organizationId","patientId","providerUserId","locationId","resourceId","appointmentType","status","startsAt","endsAt","durationMinutes","reason","notes","recurrenceRule","transportationRequired","createdById") VALUES($1,$2,$3,$4,$5,$6,'SCHEDULED',$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,a.organizationId,pid,text(req.body?.providerUserId,120)||null,text(req.body?.locationId,120)||null,text(req.body?.resourceId,120)||null,text(req.body?.appointmentType,80)||'VISIT',startsAt,endsAt,duration,text(req.body?.reason,1000)||null,text(req.body?.notes,5000)||null,text(req.body?.recurrenceRule,500)||null,Boolean(req.body?.transportationRequired),a.userId);const row=rows[0];await prisma.$executeRawUnsafe(`INSERT INTO "SpireAppointmentStatusHistory"("organizationId","appointmentId","toStatus","changedById") VALUES($1,$2,'SCHEDULED',$3)`,a.organizationId,row.id,a.userId);for(const hours of [24,2]){await prisma.$executeRawUnsafe(`INSERT INTO "SpireAppointmentReminder"("organizationId","appointmentId","channel","scheduledFor") VALUES($1,$2,'EMAIL',$3::timestamptz-($4||' hours')::interval)`,a.organizationId,row.id,startsAt,String(hours));}await audit(prisma,a,pid,'CREATE_APPOINTMENT','APPOINTMENT',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/appointments/:appointmentId/status',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const to=text(req.body?.status,40).toUpperCase();const allowedStatuses=['SCHEDULED','CONFIRMED','ARRIVED','CHECKED_IN','ROOMED','IN_PROGRESS','CHECKED_OUT','CANCELLED','NO_SHOW'];if(!allowedStatuses.includes(to))throw Object.assign(new Error('Unsupported appointment status'),{status:400});const current=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireAppointment" WHERE "organizationId"=$1 AND "patientId"=$2 AND "id"=$3`,a.organizationId,pid,req.params.appointmentId);if(!current[0])throw Object.assign(new Error('Appointment not found'),{status:404});const stamp=statusStamp[to];const reason=text(req.body?.reason,1000)||null;const sql=stamp?`UPDATE "SpireAppointment" SET "status"=$1,"${stamp}"=NOW(),"cancellationReason"=CASE WHEN $1='CANCELLED' THEN $2 ELSE "cancellationReason" END,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "patientId"=$4 AND "id"=$5 RETURNING *`:`UPDATE "SpireAppointment" SET "status"=$1,"updatedAt"=NOW() WHERE "organizationId"=$3 AND "patientId"=$4 AND "id"=$5 RETURNING *`;const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(sql,to,reason,a.organizationId,pid,req.params.appointmentId);await prisma.$executeRawUnsafe(`INSERT INTO "SpireAppointmentStatusHistory"("organizationId","appointmentId","fromStatus","toStatus","reason","changedById") VALUES($1,$2,$3,$4,$5,$6)`,a.organizationId,req.params.appointmentId,current[0].status??null,to,reason,a.userId);await audit(prisma,a,pid,'UPDATE_APPOINTMENT_STATUS','APPOINTMENT',req.params.appointmentId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/appointments/:appointmentId/preparation',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const label=text(req.body?.label,500);if(!label)throw Object.assign(new Error('Preparation item label is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAppointmentPreparation"("organizationId","appointmentId","itemType","label","required","notes") VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,a.organizationId,req.params.appointmentId,text(req.body?.itemType,80)||'GENERAL',label,req.body?.required!==false,text(req.body?.notes,2000)||null);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/appointments/:appointmentId/transportation',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAppointmentTransportation"("organizationId","appointmentId","required","mode","vendor","pickupAddress","pickupAt","returnPickupAt","status","confirmationNumber","notes") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT("appointmentId") DO UPDATE SET "required"=EXCLUDED."required","mode"=EXCLUDED."mode","vendor"=EXCLUDED."vendor","pickupAddress"=EXCLUDED."pickupAddress","pickupAt"=EXCLUDED."pickupAt","returnPickupAt"=EXCLUDED."returnPickupAt","status"=EXCLUDED."status","confirmationNumber"=EXCLUDED."confirmationNumber","notes"=EXCLUDED."notes","updatedAt"=NOW() RETURNING *`,a.organizationId,req.params.appointmentId,Boolean(req.body?.required),text(req.body?.mode,80)||null,text(req.body?.vendor,200)||null,text(req.body?.pickupAddress,1000)||null,req.body?.pickupAt||null,req.body?.returnPickupAt||null,text(req.body?.status,40)||'PENDING',text(req.body?.confirmationNumber,200)||null,text(req.body?.notes,2000)||null);res.json({data:rows[0]});}catch(e){next(e);}});
 app.post('/api/spire/scheduling/waitlist',async(req,res,next)=>{try{const a=authOf(res);ensureWrite(a);const pid=text(req.body?.patientId,120);await requirePatient(prisma,a,pid,true);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAppointmentWaitlist"("organizationId","patientId","appointmentType","providerUserId","locationId","preferredStart","preferredEnd","priority","notes","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,a.organizationId,pid,text(req.body?.appointmentType,80)||'VISIT',text(req.body?.providerUserId,120)||null,text(req.body?.locationId,120)||null,req.body?.preferredStart||null,req.body?.preferredEnd||null,text(req.body?.priority,40)||'ROUTINE',text(req.body?.notes,2000)||null,a.userId);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
};
