import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinical=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const admins=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const ensure=(a:AuthContext)=>{if(!clinical.has(a.role))throw Object.assign(new Error('Spire clinical access is required'),{status:403});};
const ensureWrite=(a:AuthContext)=>{ensure(a);if(!writers.has(a.role))throw Object.assign(new Error('This Spire role is read-only'),{status:403});};
const isAdmin=(a:AuthContext)=>admins.has(a.role)||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
const text=(v:unknown,m=20000)=>typeof v==='string'?v.trim().slice(0,m):'';
async function allowed(prisma:PrismaClient,a:AuthContext,pid:string){if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const r=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."userId"=$2 AND x."clientId"=$3 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND h."userId"=$2 AND p."patientId"=$3 AND (p."endsAt" IS NULL OR p."endsAt">NOW())) AS allowed`,a.organizationId,a.userId,pid);return r[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,pid:string,write=false){write?ensureWrite(a):ensure(a);if(!(await allowed(prisma,a,pid)))throw Object.assign(new Error('This chart is outside your authorized clinical scope'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,pid:string,action:string,type:string,id:string,after:unknown){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10)`,a.organizationId,a.userId,a.email??null,pid,action,type,id,JSON.stringify(after??{}),a.ipAddress??null,a.userAgent??null);}
export const registerSpireCarePlanRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/patients/:patientId/care-plan/overview',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);const plans=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireCarePlan" WHERE "organizationId"=$1 AND "patientId"=$2 ORDER BY COALESCE("effectiveDate","createdAt"::date) DESC`,a.organizationId,pid);const current=plans[0]??null;const planId=current?String(current.id):'';const q=async(sql:string)=>planId?prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(sql,a.organizationId,pid,planId):[];const[goals,interventions,risks,signatures,services,assessments]=await Promise.all([q(`SELECT * FROM "SpireCarePlanGoal" WHERE "organizationId"=$1 AND "patientId"=$2 AND "carePlanId"=$3 ORDER BY "createdAt"`),q(`SELECT * FROM "SpireCarePlanIntervention" WHERE "organizationId"=$1 AND "patientId"=$2 AND "carePlanId"=$3 ORDER BY "createdAt"`),q(`SELECT * FROM "SpireCarePlanRisk" WHERE "organizationId"=$1 AND "patientId"=$2 AND "carePlanId"=$3 ORDER BY "riskLevel","createdAt"`),q(`SELECT * FROM "SpireCarePlanSignature" WHERE "organizationId"=$1 AND "patientId"=$2 AND "carePlanId"=$3 ORDER BY "signedAt"`),q(`SELECT * FROM "SpireCarePlanServiceLink" WHERE "organizationId"=$1 AND "patientId"=$2 AND "carePlanId"=$3 ORDER BY "startsAt"`),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT r.*,t."title" AS "templateTitle",t."category" FROM "SpireAssessmentResponse" r LEFT JOIN "SpireAssessmentTemplate" t ON t."id"=r."templateId" AND t."organizationId"=r."organizationId" WHERE r."organizationId"=$1 AND r."patientId"=$2 ORDER BY r."completedAt" DESC LIMIT 50`,a.organizationId,pid)]);res.json({data:{current,history:plans,goals,interventions,risks,signatures,services,assessments}});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const title=text(req.body?.title,250)||'Individual Service Plan';const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireCarePlan"("organizationId","patientId","title","planType","effectiveDate","annualReviewDate","personCenteredSummary","importantTo","importantFor","communicationPlan","transportationPlan","mealPlan","behaviorSupportPlan","emergencyPlan","rightsModifications","restrictiveMeasures","nursingDelegationInstructions","status","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,'DRAFT',$18) RETURNING *`,a.organizationId,pid,title,text(req.body?.planType,40)||'ISP',req.body?.effectiveDate||null,req.body?.annualReviewDate||null,text(req.body?.personCenteredSummary),text(req.body?.importantTo),text(req.body?.importantFor),text(req.body?.communicationPlan),text(req.body?.transportationPlan),text(req.body?.mealPlan),text(req.body?.behaviorSupportPlan),text(req.body?.emergencyPlan),text(req.body?.rightsModifications),text(req.body?.restrictiveMeasures),text(req.body?.nursingDelegationInstructions),a.userId);const row=rows[0];await audit(prisma,a,pid,'CREATE_CARE_PLAN','CARE_PLAN',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans/:carePlanId/goals',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const title=text(req.body?.title,250);if(!title)throw Object.assign(new Error('Goal title is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireCarePlanGoal"("organizationId","patientId","carePlanId","title","baseline","desiredOutcome","targetValue","targetUnit","frequency","responsibleDiscipline","progressPercent","startsAt","dueDate","reviewDate","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,a.organizationId,pid,req.params.carePlanId,title,text(req.body?.baseline),text(req.body?.desiredOutcome),req.body?.targetValue??null,text(req.body?.targetUnit,80)||null,text(req.body?.frequency,120)||null,text(req.body?.responsibleDiscipline,120)||null,Number(req.body?.progressPercent??0),req.body?.startsAt||null,req.body?.dueDate||null,req.body?.reviewDate||null,a.userId);const row=rows[0];await audit(prisma,a,pid,'CREATE_GOAL','CARE_PLAN_GOAL',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans/:carePlanId/interventions',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const title=text(req.body?.title,250),instructions=text(req.body?.instructions);if(!title||!instructions)throw Object.assign(new Error('Intervention title and instructions are required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireCarePlanIntervention"("organizationId","patientId","carePlanId","goalId","title","instructions","frequency","responsibleRole","serviceType","createdById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,a.organizationId,pid,req.params.carePlanId,text(req.body?.goalId,100)||null,title,instructions,text(req.body?.frequency,120)||null,text(req.body?.responsibleRole,120)||null,text(req.body?.serviceType,120)||null,a.userId);const row=rows[0];await audit(prisma,a,pid,'CREATE_INTERVENTION','CARE_PLAN_INTERVENTION',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans/:carePlanId/progress',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const goalId=text(req.body?.goalId,100);if(!goalId)throw Object.assign(new Error('Goal is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireGoalProgressEntry"("organizationId","patientId","goalId","encounterId","noteId","interventionId","assessmentId","incidentId","appointmentId","medicationOrderId","value","unit","progressPercent","narrative","recordedById") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,a.organizationId,pid,goalId,text(req.body?.encounterId,100)||null,text(req.body?.noteId,100)||null,text(req.body?.interventionId,100)||null,text(req.body?.assessmentId,100)||null,text(req.body?.incidentId,100)||null,text(req.body?.appointmentId,100)||null,text(req.body?.medicationOrderId,100)||null,req.body?.value??null,text(req.body?.unit,80)||null,req.body?.progressPercent??null,text(req.body?.narrative),a.userId);if(req.body?.progressPercent!=null)await prisma.$executeRawUnsafe(`UPDATE "SpireCarePlanGoal" SET "progressPercent"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "patientId"=$3 AND "id"=$4`,Number(req.body.progressPercent),a.organizationId,pid,goalId);const row=rows[0];await audit(prisma,a,pid,'DOCUMENT_GOAL_PROGRESS','GOAL_PROGRESS',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans/:carePlanId/signatures',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const signerRole=text(req.body?.signerRole,80),signerName=text(req.body?.signerName,250);if(!signerRole||!signerName)throw Object.assign(new Error('Signer role and name are required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireCarePlanSignature"("organizationId","patientId","carePlanId","signerRole","signerName","signerUserId","signatureMethod","ipAddress","userAgent","attestation") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,a.organizationId,pid,req.params.carePlanId,signerRole,signerName,a.userId,text(req.body?.signatureMethod,40)||'ELECTRONIC',a.ipAddress??null,a.userAgent??null,text(req.body?.attestation));const row=rows[0];await audit(prisma,a,pid,'SIGN_CARE_PLAN','CARE_PLAN_SIGNATURE',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
};
