import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const managers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.RN,UserRole.CEO,UserRole.DOO]);
const licensed=new Set<UserRole>([UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company first');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureManager=(a:AuthContext)=>{if(!managers.has(a.role)&&!owner(a))throw httpError(403,'Medication qualification administration requires RN/delegating-nurse/program/administrator access');entity(a);};
const text=(v:unknown,max=4000)=>typeof v==='string'?v.trim().slice(0,max):'';
const grantSchema=z.object({userId:z.string().trim().min(1).max(120),qualificationType:z.enum(['DODD_MED_ADMIN','NURSING_DELEGATION','COMPANY_MED_ADMIN_COMPETENCY','OTHER_VERIFIED_AUTHORIZATION']),qualificationLevel:z.string().trim().max(160).optional().nullable(),certificateNumber:z.string().trim().max(160).optional().nullable(),effectiveAt:z.string().datetime().optional().nullable(),expiresAt:z.string().datetime().optional().nullable(),scope:z.record(z.unknown()).optional().default({}),notes:z.string().trim().max(5000).optional().nullable()});
const revokeSchema=z.object({action:z.enum(['SUSPEND','REVOKE','EXPIRE','REACTIVATE']),reason:z.string().trim().max(5000).optional().nullable(),expiresAt:z.string().datetime().optional().nullable()});
async function activeQualification(prisma:PrismaClient,a:AuthContext,userId:string){if(licensed.has(a.role)&&userId===a.userId)return{authorized:true,basis:'LICENSED_ROLE',role:a.role,qualifications:[]};const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireMedicationAdministrationQualification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "status"='ACTIVE' AND "revokedAt" IS NULL AND "effectiveAt"<=NOW() AND ("expiresAt" IS NULL OR "expiresAt">NOW()) ORDER BY "expiresAt" NULLS LAST,"verifiedAt" DESC`,a.organizationId,entity(a),userId);return{authorized:rows.length>0,basis:rows.length?'VERIFIED_QUALIFICATION':'NONE',role:userId===a.userId?a.role:null,qualifications:rows};}
async function event(prisma:PrismaClient,a:AuthContext,qid:string,userId:string,eventType:string,details:Record<string,unknown>={}){await prisma.$executeRawUnsafe(`INSERT INTO "SpireMedicationQualificationEvent"("id","organizationId","legalEntityId","qualificationId","userId","actorUserId","eventType","details") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,randomUUID(),a.organizationId,entity(a),qid,userId,a.userId,eventType,JSON.stringify(details));}
export const registerSpireMedicationQualificationRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
  app.get('/api/spire/medication-qualifications/me',async(_req,res,next)=>{try{const a=authOf(res);entity(a);res.json({data:await activeQualification(prisma,a,a.userId)});}catch(e){next(e);}});
  app.get('/api/admin/spire/medication-qualifications',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);const userId=text(req.query.userId,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireMedicationAdministrationQualification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ($3='' OR "userId"=$3) ORDER BY CASE "status" WHEN 'ACTIVE' THEN 0 ELSE 1 END,"expiresAt" NULLS LAST,"updatedAt" DESC LIMIT 1000`,a.organizationId,entity(a),userId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/admin/spire/medication-qualifications',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);const i=grantSchema.parse(req.body);if(i.expiresAt&&i.effectiveAt&&new Date(i.expiresAt)<=new Date(i.effectiveAt))throw httpError(400,'Qualification expiration must be after its effective date');const existing=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireMedicationAdministrationQualification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "qualificationType"=$4 AND "status"='ACTIVE' AND "revokedAt" IS NULL LIMIT 1`,a.organizationId,entity(a),i.userId,i.qualificationType);if(existing[0])throw httpError(409,'An active qualification of this type already exists for this employee');const id=randomUUID();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireMedicationAdministrationQualification"("id","organizationId","legalEntityId","userId","qualificationType","qualificationLevel","certificateNumber","status","effectiveAt","expiresAt","verifiedAt","verifiedById","scope","notes") VALUES($1,$2,$3,$4,$5,$6,$7,'ACTIVE',COALESCE($8::timestamptz,NOW()),$9::timestamptz,NOW(),$10,$11::jsonb,$12) RETURNING *`,id,a.organizationId,entity(a),i.userId,i.qualificationType,i.qualificationLevel??null,i.certificateNumber??null,i.effectiveAt??null,i.expiresAt??null,a.userId,JSON.stringify(i.scope),i.notes??null);await event(prisma,a,id,i.userId,'QUALIFICATION_VERIFIED',{qualificationType:i.qualificationType,expiresAt:i.expiresAt??null});res.status(201).json({data:rows[0]});}catch(e){next(e);}});
  app.post('/api/admin/spire/medication-qualifications/:qualificationId/status',async(req,res,next)=>{try{const a=authOf(res);ensureManager(a);const i=revokeSchema.parse(req.body),rows=await prisma.$queryRawUnsafe<Array<{id:string;userId:string;status:string}>>(`SELECT "id","userId","status" FROM "SpireMedicationAdministrationQualification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.qualificationId);const q=rows[0];if(!q)throw httpError(404,'Medication qualification was not found');let status='ACTIVE';if(i.action==='SUSPEND')status='SUSPENDED';if(i.action==='REVOKE')status='REVOKED';if(i.action==='EXPIRE')status='EXPIRED';await prisma.$executeRawUnsafe(`UPDATE "SpireMedicationAdministrationQualification" SET "status"=$1,"expiresAt"=COALESCE($2::timestamptz,"expiresAt"),"revokedAt"=CASE WHEN $1='REVOKED' THEN NOW() WHEN $1='ACTIVE' THEN NULL ELSE "revokedAt" END,"revokedById"=CASE WHEN $1='REVOKED' THEN $3 WHEN $1='ACTIVE' THEN NULL ELSE "revokedById" END,"revocationReason"=CASE WHEN $1 IN ('REVOKED','SUSPENDED','EXPIRED') THEN $4 WHEN $1='ACTIVE' THEN NULL ELSE "revocationReason" END,"updatedAt"=NOW() WHERE "organizationId"=$5 AND "legalEntityId"=$6 AND "id"=$7`,status,i.expiresAt??null,a.userId,i.reason??null,a.organizationId,entity(a),q.id);await event(prisma,a,q.id,q.userId,`QUALIFICATION_${i.action}`,{fromStatus:q.status,toStatus:status,reason:i.reason??null});res.json({data:{id:q.id,userId:q.userId,status}});}catch(e){next(e);}});
};
