import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const roles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const elevatedRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before opening My Shift');return a.legalEntityId;};
const elevated=(a:AuthContext)=>a.enterpriseOwner===true||elevatedRoles.has(a.role)||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensure=(a:AuthContext)=>{if(!roles.has(a.role)&&a.enterpriseOwner!==true)throw httpError(403,'SPIRE shift access is required');entity(a);};
async function medicationAuthorization(prisma:PrismaClient,a:AuthContext){if([UserRole.RN,UserRole.LPN,UserRole.DELEGATING_NURSE].includes(a.role))return{authorized:true,basis:'LICENSED_ROLE',role:a.role,qualifications:[]};const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","qualificationType","qualificationLevel","certificateNumber","effectiveAt","expiresAt","scope" FROM "SpireMedicationAdministrationQualification" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "status"='ACTIVE' AND "revokedAt" IS NULL AND "effectiveAt"<=NOW() AND ("expiresAt" IS NULL OR "expiresAt">NOW()) ORDER BY "expiresAt" NULLS LAST`,a.organizationId,entity(a),a.userId).catch(()=>[]);return{authorized:rows.length>0,basis:rows.length?'VERIFIED_QUALIFICATION':'NONE',role:a.role,qualifications:rows};}
export const registerSpireShiftWorkspaceRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/my-shift',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);const entityId=entity(a);const patients=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT p."id",p."medicalRecordNumber",p."firstName",p."lastName",p."preferredName",p."dateOfBirth",
   COALESCE((SELECT jsonb_agg(jsonb_build_object('label',f."label",'severity',f."severity",'details',f."details") ORDER BY CASE f."severity" WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,f."createdAt" DESC) FROM "SpirePatientFlag" f WHERE f."organizationId"=p."organizationId" AND f."patientId"=p."id" AND f."active"=TRUE),'[]'::jsonb) AS flags,
   (SELECT jsonb_build_object('temperature',v."temperature",'pulse',v."pulse",'respirations',v."respirations",'systolic',v."systolic",'diastolic',v."diastolic",'spo2',v."spo2",'weight',v."weight",'oxygen',v."oxygen",'recordedAt',v."recordedAt",'legalEntityId',v."legalEntityId") FROM "SpireVitalSign" v WHERE v."organizationId"=p."organizationId" AND v."patientId"=p."id" ORDER BY v."recordedAt" DESC LIMIT 1) AS "latestVitals",
   COALESCE((SELECT jsonb_agg(jsonb_build_object('id',m."id",'name',m."name",'dose',m."dose",'route',m."route",'frequency',m."frequency",'instructions',m."instructions",'dueTimes',m."dueTimes",'schedules',COALESCE((SELECT jsonb_agg(jsonb_build_object('scheduledTime',s."scheduledTime",'windowBeforeMinutes',s."windowBeforeMinutes",'windowAfterMinutes',s."windowAfterMinutes") ORDER BY s."scheduledTime") FROM "SpireMedicationSchedule" s WHERE s."organizationId"=m."organizationId" AND s."medicationOrderId"=m."id" AND s."active"=TRUE),'[]'::jsonb),'administrations',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',ma."id",'legalEntityId',ma."legalEntityId",'scheduledFor',ma."scheduledFor",'status',ma."status",'administeredAt',ma."administeredAt",'administeredById',ma."administeredById") ORDER BY ma."createdAt") FROM "SpireMedicationAdministrationEvent" ma WHERE ma."organizationId"=m."organizationId" AND ma."medicationOrderId"=m."id" AND COALESCE(ma."scheduledFor",ma."createdAt")::date=CURRENT_DATE),'[]'::jsonb))) FROM "SpireMedicationOrder" m WHERE m."organizationId"=p."organizationId" AND m."patientId"=p."id" AND m."status"='ACTIVE'),'[]'::jsonb) AS medications,
   COALESCE((SELECT jsonb_agg(jsonb_build_object('id',d."id",'dueAt',d."dueAt",'reason',d."reason",'templateTitle',t."title") ORDER BY d."dueAt") FROM "SpireClinicalReassessmentDue" d LEFT JOIN "SpireAssessmentTemplate" t ON t."id"=d."assessmentTemplateId" AND t."organizationId"=d."organizationId" WHERE d."organizationId"=p."organizationId" AND d."patientId"=p."id" AND d."status"='OPEN' AND d."dueAt"<NOW()+INTERVAL '24 hours'),'[]'::jsonb) AS "dueAssessments"
 FROM "SpirePatient" p JOIN "ClientEnrollment" ce ON ce."organizationId"=p."organizationId" AND ce."clientId"=p."id" AND ce."legalEntityId"=$2 AND ce."status" IN ('PENDING','ACTIVE','PAUSED')
 WHERE p."organizationId"=$1 AND p."active"=TRUE AND ($3::boolean=TRUE OR EXISTS(
   SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."legalEntityId"=$2 AND x."userId"=$4 AND x."clientId"=p."id"
   UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" pa JOIN "SpireEmployeeHomeAssignment" ha ON ha."organizationId"=pa."organizationId" AND ha."legalEntityId"=pa."legalEntityId" AND ha."homeId"=pa."homeId" WHERE pa."organizationId"=$1 AND pa."legalEntityId"=$2 AND ha."userId"=$4 AND pa."patientId"=p."id" AND (pa."endsAt" IS NULL OR pa."endsAt">NOW())
   UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$4 AND g."scopeType"='CLIENT' AND g."clientId"=p."id" AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())
 )) ORDER BY p."lastName",p."firstName"`,a.organizationId,entityId,elevated(a),a.userId);
 const medAuth=await medicationAuthorization(prisma,a);res.json({data:{generatedAt:new Date().toISOString(),selectedLegalEntityId:entityId,role:a.role,medicationAuthorization:medAuth,patients}});}catch(e){next(e);}});
};
