import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const clinical=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.AUDITOR,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const writers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const admins=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.CEO,UserRole.DOO]);
const ensure=(a:AuthContext)=>{if(!clinical.has(a.role))throw Object.assign(new Error('Spire clinical access is required'),{status:403});};
const ensureWrite=(a:AuthContext)=>{ensure(a);if(!writers.has(a.role))throw Object.assign(new Error('This Spire role is read-only'),{status:403});};
const isAdmin=(a:AuthContext)=>admins.has(a.role)||a.enterpriseOwner===true||String(a.email||'').toLowerCase()==='admin@sulandrahealth.com';
const entityId=(a:AuthContext)=>{if(!a.legalEntityId)throw Object.assign(new Error('Select a Sulandra company before documenting in SPIRE'),{status:409});return a.legalEntityId;};
const text=(v:unknown,m=20000)=>typeof v==='string'?v.trim().slice(0,m):'';
async function allowed(prisma:PrismaClient,a:AuthContext,pid:string){const entity=entityId(a);const enrolled=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "ClientEnrollment" e WHERE e."organizationId"=$1 AND e."legalEntityId"=$2 AND e."clientId"=$3 AND e."status" IN ('PENDING','ACTIVE','PAUSED')) AS allowed`,a.organizationId,entity,pid);if(enrolled[0]?.allowed!==true)return false;if(isAdmin(a)||a.role===UserRole.AUDITOR)return true;const r=await prisma.$queryRawUnsafe<Array<{allowed:boolean}>>(`SELECT EXISTS(SELECT 1 FROM "SpireEmployeeClientAssignment" x WHERE x."organizationId"=$1 AND x."legalEntityId"=$2 AND x."userId"=$3 AND x."clientId"=$4 UNION ALL SELECT 1 FROM "SpirePatientHomeAssignment" p JOIN "SpireEmployeeHomeAssignment" h ON h."organizationId"=p."organizationId" AND h."legalEntityId"=p."legalEntityId" AND h."homeId"=p."homeId" WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND h."userId"=$3 AND p."patientId"=$4 AND (p."endsAt" IS NULL OR p."endsAt">NOW()) UNION ALL SELECT 1 FROM "UserEntityAccessGrant" g WHERE g."organizationId"=$1 AND g."legalEntityId"=$2 AND g."userId"=$3 AND g."scopeType"='CLIENT' AND g."clientId"=$4 AND g."active"=TRUE AND g."effectiveFrom"<=NOW() AND (g."effectiveTo" IS NULL OR g."effectiveTo">NOW())) AS allowed`,a.organizationId,entity,a.userId,pid);return r[0]?.allowed===true;}
async function requirePatient(prisma:PrismaClient,a:AuthContext,pid:string,write=false){write?ensureWrite(a):ensure(a);if(!(await allowed(prisma,a,pid)))throw Object.assign(new Error('This chart is outside your authorized clinical scope for the selected company'),{status:403});}
async function audit(prisma:PrismaClient,a:AuthContext,pid:string,action:string,type:string,id:string,after:unknown){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,a.organizationId,entityId(a),a.userId,a.email??null,pid,action,type,id,JSON.stringify(after??{}),a.ipAddress??null,a.userAgent??null);}

const standardTemplates=[
  ['NURSING','Nursing Assessment','RN/LPN','General nursing assessment and change-of-condition review'],['DSP','DSP Assessment','DSP','Daily support, functional status and person-centered observations'],['FALL_RISK','Fall Risk','CLINICAL','Fall history, mobility, medications and environmental risks'],['SKIN','Skin Assessment','NURSING','Skin integrity, pressure injury and wound risk'],['PAIN','Pain Assessment','CLINICAL','Pain location, intensity, quality and response'],['NUTRITION','Nutrition Assessment','CLINICAL','Intake, swallowing, weight and nutrition risk'],['SEIZURE','Seizure Profile','NURSING','Seizure baseline, triggers, rescue plan and postictal response'],['BEHAVIOR','Behavior Assessment','CLINICAL','Behavior frequency, triggers, antecedents and supports'],['ADL','ADL / IADL','DSP','Functional independence and support needs'],['SAFETY','Environment & Safety','DSP','Home, fire, elopement, abuse and environmental safety']
];
async function ensureStandardTemplates(prisma:PrismaClient,org:string,userId:string){for(const [category,title,discipline,description] of standardTemplates){await prisma.$executeRawUnsafe(`INSERT INTO "SpireAssessmentTemplate"("id","organizationId","title","category","schema","description","discipline","scoringMethod","requiresSignature","active","createdById","createdAt","updatedAt") SELECT gen_random_uuid()::text,$1,$2,$3,'{}'::jsonb,$4,$5,'SUM',TRUE,TRUE,$6,NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM "SpireAssessmentTemplate" WHERE "organizationId"=$1 AND "category"=$3 AND "active"=TRUE)`,org,title,category,description,discipline,userId);}}
function abnormal(n:number|null,row:Record<string,unknown>){if(n==null)return null;const cl=row.criticalLow==null?null:Number(row.criticalLow),ch=row.criticalHigh==null?null:Number(row.criticalHigh),nl=row.normalLow==null?null:Number(row.normalLow),nh=row.normalHigh==null?null:Number(row.normalHigh);if((cl!=null&&n<cl)||(ch!=null&&n>ch))return 'CRITICAL';if((nl!=null&&n<nl)||(nh!=null&&n>nh))return 'ABNORMAL';return 'NORMAL';}

export const registerSpireAssessmentsFlowsheetsRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
  app.get('/api/spire/assessment-templates',async(_req,res,next)=>{try{const a=authOf(res);ensure(a);entityId(a);await ensureStandardTemplates(prisma,a.organizationId,a.userId);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT t.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',q."id",'section',q."section",'code',q."code",'label',q."label",'helpText',q."helpText",'responseType',q."responseType",'options',q."options",'required',q."required",'scoreMap',q."scoreMap",'sortOrder',q."sortOrder") ORDER BY q."sortOrder") FROM "SpireAssessmentQuestion" q WHERE q."organizationId"=t."organizationId" AND q."templateId"=t."id" AND q."active"=TRUE),'[]'::jsonb) AS questions FROM "SpireAssessmentTemplate" t WHERE t."organizationId"=$1 AND t."active"=TRUE ORDER BY t."category",t."title"`,a.organizationId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/spire/assessment-templates/:templateId/questions',async(req,res,next)=>{try{const a=authOf(res);entityId(a);if(!isAdmin(a))throw Object.assign(new Error('Assessment template administration requires clinical administration access'),{status:403});const label=text(req.body?.label,500),code=text(req.body?.code,100);if(!label||!code)throw Object.assign(new Error('Question code and label are required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAssessmentQuestion"("organizationId","templateId","section","code","label","helpText","responseType","options","required","scoreMap","sortOrder") VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10::jsonb,$11) RETURNING *`,a.organizationId,req.params.templateId,text(req.body?.section,120)||null,code,label,text(req.body?.helpText)||null,text(req.body?.responseType,40)||'TEXT',JSON.stringify(req.body?.options??[]),Boolean(req.body?.required),JSON.stringify(req.body?.scoreMap??{}),Number(req.body?.sortOrder??0));res.status(201).json({data:rows[0]});}catch(e){next(e);}});
  app.get('/api/spire/patients/:patientId/assessments/overview',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);await ensureStandardTemplates(prisma,a.organizationId,a.userId);const [responses,due]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT r.*,t."title" AS "templateTitle",t."category",t."discipline" FROM "SpireAssessmentResponse" r JOIN "SpireAssessmentTemplate" t ON t."id"=r."templateId" AND t."organizationId"=r."organizationId" WHERE r."organizationId"=$1 AND r."patientId"=$2 ORDER BY COALESCE(r."completedAt",r."startedAt") DESC LIMIT 250`,a.organizationId,pid),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT d.*,t."title" AS "templateTitle" FROM "SpireClinicalReassessmentDue" d LEFT JOIN "SpireAssessmentTemplate" t ON t."id"=d."assessmentTemplateId" AND t."organizationId"=d."organizationId" WHERE d."organizationId"=$1 AND d."patientId"=$2 AND d."status"='OPEN' ORDER BY d."dueAt"`,a.organizationId,pid)]);res.json({data:{responses,due,selectedLegalEntityId:entityId(a)}});}catch(e){next(e);}});
  app.post('/api/spire/patients/:patientId/assessments',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const templateId=text(req.body?.templateId,100);if(!templateId)throw Object.assign(new Error('Assessment template is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAssessmentResponse"("organizationId","legalEntityId","patientId","templateId","encounterId","status","responses","startedAt","completedById") VALUES($1,$2,$3,$4,$5,'DRAFT','{}'::jsonb,NOW(),$6) RETURNING *`,a.organizationId,entityId(a),pid,templateId,text(req.body?.encounterId,100)||null,a.userId);const row=rows[0];await audit(prisma,a,pid,'START_ASSESSMENT','ASSESSMENT',String(row.id),row);res.status(201).json({data:row});}catch(e){next(e);}});
  app.put('/api/spire/patients/:patientId/assessments/:responseId',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const entity=entityId(a);const answers=Array.isArray(req.body?.answers)?req.body.answers:[];let total=0;for(const ans of answers){const qid=text(ans?.questionId,100);if(!qid)continue;const score=ans?.score==null?null:Number(ans.score);if(score!=null&&Number.isFinite(score))total+=score;await prisma.$executeRawUnsafe(`INSERT INTO "SpireAssessmentAnswer"("organizationId","legalEntityId","patientId","responseId","questionId","valueText","valueNumber","valueBoolean","valueJson","score","comment") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) ON CONFLICT("responseId","questionId") DO UPDATE SET "valueText"=EXCLUDED."valueText","valueNumber"=EXCLUDED."valueNumber","valueBoolean"=EXCLUDED."valueBoolean","valueJson"=EXCLUDED."valueJson","score"=EXCLUDED."score","comment"=EXCLUDED."comment","updatedAt"=NOW() WHERE "SpireAssessmentAnswer"."legalEntityId"=EXCLUDED."legalEntityId"`,a.organizationId,entity,pid,req.params.responseId,qid,text(ans?.valueText)||null,ans?.valueNumber==null?null:Number(ans.valueNumber),typeof ans?.valueBoolean==='boolean'?ans.valueBoolean:null,JSON.stringify(ans?.valueJson??null),score,text(ans?.comment)||null);}const status=req.body?.complete?'COMPLETED':'DRAFT';const summary=text(req.body?.summary);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`UPDATE "SpireAssessmentResponse" SET "status"=$1,"score"=$2,"scoreBand"=$3,"summary"=$4,"responses"=$5::jsonb,"completedAt"=CASE WHEN $1='COMPLETED' THEN NOW() ELSE "completedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$6 AND "legalEntityId"=$7 AND "patientId"=$8 AND "id"=$9 RETURNING *`,status,total,text(req.body?.scoreBand,80)||null,summary||null,JSON.stringify(req.body?.responses??{}),a.organizationId,entity,pid,req.params.responseId);if(!rows[0])throw Object.assign(new Error('Assessment was not found in the selected company'),{status:404});await audit(prisma,a,pid,status==='COMPLETED'?'COMPLETE_ASSESSMENT':'SAVE_ASSESSMENT','ASSESSMENT',req.params.responseId,rows[0]);res.json({data:rows[0]});}catch(e){next(e);}});
  app.post('/api/spire/patients/:patientId/assessments/:responseId/sign',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const entity=entityId(a);const signerName=text(req.body?.signerName,250)||a.email||a.userId;const owner=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT "id" FROM "SpireAssessmentResponse" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity,pid,req.params.responseId);if(!owner[0])throw Object.assign(new Error('Assessment was not found in the selected company'),{status:404});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireAssessmentSignature"("organizationId","legalEntityId","patientId","responseId","signerUserId","signerName","signerRole","attestation","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,a.organizationId,entity,pid,req.params.responseId,a.userId,signerName,String(a.role),text(req.body?.attestation)||'I attest that this assessment is complete and accurate.',a.ipAddress??null,a.userAgent??null);await prisma.$executeRawUnsafe(`UPDATE "SpireAssessmentResponse" SET "signedAt"=NOW(),"signedById"=$1,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "patientId"=$4 AND "id"=$5`,a.userId,a.organizationId,entity,pid,req.params.responseId);await audit(prisma,a,pid,'SIGN_ASSESSMENT','ASSESSMENT_SIGNATURE',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
  app.get('/api/spire/patients/:patientId/flowsheets',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);const from=text(req.query.from,40)||new Date(Date.now()-7*86400000).toISOString();const to=text(req.query.to,40)||new Date().toISOString();const [rows,entries]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireFlowsheetRow" WHERE "organizationId"=$1 AND "active"=TRUE ORDER BY "groupName","sortOrder","name"`,a.organizationId),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT e.*,r."name" AS "rowName",r."groupName",r."unit",r."dataType" FROM "SpireFlowsheetEntry" e JOIN "SpireFlowsheetRow" r ON r."id"=e."rowId" AND r."organizationId"=e."organizationId" WHERE e."organizationId"=$1 AND e."patientId"=$2 AND e."recordedAt">=$3::timestamptz AND e."recordedAt"<=$4::timestamptz ORDER BY e."recordedAt" DESC`,a.organizationId,pid,from,to)]);res.json({data:{rows,entries,from,to,selectedLegalEntityId:entityId(a)}});}catch(e){next(e);}});
  app.post('/api/spire/patients/:patientId/flowsheets/entries',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid,true);const rowId=text(req.body?.rowId,100);if(!rowId)throw Object.assign(new Error('Flowsheet row is required'),{status:400});const rowRows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireFlowsheetRow" WHERE "organizationId"=$1 AND "id"=$2`,a.organizationId,rowId);if(!rowRows[0])throw Object.assign(new Error('Flowsheet row not found'),{status:404});const numeric=req.body?.numericValue==null||req.body?.numericValue===''?null:Number(req.body.numericValue);const flag=Number.isFinite(numeric as number)?abnormal(numeric as number,rowRows[0]):null;const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`INSERT INTO "SpireFlowsheetEntry"("organizationId","legalEntityId","patientId","encounterId","rowId","value","numericValue","recordedAt","recordedById","comment","abnormalFlag","source") VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8::timestamptz,NOW()),$9,$10,$11,$12) RETURNING *`,a.organizationId,entityId(a),pid,text(req.body?.encounterId,100)||null,rowId,text(req.body?.value)||null,numeric,text(req.body?.recordedAt,80)||null,a.userId,text(req.body?.comment)||null,flag,text(req.body?.source,40)||'MANUAL');await audit(prisma,a,pid,'RECORD_FLOWSHEET','FLOWSHEET_ENTRY',String(rows[0].id),rows[0]);res.status(201).json({data:rows[0]});}catch(e){next(e);}});
  app.get('/api/spire/patients/:patientId/flowsheets/trends',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId;await requirePatient(prisma,a,pid);const rowId=text(req.query.rowId,100);if(!rowId)throw Object.assign(new Error('rowId is required'),{status:400});const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT e."id",e."legalEntityId",e."recordedAt",e."numericValue",e."value",e."abnormalFlag",e."comment",r."name",r."unit",r."normalLow",r."normalHigh",r."criticalLow",r."criticalHigh" FROM "SpireFlowsheetEntry" e JOIN "SpireFlowsheetRow" r ON r."id"=e."rowId" AND r."organizationId"=e."organizationId" WHERE e."organizationId"=$1 AND e."patientId"=$2 AND e."rowId"=$3 ORDER BY e."recordedAt" DESC LIMIT 500`,a.organizationId,pid,rowId);res.json({data:rows});}catch(e){next(e);}});
};