import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext};
const contributors=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DSP,UserRole.DELEGATING_NURSE,UserRole.LPN,UserRole.RN,UserRole.HOUSE_MANAGER,UserRole.CEO,UserRole.DOO]);
const reviewers=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.DELEGATING_NURSE,UserRole.RN,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before managing the Care Plan / ISP');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureContributor=(a:AuthContext)=>{if(!contributors.has(a.role)&&!owner(a))throw httpError(403,'Care Plan contribution access is required');entity(a);};
const ensureReviewer=(a:AuthContext)=>{ensureContributor(a);if(!reviewers.has(a.role)&&!owner(a))throw httpError(403,'RN, delegating nurse, program manager, or administrator review access is required');};
const actionSchema=z.object({action:z.enum(['SUBMIT_REVIEW','RETURN_DRAFT','ACTIVATE','SUPERSEDE']),reason:z.string().trim().max(5000).optional().nullable()});
async function plan(prisma:PrismaClient,a:AuthContext,pid:string,id:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "SpireCarePlan" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity(a),pid,id);if(!rows[0])throw httpError(404,'Care Plan / ISP was not found in the selected company');return rows[0];}
async function readiness(prisma:PrismaClient,a:AuthContext,pid:string,id:string){const p=await plan(prisma,a,pid,id);const [goals,interventions,risks,signatures]=await Promise.all([prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT count(*)::int AS count FROM "SpireCarePlanGoal" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "carePlanId"=$4 AND "status"='ACTIVE'`,a.organizationId,entity(a),pid,id),prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT count(*)::int AS count FROM "SpireCarePlanIntervention" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "carePlanId"=$4 AND "status"='ACTIVE'`,a.organizationId,entity(a),pid,id),prisma.$queryRawUnsafe<Array<{count:number}>>(`SELECT count(*)::int AS count FROM "SpireCarePlanRisk" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "carePlanId"=$4 AND "active"=TRUE`,a.organizationId,entity(a),pid,id),prisma.$queryRawUnsafe<Array<{signerRole:string;signerName:string;signedAt:Date}>>(`SELECT "signerRole","signerName","signedAt" FROM "SpireCarePlanSignature" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "patientId"=$3 AND "carePlanId"=$4 AND "status"='SIGNED' ORDER BY "signedAt"`,a.organizationId,entity(a),pid,id)]);const blockers:string[]=[];if(!String(p.importantTo||'').trim())blockers.push('Document what is important TO the person');if(!String(p.importantFor||'').trim())blockers.push('Document what is important FOR the person');if(!String(p.communicationPlan||'').trim())blockers.push('Document the communication plan');if(!p.effectiveDate)blockers.push('Set an effective date');if(Number(goals[0]?.count||0)<1)blockers.push('Add at least one active goal/outcome');if(Number(interventions[0]?.count||0)<1)blockers.push('Add at least one staff intervention/support instruction');return{plan:p,goals:Number(goals[0]?.count||0),interventions:Number(interventions[0]?.count||0),risks:Number(risks[0]?.count||0),signatures,blockers,readyForReview:blockers.length===0,readyForActivation:blockers.length===0};}
async function version(prisma:PrismaClient,a:AuthContext,pid:string,id:string,reason:string){const rows=await prisma.$queryRawUnsafe<Array<{next:number}>>(`SELECT COALESCE(MAX("version"),0)::int+1 AS next FROM "SpireCarePlanVersion" WHERE "organizationId"=$1 AND "carePlanId"=$2`,a.organizationId,id);const snapshots=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT p.*,COALESCE((SELECT jsonb_agg(g ORDER BY g."createdAt") FROM "SpireCarePlanGoal" g WHERE g."organizationId"=p."organizationId" AND g."carePlanId"=p."id"),'[]'::jsonb) AS goals,COALESCE((SELECT jsonb_agg(i ORDER BY i."createdAt") FROM "SpireCarePlanIntervention" i WHERE i."organizationId"=p."organizationId" AND i."carePlanId"=p."id"),'[]'::jsonb) AS interventions,COALESCE((SELECT jsonb_agg(r ORDER BY r."createdAt") FROM "SpireCarePlanRisk" r WHERE r."organizationId"=p."organizationId" AND r."carePlanId"=p."id"),'[]'::jsonb) AS risks FROM "SpireCarePlan" p WHERE p."organizationId"=$1 AND p."legalEntityId"=$2 AND p."patientId"=$3 AND p."id"=$4 LIMIT 1`,a.organizationId,entity(a),pid,id);await prisma.$executeRawUnsafe(`INSERT INTO "SpireCarePlanVersion"("id","organizationId","carePlanId","version","snapshot","reason","createdById") VALUES($1,$2,$3,$4,$5::jsonb,$6,$7)`,randomUUID(),a.organizationId,id,rows[0]?.next||1,JSON.stringify(snapshots[0]||{}),reason,a.userId);}
async function audit(prisma:PrismaClient,a:AuthContext,pid:string,action:string,id:string,after:unknown){await prisma.$executeRawUnsafe(`INSERT INTO "SpireClinicalAuditEvent"("id","organizationId","legalEntityId","actorUserId","actorEmail","clientId","action","resourceType","resourceId","afterValue","ipAddress","userAgent") VALUES($1,$2,$3,$4,$5,$6,$7,'CARE_PLAN',$8,$9::jsonb,$10,$11)`,randomUUID(),a.organizationId,entity(a),a.userId,a.email??null,pid,action,id,JSON.stringify(after??{}),a.ipAddress??null,a.userAgent??null);}
export const registerSpireCarePlanLifecycleRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf}=deps;
 app.get('/api/spire/patients/:patientId/care-plans/:carePlanId/readiness',async(req,res,next)=>{try{const a=authOf(res);ensureContributor(a);res.json({data:await readiness(prisma,a,req.params.patientId,req.params.carePlanId)});}catch(e){next(e);}});
 app.post('/api/spire/patients/:patientId/care-plans/:carePlanId/lifecycle',async(req,res,next)=>{try{const a=authOf(res),pid=req.params.patientId,id=req.params.carePlanId,input=actionSchema.parse(req.body);ensureContributor(a);const info=await readiness(prisma,a,pid,id),current=String(info.plan.status||'DRAFT');let nextStatus='';if(input.action==='SUBMIT_REVIEW'){if(!['DRAFT','CHANGES_REQUESTED'].includes(current))throw httpError(409,`A ${current} plan cannot be submitted for review`);if(!info.readyForReview)throw httpError(409,'Complete required person-centered plan elements before review',info);nextStatus='IN_REVIEW';}else if(input.action==='RETURN_DRAFT'){ensureReviewer(a);if(current!=='IN_REVIEW')throw httpError(409,'Only a plan in review can be returned for changes');if(!input.reason)throw httpError(400,'A reason is required when returning a plan for changes');nextStatus='CHANGES_REQUESTED';}else if(input.action==='ACTIVATE'){ensureReviewer(a);if(!['IN_REVIEW','DRAFT'].includes(current))throw httpError(409,`A ${current} plan cannot be activated`);if(!info.readyForActivation)throw httpError(409,'The plan is not ready for activation',info);nextStatus='ACTIVE';}else{ensureReviewer(a);if(current!=='ACTIVE')throw httpError(409,'Only an active plan can be superseded');if(!input.reason)throw httpError(400,'A reason is required to supersede an active plan');nextStatus='SUPERSEDED';}await version(prisma,a,pid,id,`${input.action}: ${input.reason||'No additional reason entered'}`);await prisma.$executeRawUnsafe(`UPDATE "SpireCarePlan" SET "status"=$1,"signedAt"=CASE WHEN $1='ACTIVE' THEN COALESCE("signedAt",NOW()) ELSE "signedAt" END,"updatedAt"=NOW() WHERE "organizationId"=$2 AND "legalEntityId"=$3 AND "patientId"=$4 AND "id"=$5`,nextStatus,a.organizationId,entity(a),pid,id);await audit(prisma,a,pid,`CARE_PLAN_${input.action}`,id,{fromStatus:current,toStatus:nextStatus,reason:input.reason??null});res.json({data:{id,status:nextStatus,fromStatus:current,readiness:info}});}catch(e){next(e);}});
};
