import type { Express, RequestHandler, Response } from 'express';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { PrismaClient, UserRole } from '@prisma/client';

type AuthContext={userId:string;organizationId:string;role:UserRole};
type Dependencies={app:Express;prisma:PrismaClient;authOf:(res:Response)=>AuthContext;requireRoles:(...roles:UserRole[])=>RequestHandler};

const locationSchema=z.object({name:z.string().trim().min(2).max(160),address:z.string().trim().min(3).max(300),latitude:z.number().finite().min(-90).max(90).optional().nullable(),longitude:z.number().finite().min(-180).max(180).optional().nullable(),geofenceRadiusMeters:z.number().int().min(50).max(5000).default(250)});
const assignmentSchema=z.object({employeeId:z.string().trim().min(1),locationId:z.string().trim().min(1),isManager:z.boolean().optional().default(false)});
const cellSchema=z.object({employeeId:z.string().trim().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/),timezoneOffsetMinutes:z.number().int().min(-840).max(840).default(0),code:z.string().trim().min(1).max(30).default('SHIFT'),payCode:z.string().trim().max(40).default('REG')});
const saveGridSchema=z.object({locationId:z.string().trim().min(1),cells:z.array(cellSchema).max(1000),publish:z.boolean().optional().default(true)});
const copySchema=z.object({locationId:z.string().trim().min(1),sourceStart:z.coerce.date(),sourceEnd:z.coerce.date(),targetStart:z.coerce.date(),weeks:z.number().int().min(1).max(104),publish:z.boolean().optional().default(true)});

const localDateTime=(date:string,time:string,offsetMinutes:number)=>{
  const [year,month,day]=date.split('-').map(Number);
  const [hour,minute]=time.split(':').map(Number);
  return new Date(Date.UTC(year,month-1,day,hour,minute)+offsetMinutes*60000);
};

const ensureSchema=async(prisma:PrismaClient)=>{
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TimeAttendanceLocation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"address" TEXT NOT NULL,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"geofenceRadiusMeters" INTEGER NOT NULL DEFAULT 250,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "TA_location_org_name_uq" ON "TimeAttendanceLocation"("organizationId","name")`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TimeAttendanceLocationAssignment" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"isManager" BOOLEAN NOT NULL DEFAULT FALSE,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "TA_location_assignment_uq" ON "TimeAttendanceLocationAssignment"("organizationId","locationId","employeeId")`);
  await prisma.$executeRawUnsafe(`ALTER TABLE "TimeAttendanceShift" ADD COLUMN IF NOT EXISTS "locationId" TEXT`);
};

export const registerTimeAttendanceLocationSchedulerRoutes=({app,prisma,authOf,requireRoles}:Dependencies)=>{
  let readyPromise:Promise<void>|null=null;const ready=()=>readyPromise??=(ensureSchema(prisma).catch(e=>{readyPromise=null;throw e;}));
  const admin=requireRoles(UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.SCHEDULER,UserRole.CEO,UserRole.COO);
  const managers=requireRoles(UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.SCHEDULER,UserRole.CEO,UserRole.COO,UserRole.HOUSE_MANAGER);
  const isGlobal=(role:UserRole)=>['ADMINISTRATOR','PROGRAM_MANAGER','HR_MANAGER','SCHEDULER','CEO','COO'].includes(String(role));
  const canManage=async(a:AuthContext,locationId:string)=>{if(isGlobal(a.role))return true;const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT 1 FROM "TimeAttendanceLocationAssignment" WHERE "organizationId"=$1 AND "locationId"=$2 AND "employeeId"=$3 AND "isManager"=TRUE AND "active"=TRUE LIMIT 1`,a.organizationId,locationId,a.userId);return !!rows[0]};
  const assignEmployee=async(a:AuthContext,locationId:string,employeeId:string,isManager=false)=>prisma.$queryRawUnsafe<any[]>(`INSERT INTO "TimeAttendanceLocationAssignment" ("id","organizationId","locationId","employeeId","isManager") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("organizationId","locationId","employeeId") DO UPDATE SET "isManager"=("TimeAttendanceLocationAssignment"."isManager" OR EXCLUDED."isManager"),"active"=TRUE,"updatedAt"=NOW() RETURNING *`,randomUUID(),a.organizationId,locationId,employeeId,isManager);
  const ensureOffice=async(a:AuthContext)=>{let rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceLocation" WHERE "organizationId"=$1 AND LOWER("name")='office' AND "active"=TRUE LIMIT 1`,a.organizationId);if(!rows[0]&&isGlobal(a.role)){rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO "TimeAttendanceLocation" ("id","organizationId","name","address","geofenceRadiusMeters") VALUES ($1,$2,'Office','822 Dalewood Pl Dayton Ohio 45426 Suite A',250) RETURNING *`,randomUUID(),a.organizationId)}if(rows[0])await assignEmployee(a,rows[0].id,a.userId,isGlobal(a.role));return rows[0]||null};

  app.get('/api/admin/time-attendance/locations',managers,async(_req,res,next)=>{try{await ready();const a=authOf(res);await ensureOffice(a);const rows=isGlobal(a.role)?await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceLocation" WHERE "organizationId"=$1 AND "active"=TRUE ORDER BY CASE WHEN LOWER("name")='office' THEN 0 ELSE 1 END,"name"`,a.organizationId):await prisma.$queryRawUnsafe<any[]>(`SELECT l.* FROM "TimeAttendanceLocation" l JOIN "TimeAttendanceLocationAssignment" x ON x."locationId"=l."id" AND x."organizationId"=l."organizationId" WHERE l."organizationId"=$1 AND l."active"=TRUE AND x."employeeId"=$2 AND x."isManager"=TRUE AND x."active"=TRUE ORDER BY CASE WHEN LOWER(l."name")='office' THEN 0 ELSE 1 END,l."name"`,a.organizationId,a.userId);res.json({data:rows})}catch(e){next(e)}});
  app.post('/api/admin/time-attendance/locations',admin,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=locationSchema.parse(req.body);const rows=await prisma.$queryRawUnsafe<any[]>(`INSERT INTO "TimeAttendanceLocation" ("id","organizationId","name","address","latitude","longitude","geofenceRadiusMeters") VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,randomUUID(),a.organizationId,input.name,input.address,input.latitude??null,input.longitude??null,input.geofenceRadiusMeters);await assignEmployee(a,rows[0].id,a.userId,true);res.status(201).json({data:rows[0]})}catch(e){next(e)}});
  app.post('/api/admin/time-attendance/location-assignments',admin,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=assignmentSchema.parse(req.body);const rows=await assignEmployee(a,input.locationId,input.employeeId,input.isManager);res.status(201).json({data:rows[0]})}catch(e){next(e)}});
  app.get('/api/admin/time-attendance/locations/:id/employees',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);if(!(await canManage(a,req.params.id)))return res.status(403).json({error:'You may manage only assigned service locations'});let rows=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName",COALESCE(x."isManager",FALSE) AS "isManager" FROM "TimeAttendanceLocationAssignment" x JOIN "User" u ON u."id"=x."employeeId" LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE x."organizationId"=$1 AND x."locationId"=$2 AND x."active"=TRUE ORDER BY COALESCE(NULLIF(c."displayName",''),u."email")`,a.organizationId,req.params.id);if(!rows.length&&isGlobal(a.role)){await assignEmployee(a,req.params.id,a.userId,true);rows=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."email",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName",TRUE AS "isManager" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE u."id"=$1 AND u."organizationId"=$2`,a.userId,a.organizationId)}res.json({data:rows})}catch(e){next(e)}});
  app.get('/api/admin/time-attendance/location-grid',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);const locationId=String(req.query.locationId||'');if(!(await canManage(a,locationId)))return res.status(403).json({error:'You may manage only assigned service locations'});const start=new Date(String(req.query.start));const end=new Date(String(req.query.end));const [location,employees,shifts]=await Promise.all([prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceLocation" WHERE "id"=$1 AND "organizationId"=$2 LIMIT 1`,locationId,a.organizationId),prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName" FROM "TimeAttendanceLocationAssignment" x JOIN "User" u ON u."id"=x."employeeId" LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE x."organizationId"=$1 AND x."locationId"=$2 AND x."active"=TRUE ORDER BY COALESCE(NULLIF(c."displayName",''),u."email")`,a.organizationId,locationId),prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceShift" WHERE "organizationId"=$1 AND "locationId"=$2 AND "startTime">=$3 AND "startTime"<$4 ORDER BY "startTime"`,a.organizationId,locationId,start,end)]);let staff=employees;if(!staff.length&&isGlobal(a.role)){await assignEmployee(a,locationId,a.userId,true);staff=await prisma.$queryRawUnsafe<any[]>(`SELECT u."id",u."role"::text AS role,COALESCE(NULLIF(c."displayName",''),u."email") AS "displayName" FROM "User" u LEFT JOIN "EmployeePortalCredential" c ON c."userId"=u."id" WHERE u."id"=$1 AND u."organizationId"=$2`,a.userId,a.organizationId)}res.json({data:{location:location[0],employees:staff,shifts}})}catch(e){next(e)}});
  app.post('/api/admin/time-attendance/location-grid',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=saveGridSchema.parse(req.body);if(!(await canManage(a,input.locationId)))return res.status(403).json({error:'You may manage only assigned service locations'});const loc=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceLocation" WHERE "id"=$1 AND "organizationId"=$2 LIMIT 1`,input.locationId,a.organizationId))[0];if(!loc)return res.status(404).json({error:'Service location not found'});const ids:string[]=[];for(const cell of input.cells){const start=localDateTime(cell.date,cell.startTime,cell.timezoneOffsetMinutes);let end=localDateTime(cell.date,cell.endTime,cell.timezoneOffsetMinutes);if(end<=start)end=new Date(end.getTime()+86400000);await prisma.$executeRawUnsafe(`DELETE FROM "TimeAttendanceShift" WHERE "organizationId"=$1 AND "locationId"=$2 AND "employeeId"=$3 AND "startTime">=$4 AND "startTime"<$5`,a.organizationId,input.locationId,cell.employeeId,localDateTime(cell.date,'00:00',cell.timezoneOffsetMinutes),localDateTime(cell.date,'00:00',cell.timezoneOffsetMinutes-1440));const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "TimeAttendanceShift" ("id","organizationId","employeeId","locationId","startTime","endTime","code","department","location","payCode","status","latitude","longitude","geofenceRadiusMeters","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,'',$8,$9,$10,$11,$12,$13,$14)`,id,a.organizationId,cell.employeeId,input.locationId,start,end,cell.code,loc.name,cell.payCode,input.publish?'PUBLISHED':'DRAFT',loc.latitude,loc.longitude,loc.geofenceRadiusMeters,a.userId);ids.push(id)}res.status(201).json({data:{saved:ids.length,ids,published:input.publish}})}catch(e){next(e)}});
  app.delete('/api/admin/time-attendance/shifts/:id',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT "id","locationId" FROM "TimeAttendanceShift" WHERE "id"=$1 AND "organizationId"=$2 LIMIT 1`,req.params.id,a.organizationId);if(!rows[0])return res.status(404).json({error:'Shift not found'});if(!(await canManage(a,String(rows[0].locationId||''))))return res.status(403).json({error:'You may manage only assigned service locations'});await prisma.$executeRawUnsafe(`DELETE FROM "TimeAttendanceShift" WHERE "id"=$1 AND "organizationId"=$2`,req.params.id,a.organizationId);res.status(204).end()}catch(e){next(e)}});
  app.post('/api/admin/time-attendance/copy-schedule',managers,async(req,res,next)=>{try{await ready();const a=authOf(res);const input=copySchema.parse(req.body);if(!(await canManage(a,input.locationId)))return res.status(403).json({error:'You may manage only assigned service locations'});const source=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "TimeAttendanceShift" WHERE "organizationId"=$1 AND "locationId"=$2 AND "startTime">=$3 AND "startTime"<$4 ORDER BY "startTime"`,a.organizationId,input.locationId,input.sourceStart,input.sourceEnd);const delta=input.targetStart.getTime()-input.sourceStart.getTime();let copied=0;for(let w=0;w<input.weeks;w++){for(const s of source){const start=new Date(new Date(s.startTime).getTime()+delta+w*7*86400000);const end=new Date(new Date(s.endTime).getTime()+delta+w*7*86400000);await prisma.$executeRawUnsafe(`DELETE FROM "TimeAttendanceShift" WHERE "organizationId"=$1 AND "locationId"=$2 AND "employeeId"=$3 AND DATE("startTime")=DATE($4)`,a.organizationId,input.locationId,s.employeeId,start);await prisma.$executeRawUnsafe(`INSERT INTO "TimeAttendanceShift" ("id","organizationId","employeeId","locationId","startTime","endTime","code","department","location","notes","clientId","payCode","status","latitude","longitude","geofenceRadiusMeters","createdById") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)`,randomUUID(),a.organizationId,s.employeeId,input.locationId,start,end,s.code,s.department,s.location,s.notes,s.clientId,s.payCode,input.publish?'PUBLISHED':'DRAFT',s.latitude,s.longitude,s.geofenceRadiusMeters,a.userId);copied++}}res.status(201).json({data:{copied}})}catch(e){next(e)}});
};
