import { createHash, randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string,details?:unknown)=>Object.assign(new Error(message),{status,details});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before using Workforce');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureAdmin=(a:AuthContext)=>{entity(a);if(!adminRoles.has(a.role)&&!owner(a))throw httpError(403,'Workforce administration access is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const safeFileName=(v:string)=>v.replace(/[\r\n"]/g,'_').replace(/[\\/]/g,'_').slice(0,300)||'employee-document';
const MAX_FILE_BYTES=25*1024*1024;
const punchSchema=z.object({punchType:z.enum(['CLOCK_IN','BREAK_START','BREAK_END','CLOCK_OUT']),locationType:z.string().trim().max(120).optional().nullable(),clientId:z.string().trim().max(120).optional().nullable(),note:z.string().trim().max(2000).optional().nullable(),latitude:z.number().min(-90).max(90).optional().nullable(),longitude:z.number().min(-180).max(180).optional().nullable()});
const lineSchema=z.object({workDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),payCode:z.enum(['REGULAR','OVERTIME','TRAINING','ORIENTATION','PTO','HOLIDAY','SICK','MILEAGE_ONLY','OTHER']).default('REGULAR'),hours:z.number().min(0).max(24).default(0),mileage:z.number().min(0).max(10000).default(0),clientId:z.string().trim().max(120).optional().nullable(),description:z.string().trim().max(2000).optional().nullable()});
const timesheetSchema=z.object({weekEnding:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),notes:z.string().trim().max(5000).optional().nullable(),lines:z.array(lineSchema).min(1).max(31),action:z.enum(['SAVE_DRAFT','SUBMIT']).default('SAVE_DRAFT')});
const documentSchema=z.object({documentType:z.enum(['GOVERNMENT_ID','LICENSE','CERTIFICATION','BACKGROUND_CLEARANCE','VACCINATION_MEDICAL','HANDBOOK_ACKNOWLEDGMENT','DRIVER_DOCUMENT','INSURANCE','DIRECT_DEPOSIT_SUPPORT','OTHER']),title:z.string().trim().max(300).optional().nullable(),originalFileName:z.string().trim().min(1).max(300),mimeType:z.string().trim().min(1).max(200),contentBase64:z.string().min(1).max(36000000),effectiveDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),expirationDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),notes:z.string().trim().max(3000).optional().nullable()});
async function currentPunchState(prisma:PrismaClient,a:AuthContext,userId=a.userId){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimePunch" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 ORDER BY "occurredAt" DESC,"createdAt" DESC LIMIT 1`,a.organizationId,entity(a),userId);const latest=rows[0]||null,type=String(latest?.punchType||'');const state=!latest||type==='CLOCK_OUT'?'OFF':type==='BREAK_START'?'BREAK':'WORKING';const next=state==='OFF'?['CLOCK_IN']:state==='WORKING'?['BREAK_START','CLOCK_OUT']:['BREAK_END','CLOCK_OUT'];return{state,latest,nextAllowed:next};}
function requireTransition(state:string,type:string){const allowed=state==='OFF'?['CLOCK_IN']:state==='WORKING'?['BREAK_START','CLOCK_OUT']:['BREAK_END','CLOCK_OUT'];if(!allowed.includes(type))throw httpError(409,`${type.replaceAll('_',' ')} is not valid while current time state is ${state}`);}
async function timesheetById(prisma:PrismaClient,a:AuthContext,id:string,userId?:string){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimesheet" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 AND ($4::text IS NULL OR "userId"=$4) LIMIT 1`,a.organizationId,entity(a),id,userId??null);if(!rows[0])throw httpError(404,'Timesheet was not found');return rows[0];}

export const registerWorkforceRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
  app.get('/api/workforce/context',async(_req,res,next)=>{try{const a=authOf(res);const rows=await prisma.$queryRawUnsafe<Array<{id:string;code:string;displayName:string}>>(`SELECT "id","code","displayName" FROM "LegalEntity" WHERE "organizationId"=$1 AND "id"=$2 LIMIT 1`,a.organizationId,entity(a));if(!rows[0])throw httpError(404,'Selected company was not found');res.json({data:{company:rows[0],userId:a.userId,role:a.role}});}catch(e){next(e);}});
  app.get('/api/workforce/time/state',async(_req,res,next)=>{try{const a=authOf(res);entity(a);res.json({data:await currentPunchState(prisma,a)});}catch(e){next(e);}});
  app.post('/api/workforce/time/punch',async(req,res,next)=>{try{const a=authOf(res);entity(a);const i=punchSchema.parse(req.body),current=await currentPunchState(prisma,a);requireTransition(current.state,i.punchType);if(i.clientId){const patient=await prisma.$queryRawUnsafe<Array<{id:string}>>(`SELECT p."id" FROM "SpirePatient" p JOIN "ClientEnrollment" e ON e."organizationId"=p."organizationId" AND e."clientId"=p."id" AND e."legalEntityId"=$2 AND e."status" IN ('PENDING','ACTIVE','PAUSED') WHERE p."organizationId"=$1 AND p."id"=$3 LIMIT 1`,a.organizationId,entity(a),i.clientId);if(!patient[0])throw httpError(404,'Selected client is not enrolled with the selected company');}const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeTimePunch"("id","organizationId","legalEntityId","userId","punchType","locationType","clientId","note","latitude","longitude","source") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'WEB')`,id,a.organizationId,entity(a),a.userId,i.punchType,i.locationType??null,i.clientId??null,i.note??null,i.latitude??null,i.longitude??null);await audit?.(a,'WORKFORCE_TIME_PUNCH','EmployeeTimePunch',id,{punchType:i.punchType,clientId:i.clientId??null});res.status(201).json({data:{id,...await currentPunchState(prisma,a)}});}catch(e){next(e);}});
  app.get('/api/workforce/time/history',async(req,res,next)=>{try{const a=authOf(res);entity(a);const from=clean(req.query.from,40)||new Date(Date.now()-14*86400000).toISOString(),to=clean(req.query.to,40)||new Date(Date.now()+86400000).toISOString();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimePunch" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "occurredAt">=$4::timestamptz AND "occurredAt"<$5::timestamptz ORDER BY "occurredAt" DESC`,a.organizationId,entity(a),a.userId,from,to);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/workforce/timesheets',async(_req,res,next)=>{try{const a=authOf(res);entity(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT sheet.*,COALESCE((SELECT jsonb_agg(to_jsonb(line) ORDER BY line."workDate",line."createdAt") FROM "EmployeeTimesheetLine" line WHERE line."timesheetId"=sheet."id"),'[]'::jsonb) AS lines FROM "EmployeeTimesheet" sheet WHERE sheet."organizationId"=$1 AND sheet."legalEntityId"=$2 AND sheet."userId"=$3 ORDER BY sheet."weekEnding" DESC LIMIT 52`,a.organizationId,entity(a),a.userId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/workforce/timesheets',async(req,res,next)=>{try{const a=authOf(res);entity(a);const i=timesheetSchema.parse(req.body),totalHours=Number(i.lines.reduce((s,l)=>s+l.hours,0).toFixed(2)),totalMileage=Number(i.lines.reduce((s,l)=>s+l.mileage,0).toFixed(2));if(totalHours>168)throw httpError(400,'Weekly hours cannot exceed 168');const result=await prisma.$transaction(async(tx)=>{const existing=await tx.$queryRawUnsafe<Array<{id:string;status:string}>>(`SELECT "id","status" FROM "EmployeeTimesheet" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "weekEnding"=$4::date LIMIT 1`,a.organizationId,entity(a),a.userId,i.weekEnding);if(existing[0]&&!['DRAFT','REJECTED'].includes(existing[0].status))throw httpError(409,'This timesheet is locked because it has already been submitted or approved');const id=existing[0]?.id||randomUUID(),status=i.action==='SUBMIT'?'SUBMITTED':'DRAFT';if(existing[0])await tx.$executeRawUnsafe(`UPDATE "EmployeeTimesheet" SET "status"=$1,"totalHours"=$2,"totalMileage"=$3,"notes"=$4,"submittedAt"=CASE WHEN $1='SUBMITTED' THEN NOW() ELSE NULL END,"reviewedAt"=NULL,"reviewedById"=NULL,"reviewNotes"=NULL,"updatedAt"=NOW() WHERE "id"=$5`,status,totalHours,totalMileage,i.notes??null,id);else await tx.$executeRawUnsafe(`INSERT INTO "EmployeeTimesheet"("id","organizationId","legalEntityId","userId","weekEnding","status","totalHours","totalMileage","notes","submittedAt") VALUES($1,$2,$3,$4,$5::date,$6,$7,$8,$9,CASE WHEN $6='SUBMITTED' THEN NOW() ELSE NULL END)`,id,a.organizationId,entity(a),a.userId,i.weekEnding,status,totalHours,totalMileage,i.notes??null);await tx.$executeRawUnsafe(`DELETE FROM "EmployeeTimesheetLine" WHERE "timesheetId"=$1`,id);for(const line of i.lines)await tx.$executeRawUnsafe(`INSERT INTO "EmployeeTimesheetLine"("id","organizationId","legalEntityId","timesheetId","workDate","payCode","hours","mileage","clientId","description") VALUES($1,$2,$3,$4,$5::date,$6,$7,$8,$9,$10)`,randomUUID(),a.organizationId,entity(a),id,line.workDate,line.payCode,line.hours,line.mileage,line.clientId??null,line.description??null);return{id,status,totalHours,totalMileage};});await audit?.(a,i.action==='SUBMIT'?'SUBMIT_TIMESHEET':'SAVE_TIMESHEET_DRAFT','EmployeeTimesheet',result.id,{weekEnding:i.weekEnding,totalHours,totalMileage});res.json({data:result});}catch(e){next(e);}});
  app.get('/api/workforce/documents',async(_req,res,next)=>{try{const a=authOf(res);entity(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","documentType","title","originalFileName","mimeType","sizeBytes","sha256","status","effectiveDate","expirationDate","notes","submittedAt","reviewedAt","reviewNotes" FROM "EmployeeDocumentSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 ORDER BY "submittedAt" DESC`,a.organizationId,entity(a),a.userId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/workforce/documents',async(req,res,next)=>{try{const a=authOf(res);entity(a);const i=documentSchema.parse(req.body);let content:Buffer;try{content=Buffer.from(i.contentBase64.replace(/^data:[^;]+;base64,/,''),'base64');}catch{throw httpError(400,'Document content is not valid base64');}if(!content.length)throw httpError(400,'Document is empty');if(content.length>MAX_FILE_BYTES)throw httpError(413,'Employee documents may not exceed 25 MB');const id=randomUUID(),sha256=createHash('sha256').update(content).digest('hex');await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentSubmission"("id","organizationId","legalEntityId","userId","documentType","title","originalFileName","mimeType","sizeBytes","sha256","content","effectiveDate","expirationDate","notes") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::date,$13::date,$14)`,id,a.organizationId,entity(a),a.userId,i.documentType,i.title??null,safeFileName(i.originalFileName),i.mimeType,content.length,sha256,content,i.effectiveDate??null,i.expirationDate??null,i.notes??null);await audit?.(a,'SUBMIT_EMPLOYEE_DOCUMENT','EmployeeDocumentSubmission',id,{documentType:i.documentType,sha256});res.status(201).json({data:{id,status:'SUBMITTED',sha256,sizeBytes:content.length}});}catch(e){next(e);}});
  app.get('/api/workforce/documents/:documentId/download',async(req,res,next)=>{try{const a=authOf(res);entity(a);const rows=await prisma.$queryRawUnsafe<Array<{originalFileName:string;mimeType:string;sizeBytes:number;content:Buffer}>>(`SELECT "originalFileName","mimeType","sizeBytes","content" FROM "EmployeeDocumentSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity(a),a.userId,req.params.documentId);const x=rows[0];if(!x)throw httpError(404,'Employee document was not found');res.setHeader('Content-Type',x.mimeType||'application/octet-stream');res.setHeader('Content-Length',String(x.sizeBytes));res.setHeader('Content-Disposition',`attachment; filename="${safeFileName(x.originalFileName)}"`);res.setHeader('Cache-Control','private, no-store');res.send(x.content);}catch(e){next(e);}});
  app.get('/api/admin/workforce/timesheets',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const status=clean(req.query.status,40),userId=clean(req.query.userId,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT sheet.*,COALESCE((SELECT jsonb_agg(to_jsonb(line) ORDER BY line."workDate") FROM "EmployeeTimesheetLine" line WHERE line."timesheetId"=sheet."id"),'[]'::jsonb) AS lines FROM "EmployeeTimesheet" sheet WHERE sheet."organizationId"=$1 AND sheet."legalEntityId"=$2 AND ($3='' OR sheet."status"=$3) AND ($4='' OR sheet."userId"=$4) ORDER BY sheet."weekEnding" DESC,sheet."updatedAt" DESC LIMIT 1000`,a.organizationId,entity(a),status,userId);res.json({data:rows});}catch(e){next(e);}});
  app.post('/api/admin/workforce/timesheets/:timesheetId/status',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const action=z.enum(['APPROVE','REJECT','MARK_PAID','VOID']).parse(req.body?.action),notes=clean(req.body?.notes,5000)||null;const sheet=await timesheetById(prisma,a,req.params.timesheetId);const current=String(sheet.status);let status=current;if(action==='APPROVE'){if(current!=='SUBMITTED')throw httpError(409,'Only submitted timesheets can be approved');status='APPROVED';}if(action==='REJECT'){if(!['SUBMITTED','APPROVED'].includes(current))throw httpError(409,'Only submitted or approved timesheets can be rejected');if(!notes)throw httpError(400,'Rejection notes are required');status='REJECTED';}if(action==='MARK_PAID'){if(current!=='APPROVED')throw httpError(409,'Only approved timesheets can be marked paid');status='PAID';}if(action==='VOID'){if(current==='PAID')throw httpError(409,'Paid timesheets require payroll correction rather than voiding');if(!notes)throw httpError(400,'Void reason is required');status='VOID';}await prisma.$executeRawUnsafe(`UPDATE "EmployeeTimesheet" SET "status"=$1,"reviewedAt"=CASE WHEN $1 IN ('APPROVED','REJECTED') THEN NOW() ELSE "reviewedAt" END,"reviewedById"=CASE WHEN $1 IN ('APPROVED','REJECTED') THEN $2 ELSE "reviewedById" END,"reviewNotes"=CASE WHEN $1 IN ('REJECTED','VOID') THEN $3 ELSE "reviewNotes" END,"approvedAt"=CASE WHEN $1='APPROVED' THEN NOW() ELSE "approvedAt" END,"approvedById"=CASE WHEN $1='APPROVED' THEN $2 ELSE "approvedById" END,"paidAt"=CASE WHEN $1='PAID' THEN NOW() ELSE "paidAt" END,"paidById"=CASE WHEN $1='PAID' THEN $2 ELSE "paidById" END,"updatedAt"=NOW() WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "id"=$6`,status,a.userId,notes,a.organizationId,entity(a),req.params.timesheetId);await audit?.(a,`TIMESHEET_${action}`,'EmployeeTimesheet',req.params.timesheetId,{fromStatus:current,toStatus:status,notes});res.json({data:{id:req.params.timesheetId,status}});}catch(e){next(e);}});
  app.get('/api/admin/workforce/documents',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const status=clean(req.query.status,40),userId=clean(req.query.userId,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT "id","userId","documentType","title","originalFileName","mimeType","sizeBytes","sha256","status","effectiveDate","expirationDate","notes","submittedAt","reviewedAt","reviewedById","reviewNotes" FROM "EmployeeDocumentSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND ($3='' OR "status"=$3) AND ($4='' OR "userId"=$4) ORDER BY CASE "status" WHEN 'SUBMITTED' THEN 0 WHEN 'CHANGES_REQUESTED' THEN 1 ELSE 2 END,"submittedAt" DESC LIMIT 1000`,a.organizationId,entity(a),status,userId);res.json({data:rows});}catch(e){next(e);}});
  app.get('/api/admin/workforce/documents/:documentId/download',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const rows=await prisma.$queryRawUnsafe<Array<{originalFileName:string;mimeType:string;sizeBytes:number;content:Buffer}>>(`SELECT "originalFileName","mimeType","sizeBytes","content" FROM "EmployeeDocumentSubmission" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.documentId);const x=rows[0];if(!x)throw httpError(404,'Employee document was not found');res.setHeader('Content-Type',x.mimeType||'application/octet-stream');res.setHeader('Content-Length',String(x.sizeBytes));res.setHeader('Content-Disposition',`attachment; filename="${safeFileName(x.originalFileName)}"`);res.setHeader('Cache-Control','private, no-store');res.send(x.content);}catch(e){next(e);}});
  app.post('/api/admin/workforce/documents/:documentId/status',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const action=z.enum(['APPROVE','REQUEST_CHANGES','REJECT','ARCHIVE']).parse(req.body?.action),notes=clean(req.body?.notes,5000)||null;if(['REQUEST_CHANGES','REJECT'].includes(action)&&!notes)throw httpError(400,'Review notes are required');const status=action==='REQUEST_CHANGES'?'CHANGES_REQUESTED':action==='ARCHIVE'?'ARCHIVED':action;const count=await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentSubmission" SET "status"=$1,"reviewedAt"=NOW(),"reviewedById"=$2,"reviewNotes"=$3,"updatedAt"=NOW() WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "id"=$6`,status,a.userId,notes,a.organizationId,entity(a),req.params.documentId);if(!count)throw httpError(404,'Employee document was not found');await audit?.(a,`EMPLOYEE_DOCUMENT_${action}`,'EmployeeDocumentSubmission',req.params.documentId,{status,notes});res.json({data:{id:req.params.documentId,status}});}catch(e){next(e);}});
};
