import { randomUUID } from 'node:crypto';
import type express from 'express';
import type { PrismaClient } from '@prisma/client';
import { UserRole } from '@prisma/client';
import { z } from 'zod';

type AuthContext={userId:string;organizationId:string;role:UserRole;email?:string;ipAddress?:string;userAgent?:string;legalEntityId?:string;enterpriseOwner?:boolean};
type Deps={authOf:(response:express.Response)=>AuthContext;audit?:(auth:Partial<AuthContext>,action:string,resourceType:string,resourceId?:string,metadata?:object)=>Promise<void>};
const adminRoles=new Set<UserRole>([UserRole.ADMINISTRATOR,UserRole.PROGRAM_MANAGER,UserRole.HR_MANAGER,UserRole.BILLING_SPECIALIST,UserRole.CEO,UserRole.DOO]);
const httpError=(status:number,message:string)=>Object.assign(new Error(message),{status});
const entity=(a:AuthContext)=>{if(!a.legalEntityId)throw httpError(409,'Select a Sulandra company before using Workforce');return a.legalEntityId;};
const owner=(a:AuthContext)=>a.enterpriseOwner===true||String(a.email||'').trim().toLowerCase()==='admin@sulandrahealth.com';
const ensureAdmin=(a:AuthContext)=>{entity(a);if(!adminRoles.has(a.role)&&!owner(a))throw httpError(403,'Workforce administration access is required');};
const clean=(v:unknown,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const correctionSchema=z.object({correctionKind:z.enum(['ADD_MISSING_PUNCH','CHANGE_PUNCH','VOID_PUNCH','ANNOTATE_PUNCH']),originalPunchId:z.string().trim().max(120).optional().nullable(),requestedPunchType:z.enum(['CLOCK_IN','BREAK_START','BREAK_END','CLOCK_OUT']).optional().nullable(),requestedOccurredAt:z.string().datetime().optional().nullable(),requestedLocationType:z.string().trim().max(120).optional().nullable(),requestedClientId:z.string().trim().max(120).optional().nullable(),requestedNote:z.string().trim().max(2000).optional().nullable(),reason:z.string().trim().min(5).max(5000)});
const reviewSchema=z.object({action:z.enum(['APPROVE','REJECT','CANCEL']),reviewNotes:z.string().trim().max(5000).optional().nullable()});
const csvCell=(value:unknown)=>{const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;};
async function ownedPunch(prisma:PrismaClient,a:AuthContext,punchId:string,userId=a.userId){const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimePunch" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "id"=$4 LIMIT 1`,a.organizationId,entity(a),userId,punchId);return rows[0]||null;}
async function effectiveTimeline(prisma:PrismaClient,a:AuthContext,userId:string,from:string,to:string){const [punches,corrections]=await Promise.all([prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimePunch" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "occurredAt">=$4::timestamptz AND "occurredAt"<$5::timestamptz ORDER BY "occurredAt"`,a.organizationId,entity(a),userId,from,to),prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeTimeCorrection" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "userId"=$3 AND "status"='APPROVED' AND ("requestedOccurredAt" IS NULL OR ("requestedOccurredAt">=$4::timestamptz AND "requestedOccurredAt"<$5::timestamptz)) ORDER BY "requestedAt"`,a.organizationId,entity(a),userId,from,to)]);const map=new Map(punches.map(p=>[String(p.id),{...p,effectiveSource:'ORIGINAL'}]));const synthetic:Array<Record<string,unknown>>=[];for(const c of corrections){const kind=String(c.correctionKind),originalId=String(c.originalPunchId||'');if(kind==='ADD_MISSING_PUNCH')synthetic.push({id:`correction:${c.id}`,organizationId:a.organizationId,legalEntityId:entity(a),userId,punchType:c.requestedPunchType,occurredAt:c.requestedOccurredAt,locationType:c.requestedLocationType,clientId:c.requestedClientId,note:c.requestedNote||c.reason,source:'ADMIN_CORRECTION',effectiveSource:'CORRECTION',correctionId:c.id});if(kind==='VOID_PUNCH'&&originalId)map.delete(originalId);if(kind==='CHANGE_PUNCH'&&originalId&&map.has(originalId)){const p=map.get(originalId)!;map.set(originalId,{...p,punchType:c.requestedPunchType||p.punchType,occurredAt:c.requestedOccurredAt||p.occurredAt,locationType:c.requestedLocationType??p.locationType,clientId:c.requestedClientId??p.clientId,note:c.requestedNote??p.note,effectiveSource:'CORRECTION',correctionId:c.id,originalOccurredAt:p.occurredAt});}if(kind==='ANNOTATE_PUNCH'&&originalId&&map.has(originalId)){const p=map.get(originalId)!;map.set(originalId,{...p,note:[p.note,c.requestedNote||c.reason].filter(Boolean).join(' | '),effectiveSource:'CORRECTION',correctionId:c.id});}}
return [...map.values(),...synthetic].sort((x,y)=>new Date(String(x.occurredAt)).getTime()-new Date(String(y.occurredAt)).getTime());}

export const registerWorkforceAdvancedRoutes=(app:express.Express,prisma:PrismaClient,deps:Deps)=>{const{authOf,audit}=deps;
 app.get('/api/workforce/time/corrections',async(_req,res,next)=>{try{const a=authOf(res);entity(a);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c.*,p."punchType" AS "originalPunchType",p."occurredAt" AS "originalOccurredAt" FROM "EmployeeTimeCorrection" c LEFT JOIN "EmployeeTimePunch" p ON p."id"=c."originalPunchId" WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND c."userId"=$3 ORDER BY c."requestedAt" DESC LIMIT 200`,a.organizationId,entity(a),a.userId);res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/workforce/time/corrections',async(req,res,next)=>{try{const a=authOf(res);entity(a);const i=correctionSchema.parse(req.body);if(i.correctionKind==='ADD_MISSING_PUNCH'&&(!i.requestedPunchType||!i.requestedOccurredAt))throw httpError(400,'Missing-punch corrections require punch type and requested date/time');if(i.correctionKind!=='ADD_MISSING_PUNCH'&&!i.originalPunchId)throw httpError(400,'Select the original punch to correct');if(i.correctionKind==='CHANGE_PUNCH'&&!i.requestedPunchType&&!i.requestedOccurredAt&&!i.requestedLocationType&&!i.requestedNote)throw httpError(400,'Enter at least one requested change');if(i.originalPunchId&&!(await ownedPunch(prisma,a,i.originalPunchId)))throw httpError(404,'Original punch was not found in your company time history');const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeTimeCorrection"("id","organizationId","legalEntityId","userId","originalPunchId","correctionKind","requestedPunchType","requestedOccurredAt","requestedLocationType","requestedClientId","requestedNote","reason","requestedByUserId") VALUES($1,$2,$3,$4,$5,$6,$7,$8::timestamptz,$9,$10,$11,$12,$13)`,id,a.organizationId,entity(a),a.userId,i.originalPunchId??null,i.correctionKind,i.requestedPunchType??null,i.requestedOccurredAt??null,i.requestedLocationType??null,i.requestedClientId??null,i.requestedNote??null,i.reason,a.userId);await audit?.(a,'REQUEST_TIME_CORRECTION','EmployeeTimeCorrection',id,{kind:i.correctionKind,originalPunchId:i.originalPunchId??null});res.status(201).json({data:{id,status:'PENDING'}});}catch(e){next(e);}});
 app.get('/api/workforce/time/effective-history',async(req,res,next)=>{try{const a=authOf(res);entity(a);const from=clean(req.query.from,40)||new Date(Date.now()-14*86400000).toISOString(),to=clean(req.query.to,40)||new Date(Date.now()+86400000).toISOString();res.json({data:await effectiveTimeline(prisma,a,a.userId,from,to)});}catch(e){next(e);}});
 app.get('/api/admin/workforce/time-corrections',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const status=clean(req.query.status,40),userId=clean(req.query.userId,120);const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT c.*,p."punchType" AS "originalPunchType",p."occurredAt" AS "originalOccurredAt",p."locationType" AS "originalLocationType",p."note" AS "originalNote" FROM "EmployeeTimeCorrection" c LEFT JOIN "EmployeeTimePunch" p ON p."id"=c."originalPunchId" WHERE c."organizationId"=$1 AND c."legalEntityId"=$2 AND ($3='' OR c."status"=$3) AND ($4='' OR c."userId"=$4) ORDER BY CASE c."status" WHEN 'PENDING' THEN 0 ELSE 1 END,c."requestedAt" DESC LIMIT 1000`,a.organizationId,entity(a),status,userId);res.json({data:rows});}catch(e){next(e);}});
 app.post('/api/admin/workforce/time-corrections/:correctionId/status',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const i=reviewSchema.parse(req.body),rows=await prisma.$queryRawUnsafe<Array<{id:string;status:string;userId:string}>>(`SELECT "id","status","userId" FROM "EmployeeTimeCorrection" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "id"=$3 LIMIT 1`,a.organizationId,entity(a),req.params.correctionId),c=rows[0];if(!c)throw httpError(404,'Time correction was not found');if(c.status!=='PENDING')throw httpError(409,'Only pending correction requests can be reviewed');if(i.action==='REJECT'&&!i.reviewNotes)throw httpError(400,'Rejection notes are required');const status=i.action==='APPROVE'?'APPROVED':i.action==='REJECT'?'REJECTED':'CANCELLED';await prisma.$executeRawUnsafe(`UPDATE "EmployeeTimeCorrection" SET "status"=$1,"reviewedAt"=NOW(),"reviewedById"=$2,"reviewNotes"=$3,"appliedAt"=CASE WHEN $1='APPROVED' THEN NOW() ELSE NULL END WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "id"=$6`,status,a.userId,i.reviewNotes??null,a.organizationId,entity(a),c.id);await audit?.(a,`TIME_CORRECTION_${i.action}`,'EmployeeTimeCorrection',c.id,{userId:c.userId,status,reviewNotes:i.reviewNotes??null});res.json({data:{id:c.id,status}});}catch(e){next(e);}});
 app.get('/api/admin/workforce/time-report',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const userId=clean(req.query.userId,120);if(!userId)throw httpError(400,'userId is required');const from=clean(req.query.from,40)||new Date(Date.now()-14*86400000).toISOString(),to=clean(req.query.to,40)||new Date(Date.now()+86400000).toISOString();const effective=await effectiveTimeline(prisma,a,userId,from,to);res.json({data:{userId,from,to,effectivePunches:effective}});}catch(e){next(e);}});
 app.get('/api/admin/workforce/payroll-export.csv',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const weekEnding=clean(req.query.weekEnding,20),from=clean(req.query.from,20),to=clean(req.query.to,20),status=clean(req.query.status,40)||'APPROVED';const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT sheet."id" AS "timesheetId",sheet."userId",sheet."weekEnding",sheet."status",sheet."totalHours",sheet."totalMileage",line."workDate",line."payCode",line."hours",line."mileage",line."clientId",line."description" FROM "EmployeeTimesheet" sheet JOIN "EmployeeTimesheetLine" line ON line."timesheetId"=sheet."id" WHERE sheet."organizationId"=$1 AND sheet."legalEntityId"=$2 AND ($3='' OR sheet."weekEnding"=$3::date) AND ($4='' OR sheet."weekEnding">=$4::date) AND ($5='' OR sheet."weekEnding"<=$5::date) AND ($6='' OR sheet."status"=$6) ORDER BY sheet."userId",sheet."weekEnding",line."workDate",line."createdAt"`,a.organizationId,entity(a),weekEnding,from,to,status);const headers=['timesheetId','userId','weekEnding','status','totalHours','totalMileage','workDate','payCode','hours','mileage','clientId','description'];const csv=[headers.join(','),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(','))].join('\n');await audit?.(a,'EXPORT_PAYROLL_TIMESHEETS','EmployeeTimesheet','CSV',{weekEnding:weekEnding||null,from:from||null,to:to||null,status,rowCount:rows.length});res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="sulandra-payroll-${weekEnding||from||new Date().toISOString().slice(0,10)}.csv"`);res.setHeader('Cache-Control','private, no-store');res.send(csv);}catch(e){next(e);}});
 app.get('/api/admin/workforce/compliance',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const days=Math.min(365,Math.max(1,Number(req.query.days||60)));await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentSubmission" SET "status"='EXPIRED',"updatedAt"=NOW() WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "status"='APPROVED' AND "expirationDate" IS NOT NULL AND "expirationDate"<CURRENT_DATE`,a.organizationId,entity(a));await prisma.$executeRawUnsafe(`INSERT INTO "EmployeeDocumentComplianceReview"("id","organizationId","legalEntityId","documentId","userId","reviewType","dueAt","createdByUserId") SELECT gen_random_uuid()::text,d."organizationId",d."legalEntityId",d."id",d."userId",CASE WHEN d."expirationDate"<CURRENT_DATE THEN 'EXPIRED' ELSE 'EXPIRING' END,d."expirationDate"::timestamptz,$3 FROM "EmployeeDocumentSubmission" d WHERE d."organizationId"=$1 AND d."legalEntityId"=$2 AND d."expirationDate" IS NOT NULL AND d."expirationDate"<=CURRENT_DATE+$4::int AND d."status" IN ('APPROVED','EXPIRED') AND NOT EXISTS(SELECT 1 FROM "EmployeeDocumentComplianceReview" r WHERE r."documentId"=d."id" AND r."status"='OPEN')`,a.organizationId,entity(a),a.userId,days);const documents=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT d."id",d."userId",d."documentType",d."title",d."originalFileName",d."status",d."effectiveDate",d."expirationDate",(d."expirationDate"-CURRENT_DATE)::int AS "daysToExpiration",d."reviewNotes",d."submittedAt" FROM "EmployeeDocumentSubmission" d WHERE d."organizationId"=$1 AND d."legalEntityId"=$2 AND d."expirationDate" IS NOT NULL AND d."expirationDate"<=CURRENT_DATE+$3::int ORDER BY d."expirationDate",d."userId"`,a.organizationId,entity(a),days);const reviews=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>(`SELECT * FROM "EmployeeDocumentComplianceReview" WHERE "organizationId"=$1 AND "legalEntityId"=$2 AND "status"='OPEN' ORDER BY "dueAt" NULLS LAST,"createdAt"`,a.organizationId,entity(a));res.json({data:{days,documents,reviews,stats:{expired:documents.filter(d=>Number(d.daysToExpiration)<0).length,expiring:documents.filter(d=>Number(d.daysToExpiration)>=0).length,openReviews:reviews.length}}});}catch(e){next(e);}});
 app.post('/api/admin/workforce/compliance/:reviewId/resolve',async(req,res,next)=>{try{const a=authOf(res);ensureAdmin(a);const notes=clean(req.body?.notes,5000)||null,action=z.enum(['RESOLVE','DISMISS']).parse(req.body?.action||'RESOLVE'),status=action==='RESOLVE'?'RESOLVED':'DISMISSED';const count=await prisma.$executeRawUnsafe(`UPDATE "EmployeeDocumentComplianceReview" SET "status"=$1,"notes"=COALESCE($2,"notes"),"resolvedAt"=NOW(),"resolvedByUserId"=$3 WHERE "organizationId"=$4 AND "legalEntityId"=$5 AND "id"=$6 AND "status"='OPEN'`,status,notes,a.userId,a.organizationId,entity(a),req.params.reviewId);if(!count)throw httpError(404,'Open compliance review was not found');await audit?.(a,'RESOLVE_DOCUMENT_COMPLIANCE','EmployeeDocumentComplianceReview',req.params.reviewId,{status,notes});res.json({data:{id:req.params.reviewId,status}});}catch(e){next(e);}});
};
