CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "HomeHealthStaffProfile" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "userId" text NOT NULL,
  "discipline" text NOT NULL,
  "status" text NOT NULL DEFAULT 'ACTIVE',
  "licenseNumber" text,
  "licenseState" text,
  "licenseExpiresAt" date,
  "npi" text,
  "providerNumber" text,
  "canOpenCase" boolean NOT NULL DEFAULT false,
  "canSignPlanOfCare" boolean NOT NULL DEFAULT false,
  "canSuperviseAides" boolean NOT NULL DEFAULT false,
  "notes" text,
  "createdById" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthStaffProfile_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT,
  CONSTRAINT "HomeHealthStaffProfile_user_key" UNIQUE ("organizationId","legalEntityId","userId"),
  CONSTRAINT "HomeHealthStaffProfile_discipline_check" CHECK ("discipline" IN ('RN','LPN','PT','OT','ST','RT','HHA','MSW','OTHER')),
  CONSTRAINT "HomeHealthStaffProfile_status_check" CHECK ("status" IN ('ACTIVE','SUSPENDED','INACTIVE'))
);
CREATE INDEX IF NOT EXISTS "HomeHealthStaffProfile_entity_idx" ON "HomeHealthStaffProfile"("organizationId","legalEntityId","discipline","status");

CREATE TABLE IF NOT EXISTS "HomeHealthEpisode" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "patientId" text NOT NULL REFERENCES "SpirePatient"("id") ON DELETE RESTRICT,
  "intakeCaseId" text REFERENCES "ClientIntakeCase"("id") ON DELETE SET NULL,
  "episodeNumber" text NOT NULL,
  "status" text NOT NULL DEFAULT 'PRE_ADMISSION',
  "referralDate" date,
  "requestedStartOfCareDate" date,
  "startOfCareDate" date,
  "certificationPeriodStart" date,
  "certificationPeriodEnd" date,
  "primaryDiagnosis" text,
  "secondaryDiagnoses" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "referringProviderName" text,
  "referringProviderNpi" text,
  "certifyingProviderName" text,
  "certifyingProviderNpi" text,
  "providerPhone" text,
  "providerFax" text,
  "faceToFaceDate" date,
  "faceToFaceStatus" text NOT NULL DEFAULT 'PENDING',
  "homeboundStatus" text NOT NULL DEFAULT 'PENDING',
  "homeboundRationale" text,
  "skilledNeed" text,
  "payerName" text,
  "memberId" text,
  "authorizationNumber" text,
  "caseManagerUserId" text,
  "clinicalManagerUserId" text,
  "emergencyPreparednessLevel" text,
  "hospitalizationRisk" text,
  "admissionNotes" text,
  "holdReason" text,
  "dischargeDate" date,
  "dischargeReason" text,
  "createdById" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthEpisode_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT,
  CONSTRAINT "HomeHealthEpisode_number_key" UNIQUE ("episodeNumber"),
  CONSTRAINT "HomeHealthEpisode_status_check" CHECK ("status" IN ('PRE_ADMISSION','SOC_READY','ACTIVE','ON_HOLD','DISCHARGED','CANCELLED')),
  CONSTRAINT "HomeHealthEpisode_f2f_check" CHECK ("faceToFaceStatus" IN ('PENDING','COMPLETE','NOT_REQUIRED','EXCEPTION_REVIEW')),
  CONSTRAINT "HomeHealthEpisode_homebound_check" CHECK ("homeboundStatus" IN ('PENDING','MEETS','DOES_NOT_MEET','NOT_APPLICABLE'))
);
CREATE INDEX IF NOT EXISTS "HomeHealthEpisode_entity_status_idx" ON "HomeHealthEpisode"("organizationId","legalEntityId","status","updatedAt" DESC);
CREATE INDEX IF NOT EXISTS "HomeHealthEpisode_patient_idx" ON "HomeHealthEpisode"("organizationId","patientId","createdAt" DESC);

CREATE TABLE IF NOT EXISTS "HomeHealthPlanOfCare" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "episodeId" text NOT NULL REFERENCES "HomeHealthEpisode"("id") ON DELETE CASCADE,
  "version" integer NOT NULL DEFAULT 1,
  "status" text NOT NULL DEFAULT 'DRAFT',
  "effectiveDate" date,
  "endDate" date,
  "ordersSummary" text,
  "goals" text,
  "functionalLimitations" text,
  "activitiesPermitted" text,
  "mentalStatus" text,
  "safetyMeasures" text,
  "nutritionalRequirements" text,
  "allergies" text,
  "medicationManagement" text,
  "dmeSupplies" text,
  "prognosis" text,
  "rehabilitationPotential" text,
  "dischargePlans" text,
  "caregiverSupport" text,
  "frequencyDurationSummary" text,
  "physicianName" text,
  "physicianNpi" text,
  "physicianOrderDate" date,
  "physicianSignedAt" timestamptz,
  "physicianSignatureMethod" text,
  "clinicalReviewerUserId" text,
  "reviewedAt" timestamptz,
  "activatedAt" timestamptz,
  "activatedById" text,
  "supersededAt" timestamptz,
  "supersededById" text,
  "supersedeReason" text,
  "createdById" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthPlanOfCare_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT,
  CONSTRAINT "HomeHealthPlanOfCare_episode_version_key" UNIQUE ("episodeId","version"),
  CONSTRAINT "HomeHealthPlanOfCare_status_check" CHECK ("status" IN ('DRAFT','REVIEW','ACTIVE','CHANGES_REQUESTED','SUPERSEDED'))
);
CREATE INDEX IF NOT EXISTS "HomeHealthPlanOfCare_episode_idx" ON "HomeHealthPlanOfCare"("organizationId","legalEntityId","episodeId","version" DESC);

CREATE TABLE IF NOT EXISTS "HomeHealthDisciplineOrder" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "episodeId" text NOT NULL REFERENCES "HomeHealthEpisode"("id") ON DELETE CASCADE,
  "planOfCareId" text REFERENCES "HomeHealthPlanOfCare"("id") ON DELETE SET NULL,
  "discipline" text NOT NULL,
  "serviceType" text NOT NULL,
  "frequency" text,
  "duration" text,
  "visitLimit" integer,
  "startDate" date,
  "endDate" date,
  "goals" text,
  "interventions" text,
  "specialInstructions" text,
  "status" text NOT NULL DEFAULT 'ORDERED',
  "orderedByProvider" text,
  "orderedAt" timestamptz NOT NULL DEFAULT now(),
  "enteredById" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthDisciplineOrder_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT,
  CONSTRAINT "HomeHealthDisciplineOrder_discipline_check" CHECK ("discipline" IN ('SN','PT','OT','ST','RT','HHA','MSW','OTHER')),
  CONSTRAINT "HomeHealthDisciplineOrder_status_check" CHECK ("status" IN ('ORDERED','ACTIVE','COMPLETED','DISCONTINUED','CANCELLED'))
);
CREATE INDEX IF NOT EXISTS "HomeHealthDisciplineOrder_episode_idx" ON "HomeHealthDisciplineOrder"("organizationId","legalEntityId","episodeId","discipline","status");

CREATE TABLE IF NOT EXISTS "HomeHealthVisit" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "episodeId" text NOT NULL REFERENCES "HomeHealthEpisode"("id") ON DELETE CASCADE,
  "patientId" text NOT NULL REFERENCES "SpirePatient"("id") ON DELETE RESTRICT,
  "disciplineOrderId" text REFERENCES "HomeHealthDisciplineOrder"("id") ON DELETE SET NULL,
  "discipline" text NOT NULL,
  "visitType" text NOT NULL,
  "status" text NOT NULL DEFAULT 'SCHEDULED',
  "assignedUserId" text,
  "scheduledStart" timestamptz NOT NULL,
  "scheduledEnd" timestamptz,
  "actualStart" timestamptz,
  "actualEnd" timestamptz,
  "evvRequired" boolean NOT NULL DEFAULT false,
  "evvVisitId" text,
  "encounterId" text,
  "locationAddress" text,
  "patientPresent" boolean,
  "caregiverPresent" text,
  "subjective" text,
  "assessment" text,
  "interventions" text,
  "response" text,
  "education" text,
  "careCoordination" text,
  "planNextVisit" text,
  "skilledNeedStatement" text,
  "homeboundStatement" text,
  "physicianNotification" text,
  "missedVisitReason" text,
  "signatureAttestation" text,
  "signedAt" timestamptz,
  "signedById" text,
  "createdById" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthVisit_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT,
  CONSTRAINT "HomeHealthVisit_discipline_check" CHECK ("discipline" IN ('SN','PT','OT','ST','RT','HHA','MSW','OTHER')),
  CONSTRAINT "HomeHealthVisit_status_check" CHECK ("status" IN ('SCHEDULED','CONFIRMED','IN_PROGRESS','COMPLETED','MISSED','CANCELLED'))
);
CREATE INDEX IF NOT EXISTS "HomeHealthVisit_entity_schedule_idx" ON "HomeHealthVisit"("organizationId","legalEntityId","scheduledStart","status");
CREATE INDEX IF NOT EXISTS "HomeHealthVisit_user_idx" ON "HomeHealthVisit"("organizationId","legalEntityId","assignedUserId","scheduledStart") WHERE "assignedUserId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "HomeHealthVisit_patient_idx" ON "HomeHealthVisit"("organizationId","patientId","scheduledStart" DESC);

CREATE TABLE IF NOT EXISTS "HomeHealthEpisodeEvent" (
  "id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "organizationId" text NOT NULL,
  "legalEntityId" text NOT NULL,
  "episodeId" text NOT NULL REFERENCES "HomeHealthEpisode"("id") ON DELETE CASCADE,
  "actorUserId" text,
  "eventType" text NOT NULL,
  "resourceType" text,
  "resourceId" text,
  "details" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "HomeHealthEpisodeEvent_entity_fkey" FOREIGN KEY ("organizationId","legalEntityId") REFERENCES "LegalEntity"("organizationId","id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "HomeHealthEpisodeEvent_episode_idx" ON "HomeHealthEpisodeEvent"("organizationId","legalEntityId","episodeId","createdAt" DESC);

CREATE OR REPLACE FUNCTION "prevent_home_health_episode_event_mutation"()
RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'HomeHealthEpisodeEvent is append-only'; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "HomeHealthEpisodeEvent_no_update" ON "HomeHealthEpisodeEvent";
CREATE TRIGGER "HomeHealthEpisodeEvent_no_update" BEFORE UPDATE ON "HomeHealthEpisodeEvent" FOR EACH ROW EXECUTE FUNCTION "prevent_home_health_episode_event_mutation"();
DROP TRIGGER IF EXISTS "HomeHealthEpisodeEvent_no_delete" ON "HomeHealthEpisodeEvent";
CREATE TRIGGER "HomeHealthEpisodeEvent_no_delete" BEFORE DELETE ON "HomeHealthEpisodeEvent" FOR EACH ROW EXECUTE FUNCTION "prevent_home_health_episode_event_mutation"();
